/**
 * Art Category - 25 "Did You Know" Stories
 * Usage: node scripts/new-content-dyk/art-dyk.mjs
 */

const SUPABASE_URL = "https://egfwisgqdyhzpmeoracb.supabase.co";
const SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVnZndpc2dxZHloenBtZW9yYWNiIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2ODQyNzM0OSwiZXhwIjoyMDg0MDAzMzQ5fQ.S8h1fIepxWb44gPSPpWQ8fE0Q-SCYfL0QcBRUV7fXgs";

const stories = [
  {
    slug: "mona-lisa-eyebrows-mystery",
    title: "Where Are Mona Lisa's Eyebrows?",
    description: "The missing feature no one can explain",
    category: "Art",
    thumbnail_color: "#5D4037",
    body_text: `The Mona Lisa has no eyebrows. Look closely at any high-resolution image, and you'll see smooth skin where her brows should be. For centuries, art historians assumed Leonardo da Vinci painted her that way intentionally, perhaps following Renaissance fashion trends where some women plucked their brows entirely. Then, in 2007, a French engineer named Pascal Cotte spent three thousand hours scanning the painting with a 240-megapixel camera. His discovery changed everything we thought we knew. Using multispectral imaging technology that could see beneath the painting's surface, Cotte found traces of eyebrows that Leonardo had originally painted. The Mona Lisa once had clearly defined brows and even more vivid eyelashes than remain visible today. They had vanished over five centuries of cleaning and restoration. Early conservation methods were brutal by modern standards. Restorers routinely used solvents that stripped away delicate glazes—the thin, translucent layers Leonardo built up to create his famous sfumato effect. Each cleaning removed more of the surface detail. The eyebrows, painted in the finest of lines, were among the first casualties. Cotte's research revealed other lost details too. The chair in which Lisa sat originally had armrests that have since vanished. Her face was once wider, the landscape behind her more vivid. The painting we see today in the Louvre is essentially a faded copy of Leonardo's original vision, worn away by centuries of well-intentioned damage. The irony is profound. The Mona Lisa is the most studied painting in history, examined by countless experts, yet something as obvious as missing eyebrows wasn't questioned until technology revealed the truth. We had grown so accustomed to seeing her without them that her smooth forehead seemed natural. Leonardo's Lisa was always meant to have eyebrows. We just forgot to notice when they disappeared.`,
    design_config: {"thumbnailColor":"#5D4037","titlePage":{"backgroundColor":"#5D4037","textColor":"#FFD60A"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#5D4037","text":"#FFFFFF"},{"background":"#FFD60A","text":"#000000"},{"background":"#C4B39A","text":"#000000"}],"imagePlaceholderColors":["#5D4037","#FFD60A"],"imageAspectRatios":[1.4,0.85],"imageColorOffset":0,"imagePositionSeed":2}
  },
  {
    slug: "art-forger-phone-book-paint",
    title: "The Forger's Phone Book Secret",
    description: "How a master faker fooled the world",
    category: "Art",
    thumbnail_color: "#7B1FA2",
    body_text: `Han van Meegeren was dying of heart failure in 1945 when he made an astonishing confession: he had forged the Vermeer paintings that the Nazis had treasured. The Dutch authorities didn't believe him. They thought he was trying to avoid execution for selling national treasures to the enemy. To prove his innocence, van Meegeren offered to paint another Vermeer right in front of them. What he created in six weeks from his prison cell was a masterpiece of deception. But the real secret of his success wasn't his painting technique—it was his paint recipe. Van Meegeren had spent years solving the problem that defeated other forgers: how to make paint that could pass scientific testing as centuries old. Modern oil paint stays soft and dissolves in alcohol for decades after application. Genuine old masters' paint hardens like stone. The forger experimented with hundreds of formulas until he discovered something unexpected. Bakelite, the early plastic used in telephones and radios, could be mixed with oil paint to create a compound that hardened almost immediately when baked. The resulting paint could withstand alcohol tests that exposed other forgeries. There was one problem. Van Meegeren needed phenol formaldehyde resin—the key ingredient in Bakelite—but couldn't buy it without arousing suspicion. His solution was elegant and strange. He purchased old Bakelite telephones and phone book covers from junk dealers, then ground them into powder. The ground-up phone books became the secret ingredient in paintings that fooled museum directors, art historians, and Hermann Goering himself. Van Meegeren sold millions of dollars worth of fake Vermeers. His most famous forgery, "Christ at Emmaus," was hailed as the greatest Vermeer discovery of the century. When the truth emerged, van Meegeren became a folk hero in the Netherlands—the man who had swindled the Nazis with paintings made from telephone parts.`,
    design_config: {"thumbnailColor":"#7B1FA2","titlePage":{"backgroundColor":"#7B1FA2","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#7B1FA2","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#7B1FA2"},{"background":"#FFD60A","text":"#000000"}],"imagePlaceholderColors":["#7B1FA2","#FFD60A"],"imageAspectRatios":[1.3,0.9],"imageColorOffset":1,"imagePositionSeed":3}
  },
  {
    slug: "dadaists-pranked-hitler",
    title: "The Art Collective That Pranked Hitler",
    description: "When Dada made fascists look foolish",
    category: "Art",
    thumbnail_color: "#D32F2F",
    body_text: `In 1920, a group of artists in Berlin held an exhibition that would become one of the most audacious pranks in art history. The First International Dada Fair featured a stuffed German military uniform hanging from the ceiling with a pig's head attached. The sign read: "Hanged by the Revolution." The artists were arrested, but they had made their point. Dada was war on everything the establishment held sacred. The movement had started in Zurich during World War One, founded by artists who had fled to neutral Switzerland to escape the carnage. They blamed traditional culture—its pomposity, its nationalism, its reverence for authority—for enabling the slaughter. Their response was deliberate absurdity. Hugo Ball recited nonsense poetry in a cardboard costume. Marcel Duchamp submitted a urinal to an art exhibition. The very name "Dada" was meaningless, reportedly chosen by stabbing a dictionary with a knife. When the Nazis rose to power, they recognized Dada and its offspring, Surrealism, as threats. The 1937 "Degenerate Art" exhibition in Munich was supposed to mock modern art but became the most visited art show in history—over two million people came, many to see works they'd never be allowed to view again. The Nazis called it degenerate. The public called it fascinating. Some Dadaists had anticipated this decades earlier. John Heartfield, born Helmut Herzfeld, had anglicized his name as a protest during World War One and spent the 1930s creating photomontages mocking Hitler. His image of the Fuhrer with a spine made of gold coins was so effective that the Gestapo raided his apartment. Heartfield escaped with minutes to spare. The Dadaists understood something that took the world decades to learn: ridicule is a weapon against authoritarianism. You cannot debate fascism with logic. But you can make it look ridiculous.`,
    design_config: {"thumbnailColor":"#D32F2F","titlePage":{"backgroundColor":"#D32F2F","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#D32F2F","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#D32F2F"},{"background":"#FFD60A","text":"#000000"}],"imagePlaceholderColors":["#D32F2F","#FFD60A"],"imageAspectRatios":[1.5,0.8],"imageColorOffset":0,"imagePositionSeed":2}
  },
  {
    slug: "scheele-green-deadly-color",
    title: "The Color That Killed Thousands",
    description: "Victorian wallpaper's deadly secret",
    category: "Art",
    thumbnail_color: "#2E7D32",
    body_text: `In 1775, a Swedish chemist named Carl Wilhelm Scheele invented a brilliant green pigment that would kill thousands of people over the next century. Scheele's Green was vibrant, stable, and affordable—everything artists and manufacturers wanted. It was also loaded with arsenic. Victorian England fell in love with the color. Manufacturers used Scheele's Green and its successor, Paris Green, in everything from wallpaper to dresses, from children's toys to artificial flowers. A single ball gown could contain enough arsenic to kill multiple people. Factory workers who made artificial flowers from the pigment developed terrible sores and lost their hair, teeth, and eventually their lives. The wallpaper was particularly deadly. In damp conditions, mold growing on the paper converted the arsenic into a gas that filled rooms with poison. Doctors of the era noted that children in green bedrooms sickened and died at alarming rates, though they couldn't identify the cause. Some historians believe arsenic wallpaper killed Napoleon Bonaparte during his exile on St. Helena, where his bedroom was decorated in green. The most disturbing part is that the danger was known almost from the beginning. Scheele himself warned that his green was poisonous and refused to use it. Medical journals published warnings. Yet the public ignored them. The color was simply too beautiful, too fashionable, too modern. Women wore green dresses knowing the risk. Parents decorated nurseries in green wallpaper despite the evidence. It took until the 1870s for the tide to turn, when a chemist named William Morris—who ran a wallpaper company—publicly denounced arsenic pigments. Even then, some manufacturers kept using them into the twentieth century. Scheele's Green eventually disappeared, replaced by safer synthetic dyes. But for a hundred years, people had literally died for fashion.`,
    design_config: {"thumbnailColor":"#2E7D32","titlePage":{"backgroundColor":"#2E7D32","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#2E7D32","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#2E7D32"},{"background":"#C4B39A","text":"#000000"}],"imagePlaceholderColors":["#2E7D32","#C4B39A"],"imageAspectRatios":[1.4,0.9],"imageColorOffset":1,"imagePositionSeed":4}
  },
  {
    slug: "masterpiece-found-in-garbage",
    title: "The Masterpiece Found in Garbage",
    description: "A $100 million painting in the trash",
    category: "Art",
    thumbnail_color: "#FF8F00",
    body_text: `In 1958, a British art restorer named Robert Wraight was poking through the garbage outside Sotheby's auction house in London when he spotted a panel painting that looked old. The auction house had thrown it away as worthless. Wraight retrieved it, cleaned off the grime, and discovered he was holding a genuine masterpiece from the Italian Renaissance. The painting was a portrait by the Florentine master Ghirlandaio, worth what would be millions today. Sotheby's had discarded it because the painting was dirty, damaged, and unsigned—typical problems that mask masterpieces from untrained eyes. Stories like this happen more often than museums would like to admit. In 1999, a woman bought a small gold painting at an Indianapolis estate sale for three dollars. It turned out to be a medieval artwork worth over a hundred thousand dollars. In 2010, a painting purchased at a Las Vegas estate sale for fifty dollars was identified as a lost Renoir worth approximately two hundred thousand. The reverse happens too. In 2015, a man unknowingly threw away a collection of paintings his mother had left him. Among them was an original Jackson Pollock, estimated value over fifteen million dollars. It ended up in a landfill somewhere in Arizona and has never been recovered. Museums and auction houses employ teams of experts specifically to prevent these mistakes, yet they keep happening. The art world estimates that tens of thousands of significant works remain misidentified in attics, thrift stores, and garbage heaps worldwide. Some are hidden beneath later paintings, revealed only by X-ray analysis. Others are simply dirty, their beauty obscured by centuries of soot and varnish. That worthless old painting in your grandmother's attic might be worthless. Or it might be worth a fortune. The only way to know is to look beneath the surface.`,
    design_config: {"thumbnailColor":"#FF8F00","titlePage":{"backgroundColor":"#FF8F00","textColor":"#000000"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#FF8F00","text":"#000000"},{"background":"#FFFFFF","text":"#FF8F00"},{"background":"#5D4037","text":"#FFFFFF"}],"imagePlaceholderColors":["#FF8F00","#5D4037"],"imageAspectRatios":[1.3,0.85],"imageColorOffset":0,"imagePositionSeed":3}
  },
  {
    slug: "vantablack-artist-controversy",
    title: "The Blackest Black Is Off-Limits",
    description: "One artist owns the darkest color",
    category: "Art",
    thumbnail_color: "#000000",
    body_text: `Anish Kapoor owns the exclusive rights to use Vantablack in art. He can use it. No other artist can. The art world has never forgiven him. Vantablack is the darkest substance ever created, absorbing 99.965% of all light that hits it. Looking at it is like staring into a void—your brain cannot process the absolute absence of light. Developed by Surrey NanoSystems for aerospace and military applications, Vantablack is made of carbon nanotubes so densely packed that light cannot escape. In 2016, Kapoor secured exclusive artistic rights to the material. Artists around the world erupted in outrage. Color, they argued, cannot be owned. Other pigments were available to everyone. Why should one artist have a monopoly on the ultimate black? A British artist named Stuart Semple launched a counterattack. He created a pink paint called "Pinkest Pink" and made it available to everyone in the world—except Anish Kapoor. Buyers had to confirm they were not Kapoor and would not share the paint with him. The certificate of purchase explicitly banned Kapoor by name. Semple then developed his own ultra-black paint called "Black 3.0" and again banned Kapoor from using it. The feud escalated when someone sent Kapoor a pot of Pinkest Pink anyway. Kapoor posted an Instagram photo with his middle finger dipped in the paint. Semple responded by creating more exclusive colors, all banned to Kapoor. The controversy raises serious questions about art and ownership. Can anyone truly own a color? Yves Klein trademarked his signature blue decades earlier. Tiffany owns its robin's-egg blue. But those were specific formulations. Vantablack isn't just a color—it's the experience of absolute darkness. For now, only Anish Kapoor can put that darkness on a canvas. The rest of the art world must settle for second-blackest.`,
    design_config: {"thumbnailColor":"#000000","titlePage":{"backgroundColor":"#000000","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#1A1A1A","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#000000"},{"background":"#E91E63","text":"#FFFFFF"}],"imagePlaceholderColors":["#000000","#E91E63"],"imageAspectRatios":[1.5,0.9],"imageColorOffset":1,"imagePositionSeed":2}
  },
  {
    slug: "bob-ross-never-sold-paintings",
    title: "Bob Ross Never Sold His Paintings",
    description: "The happy little secret of PBS's painter",
    category: "Art",
    thumbnail_color: "#1B5E20",
    body_text: `Bob Ross painted over thirty thousand pictures during his lifetime. He sold almost none of them. The beloved PBS host, famous for his gentle voice and "happy little trees," created three paintings per episode of "The Joy of Painting." One went to the studio, one went to the TV station, and one went into storage. After eleven years and 403 episodes, that storage facility contained thousands of original Bob Ross paintings—more than his most devoted fans could have imagined. Ross had a deliberate reason for not selling. He wanted viewers to believe that anyone could paint like him, that his techniques were accessible to ordinary people without expensive training. If his originals sold for thousands of dollars, that message would be undermined. Better to let people think his art was valuable only as teaching tools. The paintings sat in a warehouse in Virginia for years after Ross's death in 1995. His business partner, Annette Kowalski, kept them carefully organized by episode number. She occasionally donated one to charity auctions, where they fetched surprising prices—not because of their artistic merit, but because of Ross's cultural legacy. That legacy only grew after his death. A new generation discovered him through internet clips. His ASMR-like voice made him a meme. His philosophical observations about painting became inspirational quotes. The painter who never sought fame became more famous than ever. His company, Bob Ross Inc., still sells licensed products worldwide. The thirty thousand paintings remain largely unseen. Ross's estate has released only a handful for public viewing or sale. The happy little trees stay locked away, waiting for someone to decide what Bob himself refused to do: put a price on his joy.`,
    design_config: {"thumbnailColor":"#1B5E20","titlePage":{"backgroundColor":"#1B5E20","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#1B5E20","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#1B5E20"},{"background":"#8D6E63","text":"#FFFFFF"}],"imagePlaceholderColors":["#1B5E20","#8D6E63"],"imageAspectRatios":[1.4,0.85],"imageColorOffset":0,"imagePositionSeed":4}
  },
  {
    slug: "starry-night-painted-from-asylum",
    title: "Van Gogh's View From the Asylum",
    description: "The most famous painting's dark origin",
    category: "Art",
    thumbnail_color: "#1565C0",
    body_text: `Vincent van Gogh painted "The Starry Night" while confined to a psychiatric asylum in Saint-Rémy-de-Provence, France. The swirling sky, the blazing stars, the quiet village below—all of it came from a barred window in a mental institution. Van Gogh had committed himself in May 1889 after cutting off part of his own ear during a psychotic episode. The asylum, a converted monastery, gave him two rooms: one for sleeping, one for painting. He worked obsessively, producing over a hundred paintings in a single year. "The Starry Night" was painted in June 1889, depicting the view from his window just before sunrise. But here's what makes it stranger: the scene is not entirely real. The village in the painting, with its distinctive church spire, doesn't match any actual town visible from the asylum. Van Gogh invented it, perhaps drawing on memories of his native Netherlands. The cypress tree in the foreground was real, but he moved it closer to create the composition he wanted. The night sky itself is pure imagination. Van Gogh painted it during the day, from memory and feeling rather than observation. The spiraling patterns that make the sky so distinctive might reflect his mental state—some scientists have suggested the turbulence patterns match mathematical models of fluid dynamics. Whether Van Gogh understood something profound about nature or simply painted what his troubled mind perceived remains debated. Van Gogh himself dismissed "The Starry Night" as a failure. In a letter to his brother Theo, he mentioned it only briefly, preferring other works from that period. He sold just one painting in his entire life, and it wasn't this one. The masterpiece that would become one of the most recognized images in Western art was painted by a man who thought he couldn't paint.`,
    design_config: {"thumbnailColor":"#1565C0","titlePage":{"backgroundColor":"#1565C0","textColor":"#FFD60A"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#1565C0","text":"#FFFFFF"},{"background":"#FFD60A","text":"#000000"},{"background":"#1A237E","text":"#FFFFFF"}],"imagePlaceholderColors":["#1565C0","#FFD60A"],"imageAspectRatios":[1.3,0.9],"imageColorOffset":1,"imagePositionSeed":3}
  },
  {
    slug: "art-thieves-leave-notes",
    title: "The Thieves Who Left Thank You Notes",
    description: "Art heists with unexpected manners",
    category: "Art",
    thumbnail_color: "#6D4C41",
    body_text: `In 1994, two thieves stole Edvard Munch's "The Scream" from Norway's National Gallery. They left behind a note: "Thanks for the poor security." It wasn't the first time art thieves had communicated with their victims, and it wouldn't be the last. The phenomenon of polite art criminals is stranger than fiction. When thieves stole a Rembrandt from a Swedish museum in 2000, they left a thank you card. The 1990 Gardner Museum heist in Boston—the largest art theft in history—included a moment where one of the thieves complimented a guard on his mustache before tying him up. Some criminals seem genuinely concerned about the art they're stealing. In 2003, thieves who stole two Renoirs from a Swedish museum called the police to report that one painting was damaged and needed conservation attention. They provided detailed instructions on how to properly handle the work. When the Mona Lisa was stolen in 1911, the thief—an Italian handyman named Vincenzo Peruggia—kept her safe in his apartment for two years. He told police he had stolen her to return her to Italy, where she belonged. He was treated as a hero by many Italians despite his crime. The art world has theories about this behavior. Some thieves are genuine art lovers who steal for passion, not profit. Others may be leaving notes as a form of signature, unable to resist the ego boost of public communication. And some are simply professionals who understand that treating art well keeps it valuable. Whatever the motivation, the notes reveal something unexpected about criminals who steal beautiful things: even thieves appreciate art.`,
    design_config: {"thumbnailColor":"#6D4C41","titlePage":{"backgroundColor":"#6D4C41","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#6D4C41","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#6D4C41"},{"background":"#FFD60A","text":"#000000"}],"imagePlaceholderColors":["#6D4C41","#FFD60A"],"imageAspectRatios":[1.5,0.85],"imageColorOffset":0,"imagePositionSeed":2}
  },
  {
    slug: "pigment-made-from-mummies",
    title: "The Paint Made From Mummies",
    description: "Artists ground up Egyptian corpses",
    category: "Art",
    thumbnail_color: "#4E342E",
    body_text: `For centuries, European artists painted with the ground-up remains of Egyptian mummies. The color was called "Mummy Brown," and it was exactly what it sounds like: a rich brown pigment made from actual human and cat mummies imported from Egypt. The practice began in the sixteenth century, when European medicine believed that powdered mummy possessed healing properties. When the medical craze faded, artists discovered that the resin-soaked flesh and bone created a warm, translucent brown perfect for shadows and glazes. Major paint manufacturers offered it in their catalogs. The Pre-Raphaelite painter Edward Burne-Jones reportedly used Mummy Brown for years before learning its origin. When a friend told him what the pigment actually contained, Burne-Jones was horrified. He took his tube of paint into his garden and gave it a proper burial. Not everyone shared his scruples. Some artists appreciated the color too much to care about its contents. Others considered the mummies so ancient that their original humanity had faded. After all, these bodies had been dead for thousands of years—did it really matter if they ended up in a painting? The supply chain was appallingly casual. Egyptian mummies were sold by weight in Cairo markets. Traders would break apart ancient tombs and sell the contents to European dealers. One paint manufacturer claimed he could process one mummy into enough pigment to last several decades. By the twentieth century, the mummy supply began to run out. Conservation efforts and stricter export laws made it harder to obtain bodies. The last known commercial supplier of Mummy Brown, a British company called C. Roberson, ran out of their mummy inventory in the 1960s. The color still exists in some old paintings—ancient Egyptians, preserved forever in oil on canvas.`,
    design_config: {"thumbnailColor":"#4E342E","titlePage":{"backgroundColor":"#4E342E","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#4E342E","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#4E342E"},{"background":"#D4A36A","text":"#000000"}],"imagePlaceholderColors":["#4E342E","#D4A36A"],"imageAspectRatios":[1.4,0.9],"imageColorOffset":1,"imagePositionSeed":4}
  },
  {
    slug: "sistine-chapel-almost-rejected",
    title: "Michelangelo Almost Said No",
    description: "The Sistine Chapel was nearly undone",
    category: "Art",
    thumbnail_color: "#3949AB",
    body_text: `Michelangelo did not want to paint the Sistine Chapel. When Pope Julius II offered him the commission in 1508, Michelangelo tried desperately to refuse. He was a sculptor, he insisted, not a painter. The ceiling would be a disaster. Someone else should do it. His protests fell on deaf ears. The Pope was not accustomed to hearing no. Michelangelo suspected a conspiracy. His rival, the architect Donato Bramante, had apparently recommended him for the project. Michelangelo believed Bramante wanted to see him fail publicly—embarrassed on a massive scale, his reputation destroyed on a ceiling he wasn't qualified to paint. Whether the conspiracy theory was true or not, Michelangelo's fears about his painting abilities were genuine. He had painted frescoes before, but nothing approaching this scale. The Sistine Chapel ceiling covers over five thousand square feet. Working on scaffolding sixty feet above the floor, painting overhead until paint dripped into his eyes, Michelangelo spent four years creating what many consider the greatest artwork in Western civilization. The physical toll was brutal. He developed an infection in his eyes from constant paint drips. His body became so contorted from painting overhead that he couldn't read letters normally—he had to hold them above his head. He wrote a poem describing his suffering: his beard toward heaven, his brush dripping on his face, his body bent like a bow. The result was transcendent. The ceiling depicts the story of Genesis, from the creation of light to the drunkenness of Noah. The central image—God's finger nearly touching Adam's—became one of the most reproduced images in history. Michelangelo, the reluctant painter who thought he couldn't do it, created an eternal masterpiece. Sometimes the things we're forced to do become the things we're remembered for.`,
    design_config: {"thumbnailColor":"#3949AB","titlePage":{"backgroundColor":"#3949AB","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#3949AB","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#3949AB"},{"background":"#C4B39A","text":"#000000"}],"imagePlaceholderColors":["#3949AB","#C4B39A"],"imageAspectRatios":[1.6,0.85],"imageColorOffset":0,"imagePositionSeed":3}
  },
  {
    slug: "banksy-shredder-stunt",
    title: "The Painting That Shredded Itself",
    description: "Banksy's million-dollar prank",
    category: "Art",
    thumbnail_color: "#212121",
    body_text: `The moment the auctioneer's hammer fell, the painting began to self-destruct. On October 5, 2018, Banksy's "Girl with Balloon" had just sold at Sotheby's in London for 1.04 million pounds. As stunned onlookers watched, the canvas began sliding through the ornate gold frame, emerging from the bottom in shreds. Banksy had hidden a battery-powered shredder inside the frame years earlier, waiting for exactly this moment. Video footage shows bidders gasping, covering their mouths, laughing in disbelief. The anonymous street artist had pulled off the most audacious prank in auction history, destroying his own work the instant it was sold. Or had he? The shredder malfunctioned partway through. Only the bottom half of the painting was destroyed. The top half—including the iconic red balloon—remained intact. What emerged was a new artwork: half-painting, half-shredded canvas, poking through a golden frame. Sotheby's quickly declared that the buyer, an anonymous European collector, still wanted the work. It was authenticated by Banksy's team and given a new name: "Love Is in the Bin." Three years later, the half-shredded painting sold again at Sotheby's. This time it fetched 18.5 million pounds—nearly twenty times the original price. The attempted destruction had made the artwork far more valuable. Art critics debated what it all meant. Was Banksy critiquing the commodification of art? Was he proving that publicity trumps aesthetics? Was the malfunction intentional—a prank within a prank? Banksy, characteristically, has said little. His Instagram posted the words "Going, going, gone..." and a grainy video of the shredding. The mystery remains part of the art. The painting that tried to destroy itself became the most expensive Banksy ever sold. Even failure, it seems, can be a masterpiece.`,
    design_config: {"thumbnailColor":"#212121","titlePage":{"backgroundColor":"#212121","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#212121","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#212121"},{"background":"#D32F2F","text":"#FFFFFF"}],"imagePlaceholderColors":["#212121","#D32F2F"],"imageAspectRatios":[1.3,0.9],"imageColorOffset":1,"imagePositionSeed":2}
  },
  {
    slug: "frida-kahlo-painted-in-bed",
    title: "Frida's Mirror Above the Bed",
    description: "How an accident created an icon",
    category: "Art",
    thumbnail_color: "#C62828",
    body_text: `Frida Kahlo learned to paint while lying on her back, staring at her own reflection in a mirror attached to her bed's canopy. At eighteen, she had survived a bus accident that impaled her with a metal handrail, fracturing her spine in three places, shattering her pelvis, and breaking her right leg in eleven places. Doctors didn't expect her to walk again. For months, Kahlo was confined to bed in a full-body cast. Her mother had a special easel constructed that allowed her to paint while lying down. She hung a mirror overhead so Frida could see her own face. Thus began one of the most distinctive artistic careers of the twentieth century. Kahlo painted herself obsessively—fifty-five self-portraits over her lifetime. "I paint myself because I am often alone," she explained, "and because I am the subject I know best." But her self-portraits were not vanity. They were confrontations with pain, identity, and mortality. She painted herself as a wounded deer, pierced with arrows. She painted herself with a broken column replacing her spine. She painted the miscarriages that followed her accident, her body's inability to carry children after the damage it had sustained. The accident that nearly killed her created the conditions for her art. Without those months of immobility, staring at her own reflection, Kahlo might never have become a painter at all. She had been studying medicine before the crash. The mirror above the bed changed everything. Kahlo walked again, against all predictions, though she was never free from pain. She underwent over thirty surgeries. She wore corsets to support her spine and painted some of them with images and symbols. Even her suffering became art. The woman who learned to paint from her sickbed became one of the most recognized artists in the world.`,
    design_config: {"thumbnailColor":"#C62828","titlePage":{"backgroundColor":"#C62828","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#C62828","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#C62828"},{"background":"#1B5E20","text":"#FFFFFF"}],"imagePlaceholderColors":["#C62828","#1B5E20"],"imageAspectRatios":[1.4,0.85],"imageColorOffset":0,"imagePositionSeed":4}
  },
  {
    slug: "louvre-empty-spot-mona-lisa",
    title: "The Louvre's Famous Empty Spot",
    description: "When the space was the art",
    category: "Art",
    thumbnail_color: "#5D4037",
    body_text: `When the Mona Lisa was stolen from the Louvre in 1911, something unexpected happened: more people came to see the empty space where the painting had hung than had ever come to see the painting itself. The theft had transformed the Mona Lisa from a respected but not particularly famous painting into an object of global fascination. Visitors lined up to stare at four iron pegs on a bare wall. Guards reported that people wept in front of the empty space. Newspapers ran front-page stories for weeks. The theft was almost comically simple. Vincenzo Peruggia, an Italian handyman who had helped install the painting's protective glass case, hid in the museum overnight. The next morning, he lifted the painting off the wall, removed it from its frame, tucked it under his white workman's smock, and walked out. No one stopped him. The painting was missing for over two years. During that time, the Mona Lisa became the most famous artwork in the world—not because people could see it, but because they couldn't. The absence created a hunger that seeing the actual painting had never inspired. When Peruggia finally tried to sell the painting to an Italian art dealer in 1913, he was arrested and the Mona Lisa was recovered. The painting returned to the Louvre, now behind bulletproof glass, with guards watching constantly. The crowds that come to see it today are so large that visitors typically spend only fifteen seconds in front of the painting before being pushed along. Some art historians argue that the Mona Lisa is famous today primarily because it was stolen. The empty space on that wall in 1911 created something that centuries of hanging in the same spot could not: a legend.`,
    design_config: {"thumbnailColor":"#5D4037","titlePage":{"backgroundColor":"#5D4037","textColor":"#FFD60A"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#5D4037","text":"#FFFFFF"},{"background":"#FFD60A","text":"#000000"},{"background":"#FFFFFF","text":"#5D4037"}],"imagePlaceholderColors":["#5D4037","#FFD60A"],"imageAspectRatios":[1.5,0.9],"imageColorOffset":1,"imagePositionSeed":3}
  },
  {
    slug: "dali-slept-with-key",
    title: "Dali's Key to Genius",
    description: "The surrealist's strangest work habit",
    category: "Art",
    thumbnail_color: "#FF6F00",
    body_text: `Salvador Dali had a technique for accessing his subconscious: he napped while holding a heavy key above a metal plate. The moment he fell truly asleep, his grip would relax, the key would clatter onto the plate, and he would wake up—capturing the hypnagogic state between waking and sleeping. In those moments, Dali believed, the mind produced its most surreal imagery. The melting clocks, the elephants on spider legs, the distorted faces—all emerged from this twilight zone of consciousness. Dali called it "slumber with a key" and considered it one of his most important creative tools. The technique wasn't entirely his invention. Thomas Edison reportedly used a similar method, holding ball bearings over a metal pan. Aristotle described the hypnagogic state as a source of prophecy. But Dali turned it into a systematic practice, napping in his studio with the key positioned perfectly to shatter his sleep at just the right moment. His wife and collaborator, Gala, reportedly tolerated the constant clattering with patience. She understood that Dali's eccentricities were inseparable from his genius. He wore a cape and carried a cane with an eye-shaped head. He once gave a lecture while wearing a diving suit—and nearly suffocated when no one knew how to open the helmet. Dali cultivated strangeness as deliberately as he cultivated his signature upturned mustache. The key technique embodied his philosophy: art should come from the unconscious, from dreams and irrationality, from the places ordinary thinking cannot reach. To paint what no one had seen before, he had to see what no one else could see. And to see that, he had to hover in the space between sleeping and waking, catching images before they faded into ordinary dreams.`,
    design_config: {"thumbnailColor":"#FF6F00","titlePage":{"backgroundColor":"#FF6F00","textColor":"#000000"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#FF6F00","text":"#000000"},{"background":"#FFFFFF","text":"#FF6F00"},{"background":"#1A237E","text":"#FFFFFF"}],"imagePlaceholderColors":["#FF6F00","#1A237E"],"imageAspectRatios":[1.3,0.85],"imageColorOffset":0,"imagePositionSeed":2}
  },
  {
    slug: "statue-of-liberty-copper",
    title: "The Statue Was Orange",
    description: "Lady Liberty's original color",
    category: "Art",
    thumbnail_color: "#BF360C",
    body_text: `The Statue of Liberty was not always green. When she arrived from France in 1886, she was the color of a shiny new penny—a brilliant reddish-brown copper that would have been visible for miles. Visitors to New York Harbor saw a gleaming copper woman holding a torch, not the pale green patina we recognize today. The transformation took about thirty years. As the copper oxidized in the salty sea air, it first turned dark brown, almost black in some areas. Then the patina developed, that distinctive verdigris green that has become inseparable from the statue's identity. By 1920, Lady Liberty had achieved roughly her current appearance. The patina isn't just cosmetic—it's protective. The green layer of copper carbonate that forms on exposed copper actually prevents further corrosion, creating a stable coating that preserves the metal beneath. The statue's skin is only about three-quarters of an inch thick, but that thin shell has survived over a century of hurricanes, nor'easters, and pollution thanks to its green armor. In the early twentieth century, some people wanted to clean the statue and restore her original copper color. The proposal was quickly rejected. By then, the green goddess had become too iconic. Removing the patina would not only strip away protection but would transform a beloved symbol into something unrecognizable. The same debate continues with old copper roofs and domes around the world. Should patina be preserved or removed? There's no single answer. But for the Statue of Liberty, the question was settled by time and familiarity. She may have arrived as a bright copper beauty, but she became herself only after turning green.`,
    design_config: {"thumbnailColor":"#BF360C","titlePage":{"backgroundColor":"#BF360C","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#BF360C","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#BF360C"},{"background":"#2E7D32","text":"#FFFFFF"}],"imagePlaceholderColors":["#BF360C","#2E7D32"],"imageAspectRatios":[1.4,0.9],"imageColorOffset":1,"imagePositionSeed":4}
  },
  {
    slug: "whistlers-mother-almost-trashed",
    title: "Whistler's Mother Was Almost Trash",
    description: "The iconic painting nobody wanted",
    category: "Art",
    thumbnail_color: "#37474F",
    body_text: `"Arrangement in Grey and Black No.1"—better known as Whistler's Mother—was rejected by every major exhibition and nearly ended up in a dustbin. Today it's one of the most recognized paintings in American art. In 1871, James Abbott McNeill Whistler submitted the portrait of his mother to the Royal Academy in London. The Academy initially rejected it. Only after a fellow artist threatened to resign did they grudgingly accept the painting—and then hung it in the worst possible location, where it would attract minimal attention. Critics dismissed it. The public ignored it. Whistler himself considered it merely an experiment in tonal arrangement, which is why he gave it such a formal title instead of calling it a portrait. The painting might have vanished into obscurity if not for a series of unlikely events. In 1891, the French government purchased it for their national collection, paying a modest sum. This was the first American painting to enter the Louvre—a distinction that suddenly made art critics pay attention. The painting's reputation grew slowly throughout the early twentieth century. During the Great Depression, it was loaned to American museums as a symbol of maternal devotion and traditional values. Postage stamps reproduced it. Politicians referenced it. What had been an obscure experiment became a cultural icon. The transformation is almost absurd. Whistler would have been horrified to see his painting reduced to sentimental kitsch. He was an aesthete who cared about color and composition, not sentiment. "To me it is interesting as a picture of my mother," he said, "but what can or ought the public to care about the identity of the portrait?" The public, as it turned out, cared very much. The painting that nearly ended in a dustbin became a symbol of motherhood itself.`,
    design_config: {"thumbnailColor":"#37474F","titlePage":{"backgroundColor":"#37474F","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#37474F","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#37474F"},{"background":"#CFD8DC","text":"#000000"}],"imagePlaceholderColors":["#37474F","#CFD8DC"],"imageAspectRatios":[1.6,0.85],"imageColorOffset":0,"imagePositionSeed":3}
  },
  {
    slug: "monet-cataracts-changed-art",
    title: "Monet's Failing Eyes Made History",
    description: "Cataracts created late masterpieces",
    category: "Art",
    thumbnail_color: "#FF7043",
    body_text: `Claude Monet's vision began failing in his sixties, and it changed the course of art history. The founder of Impressionism, famous for capturing light with unprecedented subtlety, was going blind from cataracts. The world he painted became increasingly distorted—and increasingly beautiful. By 1912, Monet could barely distinguish colors. The delicate lilacs and azure blues of his earlier water lilies gave way to reds and yellows, the only colors his damaged eyes could still perceive. His brushstrokes grew broader, more aggressive, less concerned with detail. Critics assumed he was simply declining with age. In fact, he was pioneering abstraction decades before it became mainstream. Monet was devastated by his condition. "I no longer perceive colors with the same intensity," he wrote. "I can no longer distinguish tones of color... Red appears muddy to me, and pink seems insipid." He destroyed several canvases in frustration, convinced they were failures. In 1923, at age eighty-two, Monet finally agreed to cataract surgery. The operation was primitive by modern standards and initially seemed unsuccessful—he complained that everything looked yellow. But gradually his vision improved, and he was horrified to see what he had painted while blind. The canvases he thought were failures were actually masterpieces, their distorted colors forming patterns that would later inspire Abstract Expressionism. Today, museums display both his clear-sighted early works and his cataract-affected late paintings side by side. The contrast is striking. The early works are exercises in observation; the late works are visions from a world most people never see. Monet's failing eyes, the tragedy of his old age, became the source of some of his most influential work.`,
    design_config: {"thumbnailColor":"#FF7043","titlePage":{"backgroundColor":"#FF7043","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#FF7043","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#FF7043"},{"background":"#81D4FA","text":"#000000"}],"imagePlaceholderColors":["#FF7043","#81D4FA"],"imageAspectRatios":[1.4,0.9],"imageColorOffset":1,"imagePositionSeed":2}
  },
  {
    slug: "hands-cave-art-stencils",
    title: "The Cave Hands Were Women's",
    description: "Rewriting prehistoric art history",
    category: "Art",
    thumbnail_color: "#6D4C41",
    body_text: `For over a century, archaeologists assumed that prehistoric cave art was made by men. The handprints stenciled on cave walls across Europe and Asia, they believed, were left by male hunters recording their exploits. Then someone thought to measure the fingers. In 2013, a researcher named Dean Snow analyzed the handprints in caves across France and Spain using an algorithm based on the relative lengths of fingers, which differ systematically between men and women. His conclusion overturned decades of assumptions: up to 75 percent of the handprints were made by women. The implications are profound. If women created the handprints, they may have created the paintings too. The magnificent animals that charge across the walls of Lascaux and Chauvet—the horses and bulls, the lions and mammoths—may have been painted by women. The earliest human artists, stretching back thirty thousand years or more, may have been predominantly female. Snow's research suggests that cave art might not have been about hunting at all. Female artists may have had entirely different motivations: ritual, storytelling, teaching, or purposes we cannot imagine. The caves may have been spaces for women's work, not celebrations of masculine prowess. Not all researchers accept Snow's conclusions. Some argue that juvenile males could have had finger proportions similar to adult females, skewing the data. Others point out that the sample size is limited—only about thirty-two hands were analyzed in the original study. But the research has forced archaeologists to question assumptions they didn't realize they held. For a century, when experts imagined prehistoric artists, they imagined men. Now we have evidence that the earliest human art may have been created by women whose names and stories are lost to time.`,
    design_config: {"thumbnailColor":"#6D4C41","titlePage":{"backgroundColor":"#6D4C41","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#6D4C41","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#6D4C41"},{"background":"#D4A36A","text":"#000000"}],"imagePlaceholderColors":["#6D4C41","#D4A36A"],"imageAspectRatios":[1.3,0.85],"imageColorOffset":0,"imagePositionSeed":4}
  },
  {
    slug: "great-wave-kanagawa-copies",
    title: "The Wave Nobody Saw Twice",
    description: "Hokusai's masterpiece was disposable",
    category: "Art",
    thumbnail_color: "#0277BD",
    body_text: `"The Great Wave off Kanagawa" is one of the most reproduced images in history, appearing on everything from coffee mugs to laptop cases. When Katsushika Hokusai created it around 1831, it was essentially disposable commercial art, printed on cheap paper and sold for about the price of a bowl of noodles. The original woodblock prints were not meant to last. Japanese publishers produced them in editions of thousands, selling them to commoners who pinned them on walls, collected them in albums, or simply threw them away when they faded. The bold colors that make the wave so striking were achieved with Prussian blue, a synthetic pigment recently imported from Europe that was both vivid and cheap. Hokusai was in his seventies when he created the wave, part of a series called "Thirty-six Views of Mount Fuji." He had been making woodblock prints for decades, producing thousands of designs for books, prints, and advertisements. The wave was just another commission, not a masterpiece to be preserved in museums. Today, original prints of "The Great Wave" sell for millions of dollars. Museums compete to acquire them. Conservation specialists work to preserve the faded colors of surviving copies. But of the estimated five to eight thousand prints originally made, only a few hundred survive in any condition. The rest were used up—loved to death by ordinary people who had no idea they were holding cultural treasures. Hokusai himself was unsatisfied with his work throughout his life. At age seventy-five, he wrote: "All I have done before the age of seventy is not worth bothering with." He died at eighty-nine, still trying to improve. The disposable picture he made for noodle money became the most famous Japanese artwork in the world.`,
    design_config: {"thumbnailColor":"#0277BD","titlePage":{"backgroundColor":"#0277BD","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#0277BD","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#0277BD"},{"background":"#FFD60A","text":"#000000"}],"imagePlaceholderColors":["#0277BD","#FFD60A"],"imageAspectRatios":[1.5,0.85],"imageColorOffset":1,"imagePositionSeed":3}
  },
  {
    slug: "cia-funded-modern-art",
    title: "The CIA's Secret Art Collection",
    description: "Abstract Expressionism as a weapon",
    category: "Art",
    thumbnail_color: "#1A237E",
    body_text: `During the Cold War, the Central Intelligence Agency secretly funded the spread of Abstract Expressionism around the world. Jackson Pollock's drip paintings, Mark Rothko's color fields, Willem de Kooning's abstract women—all were promoted as weapons against Soviet cultural dominance. The program was called the Congress for Cultural Freedom, and it spent millions of dollars sponsoring exhibitions, publications, and tours that showcased American modern art. The CIA saw Abstract Expressionism as proof of American freedom: while Soviet artists were forced to paint idealized workers and approved historical scenes, American artists could splash paint anywhere they wanted. The irony was profound. Many of the artists being promoted had leftist politics and would have been horrified to learn they were serving as Cold War propaganda. Some had been investigated by the FBI for communist sympathies. Yet their work was being shipped around Europe and Asia as evidence of American cultural superiority. The program was remarkably effective. Before World War II, the center of the art world was Paris. By the 1960s, it was New York. Art historians debate how much of this shift was organic and how much was engineered. Would Abstract Expressionism have conquered the world without CIA funding? Probably—the art was genuinely revolutionary. But the speed and thoroughness of its triumph owed something to government money. The full extent of the program wasn't revealed until the 1990s, when former CIA officials began talking. By then, the artists they had promoted were dead, their reputations secure, their place in art history seemingly beyond politics. The paintings themselves didn't change—only our understanding of how they came to hang in museums around the world.`,
    design_config: {"thumbnailColor":"#1A237E","titlePage":{"backgroundColor":"#1A237E","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#1A237E","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#1A237E"},{"background":"#D32F2F","text":"#FFFFFF"}],"imagePlaceholderColors":["#1A237E","#D32F2F"],"imageAspectRatios":[1.4,0.9],"imageColorOffset":0,"imagePositionSeed":2}
  },
  {
    slug: "titian-paintings-took-decades",
    title: "The Painting Took 30 Years",
    description: "Titian's infinite patience",
    category: "Art",
    thumbnail_color: "#BF360C",
    body_text: `Titian, the greatest painter of Renaissance Venice, kept some canvases in his studio for over thirty years before declaring them finished. He would start a painting, set it against the wall, and return to it periodically over decades—adding a glaze here, adjusting a shadow there, slowly perfecting his vision. His contemporaries were baffled by this method. Other painters completed commissions in months. Titian completed them when he was ready, which could be never. Wealthy patrons who ordered portraits found themselves waiting years, sometimes decades, for delivery. Some died before their paintings were finished. Titian's technique justified the delay. He built up his paintings in dozens of transparent layers, each one slightly modifying the colors beneath. This glazing technique created depth and luminosity that faster methods couldn't match. His flesh tones seem to glow from within. His fabrics appear to have actual texture. The effect took time—years of time. There was method to the slowness. Titian would turn a canvas to the wall and deliberately forget about it. Months later, he would look at it with fresh eyes, seeing flaws invisible to someone who had been staring at the same image daily. Then he would make corrections and turn it to the wall again. He described looking at his paintings "as if they were his mortal enemies." The approach worked. Titian's paintings have survived for five centuries with remarkably stable colors, their layers of glaze protecting each other like geological strata. Museums display works that took longer to create than some artists' entire careers. When asked about his slow pace, Titian reportedly said that he painted for eternity. His patrons might have disagreed. But eternity, as it turned out, proved him right.`,
    design_config: {"thumbnailColor":"#BF360C","titlePage":{"backgroundColor":"#BF360C","textColor":"#FFD60A"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#BF360C","text":"#FFFFFF"},{"background":"#FFD60A","text":"#000000"},{"background":"#FFFFFF","text":"#BF360C"}],"imagePlaceholderColors":["#BF360C","#FFD60A"],"imageAspectRatios":[1.3,0.85],"imageColorOffset":1,"imagePositionSeed":4}
  },
  {
    slug: "guernica-refused-by-spain",
    title: "Spain Refused Guernica",
    description: "The unwanted masterpiece of war",
    category: "Art",
    thumbnail_color: "#424242",
    body_text: `When Pablo Picasso completed "Guernica" in 1937, he intended it as a gift to Spain. Spain didn't want it. The painting would spend over four decades in exile, displayed in New York while Spanish politics made its return impossible. Picasso created "Guernica" in response to the Nazi bombing of a Basque town during the Spanish Civil War. The monumental canvas—over twenty-five feet wide—depicted the horrors of modern warfare in stark black, white, and gray: screaming horses, dismembered soldiers, a mother holding her dead child. It became one of the most powerful anti-war images ever created. The problem was Franco. After winning the civil war, the fascist dictator ruled Spain for nearly four decades. Picasso refused to allow "Guernica" to enter Spain while Franco remained in power. The painting was held by the Museum of Modern Art in New York, technically on extended loan, waiting for Spain to become a democracy again. Franco died in 1975. Even then, the transfer wasn't immediate. Picasso had died in 1973, and his estate had to negotiate the return. Questions arose about whether the painting could survive transportation. Some argued it should stay in New York, where it had been protected for so long. Finally, in 1981, "Guernica" came home. It traveled in a specially constructed climate-controlled container, accompanied by armed guards. When it was unveiled in Madrid, Spaniards wept. The painting that had been created in response to their tragedy, and rejected by their government for almost half a century, had finally arrived where Picasso always intended it to be. Today it hangs in the Reina Sofía museum behind bulletproof glass, seen by millions each year.`,
    design_config: {"thumbnailColor":"#424242","titlePage":{"backgroundColor":"#424242","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#424242","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#424242"},{"background":"#BDBDBD","text":"#000000"}],"imagePlaceholderColors":["#424242","#BDBDBD"],"imageAspectRatios":[1.6,0.9],"imageColorOffset":0,"imagePositionSeed":3}
  }
];

async function uploadStory(story) {
  const response = await fetch(`${SUPABASE_URL}/rest/v1/stories`, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      "apikey": SUPABASE_KEY,
      "Authorization": `Bearer ${SUPABASE_KEY}`,
      "Prefer": "resolution=merge-duplicates,return=minimal"
    },
    body: JSON.stringify({
      slug: story.slug,
      title: story.title,
      description: story.description,
      category: story.category,
      thumbnail_color: story.thumbnail_color,
      published: true,
      published_at: new Date().toISOString(),
      body_text: story.body_text,
      design_config: story.design_config,
      updated_at: new Date().toISOString()
    })
  });

  if (!response.ok) {
    const text = await response.text();
    throw new Error(`${response.status}: ${text}`);
  }
}

async function main() {
  console.log(`Uploading ${stories.length} Art "Did You Know" stories to Supabase...\n`);

  let success = 0;
  let failed = 0;

  for (const story of stories) {
    try {
      process.stdout.write(`Uploading: ${story.title}... `);
      await uploadStory(story);
      console.log("Done!");
      success++;
    } catch (error) {
      console.log(`Error: ${error.message}`);
      failed++;
    }
  }

  console.log(`\nComplete! ${success} succeeded, ${failed} failed.`);
}

main();
