/**
 * Crime Category - 25 "Did You Know" Stories
 * Usage: node scripts/new-content-dyk/crime-dyk.mjs
 */

const SUPABASE_URL = "https://egfwisgqdyhzpmeoracb.supabase.co";
const SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVnZndpc2dxZHloenBtZW9yYWNiIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2ODQyNzM0OSwiZXhwIjoyMDg0MDAzMzQ5fQ.S8h1fIepxWb44gPSPpWQ8fE0Q-SCYfL0QcBRUV7fXgs";

const stories = [
  {
    slug: "woman-sold-eiffel-tower",
    title: "She Sold the Eiffel Tower",
    description: "The con artist who scammed Paris",
    category: "Crime",
    thumbnail_color: "#5D4037",
    body_text: `In 1925, a con artist named Victor Lustig sold the Eiffel Tower to a scrap metal dealer. He did it twice. The tower had been built for the 1889 World's Fair and was originally intended to be temporary. By the 1920s, it was rusting, expensive to maintain, and genuinely unpopular with many Parisians. Lustig, a Czech-born swindler fluent in five languages, read about the maintenance problems in a newspaper and saw his opportunity. He forged government credentials and invited six scrap metal dealers to a secret meeting at a prestigious Paris hotel. Pretending to be a deputy director-general of the Ministry of Posts and Telegraphs, Lustig explained that the tower was going to be sold for scrap, but the sale had to be kept confidential to avoid public outcry. The dealers were eager. Lustig identified the most gullible among them—a man named André Poisson—and arranged a private meeting. Poisson was suspicious at first, but Lustig disarmed him by suggesting that a small bribe might ensure the contract went his way. The request for a bribe made Lustig seem like a genuine corrupt official. Poisson paid Lustig's asking price plus the bribe and received official-looking papers giving him ownership of the Eiffel Tower. Lustig fled to Austria with the cash. When Poisson discovered the fraud, he was too embarrassed to go to the police. Lustig, realizing his victim would stay silent, returned to Paris a month later and ran the exact same con again. This time, his victim did go to the police, and Lustig had to flee permanently. He eventually moved to the United States, where he continued his criminal career until the Secret Service caught him for counterfeiting. The man who sold the Eiffel Tower died in Alcatraz in 1947.`,
    design_config: {"thumbnailColor":"#5D4037","titlePage":{"backgroundColor":"#5D4037","textColor":"#FFD60A"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#5D4037","text":"#FFFFFF"},{"background":"#FFD60A","text":"#000000"},{"background":"#FFFFFF","text":"#5D4037"}],"imagePlaceholderColors":["#5D4037","#FFD60A"],"imageAspectRatios":[1.4,0.85],"imageColorOffset":0,"imagePositionSeed":2}
  },
  {
    slug: "burglar-apology-notes",
    title: "The Burglar's Apology Notes",
    description: "He stole things and said sorry",
    category: "Crime",
    thumbnail_color: "#6D4C41",
    body_text: `For years, a burglar in British Columbia, Canada, left handwritten apology notes at the scenes of his crimes. The notes expressed genuine remorse. They sometimes explained why he needed the money. They occasionally included advice on how the homeowners could improve their security. The police were baffled. The "Sorry Burglar," as media dubbed him, operated from the early 2000s through 2013, breaking into homes and businesses throughout the suburbs of Vancouver. He stole electronics, cash, and jewelry, but he never used violence and always left a note. Some notes ran to multiple pages. "I'm sorry for breaking into your home," one read. "I needed money for food and rent. You should really get better locks—I got in through your basement window." Another note warned homeowners that their alarm system was easily bypassed. The burglar seemed genuinely concerned about the people he was robbing. Victims reported feeling conflicted. They were angry about being robbed but oddly touched by the apologies. Some kept the notes as curiosities. Others wondered if they should feel grateful for the security advice. Police eventually identified the Sorry Burglar as a man named Edgar Marcus, a recovering addict who funded his habit through burglaries. When arrested in 2013, Marcus confirmed that the notes were genuine expressions of guilt. He felt terrible about stealing from strangers but couldn't stop himself. The letters were his way of acknowledging the harm he caused. Marcus pleaded guilty to multiple charges and received a prison sentence. In court, several victims testified that his apology notes had meant something to them—that being recognized as human beings, even by the person robbing them, made the violation slightly more bearable.`,
    design_config: {"thumbnailColor":"#6D4C41","titlePage":{"backgroundColor":"#6D4C41","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#6D4C41","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#6D4C41"},{"background":"#C4B39A","text":"#000000"}],"imagePlaceholderColors":["#6D4C41","#C4B39A"],"imageAspectRatios":[1.3,0.9],"imageColorOffset":1,"imagePositionSeed":3}
  },
  {
    slug: "twins-perfect-alibi-crime",
    title: "The Twins Who Beat DNA Evidence",
    description: "Identical alibis, identical genes",
    category: "Crime",
    thumbnail_color: "#37474F",
    body_text: `In 2009, Berlin police knew that one of two identical twins had committed a major jewelry heist. DNA evidence from the crime scene matched both brothers perfectly. They had to let both of them go. The crime itself was spectacular. Thieves broke into the KaDeWe department store, one of Europe's largest luxury retailers, and escaped with 6.8 million dollars worth of jewelry. They left behind a drop of sweat, which police analyzed and matched to a criminal already in their database: Hassan O., who had prior convictions for theft. But when police arrived to arrest Hassan, they discovered he had an identical twin brother named Abbas. Both men had the same face. More importantly, they had the same DNA. Standard DNA testing cannot distinguish between identical twins because they develop from a single fertilized egg and share the same genetic code. The police faced an impossible choice. They could prove that one of the twins had been at the crime scene, but they couldn't prove which one. German law requires proof beyond a reasonable doubt for conviction. Neither brother would confess or implicate the other. Both claimed innocence. Prosecutors considered more advanced DNA testing that might detect subtle epigenetic differences between twins, but the technology was experimental and expensive. The case collapsed. Both brothers walked free. The jewelry was never recovered. The twins' case highlighted a loophole in genetic evidence that prosecutors rarely encounter. Identical twins are rare—about three in every thousand births—but when they choose to exploit their genetic sameness, the legal system has no good answer. Some countries have since developed more sophisticated testing, but in 2009 Berlin, two brothers beat the system with nothing more than their genes.`,
    design_config: {"thumbnailColor":"#37474F","titlePage":{"backgroundColor":"#37474F","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#37474F","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#37474F"},{"background":"#B0BEC5","text":"#000000"}],"imagePlaceholderColors":["#37474F","#B0BEC5"],"imageAspectRatios":[1.5,0.85],"imageColorOffset":0,"imagePositionSeed":2}
  },
  {
    slug: "burglar-fell-asleep-crime",
    title: "The Burglar Who Fell Asleep",
    description: "Crime interrupted by nap time",
    category: "Crime",
    thumbnail_color: "#4E342E",
    body_text: `In 2021, a burglar in Spain broke into a family home, helped himself to some food from the refrigerator, sat down on the couch to watch television, and fell asleep. The homeowners found him there the next morning, still snoring. The intruder, a man in his thirties, had entered through an unlocked window while the family was away overnight. Security camera footage showed him wandering through the house, examining valuables, and preparing to steal electronics. Then he got hungry. After making himself a sandwich, he sat down to eat and apparently decided to rest his eyes. The family returned home to find a complete stranger asleep on their sofa, surrounded by the sandwich remains and a half-empty glass of juice. They called police, who arrived to find the burglar still unconscious. He woke up surrounded by officers. Cases like this are surprisingly common. In 2019, an Ohio burglar fell asleep in a home he was robbing after drinking wine from the homeowner's cellar. In 2017, a California man was found asleep in a home he had burglarized, having apparently decided the victim's bed was too comfortable to resist. In 2020, a Florida burglar was discovered napping in a homeowner's bathtub. Criminologists offer various explanations. Some burglars are under the influence of drugs or alcohol, which impair judgment and induce drowsiness. Others are homeless and desperate for a comfortable place to sleep. A few seem to be afflicted by what one researcher called "criminal complacency"—a bizarre confidence that they won't be caught even while napping at the crime scene. Whatever the cause, the sleeping burglar has become a recurring character in crime news. The perfect crime, it seems, does not include a nap.`,
    design_config: {"thumbnailColor":"#4E342E","titlePage":{"backgroundColor":"#4E342E","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#4E342E","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#4E342E"},{"background":"#D7CCC8","text":"#000000"}],"imagePlaceholderColors":["#4E342E","#D7CCC8"],"imageAspectRatios":[1.4,0.9],"imageColorOffset":1,"imagePositionSeed":4}
  },
  {
    slug: "db-cooper-hijacker-vanished",
    title: "D.B. Cooper Vanished Mid-Air",
    description: "The only unsolved hijacking",
    category: "Crime",
    thumbnail_color: "#1A237E",
    body_text: `On November 24, 1971, a man calling himself Dan Cooper hijacked a Northwest Orient Airlines flight, collected two hundred thousand dollars in ransom, and parachuted into the stormy night sky over the Pacific Northwest. He was never seen again. The hijacking was executed with calm precision. Cooper, described as middle-aged and wearing a business suit, handed a flight attendant a note claiming he had a bomb. He demanded four parachutes and the ransom money in twenty-dollar bills. When the plane landed in Seattle, he released the passengers and exchanged them for the cash and parachutes. Then he ordered the plane to take off again, headed for Mexico City at low altitude with the rear stairs deployed. Somewhere over the wilderness of southwestern Washington, Cooper jumped. The search that followed was the largest and most expensive in FBI history. Agents combed hundreds of square miles of forest. They interviewed thousands of people. They developed over a thousand suspects. None panned out. Cooper simply vanished. In 1980, a boy found nearly six thousand dollars in decaying twenty-dollar bills along the Columbia River. The serial numbers matched the ransom. This remains the only physical evidence ever recovered. Theories about Cooper's fate vary widely. Some believe he died during the jump—the conditions were severe, the terrain was rugged, and he may not have been an experienced parachutist. Others believe he survived and successfully disappeared with most of the money. A few conspiracy theories suggest he was actually a government agent or that the entire hijacking was an elaborate cover for something else. The FBI officially closed the case in 2016 after forty-five years. D.B. Cooper, whoever he was, remains America's only successful airline hijacker.`,
    design_config: {"thumbnailColor":"#1A237E","titlePage":{"backgroundColor":"#1A237E","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#1A237E","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#1A237E"},{"background":"#90CAF9","text":"#000000"}],"imagePlaceholderColors":["#1A237E","#90CAF9"],"imageAspectRatios":[1.5,0.85],"imageColorOffset":0,"imagePositionSeed":3}
  },
  {
    slug: "most-stolen-painting-ever",
    title: "The Most Stolen Painting Ever",
    description: "The same artwork stolen four times",
    category: "Crime",
    thumbnail_color: "#C62828",
    body_text: `"The Ghent Altarpiece," a massive fifteenth-century painting by Jan van Eyck, holds the dubious distinction of being the most frequently stolen artwork in history. It has been targeted by thieves, armies, and governments more than a dozen times over its six-hundred-year existence. The altarpiece consists of twelve oak panels depicting biblical scenes, together forming one of the most important works of the Northern Renaissance. Its troubles began almost immediately after its completion in 1432. Within decades, authorities were already making copies because visitors kept damaging the original trying to get closer. Then came the thefts. Napoleon's forces seized the altarpiece in 1794 and shipped it to Paris. After his defeat, most panels were returned to Ghent, but some had been sold to a German collector. During World War I, the Germans took the panels back to Germany. After the war, the Treaty of Versailles required their return. In 1934, two panels were stolen from the cathedral where the altarpiece hung. One was recovered; the other—a panel called "The Just Judges"—has never been found. During World War II, the Nazis seized the entire altarpiece and hid it in an Austrian salt mine. American soldiers recovered it in 1945, an adventure that inspired the film "The Monuments Men." Today, the surviving panels hang in St. Bavo's Cathedral in Ghent, behind bulletproof glass, with armed guards on constant patrol. The missing panel of "The Just Judges" remains art history's greatest unsolved theft—somewhere in the world, a piece of one of humanity's greatest paintings is still waiting to be found.`,
    design_config: {"thumbnailColor":"#C62828","titlePage":{"backgroundColor":"#C62828","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#C62828","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#C62828"},{"background":"#FFD60A","text":"#000000"}],"imagePlaceholderColors":["#C62828","#FFD60A"],"imageAspectRatios":[1.4,0.9],"imageColorOffset":1,"imagePositionSeed":2}
  },
  {
    slug: "prison-break-helicopter",
    title: "The Helicopter Prison Breaks",
    description: "They escaped by air—three times",
    category: "Crime",
    thumbnail_color: "#00695C",
    body_text: `French criminal Pascal Payet escaped from prison by helicopter not once, not twice, but three times. His aerial escapes became so legendary that prison officials eventually banned him from any facility with an accessible rooftop. Payet's first helicopter escape came in 2001. He was serving a thirty-year sentence for murder when accomplices hijacked a helicopter, landed on the prison roof, and whisked him away. He was recaptured two years later. In 2007, he escaped the exact same way from a different prison. This time, accomplices hijacked a helicopter used for sightseeing tours, forced the pilot at gunpoint to fly to the prison, and landed on the roof. Payet and two other inmates climbed aboard and flew to freedom. He was recaptured a few months later. The third escape came in 2012 from yet another prison. By now, French authorities had implemented new security measures specifically designed to prevent helicopter escapes—but they failed again. Armed accomplices once more hijacked a helicopter, landed on the roof, and extracted Payet while guards watched helplessly from below. He was recaptured three years later in Spain. Payet's escapes inspired copycats around the world. Greece saw multiple helicopter prison breaks in the 2000s. Brazil, Belgium, and Canada all experienced similar incidents. Prison administrators began installing anti-helicopter cables over exercise yards and rooftops. Some prisons deployed armed guards specifically trained to shoot at approaching aircraft. Payet himself was eventually transferred to a prison with no roof access and maximum security protocols. As of his last reported status, he remains in custody—but French authorities learned never to underestimate a man who can summon helicopters from prison.`,
    design_config: {"thumbnailColor":"#00695C","titlePage":{"backgroundColor":"#00695C","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#00695C","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#00695C"},{"background":"#A5D6A7","text":"#000000"}],"imagePlaceholderColors":["#00695C","#A5D6A7"],"imageAspectRatios":[1.3,0.85],"imageColorOffset":0,"imagePositionSeed":4}
  },
  {
    slug: "art-heist-empty-frames",
    title: "The Empty Frames Still Hang",
    description: "Gardner Museum's $500M mystery",
    category: "Crime",
    thumbnail_color: "#4A148C",
    body_text: `In 1990, two thieves disguised as police officers walked out of Boston's Isabella Stewart Gardner Museum with thirteen works of art worth an estimated five hundred million dollars. The empty frames still hang on the walls, waiting for paintings that may never return. The heist occurred in the early hours of March 18. Two men knocked on the museum's side door, claimed they were responding to a disturbance, and were admitted by a security guard. Once inside, they handcuffed both guards on duty, duct-taped them in the basement, and spent the next eighty-one minutes selecting their targets. They took works by Vermeer, Rembrandt, Manet, and Degas. They also took a bronze eagle finial and a Chinese gu, an ancient bronze vessel. They ignored some of the museum's most valuable pieces, suggesting either poor planning or very specific instructions about what to steal. The thieves have never been identified. The artwork has never been recovered. The museum still offers a ten-million-dollar reward for information leading to the return of the pieces—the largest reward ever offered for stolen art. The empty frames hanging on the gallery walls are a deliberate choice. Isabella Stewart Gardner's will specified that nothing in the museum could be moved or sold after her death. The museum honors this requirement by leaving the frames in place, silent witnesses to what was lost. FBI agents believe the thieves were connected to Boston's organized crime families, but they've never gathered enough evidence for prosecution. Most experts assume the artwork was either destroyed or is hidden somewhere, too famous to sell. The empty frames remain, a monument to the greatest unsolved art crime in history.`,
    design_config: {"thumbnailColor":"#4A148C","titlePage":{"backgroundColor":"#4A148C","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#4A148C","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#4A148C"},{"background":"#CE93D8","text":"#000000"}],"imagePlaceholderColors":["#4A148C","#CE93D8"],"imageAspectRatios":[1.5,0.9],"imageColorOffset":1,"imagePositionSeed":3}
  },
  {
    slug: "counterfeit-wine-billions",
    title: "The Wine Faker's Millions",
    description: "He forged bottles worth fortunes",
    category: "Crime",
    thumbnail_color: "#7B1FA2",
    body_text: `Rudy Kurniawan sold millions of dollars worth of rare wines that he had made in his kitchen. For years, he was celebrated as one of the world's greatest wine collectors. He was actually one of its greatest forgers. Kurniawan arrived in the Los Angeles wine scene in the early 2000s, a young Indonesian immigrant with seemingly unlimited money and an incredible palate. He bought rare bottles at auction, hosted legendary tastings, and built a reputation as a connoisseur's connoisseur. The most elite wine collectors considered him a friend. What they didn't know was that Kurniawan was manufacturing fake wine in industrial quantities. He would buy cheap bottles, strip off their labels, and replace them with counterfeit labels from prestigious estates. The corks were artificially aged using dirt and rubber bands. The bottles were filled with blends designed to approximate the taste of famous vintages. He sold these fakes at auction for fortunes—sometimes hundreds of thousands of dollars per bottle. The scheme unraveled when he consigned a collection of Domaine Ponsot Clos Saint-Denis for auction. The wine was supposedly from 1945 and earlier. But Laurent Ponsot, the domain's owner, knew that his family hadn't made that wine until 1982. The vintage simply didn't exist. FBI agents raided Kurniawan's house and found a counterfeiting operation in full swing: thousands of labels, rubber stamps, empty bottles waiting to be filled, and notebooks detailing his blending recipes. They estimated he had sold at least thirty million dollars worth of fake wine. Kurniawan was convicted in 2013 and sentenced to ten years in federal prison. Wine experts believe many of his fakes are still circulating, sitting in collectors' cellars, waiting to be opened by people who have no idea they paid a fortune for Kurniawan's kitchen blends.`,
    design_config: {"thumbnailColor":"#7B1FA2","titlePage":{"backgroundColor":"#7B1FA2","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#7B1FA2","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#7B1FA2"},{"background":"#F3E5F5","text":"#7B1FA2"}],"imagePlaceholderColors":["#7B1FA2","#F3E5F5"],"imageAspectRatios":[1.4,0.85],"imageColorOffset":0,"imagePositionSeed":2}
  },
  {
    slug: "bitcoin-pizza-crime",
    title: "The $800 Million Pizza Order",
    description: "The most expensive meal in history",
    category: "Crime",
    thumbnail_color: "#FF6F00",
    body_text: `On May 22, 2010, a programmer named Laszlo Hanyecz paid 10,000 Bitcoin for two pizzas. At the time, this seemed like a reasonable deal—Bitcoin was worth almost nothing, and Hanyecz wanted to prove the cryptocurrency could be used for real transactions. Those 10,000 Bitcoin would eventually be worth over eight hundred million dollars. The pizza purchase is remembered as the first real-world Bitcoin transaction and celebrated annually as "Bitcoin Pizza Day." But it also illustrates something darker: the staggering wealth that early Bitcoin adopters could have accumulated if they'd simply held onto their coins instead of spending them. Hanyecz himself has said he doesn't regret the purchase. He wanted to support the development of Bitcoin, and spending it on everyday items was part of that support. He continued to buy pizza with Bitcoin throughout 2010, spending over a hundred thousand coins total. All of them would eventually be worth billions. The early Bitcoin community was small and idealistic. Most participants were programmers and cryptography enthusiasts who believed they were building something important, not getting rich. They traded Bitcoin freely, sometimes giving away thousands of coins to strangers who expressed interest. Many of those coins were lost when hard drives crashed or passwords were forgotten. One man in Wales accidentally threw away a hard drive containing 7,500 Bitcoin, now worth hundreds of millions. The pizza transaction wasn't a crime, of course. But it represents a kind of innocent loss that haunts cryptocurrency history. Every early Bitcoin user who spent or lost their coins is left wondering what might have been. The two pizzas that Laszlo Hanyecz bought were from Papa John's. They cost about twenty-five dollars. Adjusted for Bitcoin's peak value, they remain the most expensive pizzas ever purchased.`,
    design_config: {"thumbnailColor":"#FF6F00","titlePage":{"backgroundColor":"#FF6F00","textColor":"#000000"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#FF6F00","text":"#000000"},{"background":"#FFFFFF","text":"#FF6F00"},{"background":"#FFD60A","text":"#000000"}],"imagePlaceholderColors":["#FF6F00","#FFD60A"],"imageAspectRatios":[1.3,0.9],"imageColorOffset":1,"imagePositionSeed":4}
  },
  {
    slug: "imposter-fake-pilot",
    title: "The Fake Pilot Who Flew",
    description: "He conned his way into cockpits",
    category: "Crime",
    thumbnail_color: "#0277BD",
    body_text: `Frank Abagnale Jr. successfully posed as a Pan Am pilot for two years, flying over a million miles on more than 250 flights—all without knowing how to fly a plane. He was sixteen years old when he started. Abagnale's story, later dramatized in the film "Catch Me If You Can," began when he ran away from home in New York in 1964. Discovering that pilots received respect and free travel, he obtained a Pan Am uniform by claiming his own had been lost at a hotel dry cleaner. He forged an employee ID and FAA pilot's license. He then exploited a practice called "deadheading," in which off-duty pilots rode free in the cockpit jump seat to reach their next assignment. Airlines didn't verify credentials because pilots from different companies constantly deadheaded together. Abagnale never actually flew a plane—he just sat in the jump seat and let the real pilots do the work. When asked to take the controls, he would claim to be exhausted from a long previous flight. Over time, he became skilled at pilot jargon and cockpit procedures. Pan Am employees assumed he was legitimate because he acted like he belonged. The con eventually ended, but Abagnale didn't stop impersonating professionals. He also posed as a doctor, a lawyer, and a college professor, forging credentials for each role. He passed the Louisiana bar exam on his third attempt, having studied law on his own. When finally caught and imprisoned, Abagnale served time in France, Sweden, and the United States. He was released early and hired as a consultant by the FBI, eventually building a legitimate career advising businesses on fraud prevention. The teenage con man who faked his way around the world became one of the country's leading experts on how to spot fakes.`,
    design_config: {"thumbnailColor":"#0277BD","titlePage":{"backgroundColor":"#0277BD","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#0277BD","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#0277BD"},{"background":"#B3E5FC","text":"#000000"}],"imagePlaceholderColors":["#0277BD","#B3E5FC"],"imageAspectRatios":[1.5,0.85],"imageColorOffset":0,"imagePositionSeed":3}
  },
  {
    slug: "crow-police-informant",
    title: "The Crow That Solved Crimes",
    description: "A bird became a police witness",
    category: "Crime",
    thumbnail_color: "#212121",
    body_text: `In the 1990s, a crow in the Netherlands helped police solve multiple car break-ins by identifying suspects. The bird, trained by a retired police officer, would perch near crime scenes and later react to photographs of people it had observed. It wasn't admissible in court, but it led to convictions anyway. The crow's owner, a former detective named Dirk van der Laan, had spent years studying corvid intelligence. He knew that crows could recognize human faces and remember them for years. He theorized that a trained crow might remember the faces of criminals it witnessed committing crimes. Van der Laan stationed his crow near areas where car break-ins were frequent. When police developed suspects, they would show photographs to the bird. If the crow reacted with agitation to a particular photo, police would investigate that suspect more closely. The method was unconventional but effective. In several cases, the crow's identification led police to evidence that produced convictions. Suspects confessed when confronted with the evidence, never knowing that their initial identification came from a bird. The technique never gained widespread acceptance. Courts wouldn't accept crow identifications, and most police departments considered the method too strange to adopt. But van der Laan's experiments demonstrated something important about corvid cognition: crows are excellent witnesses. They notice details. They remember faces. They hold grudges against people who have wronged them. Researchers at the University of Washington later confirmed that crows can remember human faces for at least five years and will warn other crows about dangerous individuals. The birds even teach their offspring which humans to fear. Van der Laan's crime-solving crow was ahead of its time—a pioneer in a field that science would eventually validate.`,
    design_config: {"thumbnailColor":"#212121","titlePage":{"backgroundColor":"#212121","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#212121","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#212121"},{"background":"#757575","text":"#FFFFFF"}],"imagePlaceholderColors":["#212121","#757575"],"imageAspectRatios":[1.4,0.9],"imageColorOffset":1,"imagePositionSeed":2}
  },
  {
    slug: "prison-built-by-prisoners",
    title: "Prisoners Built Their Own Prison",
    description: "Convicts who constructed Alcatraz",
    category: "Crime",
    thumbnail_color: "#455A64",
    body_text: `When Alcatraz needed repairs in the 1930s, the prison used its own inmates as construction workers. Convicted bank robbers, kidnappers, and murderers spent years rebuilding the very facility designed to hold them. The irony was not lost on anyone involved. Alcatraz Island had been a military fortification and prison since the Civil War. When it became a federal penitentiary in 1934, the existing structures were in poor condition. The Bureau of Prisons faced a choice: hire expensive outside contractors to visit a remote island filled with dangerous criminals, or use the criminals themselves. They chose the criminals. Inmates poured concrete, laid bricks, installed plumbing, and wired electrical systems. They built the very cells that would contain them and the walls that would surround them. Guards supervised carefully, but the prisoners did the actual work. Some inmates became skilled tradesmen during their incarceration. They learned construction techniques they couldn't have accessed on the outside, ironically gaining job skills while serving time for crimes that had nothing to do with construction. When they were eventually released, some found legitimate work in the building trades. The arrangement also created security vulnerabilities that inmates occasionally exploited. Workers learned the layout of the prison more intimately than any guard. They knew where pipes ran, which walls were hollow, and where structural weaknesses might be hidden. The famous 1962 escape, in which three men vanished through holes they had chipped behind their cells, may have been aided by knowledge gained during construction work. Alcatraz closed in 1962, deemed too expensive to maintain. The prisoners' construction work had extended its life by decades, but the old military fortress was never suited to be a modern prison. Today it's a national park, and rangers tell visitors about the men who built their own cage.`,
    design_config: {"thumbnailColor":"#455A64","titlePage":{"backgroundColor":"#455A64","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#455A64","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#455A64"},{"background":"#B0BEC5","text":"#000000"}],"imagePlaceholderColors":["#455A64","#B0BEC5"],"imageAspectRatios":[1.5,0.85],"imageColorOffset":0,"imagePositionSeed":4}
  },
  {
    slug: "fingerprints-twins-different",
    title: "Identical Twins' Different Prints",
    description: "The one thing twins don't share",
    category: "Crime",
    thumbnail_color: "#3E2723",
    body_text: `Identical twins share the same DNA, the same blood type, the same face—but not the same fingerprints. This quirk of biology has solved crimes that genetic evidence could not. Fingerprints form in the womb during the second trimester of pregnancy. They're created by the random folding of skin as it develops over the underlying tissue. Even though identical twins share genetic instructions, the exact pattern of that folding is influenced by tiny variations in position, nutrition, and movement that differ between twins. The result is that no two people in history have ever had matching fingerprints—not even twins who are otherwise genetically indistinguishable. This became crucial in criminal cases where DNA evidence implicated twins without distinguishing between them. In 2004, British authorities used fingerprints to convict the correct twin of a robbery after DNA testing pointed to both brothers. In 2009, Malaysian police solved a drug trafficking case the same way. The fingerprint exception has fascinated researchers who study identity. If genetics determined everything about us, identical twins would be truly identical. The fact that fingerprints differ proves that random chance plays a role in who we become, even in something as basic as the ridges on our fingertips. Police rely on this randomness. Fingerprint databases contain millions of records, and matches can be made with extremely high confidence. When DNA testing was introduced, some predicted it would make fingerprints obsolete. Instead, the two technologies complement each other. DNA tells you who the suspect might be. Fingerprints tell you which twin left the print. In a world where identical twins are increasingly common due to fertility treatments, that distinction matters more than ever.`,
    design_config: {"thumbnailColor":"#3E2723","titlePage":{"backgroundColor":"#3E2723","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#3E2723","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#3E2723"},{"background":"#8D6E63","text":"#FFFFFF"}],"imagePlaceholderColors":["#3E2723","#8D6E63"],"imageAspectRatios":[1.4,0.85],"imageColorOffset":1,"imagePositionSeed":3}
  },
  {
    slug: "casino-whale-baccarat",
    title: "The Gambler Who Broke Casinos",
    description: "How one man won $15 million",
    category: "Crime",
    thumbnail_color: "#B71C1C",
    body_text: `Phil Ivey won fifteen million dollars playing baccarat at two different casinos using a technique called "edge sorting." The casinos called it cheating. The courts agreed—sort of. Edge sorting exploits microscopic imperfections in the patterns on playing card backs. These imperfections, invisible to casual observation, can reveal whether a card is high or low if you know what to look for. Ivey knew what to look for. His scheme was elegant. While playing baccarat, he convinced casino staff to rotate certain cards, claiming it was a superstitious ritual for good luck. Once the deck was arranged with valuable cards oriented differently from worthless ones, Ivey could identify them from behind. He bet accordingly and won consistently. At the Borgata in Atlantic City, he won $9.6 million over four sessions. At Crockfords in London, he won another $10 million (which the casino refused to pay). When the casinos discovered what Ivey had done, they sued. The legal battles that followed hinged on whether edge sorting constituted cheating. Ivey hadn't marked the cards himself—he had merely exploited defects that already existed. He hadn't used any devices. He had simply looked at the cards more carefully than anyone expected. Courts ultimately ruled against Ivey in both jurisdictions. The judges acknowledged that he hadn't cheated in the traditional sense but found that his technique violated the implicit contract of fair play between gamblers and casinos. Ivey was ordered to return his winnings. The decisions remain controversial among gamblers. Casinos, after all, use every statistical advantage available to them. Why shouldn't players do the same? The difference, courts suggested, is that Ivey's technique required deceiving casino staff about his true intentions. The superstitious requests weren't superstitious at all. That deception crossed the line.`,
    design_config: {"thumbnailColor":"#B71C1C","titlePage":{"backgroundColor":"#B71C1C","textColor":"#FFD60A"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#B71C1C","text":"#FFFFFF"},{"background":"#FFD60A","text":"#000000"},{"background":"#FFFFFF","text":"#B71C1C"}],"imagePlaceholderColors":["#B71C1C","#FFD60A"],"imageAspectRatios":[1.3,0.9],"imageColorOffset":0,"imagePositionSeed":2}
  },
  {
    slug: "escaped-using-spoon",
    title: "The Great Spoon Escape",
    description: "He tunneled out with cutlery",
    category: "Crime",
    thumbnail_color: "#546E7A",
    body_text: `John Dillinger, America's most wanted criminal in 1934, escaped from an "escape-proof" Indiana prison using what appeared to be a gun carved from a wooden washboard, blackened with shoe polish. But the real story of improvised prison escapes involves something even more mundane: spoons. Throughout history, prisoners have used spoons to tunnel their way to freedom. The implements are small enough to hide, strong enough to scrape mortar, and universally available in prison dining halls. Security officials have waged a decades-long war against the humble spoon. In 1962, the famous Alcatraz escapees—Frank Morris and the Anglin brothers—used modified spoons to dig through the concrete around their cell vents. They made their digging tools by attaching spoon bowls to stolen electric fan motors. The work took over a year, conducted in tiny increments during nighttime hours. In 2015, two murderers escaped from a maximum-security New York prison using tools smuggled in frozen hamburger meat—including hacksaw blades that they reportedly acquired by promising a prison employee romantic attention. But spoons had started the holes. The men had spent months weakening their cell walls with nothing more than eating utensils. Modern prisons have responded by restricting spoon access, using plastic cutlery that breaks before it can damage concrete, and employing metal detectors that can identify hidden implements. Some facilities count spoons obsessively, reporting any missing utensil as a potential security threat. But determined prisoners remain creative. In 2020, a South Carolina inmate was caught digging an escape tunnel using a plastic spork from his lunch tray. The tool had broken multiple times, but he kept at it, replacing each broken spork with the next day's. Security found the tunnel before he could complete it—barely.`,
    design_config: {"thumbnailColor":"#546E7A","titlePage":{"backgroundColor":"#546E7A","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#546E7A","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#546E7A"},{"background":"#B0BEC5","text":"#000000"}],"imagePlaceholderColors":["#546E7A","#B0BEC5"],"imageAspectRatios":[1.5,0.85],"imageColorOffset":1,"imagePositionSeed":4}
  },
  {
    slug: "detective-never-gave-up",
    title: "The 50-Year Cold Case",
    description: "A detective's dying obsession",
    category: "Crime",
    thumbnail_color: "#1B5E20",
    body_text: `When Detective Dave Reichert retired from the King County Sheriff's Office in 2007, he had spent thirty years pursuing one case: the Green River Killer. The murderer had killed at least forty-nine women. For most of those three decades, he remained unknown. The Green River murders began in 1982 when bodies started appearing along the Green River near Seattle. The victims were mostly young women, many of them sex workers or runaways. The killer strangled them, then dumped their bodies in clusters throughout the region. Reichert was assigned to the task force from the beginning. He was a young detective when the first bodies were found and a gray-haired veteran when the case finally broke. He interviewed hundreds of suspects. He followed thousands of tips. He watched as colleagues transferred away, retired, or died while he kept working the same case. Gary Ridgway, a truck painter who had been questioned and released in 1984 and again in 1987, was finally arrested in 2001 after new DNA technology matched him to the crimes. He confessed to forty-eight murders and led police to additional victims' remains. The total may have been higher—Ridgway himself couldn't remember exactly how many women he had killed. Reichert was there for the arrest, the confession, and the sentencing. By then, he had dedicated half his life to catching one man. The case had cost him his first marriage and much of his personal life. It had also driven him to become sheriff and eventually a United States Congressman. Some of the victims were never identified. Some were never found. Reichert kept photographs of them all on his office wall—the known and the unknown, the named and the nameless. He retired but never really let go of the case. Some obsessions don't end with arrests.`,
    design_config: {"thumbnailColor":"#1B5E20","titlePage":{"backgroundColor":"#1B5E20","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#1B5E20","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#1B5E20"},{"background":"#A5D6A7","text":"#000000"}],"imagePlaceholderColors":["#1B5E20","#A5D6A7"],"imageAspectRatios":[1.4,0.9],"imageColorOffset":0,"imagePositionSeed":3}
  },
  {
    slug: "bank-robber-polite-note",
    title: "The Most Polite Bank Robber",
    description: "He asked nicely for the money",
    category: "Crime",
    thumbnail_color: "#00838F",
    body_text: `Between 2003 and 2009, a bank robber known as the "Gentleman Bandit" robbed at least thirty banks across California. He never used a weapon. He never raised his voice. He simply handed tellers polite notes asking for money, and they gave it to him. The notes were remarkably courteous. "Good morning," one read. "This is a bank robbery. Please give me all the money from your drawer. I'm sorry to have to do this but I need the money." Another apologized for the inconvenience. Several thanked tellers for their cooperation. The robber, later identified as Mark Smith, spoke softly and dressed in business casual. He never wore a disguise. He walked into banks during business hours, waited in line like a regular customer, and conducted his robberies as though he were making routine withdrawals. Tellers consistently described him as calm, professional, and genuinely apologetic. Smith's politeness served a purpose. Calm robbers receive larger amounts because tellers aren't panicked. Unarmed robbers trigger fewer alarms. Pleasant interactions make witnesses' memories less reliable—people remember threats more clearly than courtesies. Smith understood that aggression was counterproductive. The FBI eventually identified Smith through bank surveillance photographs. When agents arrested him in 2009, he was living in a modest apartment and had spent most of his stolen money on ordinary expenses. He wasn't wealthy. He wasn't financing anything exotic. He had simply found a low-risk way to make a living and pursued it for six years. In court, Smith pleaded guilty and received a twelve-year sentence. Several tellers wrote letters describing their interactions with him. None expressed anger. Some said he was the most pleasant person who had ever robbed them. The Gentleman Bandit, it seemed, had made a lasting impression.`,
    design_config: {"thumbnailColor":"#00838F","titlePage":{"backgroundColor":"#00838F","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#00838F","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#00838F"},{"background":"#B2EBF2","text":"#000000"}],"imagePlaceholderColors":["#00838F","#B2EBF2"],"imageAspectRatios":[1.5,0.85],"imageColorOffset":1,"imagePositionSeed":2}
  },
  {
    slug: "pink-panthers-diamond",
    title: "The Pink Panthers' Perfect Heists",
    description: "The gang that stole $500 million",
    category: "Crime",
    thumbnail_color: "#E91E63",
    body_text: `The Pink Panthers are the most successful jewel thieves in history, responsible for an estimated five hundred million dollars in stolen gems across more than twenty countries. Their name comes from a 2003 heist in London where a thief hid a stolen diamond in a jar of face cream—a technique used in the classic "Pink Panther" films. The gang isn't a traditional criminal organization. It's a loose network of professionals, many from the former Yugoslavia, who collaborate on specific jobs and then disperse. At their peak, they executed multiple spectacular heists per year, moving across borders with ease. In 2008, four Pink Panthers dressed as women walked into a jewelry store in Dubai, produced axes, smashed display cases, and escaped with thirty-five million dollars in diamonds in less than two minutes. In 2013, a lone member walked into a hotel jewelry exhibition in Cannes and escaped with over one hundred million dollars in a single bag. The heists follow a pattern. Teams conduct extensive surveillance, sometimes for months, before striking. They work quickly—most robberies last under three minutes. They rarely use lethal violence, preferring speed and shock to confrontation. They target high-value jewelry that can be smuggled easily across borders. Interpol has identified over eight hundred individuals associated with the network, but arrests have done little to slow operations. Members serve their sentences and return to work. The gang replaces captured members with new recruits. The estimated half billion dollars they've stolen has never been recovered. Some experts believe the Pink Panthers represent a new kind of criminal enterprise—decentralized, international, and virtually impossible to dismantle. As long as there are diamonds worth stealing, there will be Panthers willing to steal them.`,
    design_config: {"thumbnailColor":"#E91E63","titlePage":{"backgroundColor":"#E91E63","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#E91E63","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#E91E63"},{"background":"#F8BBD0","text":"#E91E63"}],"imagePlaceholderColors":["#E91E63","#F8BBD0"],"imageAspectRatios":[1.4,0.9],"imageColorOffset":0,"imagePositionSeed":4}
  },
  {
    slug: "body-farm-forensics",
    title: "The Body Farm's Dark Science",
    description: "Where corpses become evidence",
    category: "Crime",
    thumbnail_color: "#33691E",
    body_text: `In 1981, a forensic anthropologist named William Bass founded the world's first outdoor laboratory for studying human decomposition. Located on a wooded hillside in Tennessee, the facility became known as "the Body Farm." Donated corpses are placed outdoors in various conditions—buried, submerged in water, locked in car trunks, left exposed to the elements—while scientists observe how they decompose. Before Bass's facility, forensic science had limited understanding of what happens to bodies after death. Time-of-death estimates were often wildly inaccurate. Insects found on corpses couldn't be reliably linked to decomposition stages. Defense attorneys regularly challenged forensic testimony because the underlying science was so incomplete. The Body Farm changed everything. By studying hundreds of donated bodies over decades, researchers developed precise timelines for decomposition in different conditions. They learned which insects arrive at which stages, how temperature affects decay, and what chemical signatures remain long after death. This knowledge has helped solve countless murder cases. The original facility in Knoxville has been joined by similar research centers across the United States. Each one accepts donated bodies from people who want their deaths to serve justice. The waiting lists are long—people sign up years in advance. Some families visit to see where their loved ones will end up, walking through fields where other bodies lie in various states of decay. The work remains controversial. Neighbors have complained about odors. Some religious groups object to the treatment of human remains. The researchers themselves admit that their workplace is deeply strange. But the science has become essential to criminal investigation. Every time a prosecutor presents forensic evidence about time of death or body disposal, the Body Farm's research underlies the testimony. The dead are helping to catch the killers of other dead.`,
    design_config: {"thumbnailColor":"#33691E","titlePage":{"backgroundColor":"#33691E","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#33691E","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#33691E"},{"background":"#DCEDC8","text":"#000000"}],"imagePlaceholderColors":["#33691E","#DCEDC8"],"imageAspectRatios":[1.3,0.85],"imageColorOffset":1,"imagePositionSeed":3}
  },
  {
    slug: "statue-of-liberty-ransom",
    title: "The Statue of Liberty Ransom",
    description: "When terrorists demanded payment",
    category: "Crime",
    thumbnail_color: "#2E7D32",
    body_text: `In 1965, a group calling itself the "Black Liberation Front" claimed to have planted twenty-five sticks of dynamite inside the Statue of Liberty. They demanded that all African Americans be released from prison immediately, or they would destroy one of America's most beloved monuments. The NYPD's bomb squad spent sixteen terrifying hours searching Lady Liberty from torch to foundation. They found nothing. The threat was a hoax—but it revealed how vulnerable America's most iconic landmark was to attack. Security at the statue was minimal in 1965. Visitors could climb through the interior unmonitored. The hollow copper shell could conceal explosives indefinitely. If someone had actually planted bombs, they might have gone undetected for months. The hoax changed everything. The National Park Service implemented new security protocols. Visitors' bags were searched. Rangers began conducting regular sweeps of the interior. The days of unrestricted access to Lady Liberty were over. Subsequent decades brought more threats. In 1980, Croatian nationalists climbed into the statue's crown and unfurled a banner demanding independence for their homeland. In 2001, after the September 11 attacks, the statue was closed entirely for three years. When it reopened, visitors could no longer access the torch, and crown tickets became limited and expensive. Today, visiting the Statue of Liberty requires passing through airport-style security, reserving tickets months in advance, and accepting restrictions that would have been unimaginable in 1965. The Black Liberation Front hoax, whatever its motivations, helped create this reality. A fake bomb threat revealed real vulnerabilities and transformed how America protects its symbols. The statue still stands, but the freedom it represents has become harder to access.`,
    design_config: {"thumbnailColor":"#2E7D32","titlePage":{"backgroundColor":"#2E7D32","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#2E7D32","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#2E7D32"},{"background":"#A5D6A7","text":"#000000"}],"imagePlaceholderColors":["#2E7D32","#A5D6A7"],"imageAspectRatios":[1.5,0.9],"imageColorOffset":0,"imagePositionSeed":2}
  },
  {
    slug: "thief-returned-art",
    title: "The Thief Who Returned Everything",
    description: "Guilt made him give it all back",
    category: "Crime",
    thumbnail_color: "#6A1B9A",
    body_text: `In 2005, a Swedish man walked into a museum in Stockholm and confessed to stealing art worth millions of dollars. Then he returned it. He had been living with the guilt for over twenty years. The thief, whose identity was protected under Swedish law, had stolen works by Picasso, Braque, and other major artists from private collections and small museums throughout the 1970s and 1980s. He had kept the paintings hidden in his home, occasionally looking at them but never trying to sell them. The art was too famous—any attempt to sell would have led to immediate arrest. Decades passed. The thief married, had children, grew old. The stolen paintings stayed in his closet, a secret he had never shared with anyone. As he aged, the guilt became unbearable. He couldn't die with this burden on his conscience. His confession shocked the Swedish art world. The works he returned included pieces that had been missing for so long that insurance companies had paid out claims and museums had given up hope. Some of the art was in remarkable condition; some had suffered from improper storage. The thief received a reduced sentence in exchange for his cooperation. Swedish authorities were more interested in recovering the art than in punishing a repentant old man. He served a brief prison term and returned to private life. His name was never released. Art crime experts say his story is more common than people realize. Many art thieves discover that stolen masterpieces are worthless—too famous to sell, too incriminating to keep, too heavy a burden to bear. Some destroy what they've stolen. Some hide it for decades. A few, like the Swedish thief, eventually find that guilt is heavier than any painting.`,
    design_config: {"thumbnailColor":"#6A1B9A","titlePage":{"backgroundColor":"#6A1B9A","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#6A1B9A","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#6A1B9A"},{"background":"#E1BEE7","text":"#6A1B9A"}],"imagePlaceholderColors":["#6A1B9A","#E1BEE7"],"imageAspectRatios":[1.4,0.85],"imageColorOffset":1,"imagePositionSeed":4}
  },
  {
    slug: "atm-glitch-millionaire",
    title: "The ATM Glitch Millionaire",
    description: "He found a bug worth millions",
    category: "Crime",
    thumbnail_color: "#0D47A1",
    body_text: `In 2010, an Australian man discovered that his bank's ATM had a software glitch. He could withdraw unlimited amounts of money from any account by exploiting the error. Over five months, he took 1.1 million dollars. Then he tried to return it. Dan Saunders was a barman in Melbourne when he discovered the flaw. The bank's system didn't properly record after-hours transactions from certain ATMs. Money withdrawn overnight wouldn't be deducted from account balances until the following morning—and by then, Saunders could repeat the process. He started small, withdrawing a few hundred dollars to test the glitch. When the money never disappeared from his balance, he escalated. Soon he was pulling thousands per night, funding a lifestyle of expensive bars, hotels, and gambling. He gave money to friends. He bought round after round of drinks for strangers. The guilt began almost immediately. Saunders knew what he was doing was wrong. He also couldn't stop. The easy money was addictive. Every night he told himself this would be the last withdrawal. Every night he went back to the ATM. After five months, Saunders walked into a police station and confessed everything. He showed detectives records of every withdrawal. He offered to work with the bank to identify and fix the glitch. He asked to return the money he hadn't spent—though by then, most of it was gone. The bank declined to press criminal charges at first, apparently embarrassed by the security flaw. But when prosecutors learned about the case, they pursued it anyway. Saunders was convicted of fraud and sentenced to community service. He had wanted to do the right thing. He just couldn't stop doing the wrong thing first.`,
    design_config: {"thumbnailColor":"#0D47A1","titlePage":{"backgroundColor":"#0D47A1","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#0D47A1","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#0D47A1"},{"background":"#BBDEFB","text":"#000000"}],"imagePlaceholderColors":["#0D47A1","#BBDEFB"],"imageAspectRatios":[1.5,0.85],"imageColorOffset":0,"imagePositionSeed":3}
  },
  {
    slug: "prison-escape-cardboard",
    title: "The Cardboard Dummy Escape",
    description: "They left fake heads in their beds",
    category: "Crime",
    thumbnail_color: "#424242",
    body_text: `The 1962 Alcatraz escape remains unsolved partly because the prisoners who attempted it were such skilled craftsmen. Frank Morris and the Anglin brothers spent months creating fake heads from soap, toilet paper, and real human hair—so realistic that guards thought they were sleeping peacefully while the men tunneled to freedom. The heads are still on display at Alcatraz today, haunting reminders of the prisoners' ingenuity. Each head features painted skin, detailed facial features, and hair salvaged from the prison barbershop. In dim cell lighting, during routine nighttime bed checks, they were convincing enough to buy the escapees hours of time. The escape plan was elaborate. The men had dug through the ventilation shafts behind their cells using improvised tools, including the famous modified spoons. They had constructed a raft from raincoats, sealed with contact cement stolen from the prison workshop. Everything required secrecy, patience, and manual skill that most people would consider impossible in a maximum-security prison. The dummy heads solved a specific problem: guards conducted nightly bed checks by shining flashlights through cell bars. If a man's bed appeared occupied, guards moved on. The heads just needed to fool observers for a few seconds at a time. They succeeded. By morning, the three men were gone, along with a fourth prisoner whose raft apparently failed during the escape attempt. The FBI concluded that the escapees probably drowned in San Francisco Bay's frigid waters, but no bodies were ever found. The case officially remains open. The dummy heads became famous as symbols of prisoner ingenuity. But they also demonstrated something else: the power of patience and craft. Morris and the Anglins spent over a year preparing. Their fake heads, like everything else about the escape, represented months of careful work, done in secret, one small step at a time.`,
    design_config: {"thumbnailColor":"#424242","titlePage":{"backgroundColor":"#424242","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#424242","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#424242"},{"background":"#BDBDBD","text":"#000000"}],"imagePlaceholderColors":["#424242","#BDBDBD"],"imageAspectRatios":[1.4,0.9],"imageColorOffset":1,"imagePositionSeed":2}
  }
];

async function uploadStory(story) {
  const response = await fetch(`${SUPABASE_URL}/rest/v1/stories`, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      "apikey": SUPABASE_KEY,
      "Authorization": `Bearer ${SUPABASE_KEY}`,
      "Prefer": "resolution=merge-duplicates,return=minimal"
    },
    body: JSON.stringify({
      slug: story.slug,
      title: story.title,
      description: story.description,
      category: story.category,
      thumbnail_color: story.thumbnail_color,
      published: true,
      published_at: new Date().toISOString(),
      body_text: story.body_text,
      design_config: story.design_config,
      updated_at: new Date().toISOString()
    })
  });

  if (!response.ok) {
    const text = await response.text();
    throw new Error(`${response.status}: ${text}`);
  }
}

async function main() {
  console.log(`Uploading ${stories.length} Crime "Did You Know" stories to Supabase...\n`);

  let success = 0;
  let failed = 0;

  for (const story of stories) {
    try {
      process.stdout.write(`Uploading: ${story.title}... `);
      await uploadStory(story);
      console.log("Done!");
      success++;
    } catch (error) {
      console.log(`Error: ${error.message}`);
      failed++;
    }
  }

  console.log(`\nComplete! ${success} succeeded, ${failed} failed.`);
}

main();
