/**
 * Economics Category - 25 "Did You Know" Stories
 * Usage: node scripts/new-content-dyk/economics-dyk.mjs
 */

const SUPABASE_URL = "https://egfwisgqdyhzpmeoracb.supabase.co";
const SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVnZndpc2dxZHloenBtZW9yYWNiIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2ODQyNzM0OSwiZXhwIjoyMDg0MDAzMzQ5fQ.S8h1fIepxWb44gPSPpWQ8fE0Q-SCYfL0QcBRUV7fXgs";

const stories = [
  {
    slug: "sweden-raisin-monopoly",
    title: "Sweden's Strange Raisin Trade",
    description: "The monopoly that shaped a nation",
    category: "Economics",
    thumbnail_color: "#5D4037",
    body_text: `For over three hundred years, Sweden controlled the European raisin trade through a bizarre monopoly that shaped its economy and foreign policy. The arrangement began in 1628 and didn't end until the nineteenth century. It remains one of the strangest trade arrangements in European history. The monopoly started when Sweden granted exclusive raisin import rights to a single trading company. All raisins entering the country had to pass through this company, which set prices and controlled distribution. The company became fabulously wealthy, and its owners gained enormous political influence. But why raisins? In seventeenth-century Scandinavia, raisins were considered essential. They were one of the few ways to add sweetness to foods during long winters when fresh fruit was unavailable. They could be stored indefinitely. They were used in medicine, brewing, and religious ceremonies. Controlling raisins meant controlling a basic necessity. The monopoly also served political purposes. Sweden's kings used raisin import licenses as rewards for loyal nobles. Threatening to revoke someone's raisin privileges was a powerful tool of statecraft. The entire system was designed to concentrate wealth and power while ensuring a steady supply of a product that ordinary Swedes considered vital. By the late eighteenth century, the monopoly had become corrupt and inefficient. Smugglers brought in raisins through Finland and Norway. Official prices rose while quality declined. When Sweden finally liberalized trade in the 1800s, the raisin monopoly was among the first restrictions to fall. Today, Sweden imports raisins freely from around the world. Few Swedes know that their ancestors lived under a raisin regime that lasted longer than the American Constitution.`,
    design_config: {"thumbnailColor":"#5D4037","titlePage":{"backgroundColor":"#5D4037","textColor":"#FFD60A"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#5D4037","text":"#FFFFFF"},{"background":"#FFD60A","text":"#000000"},{"background":"#FFFFFF","text":"#5D4037"}],"imagePlaceholderColors":["#5D4037","#FFD60A"],"imageAspectRatios":[1.4,0.85],"imageColorOffset":0,"imagePositionSeed":2}
  },
  {
    slug: "yap-stone-money",
    title: "The Island of Giant Stone Money",
    description: "Currency too heavy to move",
    category: "Economics",
    thumbnail_color: "#607D8B",
    body_text: `On the Pacific island of Yap, money takes the form of massive limestone disks, some weighing more than a car. The largest are over twelve feet in diameter. And here's the strangest part: even when these stones sink to the ocean floor, they still function as currency. The Yapese call their stone money "rai." For centuries, islanders carved these disks on distant Palau, then transported them across four hundred miles of open ocean in canoes. The difficulty of the journey added value—a stone that cost many lives to transport was worth more than one acquired easily. The size of a stone matters less than its history. When a rai changes owners, nobody moves it. The stone stays where it has always been—in front of a village, along a path, or at the bottom of the sea. Everyone simply agrees that ownership has transferred. A stone can lie underwater for generations while remaining a valid form of currency, changing hands repeatedly without anyone touching it. This system fascinates economists because it demonstrates that money doesn't require physical possession. What matters is that everyone agrees on who owns what. The Yapese developed this insight centuries before modern banking, which operates on the same principle. Your bank balance doesn't exist as physical cash in a vault; it exists as a number that everyone agrees represents your money. Today, the Yapese use American dollars for everyday transactions. But stone money still matters for important exchanges—land purchases, political tributes, wedding gifts. The massive disks remain scattered across the island, silent monuments to a monetary system that anticipated the digital age.`,
    design_config: {"thumbnailColor":"#607D8B","titlePage":{"backgroundColor":"#607D8B","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#607D8B","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#607D8B"},{"background":"#B0BEC5","text":"#000000"}],"imagePlaceholderColors":["#607D8B","#B0BEC5"],"imageAspectRatios":[1.3,0.9],"imageColorOffset":1,"imagePositionSeed":3}
  },
  {
    slug: "flash-crash-typo",
    title: "The Trillion-Dollar Typo",
    description: "A keystroke crashed the market",
    category: "Economics",
    thumbnail_color: "#D32F2F",
    body_text: `On May 6, 2010, the American stock market lost nearly a trillion dollars of value in approximately five minutes. Then it recovered almost as quickly. The event, known as the "Flash Crash," was partly triggered by what investigators believe was a simple typographical error. The official story is complicated. A trader at a Kansas City firm wanted to sell a large block of futures contracts. The selling algorithm he used was poorly designed, dumping contracts too fast for the market to absorb. But the initial selling pressure may have been amplified by a data entry error—someone typed a number with too many zeros. The mistake cascaded through a market dominated by high-frequency trading algorithms. These computer programs detected the unusual selling and responded by selling their own positions. Their selling triggered other algorithms to sell. Within minutes, a feedback loop had developed that sent prices into free fall. Blue-chip stocks briefly traded for pennies. Some exchange-traded funds showed prices of zero. The entire financial system seemed to be collapsing. Then, just as suddenly, prices recovered. The algorithms that had caused the crash began buying back the shares they had sold. Within twenty minutes, most stocks had returned to near their original values. Regulators spent months investigating. They implemented new circuit breakers designed to pause trading when prices move too quickly. They examined the role of high-frequency trading in amplifying market movements. But they never fully explained how an algorithm malfunction could temporarily wipe out a trillion dollars. The Flash Crash demonstrated how fragile modern markets have become. Trades that once required human judgment now happen in milliseconds, executed by computers that can amplify small errors into catastrophic collapses.`,
    design_config: {"thumbnailColor":"#D32F2F","titlePage":{"backgroundColor":"#D32F2F","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#D32F2F","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#D32F2F"},{"background":"#FFCDD2","text":"#D32F2F"}],"imagePlaceholderColors":["#D32F2F","#FFCDD2"],"imageAspectRatios":[1.5,0.85],"imageColorOffset":0,"imagePositionSeed":2}
  },
  {
    slug: "bank-run-mary-poppins",
    title: "The Mary Poppins Bank Run",
    description: "A song that almost crashed banks",
    category: "Economics",
    thumbnail_color: "#1976D2",
    body_text: `When Walt Disney's "Mary Poppins" was released in 1964, it included a scene where children cause a bank run by asking for their money back. Disney received letters from bankers worried that the film might inspire real customers to withdraw their savings. Their concerns weren't entirely paranoid. In the film, young Michael Banks wants to spend his tuppence on feeding the pigeons. The stern bankers insist he should invest it instead. When Michael protests loudly, other customers in the bank misunderstand and think their money isn't safe. They rush to withdraw their deposits, causing chaos. The scene was played for comedy, but it illustrated a genuine vulnerability of the banking system. Banks don't keep all depositors' money in the vault—they lend most of it out, keeping only a fraction on hand. If too many customers demand their money at once, the bank runs out of cash, even if it's fundamentally healthy. Real bank runs have been triggered by rumors, newspaper articles, and even dreams. In 1907, a run on New York's Knickerbocker Trust started when depositors heard that the bank had made bad investments—which they had, but the panic made a manageable problem into a catastrophe. Disney's bankers worried that children who watched the film might go home and ask their parents uncomfortable questions about how banking actually worked. If those questions spread, if trust in banks wavered even slightly, the consequences could be serious. The letters from bankers have become a historical curiosity, but the underlying fear was rational. Banking depends on confidence. A song about tuppence and pigeons highlighted just how fragile that confidence can be.`,
    design_config: {"thumbnailColor":"#1976D2","titlePage":{"backgroundColor":"#1976D2","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#1976D2","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#1976D2"},{"background":"#BBDEFB","text":"#000000"}],"imagePlaceholderColors":["#1976D2","#BBDEFB"],"imageAspectRatios":[1.4,0.9],"imageColorOffset":1,"imagePositionSeed":4}
  },
  {
    slug: "hungary-hyperinflation",
    title: "The Worst Inflation in History",
    description: "Prices doubled every 15 hours",
    category: "Economics",
    thumbnail_color: "#C62828",
    body_text: `In 1946, Hungary experienced the worst hyperinflation in recorded history. At its peak, prices doubled approximately every fifteen hours. The government printed banknotes with denominations so large that the numbers became meaningless. Hungary's highest denomination note, the 100 quintillion pengo, was worth less than a penny in American currency. The causes were typical of hyperinflation: a government printing money to pay debts it couldn't otherwise afford. Hungary emerged from World War II devastated, with its infrastructure destroyed and its economy in ruins. Rather than implement painful austerity measures, the government simply printed more currency. The results were catastrophic for ordinary Hungarians. Workers rushed to spend their wages the moment they received them because waiting even hours meant losing purchasing power. People carried money in wheelbarrows and suitcases. Prices were quoted in scientific notation because the numbers were too long to write out. By July 1946, prices were rising so fast that the currency had essentially ceased to function. Shop owners stopped posting prices because they changed too frequently. Barter replaced cash transactions. The pengo became useful mainly as kindling and wallpaper. The crisis ended in August 1946 when Hungary introduced a new currency, the forint. The exchange rate was 400 octillion (that's 400 followed by 27 zeros) pengo to one forint. It remains the largest currency conversion in history. The forint stabilized within weeks, demonstrating that hyperinflation is fundamentally a policy choice—and can be ended with different policy choices. But the trauma of 1946 left lasting scars. Hungarians of a certain generation still remember when money meant nothing.`,
    design_config: {"thumbnailColor":"#C62828","titlePage":{"backgroundColor":"#C62828","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#C62828","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#C62828"},{"background":"#FFCDD2","text":"#C62828"}],"imagePlaceholderColors":["#C62828","#FFCDD2"],"imageAspectRatios":[1.3,0.85],"imageColorOffset":0,"imagePositionSeed":3}
  },
  {
    slug: "tulip-mania-myth",
    title: "Tulip Mania Was Exaggerated",
    description: "The bubble that barely burst",
    category: "Economics",
    thumbnail_color: "#E91E63",
    body_text: `The story of tulip mania—the supposed speculative bubble in 17th-century Netherlands where tulip bulbs sold for more than houses—is largely a myth. The reality was far less dramatic than the legend suggests. According to the standard narrative, Dutch speculators in the 1630s drove tulip prices to absurd heights before the market crashed catastrophically, ruining countless fortunes. This story is cited in almost every economics textbook as the first modern financial bubble. The problem is that the historical evidence doesn't support most of these claims. Modern historians who examined primary sources found that the famous examples of extreme tulip prices—single bulbs trading for thousands of guilders—came from a small number of isolated transactions, often between specialized collectors. The broader tulip market was never that expensive. The "crash" of 1637 did happen, but its effects were limited. Most tulip trading occurred through a system of futures contracts that required little upfront payment. When prices fell, traders simply walked away from their contracts. There's no evidence of widespread bankruptcies, social upheaval, or economic collapse. So where did the myth come from? Mostly from pamphlets written years later by Dutch Calvinists who wanted to condemn speculation as sinful. These morality tales exaggerated the greed and suffering involved, creating a cautionary narrative that persists to this day. The tulip mania myth matters because it shapes how we think about bubbles. We assume all speculative manias end in catastrophic crashes because the tulip story told us so. But bubbles can deflate slowly, and speculation doesn't always destroy economies. The true lesson of the tulips might be that we're too eager to find simple stories in complex economic events.`,
    design_config: {"thumbnailColor":"#E91E63","titlePage":{"backgroundColor":"#E91E63","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#E91E63","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#E91E63"},{"background":"#F8BBD0","text":"#E91E63"}],"imagePlaceholderColors":["#E91E63","#F8BBD0"],"imageAspectRatios":[1.5,0.9],"imageColorOffset":1,"imagePositionSeed":2}
  },
  {
    slug: "mcdonalds-real-estate",
    title: "McDonald's Sells Real Estate",
    description: "The burger chain's secret business",
    category: "Economics",
    thumbnail_color: "#FF6F00",
    body_text: `McDonald's isn't really in the hamburger business. It's in the real estate business. This revelation, supposedly made by founder Ray Kroc himself, explains why the company has become one of the largest property owners in the world. The model works like this: when McDonald's opens a new restaurant, the corporation typically buys or leases the land and building, then rents it to the franchisee who operates the location. The rent is often a percentage of sales, creating an income stream that exceeds what the company makes from selling hamburgers and franchise fees. By owning the real estate, McDonald's gains enormous leverage over its franchisees. Operators who don't follow corporate rules can lose their restaurants entirely—not just the franchise agreement, but the physical location where they've built their business. This power ensures remarkable consistency across thousands of independently operated restaurants. The strategy also creates value that doesn't appear on typical restaurant metrics. McDonald's owns or holds long-term leases on most of its over 40,000 locations worldwide. As property values rise, so does McDonald's underlying wealth. During recessions, when property values fall but people keep buying cheap food, the company can acquire locations at bargain prices. Critics argue that this model extracts wealth from franchisees, who take most of the operational risk while McDonald's captures a guaranteed income stream regardless of how well individual restaurants perform. Supporters counter that the arrangement provides stability—franchisees gain access to prime locations they couldn't afford independently, while the parent company ensures quality control. Either way, the real estate model explains McDonald's remarkable durability. Fast food trends change; restaurant concepts rise and fall. But land in high-traffic locations holds its value. Ray Kroc wasn't selling hamburgers. He was selling access to the best corners in America.`,
    design_config: {"thumbnailColor":"#FF6F00","titlePage":{"backgroundColor":"#FF6F00","textColor":"#000000"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#FF6F00","text":"#000000"},{"background":"#FFFFFF","text":"#FF6F00"},{"background":"#FFF3E0","text":"#FF6F00"}],"imagePlaceholderColors":["#FF6F00","#FFF3E0"],"imageAspectRatios":[1.4,0.85],"imageColorOffset":0,"imagePositionSeed":4}
  },
  {
    slug: "salt-as-salary",
    title: "Your Salary Comes From Salt",
    description: "The origins of what we call pay",
    category: "Economics",
    thumbnail_color: "#BDBDBD",
    body_text: `The word "salary" comes from the Latin "salarium," which referred to a Roman soldier's allowance for purchasing salt. Salt was so valuable in the ancient world that it served as currency, paid taxes, and started wars. The phrase "worth his salt" originally meant someone who earned his wages. Salt's value seems strange today, when it costs pennies and sits in every kitchen. But before refrigeration, salt was essential for preserving food. Without it, meat spoiled within days. Civilizations that controlled salt deposits became wealthy and powerful. Those that didn't had to pay whatever price salt traders demanded. Roman soldiers received part of their compensation in salt or in money specifically designated for salt purchases. The practice spread throughout the Mediterranean world. Salt taxes funded governments from China to France. The word "soldier" may itself derive from "sal dare," to give salt. In some African societies, salt was compressed into standardized blocks that served as money. Merchants accepted salt in trade from Ethiopia to the Sahara. Camel caravans transported salt across deserts, trading it for gold at equal weights. The gold mines of West Africa were useless without salt to pay the miners and preserve the food that fed them. Salt's monetary role declined with modern preservation methods and industrial production. By the late 1800s, salt had become cheap enough that its monetary associations faded from memory. But the language remains. Every time you receive a salary, you're participating in an economic tradition that began when Roman legions marched for their salt.`,
    design_config: {"thumbnailColor":"#BDBDBD","titlePage":{"backgroundColor":"#BDBDBD","textColor":"#000000"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#BDBDBD","text":"#000000"},{"background":"#FFFFFF","text":"#000000"},{"background":"#E0E0E0","text":"#000000"}],"imagePlaceholderColors":["#BDBDBD","#E0E0E0"],"imageAspectRatios":[1.3,0.9],"imageColorOffset":1,"imagePositionSeed":3}
  },
  {
    slug: "coca-cola-cocaine-economics",
    title: "Coca-Cola's Classified Formula",
    description: "The secret worth billions",
    category: "Economics",
    thumbnail_color: "#B71C1C",
    body_text: `Coca-Cola's recipe is one of the most valuable trade secrets in history—worth an estimated sixteen billion dollars. The company goes to extraordinary lengths to protect it, including keeping the written formula in a vault that requires multiple executives to open simultaneously. But the secrecy is more valuable than the secret itself. The recipe has been reverse-engineered multiple times. Food scientists have identified Coca-Cola's main ingredients: sugar, caramel, phosphoric acid, and a blend of flavoring oils that includes cinnamon, lime, vanilla, and others. Competitors have created nearly identical colas. Yet Coca-Cola remains dominant. The secret formula's real value is psychological. By treating the recipe as a closely guarded mystery, Coca-Cola transforms a soft drink into something magical. Marketing campaigns have emphasized the secret for over a century. The vault, the security procedures, the mythology—these create a story that advertising alone couldn't buy. The company has rejected multiple offers to buy the formula, including one reportedly worth billions. Selling would destroy the mystique that makes Coca-Cola worth far more than any recipe could justify. The secret formula has become a symbol of the product itself, inseparable from the brand identity. Other companies have learned from Coca-Cola's example. KFC promotes its secret blend of eleven herbs and spices with similar mystique. The exact formulas of many luxury perfumes are closely guarded. In each case, the secrecy adds value by creating a story. The lesson is paradoxical: sometimes the best business strategy is to make people curious about something that doesn't matter very much. The mystery becomes more valuable than whatever it conceals.`,
    design_config: {"thumbnailColor":"#B71C1C","titlePage":{"backgroundColor":"#B71C1C","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#B71C1C","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#B71C1C"},{"background":"#FFCDD2","text":"#B71C1C"}],"imagePlaceholderColors":["#B71C1C","#FFCDD2"],"imageAspectRatios":[1.5,0.85],"imageColorOffset":0,"imagePositionSeed":2}
  },
  {
    slug: "printer-ink-expensive",
    title: "Ink Costs More Than Blood",
    description: "The real price of printing",
    category: "Economics",
    thumbnail_color: "#1A237E",
    body_text: `Printer ink is one of the most expensive liquids on Earth. Per gallon, it costs more than vintage champagne, human blood, and even some rare perfumes. A gallon of black printer ink can cost over two thousand dollars. The ink itself isn't that expensive to manufacture. The high prices result from a deliberate business model called "razor and blades" pricing—sell the printer cheaply to lock customers into buying overpriced consumables. Printer manufacturers often sell their machines at or below cost, planning to profit from ink sales over the printer's lifetime. This model has made printer ink one of the highest-margin products in consumer electronics. The margins on brand-name ink cartridges exceed 60 percent—far higher than most luxury goods. Some analysts estimate that the ink itself costs less than a dollar per cartridge to produce. The companies spend millions fighting third-party ink suppliers who offer cheaper alternatives. Printer manufacturers embed chips in their cartridges that prevent printers from accepting off-brand ink. They issue firmware updates that disable previously compatible cartridges. They void warranties for customers who use non-approved ink. These practices have sparked lawsuits and regulatory investigations, but the business model persists. The economics are simply too favorable. Customers who paid $50 for a printer don't want to replace it, so they keep buying $40 ink cartridges. They're locked in. Some customers have calculated that buying a new printer is cheaper than replacing ink cartridges. The practice has become so common that it has its own name: "printer abuse." People buy new printers for the starter ink, then discard the empty machine when the ink runs out. It's economically rational but environmentally absurd—a monument to the perverse incentives of razor-and-blades pricing.`,
    design_config: {"thumbnailColor":"#1A237E","titlePage":{"backgroundColor":"#1A237E","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#1A237E","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#1A237E"},{"background":"#C5CAE9","text":"#000000"}],"imagePlaceholderColors":["#1A237E","#C5CAE9"],"imageAspectRatios":[1.4,0.9],"imageColorOffset":1,"imagePositionSeed":4}
  },
  {
    slug: "great-depression-board-games",
    title: "Monopoly Born From Desperation",
    description: "The Depression's surprise hit",
    category: "Economics",
    thumbnail_color: "#1B5E20",
    body_text: `Monopoly became America's bestselling board game during the Great Depression, when millions of unemployed Americans used it to fantasize about the wealth they couldn't obtain in real life. The game's timing wasn't coincidental—it was designed to scratch an economic itch. The game's origin story is more complicated than Parker Brothers long claimed. The standard tale credits Charles Darrow, an unemployed salesman who invented the game in 1933. But Monopoly actually evolved from "The Landlord's Game," created in 1903 by Elizabeth Magie specifically to demonstrate the evils of concentrated property ownership. Magie was a progressive activist who wanted players to experience how landlords exploit tenants. The game spread through progressive communities for decades before Darrow encountered it and sold his version to Parker Brothers. The company paid Magie $500 and no royalties. Whatever its origins, Monopoly's success during the Depression reveals something about human psychology. Players who had lost their jobs, their savings, and their homes could briefly pretend to be real estate moguls. The game offered a structured fantasy of financial success, complete with mansions on Boardwalk and piles of colorful cash. Sales reflected the economic reality. In 1935, during the worst of the Depression, Monopoly was the bestselling game in America. Parker Brothers couldn't manufacture sets fast enough. The company hired hundreds of workers specifically to meet demand, providing jobs that the real economy couldn't. Critics have always noted the game's dark side. Monopoly rewards ruthless behavior and punishes bad luck. Victory requires bankrupting other players. But those features may explain the game's appeal during hard times—it offered a space where the economic brutality of the Depression became entertainment rather than tragedy.`,
    design_config: {"thumbnailColor":"#1B5E20","titlePage":{"backgroundColor":"#1B5E20","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#1B5E20","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#1B5E20"},{"background":"#A5D6A7","text":"#000000"}],"imagePlaceholderColors":["#1B5E20","#A5D6A7"],"imageAspectRatios":[1.3,0.85],"imageColorOffset":0,"imagePositionSeed":3}
  },
  {
    slug: "diamonds-not-rare",
    title: "Diamonds Aren't Actually Rare",
    description: "The illusion of scarcity",
    category: "Economics",
    thumbnail_color: "#90CAF9",
    body_text: `Diamonds are one of the most common gemstones on Earth. The illusion of their scarcity is the greatest marketing achievement in modern history—a century-long campaign that transformed abundant carbon crystals into symbols of eternal love and astronomical prices. Before the 1870s, diamonds were genuinely rare. Then massive deposits were discovered in South Africa. The supply glut threatened to crash prices and destroy the mystique that made diamonds valuable. A group of investors, who would eventually become De Beers, responded by buying up the mines and creating an artificial monopoly. For over a century, De Beers controlled roughly 90 percent of the world's diamond supply. They stockpiled stones in vaults, releasing just enough to meet demand while keeping prices high. Diamonds that flooded the market would have been worth little more than any other pretty rock. The real innovation was marketing. In 1938, De Beers hired the advertising agency N.W. Ayer to convince Americans that diamond engagement rings were essential. The campaign invented the tradition we now consider ancient. "A diamond is forever" became one of the most successful slogans in advertising history. By the 1950s, an engagement without a diamond ring had become socially unacceptable. The marketing extended to preventing resale. De Beers established that diamonds should never be sold—they should be passed down as heirlooms. This prevented a used-diamond market from developing and revealing the truth: that diamonds have almost no resale value because they were never rare. The monopoly has weakened in recent decades as new mines opened and synthetic diamonds became practical. But the psychology persists. People still believe diamonds are rare, still pay premium prices, still consider them essential for engagements. The greatest heist in economic history wasn't stealing diamonds. It was making people pay fortunes for common stones.`,
    design_config: {"thumbnailColor":"#90CAF9","titlePage":{"backgroundColor":"#90CAF9","textColor":"#000000"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#90CAF9","text":"#000000"},{"background":"#FFFFFF","text":"#1976D2"},{"background":"#E3F2FD","text":"#1976D2"}],"imagePlaceholderColors":["#90CAF9","#E3F2FD"],"imageAspectRatios":[1.5,0.9],"imageColorOffset":1,"imagePositionSeed":2}
  },
  {
    slug: "japan-lost-decades",
    title: "Japan's Missing Thirty Years",
    description: "The economy that stopped growing",
    category: "Economics",
    thumbnail_color: "#D32F2F",
    body_text: `In 1989, Japan's stock market reached its all-time high. More than three decades later, it still hasn't recovered to that level. Japan's "lost decade" became lost decades—the longest economic stagnation in modern developed-country history. At the peak of Japan's bubble economy, the Imperial Palace grounds in Tokyo were worth more than all the real estate in California. Japanese companies were buying American landmarks—Rockefeller Center, Pebble Beach, Columbia Pictures. Books predicted that Japan would surpass America as the world's dominant economy. Then the bubble burst. Stock prices fell by half within two years. Real estate values collapsed by as much as 80 percent. Banks that had lent against inflated asset values found themselves holding worthless collateral. The government tried everything. Interest rates went to zero. Massive public works programs built bridges to nowhere. The central bank eventually adopted "quantitative easing," creating trillions of yen to stimulate the economy. Nothing worked for long. Deflation set in—prices actually fell year after year, encouraging consumers to delay purchases because things would be cheaper tomorrow. This logic became self-fulfilling. Why buy today when waiting makes you wealthier? Japan's population began shrinking, reducing the consumer base and workforce simultaneously. Young people stopped forming families. The social contract that had produced Japan's postwar miracle—lifetime employment, company loyalty, sacrifice for the group—began to fray. Economists still debate what caused the stagnation and why conventional remedies failed. The Japanese case became a warning for other developed nations about bubbles, debt, demographics, and deflation. What happened to Japan could happen anywhere. Some argue it already has.`,
    design_config: {"thumbnailColor":"#D32F2F","titlePage":{"backgroundColor":"#D32F2F","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#D32F2F","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#D32F2F"},{"background":"#FFCDD2","text":"#D32F2F"}],"imagePlaceholderColors":["#D32F2F","#FFCDD2"],"imageAspectRatios":[1.4,0.85],"imageColorOffset":0,"imagePositionSeed":4}
  },
  {
    slug: "banana-almost-extinct",
    title: "The Banana Is Dying",
    description: "The fruit with no genetic future",
    category: "Economics",
    thumbnail_color: "#FFD600",
    body_text: `The bananas you eat today are genetically identical clones that cannot reproduce naturally. Every Cavendish banana in every supermarket worldwide shares the same DNA. This makes them incredibly efficient to farm—and incredibly vulnerable to extinction. Bananas reproduce through cuttings, not seeds. Commercial banana varieties lost the ability to produce viable seeds long ago. This means genetic diversity has essentially stopped. The entire global banana trade depends on a single cultivar that cannot evolve to resist new threats. We've been through this before. Until the 1950s, the dominant commercial banana was the Gros Michel, said to be tastier and hardier than today's Cavendish. Then a fungal disease called Panama Disease swept through plantations worldwide, effectively wiping out the Gros Michel as a commercial crop. The Cavendish replaced it because it was resistant to that particular fungus. Now a new strain of Panama Disease, called Tropical Race 4, is spreading through Cavendish plantations. It has already devastated crops in Asia and Africa. Scientists expect it to reach Latin America's major banana-growing regions eventually. When it does, the Cavendish may go the way of the Gros Michel. The banana industry is racing to develop resistant varieties through traditional breeding and genetic engineering. But bananas' lack of sexual reproduction makes this extraordinarily difficult. Creating a new commercial banana could take decades—time the industry may not have. For now, the bananas in your grocery store are a vulnerable monoculture living on borrowed time. The fruit that became the world's most popular may not survive the century in its current form.`,
    design_config: {"thumbnailColor":"#FFD600","titlePage":{"backgroundColor":"#FFD600","textColor":"#000000"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#FFD600","text":"#000000"},{"background":"#FFFFFF","text":"#FFD600"},{"background":"#FFF9C4","text":"#000000"}],"imagePlaceholderColors":["#FFD600","#FFF9C4"],"imageAspectRatios":[1.3,0.9],"imageColorOffset":1,"imagePositionSeed":3}
  },
  {
    slug: "amazon-not-profitable-years",
    title: "Amazon Lost Money for Decades",
    description: "The company that rejected profits",
    category: "Economics",
    thumbnail_color: "#FF9800",
    body_text: `Amazon went public in 1997 and didn't report a consistent profit until 2016—nearly two decades of losses that would have killed almost any other company. Jeff Bezos's strategy of prioritizing growth over profit seemed insane until it made him the richest person in the world. The traditional business model is simple: sell products for more than they cost, pocket the difference. Bezos rejected this approach. Instead, he took every dollar Amazon earned and reinvested it in growth—new warehouses, new product lines, new technologies, new countries. The company grew relentlessly while reporting minimal or negative profits. Wall Street analysts were baffled. A company losing money year after year should see its stock price collapse. Instead, Amazon's stock kept climbing. Investors believed that Bezos would eventually "turn on" the profit machine once Amazon had crushed its competitors. They were betting on a future monopoly. The strategy required extraordinary discipline. Amazon could have been profitable much earlier simply by raising prices or cutting investment. Every quarter, Bezos chose long-term dominance over short-term earnings. When challenged, he'd point to the company's growing revenue and market share. Profits, he insisted, were a choice. The strategy eventually paid off spectacularly. Amazon became dominant in e-commerce, cloud computing, and streaming video. When Bezos finally allowed the company to generate consistent profits, they were enormous. The years of investment had created competitive moats that few rivals could cross. Critics argue that Amazon's strategy was only possible because of unusual stock market patience and regulatory tolerance for predatory pricing. The tactics that built Amazon might now be illegal, and similar strategies have failed for companies without Bezos's credibility. But the Amazon model changed how Silicon Valley thinks about profit—as something to defer, not pursue.`,
    design_config: {"thumbnailColor":"#FF9800","titlePage":{"backgroundColor":"#FF9800","textColor":"#000000"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#FF9800","text":"#000000"},{"background":"#FFFFFF","text":"#FF9800"},{"background":"#FFE0B2","text":"#FF6F00"}],"imagePlaceholderColors":["#FF9800","#FFE0B2"],"imageAspectRatios":[1.5,0.85],"imageColorOffset":0,"imagePositionSeed":2}
  },
  {
    slug: "penny-costs-more-to-make",
    title: "Pennies Cost More Than a Penny",
    description: "The currency that loses money",
    category: "Economics",
    thumbnail_color: "#BF360C",
    body_text: `The United States Mint loses money on every penny it produces. The coin that's worth one cent costs approximately two cents to manufacture. The same is true for nickels, which cost about seven cents to make. Taxpayers subsidize their own currency. The numbers add up quickly. The Mint produces billions of pennies and nickels each year, losing tens of millions of dollars annually on coins that many Americans throw in jars and forget about. Some estimate that the penny costs the economy more than it returns in value when you factor in the time people spend counting and handling them. Several countries have eliminated their lowest-denomination coins. Australia retired its one- and two-cent coins in 1992. Canada stopped making pennies in 2012. In both cases, stores rounded transactions to the nearest five cents without significant economic disruption. Yet the United States keeps making pennies. The coin has powerful defenders. Zinc industry lobbyists push to maintain penny production because pennies are mostly made of zinc. Charities that collect pennies fear losing donation streams. Some economists argue that eliminating pennies would create a "rounding tax" that slightly raises prices. The debate reveals something strange about money. A penny has value because we agree it has value, not because of what it contains or what it costs to make. If we collectively decided to stop using pennies, they would become worthless metal disks. The Mint would stop losing money. Nothing would change except our perception. Perhaps that's why the penny persists—not because it's economically rational, but because abandoning it feels like abandoning something essential about money itself.`,
    design_config: {"thumbnailColor":"#BF360C","titlePage":{"backgroundColor":"#BF360C","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#BF360C","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#BF360C"},{"background":"#FFCCBC","text":"#BF360C"}],"imagePlaceholderColors":["#BF360C","#FFCCBC"],"imageAspectRatios":[1.4,0.9],"imageColorOffset":1,"imagePositionSeed":4}
  },
  {
    slug: "airline-food-expensive",
    title: "Why Airline Food Tastes Bad",
    description: "It's not the chef's fault",
    category: "Economics",
    thumbnail_color: "#0277BD",
    body_text: `Airplane food tastes bland because of physics, not poor cooking. At cruising altitude, your sense of taste is reduced by approximately 30 percent. Airlines spend enormous sums trying to compensate for conditions that make deliciousness nearly impossible. Cabin pressure reduces to the equivalent of about 8,000 feet elevation, which causes inflammation in nasal passages and dulls the olfactory senses that contribute most of what we perceive as taste. The humidity inside an airplane is typically around 12 percent—drier than most deserts—which further impairs smell and taste. The constant background noise of jet engines makes food taste less sweet and less salty. Chefs who prepare airline meals must compensate for all of this. They add extra salt and stronger flavors to dishes that would taste overwhelming on the ground. Ingredients are selected for their ability to survive industrial-scale preparation, freezing, storage, and reheating in convection ovens that can't achieve high temperatures. The economics compound the problem. Full-service meals cost airlines anywhere from five to fifteen dollars per passenger to produce—a fraction of what a comparable restaurant meal would cost. Competition drives airlines to cut food budgets whenever possible. Business class and first class get better meals not because the physics are different but because the economics allow higher spending. Despite everything, some airlines achieve remarkable results. Carriers like Singapore Airlines and Emirates employ celebrity chefs and conduct high-altitude taste tests to optimize their menus. The best airline meals are genuine culinary achievements, given the constraints. But those constraints are fundamental. Until someone invents a way to pressurize cabins at sea-level equivalent or filter out engine noise, airplane food will always fight physics.`,
    design_config: {"thumbnailColor":"#0277BD","titlePage":{"backgroundColor":"#0277BD","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#0277BD","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#0277BD"},{"background":"#B3E5FC","text":"#000000"}],"imagePlaceholderColors":["#0277BD","#B3E5FC"],"imageAspectRatios":[1.3,0.85],"imageColorOffset":0,"imagePositionSeed":3}
  },
  {
    slug: "gold-standard-abandonment",
    title: "Nixon Broke the Dollar",
    description: "The day money changed forever",
    category: "Economics",
    thumbnail_color: "#FFD700",
    body_text: `On August 15, 1971, President Richard Nixon announced that the United States would no longer exchange dollars for gold. The decision, meant to be temporary, permanently transformed the global monetary system and created the currency we use today. For nearly a century, major currencies had been tied to gold at fixed rates. This "gold standard" limited how much money governments could print—you couldn't create currency without the gold to back it. The system promoted stability but constrained flexibility. Countries couldn't easily respond to recessions or crises. By 1971, the system was breaking down. America had printed more dollars than its gold reserves could support. Foreign governments began exchanging their dollars for gold, draining Fort Knox. Nixon faced a choice: either implement painful austerity to defend the gold price, or end convertibility and let the dollar float. He chose to float. The "Nixon Shock," as it became known, was presented as a temporary measure while a new monetary system was negotiated. That negotiation never succeeded. Instead, the world gradually accepted that currencies would no longer be backed by gold. They would be backed by nothing except confidence in the governments that issued them. This "fiat money" system enabled unprecedented economic expansion. Governments could now respond to recessions by printing money. Central banks could manage inflation and unemployment in ways the gold standard prevented. But the system also enabled unprecedented debt accumulation and financial crises. Without the golden anchor, money became whatever we collectively believed it to be. Every dollar in your pocket, every number in your bank account, is backed by nothing but faith. Nixon's temporary measure became the permanent foundation of modern economics.`,
    design_config: {"thumbnailColor":"#FFD700","titlePage":{"backgroundColor":"#FFD700","textColor":"#000000"},"colorPalette":[{"background":"#000000","text":"#FFD700"},{"background":"#FFD700","text":"#000000"},{"background":"#FFFFFF","text":"#000000"},{"background":"#FFF8E1","text":"#000000"}],"imagePlaceholderColors":["#FFD700","#FFF8E1"],"imageAspectRatios":[1.5,0.9],"imageColorOffset":1,"imagePositionSeed":2}
  },
  {
    slug: "subscription-economy-trap",
    title: "The Subscription Trap",
    description: "Why everything became monthly",
    category: "Economics",
    thumbnail_color: "#7B1FA2",
    body_text: `In 2010, Adobe charged $2,600 for its Creative Suite software. By 2020, the same products were only available as subscriptions costing $600 per year. Adobe's revenue doubled. The subscription economy had triumphed. The shift from ownership to rental transformed nearly every software company during the 2010s. Microsoft, Autodesk, and dozens of other companies moved from selling products to selling access. The financial logic was compelling: predictable recurring revenue, higher lifetime customer value, and protection against piracy. For companies, subscriptions are almost universally better than one-time sales. A customer who pays $600 per year for a decade has spent $6,000—far more than the $2,600 one-time purchase price. Companies can also monitor usage patterns, roll out updates continuously, and cut off customers who stop paying. For consumers, the calculation is more complex. Subscriptions lower the barrier to entry—$50 per month feels more affordable than $2,600 upfront. But many people accumulate subscriptions they barely use, paying monthly for services they forget they have. Studies suggest the average American spends over $200 per month on subscriptions, often more than they realize. The model has spread far beyond software. Razors, vitamins, pet food, cars, and even underwear are now sold primarily through subscriptions. Companies have discovered that automatic billing reduces customer attention to costs. People are less likely to cancel a subscription than to decide not to make a purchase. Some critics call this "dark pattern" design—services that are easy to join but hard to leave. Others argue that subscriptions democratize access to products that were previously unaffordable. Either way, the trend seems irreversible. The future of commerce is increasingly rental, not ownership.`,
    design_config: {"thumbnailColor":"#7B1FA2","titlePage":{"backgroundColor":"#7B1FA2","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#7B1FA2","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#7B1FA2"},{"background":"#E1BEE7","text":"#7B1FA2"}],"imagePlaceholderColors":["#7B1FA2","#E1BEE7"],"imageAspectRatios":[1.4,0.85],"imageColorOffset":0,"imagePositionSeed":4}
  },
  {
    slug: "free-sample-psychology",
    title: "Why Free Samples Work",
    description: "The psychology of gift economics",
    category: "Economics",
    thumbnail_color: "#4CAF50",
    body_text: `Free samples are one of the most effective marketing techniques ever developed, and the reason has little to do with letting customers try products. The real power of free samples lies in reciprocity—the deeply human compulsion to repay gifts. Social psychologists have demonstrated that receiving something for free creates a psychological debt. We feel obligated to reciprocate, even when the gift was unsolicited and even when reciprocating costs us more than the gift was worth. This obligation overrides rational economic calculation. Costco understands this perfectly. The warehouse store offers free samples throughout its locations, and studies show that sampling increases product sales by as much as 2,000 percent for some items. Customers who accept samples feel socially obligated to buy, even if they wouldn't have otherwise considered the product. The technique works across cultures and contexts. In restaurants, mints provided with the check increase tips significantly—even though the mints cost the restaurant almost nothing. Door-to-door salespeople have known for generations that giving small gifts before making a pitch dramatically increases sales. The obligation effect applies even to gifts we didn't ask for. Hare Krishnas famously offered flowers to airport travelers in the 1970s and 1980s, then asked for donations. The recipients felt obligated to give money for flowers they hadn't wanted and would immediately throw away. The strategy was remarkably effective until airports banned solicitation. Understanding reciprocity explains behaviors that seem irrational. People buy things they don't need, give money to causes they don't support, and feel guilty for refusing gifts they never wanted. The social debt of receiving is powerful enough to override our economic self-interest.`,
    design_config: {"thumbnailColor":"#4CAF50","titlePage":{"backgroundColor":"#4CAF50","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#4CAF50","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#4CAF50"},{"background":"#C8E6C9","text":"#000000"}],"imagePlaceholderColors":["#4CAF50","#C8E6C9"],"imageAspectRatios":[1.3,0.9],"imageColorOffset":1,"imagePositionSeed":3}
  },
  {
    slug: "bottled-water-marketing",
    title: "The Bottled Water Invention",
    description: "Selling what comes from the tap",
    category: "Economics",
    thumbnail_color: "#00ACC1",
    body_text: `Bottled water is the greatest marketing triumph of the late twentieth century. Companies convinced billions of people to pay thousands of times more for a product that flows freely from their taps. The industry generates over $200 billion in annual revenue selling what is essentially free. Before the 1970s, bottled water barely existed as a consumer product in developed countries. Perrier pioneered the modern market by positioning their product as a healthy, sophisticated alternative to soda. The green bottle became a status symbol in restaurants and offices. Other companies followed, gradually expanding the market from special occasions to everyday hydration. The marketing messages are brilliantly misleading. Images of mountain springs and pristine glaciers imply purity, but much bottled water is simply filtered municipal tap water—the same water that reaches your sink, packaged in plastic. The taste tests that supposedly prove bottled water's superiority have repeatedly failed to show consistent differences when conducted blind. Environmental concerns should have killed the industry. Plastic bottles require petroleum to produce, energy to transport, and centuries to decompose. Americans throw away about 60 million plastic bottles daily. Yet sales continue to grow because the marketing has convinced people that bottled water is fundamentally different from tap water—cleaner, safer, more natural. Some bottled water is legitimately distinctive—natural mineral waters with unique mineral content, or purified water in areas where tap water is contaminated. But most bottled water sold in developed countries is functionally identical to what comes from municipal systems that are more rigorously tested than bottled water plants. The industry proves that perception can override reality indefinitely.`,
    design_config: {"thumbnailColor":"#00ACC1","titlePage":{"backgroundColor":"#00ACC1","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#00ACC1","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#00ACC1"},{"background":"#B2EBF2","text":"#000000"}],"imagePlaceholderColors":["#00ACC1","#B2EBF2"],"imageAspectRatios":[1.5,0.85],"imageColorOffset":0,"imagePositionSeed":2}
  },
  {
    slug: "insurance-invented-coffee",
    title: "Insurance Began in a Coffee Shop",
    description: "Lloyd's Coffee House created finance",
    category: "Economics",
    thumbnail_color: "#795548",
    body_text: `Modern insurance was invented in a London coffee shop. In the 1680s, merchants and ship owners gathered at Edward Lloyd's coffeehouse to gossip, negotiate, and share the risks of maritime trade. Three centuries later, Lloyd's of London remains one of the world's largest insurance markets. Coffee houses were the social media of early modern London. Different establishments attracted different clientele—politicians, scientists, writers, merchants. Lloyd's became the hub for marine intelligence. Ship captains brought news of voyages. Merchants discussed trade routes. Gamblers bet on whether ships would arrive safely. From gambling to insurance was a natural evolution. Instead of betting after the fact on whether a ship had survived, merchants began paying premiums before voyages to guarantee compensation if ships were lost. The "underwriters" who accepted these premiums literally wrote their names under the policy terms—a practice that continues at Lloyd's today. The coffee house environment shaped how insurance developed. Underwriters could examine each other's assessments and adjust their own. Reputations were built or destroyed in full view of the market. The transparency and competition produced remarkably accurate pricing for the risks of the age. Lloyd's eventually moved to dedicated premises, but it preserved the coffee house culture. Underwriters still meet face-to-face to negotiate policies. The bell that once announced ship arrivals—the Lutine Bell, salvaged from a sunken vessel—still rings to mark significant losses. Some of the largest and strangest policies in the world are written at Lloyd's: satellites, sports stars' body parts, events that seem too bizarre to insure anywhere else. The coffeehouse that became a global market still operates on principles established when merchants gathered over cups of coffee to share the risks of the sea.`,
    design_config: {"thumbnailColor":"#795548","titlePage":{"backgroundColor":"#795548","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#795548","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#795548"},{"background":"#D7CCC8","text":"#000000"}],"imagePlaceholderColors":["#795548","#D7CCC8"],"imageAspectRatios":[1.4,0.9],"imageColorOffset":1,"imagePositionSeed":4}
  },
  {
    slug: "gift-card-breakage",
    title: "The Gift Card Graveyard",
    description: "Billions in cards never spent",
    category: "Economics",
    thumbnail_color: "#FF5722",
    body_text: `Americans hold approximately $21 billion in unspent gift cards at any given time. Retailers call this "breakage"—the money paid for gift cards that is never redeemed. It's essentially free profit. The gift card business model depends on human psychology. We buy gift cards to avoid the awkwardness of cash. We receive them and promise ourselves we'll use them. Then we forget, lose them, or let them expire. Studies suggest that about 10 percent of gift card value is never redeemed, though rates vary by retailer and card type. From the retailer's perspective, gift cards are nearly perfect products. They're paid for upfront, have no inventory costs, and generate additional visits to stores where cardholders typically spend more than the card's face value. When cards go unredeemed, the retailer keeps both the payment and the merchandise that was never purchased. The accounting treatment is strange. Gift card revenue appears on balance sheets as a liability—money owed to cardholders. As cards go unspent, retailers gradually convert this liability into profit through complex "escheatment" and breakage recognition rules. Some retailers have become so dependent on breakage that they've actively tried to make cards harder to use. Expiration dates, hidden fees, and complicated terms all increase breakage rates. Consumer protection laws have addressed the worst abuses, but the fundamental psychology remains exploitable. Gift givers worry that they'll choose the wrong present, so they choose a card instead. Recipients appreciate the flexibility but value the card less than cash. The difference between what givers pay and what recipients perceive is captured by retailers. Every unredeemed gift card represents a pure transfer of wealth from consumers to corporations.`,
    design_config: {"thumbnailColor":"#FF5722","titlePage":{"backgroundColor":"#FF5722","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#FF5722","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#FF5722"},{"background":"#FFCCBC","text":"#BF360C"}],"imagePlaceholderColors":["#FF5722","#FFCCBC"],"imageAspectRatios":[1.3,0.85],"imageColorOffset":0,"imagePositionSeed":3}
  }
];

async function uploadStory(story) {
  const response = await fetch(`${SUPABASE_URL}/rest/v1/stories`, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      "apikey": SUPABASE_KEY,
      "Authorization": `Bearer ${SUPABASE_KEY}`,
      "Prefer": "resolution=merge-duplicates,return=minimal"
    },
    body: JSON.stringify({
      slug: story.slug,
      title: story.title,
      description: story.description,
      category: story.category,
      thumbnail_color: story.thumbnail_color,
      published: true,
      published_at: new Date().toISOString(),
      body_text: story.body_text,
      design_config: story.design_config,
      updated_at: new Date().toISOString()
    })
  });

  if (!response.ok) {
    const text = await response.text();
    throw new Error(`${response.status}: ${text}`);
  }
}

async function main() {
  console.log(`Uploading ${stories.length} Economics "Did You Know" stories to Supabase...\n`);

  let success = 0;
  let failed = 0;

  for (const story of stories) {
    try {
      process.stdout.write(`Uploading: ${story.title}... `);
      await uploadStory(story);
      console.log("Done!");
      success++;
    } catch (error) {
      console.log(`Error: ${error.message}`);
      failed++;
    }
  }

  console.log(`\nComplete! ${success} succeeded, ${failed} failed.`);
}

main();
