/**
 * Exploration Category - 25 "Did You Know" Stories
 * Usage: node scripts/new-content-dyk/exploration-dyk.mjs
 */

const SUPABASE_URL = "https://egfwisgqdyhzpmeoracb.supabase.co";
const SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVnZndpc2dxZHloenBtZW9yYWNiIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2ODQyNzM0OSwiZXhwIjoyMDg0MDAzMzQ5fQ.S8h1fIepxWb44gPSPpWQ8fE0Q-SCYfL0QcBRUV7fXgs";

const stories = [
  {
    slug: "rubber-ducks-ocean-currents",
    title: "Rubber Ducks That Mapped the Ocean",
    description: "A shipping accident that changed science",
    category: "Exploration",
    thumbnail_color: "#FFD600",
    body_text: `In January 1992, a shipping container fell off a cargo ship in the North Pacific and cracked open, releasing 28,800 rubber bath toys into the ocean. The toys—yellow ducks, blue turtles, green frogs, and red beavers—began a journey that would last decades and revolutionize our understanding of ocean currents. The spill happened during a storm about midway between Hong Kong and Seattle. Within months, the toys started washing ashore along the Alaskan coast. Then they appeared in Hawaii. Then Japan. Some made it all the way to Maine, having navigated through the Arctic ice. Others turned up in Scotland and Australia. Oceanographer Curtis Ebbesmeyer realized he was looking at the perfect natural experiment. Unlike scientific tracking buoys, which are expensive and released in limited numbers, these toys came in the tens of thousands. Each one that washed up was another data point. Ebbesmeyer enlisted beachcombers around the world to report sightings. The rubber ducks became celebrities of oceanic science. They revealed current patterns that computer models had predicted but never confirmed. They showed how debris circulates in the Great Pacific Garbage Patch. They proved that objects could survive Arctic freezing and keep floating for years. More than three decades later, the ducks are still washing up. Their yellow color has faded to white from sun exposure and salt water, but they remain recognizable. Scientists estimate that many are still floating somewhere in the world's oceans, carried by currents that the ducks themselves helped us understand. A manufacturing accident became one of the most valuable oceanographic experiments ever conducted—entirely by accident.`,
    design_config: {"thumbnailColor":"#FFD600","titlePage":{"backgroundColor":"#FFD600","textColor":"#000000"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#FFD600","text":"#000000"},{"background":"#00695C","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#00695C"}],"imagePlaceholderColors":["#FFD600","#00695C"],"imageAspectRatios":[1.4,0.85],"imageColorOffset":0,"imagePositionSeed":2}
  },
  {
    slug: "explorer-found-himself-on-map",
    title: "The Explorer Who Found Himself",
    description: "When the map was wrong about him",
    category: "Exploration",
    thumbnail_color: "#5D4037",
    body_text: `In 1869, Henry Morton Stanley set out to find the missing explorer David Livingstone in the African interior. When he finally tracked down Livingstone at Ujiji on the shores of Lake Tanganyika, Stanley delivered one of history's most famous understatements: "Dr. Livingstone, I presume?" But years later, Stanley had an even stranger encounter with exploration—he found himself already on a map. During his 1874-1877 expedition across central Africa, Stanley was pushing through territory that Europeans had never entered. His maps showed vast blank spaces labeled "unknown." Yet when he reached certain villages, the locals told him that another white man had already passed through and mapped the area—a man named Stanley. The confusion arose from competing expeditions and unreliable intelligence. Earlier explorers had pieced together information from Arab traders and local accounts, then published maps based on secondhand reports. Some cartographers, eager to fill in blanks, had attributed discoveries to Stanley that he hadn't yet made. Stanley was essentially following a map of his own future achievements. The experience haunted him. Were his discoveries truly discoveries if someone had already drawn them on a map based on rumor? The philosophical question of what counts as exploration—being the first to see something, or the first to accurately record it—became a persistent problem for Victorian-era explorers. Stanley resolved it by becoming almost obsessive about verification. He measured everything, documented everything, and famously traveled with a complete printing press to publish his findings before anyone could dispute them. Finding himself on a map taught him that in exploration, being first mattered less than proving it.`,
    design_config: {"thumbnailColor":"#5D4037","titlePage":{"backgroundColor":"#5D4037","textColor":"#FFD60A"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#5D4037","text":"#FFFFFF"},{"background":"#FFD60A","text":"#000000"},{"background":"#FFFFFF","text":"#5D4037"}],"imagePlaceholderColors":["#5D4037","#FFD60A"],"imageAspectRatios":[1.3,0.9],"imageColorOffset":1,"imagePositionSeed":3}
  },
  {
    slug: "franklin-expedition-ate-shoes",
    title: "The Expedition That Ate Their Shoes",
    description: "Franklin's men starved in ice",
    category: "Exploration",
    thumbnail_color: "#90A4AE",
    body_text: `When Sir John Franklin's expedition to find the Northwest Passage vanished in 1845, it sparked one of the greatest mysteries in exploration history. One hundred twenty-nine men and two ships disappeared into the Arctic ice. The rescue missions that followed pieced together a story of escalating horror, including evidence that the starving crew ate their own leather boots. Franklin's expedition was the best-equipped Arctic mission ever launched. The ships, HMS Erebus and HMS Terror, had been fitted with steam engines, iron plating, and three years of food supplies. They had libraries, silverware, and a hand organ for entertainment. The Victorian elite expected triumph. What followed was catastrophe. Inuit witnesses later reported seeing desperate, skeletal men dragging boats across the ice. They found camps with human bones showing knife marks consistent with cannibalism. But some of the strangest evidence came from the leather items—boots with the soles eaten away, belts gnawed to the stitching. The crew had consumed their own equipment. Modern analysis revealed another twist. The expedition's canned food, a cutting-edge technology in 1845, had been improperly sealed with lead solder. The men were slowly being poisoned even as they starved. Lead toxicity causes confusion, paranoia, and poor decision-making—which may explain some of the expedition's fatal choices. The ships were found in 2014 and 2016, remarkably preserved in the cold Arctic waters. Erebus yielded artifacts including dishes, buttons, and personal items. But the crews themselves were never found—only scattered bones across the ice, testimony to an expedition that had everything except luck.`,
    design_config: {"thumbnailColor":"#90A4AE","titlePage":{"backgroundColor":"#90A4AE","textColor":"#000000"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#90A4AE","text":"#000000"},{"background":"#FFFFFF","text":"#37474F"},{"background":"#37474F","text":"#FFFFFF"}],"imagePlaceholderColors":["#90A4AE","#37474F"],"imageAspectRatios":[1.5,0.85],"imageColorOffset":0,"imagePositionSeed":4}
  },
  {
    slug: "cave-isolated-lake-million-years",
    title: "The Lake Sealed for a Million Years",
    description: "Life evolving in total darkness",
    category: "Exploration",
    thumbnail_color: "#1A237E",
    body_text: `In the Movile Cave of Romania, scientists discovered a lake that had been completely sealed off from the outside world for approximately five and a half million years. The water contains creatures found nowhere else on Earth—species that evolved in total isolation, in complete darkness, breathing an atmosphere that would kill a human in minutes. The cave was discovered accidentally in 1986 when workers testing the ground for a power plant broke through into an underground chamber. The air inside was thick with hydrogen sulfide and carbon dioxide, with almost no oxygen. Scientists who entered had to wear breathing apparatus and limit their time underground. Yet the cave teemed with life. Researchers have identified over fifty species found only in Movile—spiders, water scorpions, leeches, and worms that have never seen light and never will. Many are completely blind, having lost their eyes over millions of years of evolution. Some have developed other heightened senses to compensate. The ecosystem operates without sunlight. Instead of photosynthesis, bacteria in the cave use chemosynthesis—extracting energy from chemical reactions involving hydrogen sulfide. These bacteria form the base of a food chain that supports predators and prey in perpetual darkness. It's the closest thing on Earth to what we might find on other planets. Astrobiologists have studied Movile as a potential model for life on Mars or the moons of Jupiter and Saturn. If creatures can thrive in a poisonous, lightless cave sealed for millions of years, life might flourish in places we never thought to look. The lake that time forgot is teaching us to expand our imagination.`,
    design_config: {"thumbnailColor":"#1A237E","titlePage":{"backgroundColor":"#1A237E","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#1A237E","text":"#FFFFFF"},{"background":"#00695C","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#1A237E"}],"imagePlaceholderColors":["#1A237E","#00695C"],"imageAspectRatios":[1.4,0.9],"imageColorOffset":1,"imagePositionSeed":2}
  },
  {
    slug: "mountains-discovered-by-echo",
    title: "Mountains Found by Echo Alone",
    description: "Discovering peaks nobody could see",
    category: "Exploration",
    thumbnail_color: "#455A64",
    body_text: `In 1958, Soviet scientists discovered a massive mountain range beneath the Antarctic ice sheet using nothing but sound waves. The Gamburtsev Mountains are as tall as the Alps, stretching over 750 miles—and they remain completely invisible, buried under two miles of ice. Nobody has ever seen them directly. The discovery happened during the International Geophysical Year, when scientists from multiple nations cooperated to study Antarctica. Soviet researchers dragged seismic equipment across the frozen continent, setting off explosions and measuring how sound waves bounced back. The returning echoes painted a picture of what lay beneath the ice. What they found defied expectations. Instead of a flat bedrock scraped smooth by glaciers, they detected soaring peaks and deep valleys. A mountain range larger than many on the surface was hiding in plain sight, entombed in ice for millions of years. The Gamburtsev Mountains present a geological mystery. Mountains usually form through tectonic activity—continental collisions, volcanic eruptions—and then erode over time. These peaks show no signs of recent tectonic activity, yet they haven't eroded. The ice that covers them has preserved them like a frozen time capsule for roughly 34 million years. Scientists have since mapped the mountains in greater detail using ice-penetrating radar. The highest peaks reach over 11,000 feet—comparable to the tallest summits in the American Rockies. Glaciers flow through the buried valleys, invisible rivers of ice moving through a landscape no human eyes will ever see. The Gamburtsev Mountains remind us that even on our own planet, exploration is not finished. There are still mountains waiting to be discovered, hidden just beyond the reach of sight.`,
    design_config: {"thumbnailColor":"#455A64","titlePage":{"backgroundColor":"#455A64","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#455A64","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#455A64"},{"background":"#B0BEC5","text":"#000000"}],"imagePlaceholderColors":["#455A64","#B0BEC5"],"imageAspectRatios":[1.3,0.85],"imageColorOffset":0,"imagePositionSeed":3}
  },
  {
    slug: "disappearing-island-sandy",
    title: "The Island That Keeps Vanishing",
    description: "Sandy Island exists only on maps",
    category: "Exploration",
    thumbnail_color: "#0097A7",
    body_text: `Sandy Island appeared on maps for over a century—a sizable land mass in the Coral Sea between Australia and New Caledonia. Google Earth showed it. National Geographic atlases included it. The only problem: it doesn't exist. In 2012, a team of Australian scientists sailed directly through the spot where Sandy Island was supposed to be. Instead of land, they found open ocean more than a mile deep. They had accidentally disproven the existence of an island that cartographers had been copying from map to map for over a hundred years. The phantom island probably originated from a genuine sighting. In 1876, a whaling ship reported a sandy shoal in approximately that location. The report was noted on admiralty charts, then copied to other maps. Each time a new map was created, cartographers assumed previous versions were accurate. Nobody verified the island; they just traced it. Sandy Island became so established that when satellite mapping began, the data was adjusted to match existing charts. A human error from the 1800s persisted into the digital age. The island appeared on Google Earth not because satellites saw it, but because maps said it should be there. The discovery sparked a hunt for other phantom islands. Researchers found dozens—specks of land that appeared on maps but had never existed, or had existed briefly before eroding beneath the waves. Some were navigational errors; others were deliberate frauds. A few were real islands that simply sank. The deletion of Sandy Island from world maps was strangely controversial. Some people had formed emotional attachments to an island they'd never visited. Others worried about what else might be wrong on our supposedly accurate modern maps. If Sandy Island was a ghost, what other phantoms are we still drawing?`,
    design_config: {"thumbnailColor":"#0097A7","titlePage":{"backgroundColor":"#0097A7","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#0097A7","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#0097A7"},{"background":"#FFD600","text":"#000000"}],"imagePlaceholderColors":["#0097A7","#FFD600"],"imageAspectRatios":[1.5,0.9],"imageColorOffset":1,"imagePositionSeed":4}
  },
  {
    slug: "ship-frozen-museum-maud",
    title: "The Ship That Became a Museum",
    description: "Frozen in time for a century",
    category: "Exploration",
    thumbnail_color: "#4E342E",
    body_text: `When Roald Amundsen's ship Maud became trapped in Arctic ice in 1926, the crew abandoned her and walked to safety. The ship sank in shallow water near Cambridge Bay, Canada, and sat on the seafloor for nearly a century—a perfectly preserved time capsule from the age of polar exploration. The Maud had been built specifically for Amundsen's attempt to drift across the Arctic Ocean, following the example of Fridtjof Nansen's famous Fram expedition. But the ice didn't cooperate. Instead of drifting toward the pole, the ship was pushed into shallow waters near the Canadian coast. After years of failed attempts, Amundsen sold her to the Hudson's Bay Company, which used her as a floating warehouse before she finally sank. The cold Arctic waters preserved the Maud almost perfectly. When divers began exploring the wreck in the 1990s, they found artifacts that looked like they had been left yesterday: canned food, tools, personal items, even papers that remained legible despite decades underwater. The ship's hull was largely intact, encased in silt but structurally sound. In 2016, a Norwegian expedition raised the Maud from the seafloor—a feat of engineering that required pontoons, winches, and months of careful preparation. The ship was towed back to Norway, where restoration began on what may become the world's only museum of a preserved polar exploration vessel. The Maud that visitors will eventually see isn't a replica or reconstruction. It's the actual ship that carried Amundsen through the Arctic, frozen in time by the same ice that defeated her mission. Sometimes failure preserves history better than success.`,
    design_config: {"thumbnailColor":"#4E342E","titlePage":{"backgroundColor":"#4E342E","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#4E342E","text":"#FFFFFF"},{"background":"#90A4AE","text":"#000000"},{"background":"#FFFFFF","text":"#4E342E"}],"imagePlaceholderColors":["#4E342E","#90A4AE"],"imageAspectRatios":[1.4,0.85],"imageColorOffset":0,"imagePositionSeed":2}
  },
  {
    slug: "nursery-rhyme-rescue-expedition",
    title: "Saved by a Children's Song",
    description: "A nursery rhyme that rescued explorers",
    category: "Exploration",
    thumbnail_color: "#7B1FA2",
    body_text: `In 1916, Ernest Shackleton's men were stranded on the Antarctic ice after their ship Endurance was crushed. When Shackleton finally reached the whaling station on South Georgia Island to get help, he faced one last obstacle: the station was on the wrong side of a mountain range he'd have to cross on foot, without maps, in winter conditions. After thirty-six hours of climbing, Shackleton and two companions reached the outskirts of the station at Stromness. They were gaunt, frostbitten, and nearly unrecognizable. The station manager didn't know who they were until Shackleton introduced himself. But what guided them through the final approach wasn't navigation—it was sound. The station's steam whistle blew at 7 AM every day to wake the workers. When Shackleton heard it through the fog and wind, he knew which direction to walk. But there's a lesser-known story about another sound that saved Antarctic explorers. During a different expedition, men lost in whiteout conditions managed to find their base camp because one of the scientists was playing a phonograph—and the record playing was a children's nursery rhyme. The tinny sound of "Rock-a-Bye Baby" carried through the Antarctic air just far enough for lost men to follow it home. Sound carries strangely in polar environments. Cold air creates temperature inversions that can trap sound waves near the surface, allowing them to travel much farther than normal. Expeditions learned to use this quirk—blowing whistles, ringing bells, or playing music during storms to guide lost team members back to camp. The nursery rhymes that soothed children to sleep were repurposed to save men from freezing to death in the world's coldest places.`,
    design_config: {"thumbnailColor":"#7B1FA2","titlePage":{"backgroundColor":"#7B1FA2","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#7B1FA2","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#7B1FA2"},{"background":"#FFD60A","text":"#000000"}],"imagePlaceholderColors":["#7B1FA2","#FFD60A"],"imageAspectRatios":[1.3,0.9],"imageColorOffset":1,"imagePositionSeed":3}
  },
  {
    slug: "columbus-discovered-america-accident",
    title: "Columbus Got Lucky, Not Smart",
    description: "America found entirely by mistake",
    category: "Exploration",
    thumbnail_color: "#00695C",
    body_text: `Christopher Columbus didn't discover America through brilliant navigation. He discovered it because he was spectacularly wrong about the size of the Earth—and got lucky that a continent happened to be in the way. Columbus believed the Earth was much smaller than it actually is. He calculated that Japan was about 2,400 miles west of the Canary Islands. The actual distance is closer to 12,000 miles. If the Americas hadn't existed, Columbus and his crew would have run out of food and water long before reaching Asia. They would have died at sea, remembered as fools who ignored the expert opinion of their time. Because the experts weren't wrong about the Earth's size—they had calculated it reasonably accurately since ancient Greek times. Eratosthenes measured the Earth's circumference around 240 BCE and came within a few percentage points of the correct figure. Medieval scholars knew this. When Columbus presented his plan to Spanish academics, they rejected it not because they thought the Earth was flat, but because they knew his math was wrong. Columbus's success came from stubbornness and luck, not skill. He kept sailing west despite his crew's near-mutiny. When he hit the Bahamas, he assumed he'd reached islands off the coast of Asia and never admitted otherwise. He died in 1506 still insisting he'd found a western route to the Indies. The irony is profound. The man credited with proving the Earth could be circumnavigated actually proved nothing of the sort. His calculations would have killed him. America saved him from his own errors—and he never even realized what he'd found. Sometimes history's greatest discoveries happen not because of genius, but despite its absence.`,
    design_config: {"thumbnailColor":"#00695C","titlePage":{"backgroundColor":"#00695C","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#00695C","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#00695C"},{"background":"#FFD600","text":"#000000"}],"imagePlaceholderColors":["#00695C","#FFD600"],"imageAspectRatios":[1.5,0.85],"imageColorOffset":0,"imagePositionSeed":4}
  },
  {
    slug: "cave-own-weather-son-doong",
    title: "The Cave With Its Own Weather",
    description: "Clouds form inside this cavern",
    category: "Exploration",
    thumbnail_color: "#2E7D32",
    body_text: `In Vietnam's Quang Binh province, a cave so vast that it generates its own weather systems went undiscovered until 2009. Son Doong cave is large enough to fly a Boeing 747 through without touching the walls. It contains a jungle, a river, and clouds that form inside its chambers. Local hunter Ho Khanh found the entrance in 1991 but was frightened away by the sound of wind and water rushing from the darkness. He didn't return for almost two decades, and when he finally led British cavers to the spot, they realized he had stumbled upon the largest cave passage ever discovered. The main chamber is over three miles long, with ceilings reaching 650 feet—taller than a 65-story building. In some sections, the cave opens to the sky through collapsed dolines, allowing sunlight to stream in and forests to grow on the cave floor. The contrast is surreal: lush green jungle inside a limestone cavern, with mist rising from underground rivers. The weather phenomenon happens because of temperature and humidity differences between the cave interior and the outside air. When humid air enters the cave and hits cooler surfaces, water vapor condenses into fog. The cave essentially functions as a giant natural humidifier, producing clouds that drift through its passages. Exploring Son Doong requires a five-day expedition. Visitors must navigate underground rivers, camp inside the cave, and scale massive calcite walls. The Vietnamese government limits access to preserve the cave's pristine ecosystem, which includes species found nowhere else. Son Doong proves that even in the age of satellite mapping, wonders remain hidden. A cavern large enough to swallow skyscrapers went unnoticed until a hunter heard strange sounds and walked away.`,
    design_config: {"thumbnailColor":"#2E7D32","titlePage":{"backgroundColor":"#2E7D32","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#2E7D32","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#2E7D32"},{"background":"#81C784","text":"#000000"}],"imagePlaceholderColors":["#2E7D32","#81C784"],"imageAspectRatios":[1.4,0.9],"imageColorOffset":1,"imagePositionSeed":2}
  },
  {
    slug: "lake-vostok-antarctic-ice",
    title: "The Lake Hidden Under Antarctica",
    description: "Water sealed for 15 million years",
    category: "Exploration",
    thumbnail_color: "#0D47A1",
    body_text: `Beneath two and a half miles of Antarctic ice lies a lake roughly the size of Lake Ontario, sealed off from the outside world for at least 15 million years. Lake Vostok is one of the most extreme environments on Earth—and scientists have spent decades trying to reach it without contaminating its pristine waters. Russian scientists first detected the lake in the 1970s using ice-penetrating radar. The readings showed a smooth, flat surface deep beneath the ice—unmistakable evidence of liquid water. But it took until 2012 for a drill to finally break through the ice sheet and sample the lake below. The technical challenges were immense. The lake sits under pressure equivalent to being 400 meters underwater. Its water temperature is below freezing but remains liquid due to geothermal heat and the intense pressure. Any drilling fluid used to keep the borehole open risked contaminating an ecosystem that might have evolved in complete isolation for millions of years. What scientists found surprised them. Despite the extreme darkness, cold, and pressure, the lake water contained microbial life—tiny organisms that had survived cut off from the sun and surface world. Some appeared to be bacteria never seen before, living on chemical energy from minerals in the bedrock. Lake Vostok has become a model for how we might search for life on other worlds. Jupiter's moon Europa and Saturn's moon Enceladus both have liquid water oceans beneath icy crusts. If life can survive in Lake Vostok's sealed darkness, it might survive on moons billions of miles away. The buried Antarctic lake is a laboratory for astrobiology, hidden in our own polar ice.`,
    design_config: {"thumbnailColor":"#0D47A1","titlePage":{"backgroundColor":"#0D47A1","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#0D47A1","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#0D47A1"},{"background":"#90CAF9","text":"#000000"}],"imagePlaceholderColors":["#0D47A1","#90CAF9"],"imageAspectRatios":[1.3,0.85],"imageColorOffset":0,"imagePositionSeed":3}
  },
  {
    slug: "mountain-mapped-wrong-centuries",
    title: "The Mountain That Wasn't There",
    description: "Cartographers believed a myth",
    category: "Exploration",
    thumbnail_color: "#6D4C41",
    body_text: `For over three centuries, European maps showed a massive mountain range called the Kong Mountains stretching across West Africa, blocking access to the continent's interior. Explorers who tried to find them returned confused. The Kong Mountains didn't exist—they were a cartographic fantasy that refused to die. The myth began in 1798 when British cartographer James Rennell drew a mountain range on his map of Africa, connecting fragmented reports from various sources. Other mapmakers copied his work, as was standard practice. Each copy added more detail, making the imaginary mountains seem more real. By the mid-1800s, the Kong Mountains appeared on virtually every map of Africa. The problem was that no European had actually seen them. Reports came secondhand from traders and local informants, filtered through multiple translations and cultural misunderstandings. Some Africans may have described real but distant mountains; others may have invented obstacles to discourage European intrusion. The telephone-game nature of the information transformed scattered hills into an impenetrable barrier. French explorer Louis-Gustave Binger finally disproved the Kong Mountains in 1888 by walking through the area where they supposedly stood. He found nothing but savanna and low hills. Yet some maps continued to show the phantom range for decades afterward—cartographers reluctant to delete features they had been drawing their entire careers. The Kong Mountains illustrate how knowledge can become entrenched through repetition. Each map that copied the range made it seem more authoritative. Each explorer who failed to reach them seemed to confirm their impassability. The mountains that never existed became real enough to shape exploration policy for nearly a century.`,
    design_config: {"thumbnailColor":"#6D4C41","titlePage":{"backgroundColor":"#6D4C41","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#6D4C41","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#6D4C41"},{"background":"#D7CCC8","text":"#000000"}],"imagePlaceholderColors":["#6D4C41","#D7CCC8"],"imageAspectRatios":[1.5,0.9],"imageColorOffset":1,"imagePositionSeed":4}
  },
  {
    slug: "explorer-killed-discovered-tribe",
    title: "Killed by the Tribe He Found",
    description: "First contact became fatal contact",
    category: "Exploration",
    thumbnail_color: "#B71C1C",
    body_text: `In 2018, American missionary John Allen Chau paddled a kayak to North Sentinel Island in the Indian Ocean, determined to make contact with one of the world's last uncontacted peoples. The Sentinelese greeted him with arrows. His body was never recovered. North Sentinel Island is home to a tribe that has rejected all contact with the outside world for at least 60,000 years. When helicopters fly overhead, they shoot arrows at them. When ships approach, they launch attacks. After the 2004 tsunami, Indian officials flew over the island to check for survivors and were met with a volley of arrows—the Sentinelese had survived and wanted everyone to know they weren't interested in help. Chau knew the risks. He had trained for years, learning survival skills and attempting to study the Sentinelese language from extremely limited recordings. He believed God had called him to bring Christianity to the island. In his final journal entries, written the night before his last approach, he wrestled with fear and faith. The Sentinelese killed him on his third attempt to reach the island. Fishermen who had ferried Chau partway reported seeing his body being dragged along the beach. Indian authorities attempted to recover the remains but withdrew after the tribe's hostile response. Chau remains buried—if buried at all—on the island where he died. The incident sparked debates about exploration, religion, and indigenous rights. Some called Chau a martyr; others called him a colonizer who endangered an isolated population with potential disease exposure. The Sentinelese, for their part, have made their position clear for millennia: they wish to be left alone. The explorer who refused to listen became another lesson in why we should.`,
    design_config: {"thumbnailColor":"#B71C1C","titlePage":{"backgroundColor":"#B71C1C","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#B71C1C","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#B71C1C"},{"background":"#FFCDD2","text":"#000000"}],"imagePlaceholderColors":["#B71C1C","#FFCDD2"],"imageAspectRatios":[1.4,0.85],"imageColorOffset":0,"imagePositionSeed":2}
  },
  {
    slug: "boiling-river-amazon-shanay",
    title: "The River That Boils",
    description: "Water hot enough to kill",
    category: "Exploration",
    thumbnail_color: "#E65100",
    body_text: `Deep in the Peruvian Amazon, a river runs hot enough to cook anything that falls into it. The Shanay-timpishka—"boiled with the heat of the sun" in the local Asháninka language—reaches temperatures of nearly 200 degrees Fahrenheit along some stretches, killing any animal unlucky enough to fall in. Geoscientist Andrés Ruzo first heard about the river from his grandfather and assumed it was a legend. Boiling rivers don't exist outside of volcanic areas, and the Shanay-timpishka is hundreds of miles from the nearest volcano. When Ruzo finally visited the site in 2011, he was stunned to find the legend was real. The river runs hot for nearly four miles, steaming through the jungle like something from a primordial earth. Animals that fall in die within seconds, their flesh literally cooking. Local shamans consider the river sacred, using its waters for rituals and healing ceremonies. Ruzo's research revealed that the heat comes from geothermal sources deep underground—fault lines that allow hot water to rise from the earth's interior. But the mechanism remains partially mysterious. No other river in the world maintains such temperatures for such a distance without a nearby volcano. The Shanay-timpishka may be unique. The discovery highlights how much of our planet remains unexplored. A boiling river four miles long, known to indigenous peoples for generations, went unstudied by science until 2011. The Amazon still holds secrets that sound like myths—until someone walks into the jungle and finds them steaming through the trees. The river that shouldn't exist does, waiting to scald anyone who doubts it.`,
    design_config: {"thumbnailColor":"#E65100","titlePage":{"backgroundColor":"#E65100","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#E65100","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#E65100"},{"background":"#FFCC80","text":"#000000"}],"imagePlaceholderColors":["#E65100","#FFCC80"],"imageAspectRatios":[1.3,0.9],"imageColorOffset":1,"imagePositionSeed":3}
  },
  {
    slug: "walking-trees-ecuador",
    title: "The Forest Where Trees Walk",
    description: "Plants that move across the jungle",
    category: "Exploration",
    thumbnail_color: "#33691E",
    body_text: `In the cloud forests of Ecuador, a species of palm tree appears to walk across the jungle floor, moving up to 20 meters over its lifetime. The walking palm, Socratea exorrhiza, grows on stilt-like roots that give it the appearance of legs—and according to local guides, it actually uses them to relocate when conditions change. The phenomenon became famous after tour guides began telling visitors that the trees could walk. The explanation seemed plausible: when one side of the tree's roots dies off and new roots grow on the opposite side, the tree would effectively shift position over time. Sunlight, water, or soil conditions might trigger the movement, allowing trees to slowly migrate toward better resources. Scientists who studied the trees found the reality more complicated. While the stilt roots do grow and die, careful measurements showed no significant horizontal movement of the trunks. The walking palm, it seems, stays roughly where it sprouted. But the myth persists because it contains a kernel of biological truth: the tree's unusual root system does allow it to survive in conditions that would kill other palms. When the ground shifts or erodes, when a fallen tree creates new light gaps, the walking palm's flexible root structure keeps it stable. It may not literally walk, but it adapts in ways that seem almost intentional. The persistence of the walking tree legend says something about how we experience forests. In the green twilight of the cloud forest, surrounded by unfamiliar life forms, the boundary between fact and myth blurs. The trees may not walk, but they do live in ways we barely understand—slowly, patiently, on timescales that make human observation almost meaningless.`,
    design_config: {"thumbnailColor":"#33691E","titlePage":{"backgroundColor":"#33691E","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#33691E","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#33691E"},{"background":"#AED581","text":"#000000"}],"imagePlaceholderColors":["#33691E","#AED581"],"imageAspectRatios":[1.5,0.85],"imageColorOffset":0,"imagePositionSeed":4}
  },
  {
    slug: "lost-city-found-by-laser",
    title: "The City Laser Found",
    description: "LIDAR revealed a hidden metropolis",
    category: "Exploration",
    thumbnail_color: "#5D4037",
    body_text: `In 2016, researchers pointed lasers from helicopters at the Honduran jungle and discovered a lost city that had been hidden for five centuries. The technology, called LIDAR, could see through the dense canopy to reveal pyramids, plazas, and earthworks of an unknown civilization that thrived before European contact. The region, known as La Mosquitia, had long been rumored to contain a legendary "White City" or "City of the Monkey God." Explorers had searched for it since the 1920s, but the jungle was so dense and dangerous that traditional archaeology was nearly impossible. Venomous snakes, dense vegetation, and the risk of disease had defeated expedition after expedition. LIDAR changed everything. By firing millions of laser pulses at the ground and measuring their return time, researchers could create detailed 3D maps of the terrain beneath the trees. What emerged from the data was unmistakable: the outlines of a major settlement, complete with monumental architecture and carefully planned urban spaces. A ground expedition confirmed the LIDAR findings. Archaeologists found extensive plazas, ceremonial structures, and artifacts including carved stone vessels depicting vultures and serpents. The jungle had preserved the site so well that some artifacts were still sitting on the surface, undisturbed for centuries. The discovery demonstrated that LIDAR is revolutionizing archaeology. Similar surveys have revealed previously unknown temple complexes at Angkor Wat, Maya cities in Guatemala, and medieval settlements in Europe. We are finding lost civilizations not by hacking through jungles, but by flying over them with lasers. The cities that vanished into forests are appearing on screens, pixel by pixel.`,
    design_config: {"thumbnailColor":"#5D4037","titlePage":{"backgroundColor":"#5D4037","textColor":"#76FF03"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#5D4037","text":"#FFFFFF"},{"background":"#76FF03","text":"#000000"},{"background":"#FFFFFF","text":"#5D4037"}],"imagePlaceholderColors":["#5D4037","#76FF03"],"imageAspectRatios":[1.4,0.9],"imageColorOffset":1,"imagePositionSeed":2}
  },
  {
    slug: "ocean-inside-earth-ringwoodite",
    title: "The Ocean Inside Earth",
    description: "More water below than above",
    category: "Exploration",
    thumbnail_color: "#1565C0",
    body_text: `In 2014, scientists discovered evidence of a vast reservoir of water locked inside minerals 400 miles beneath Earth's surface. The underground ocean may contain three times as much water as all the surface oceans combined—but you could never swim in it. It exists trapped within the crystal structure of rocks. The discovery came from studying a tiny diamond that had been blasted to the surface by a volcanic eruption in Brazil. Inside the diamond was a microscopic inclusion of a mineral called ringwoodite, which had formed deep in Earth's mantle under immense pressure. When scientists analyzed it, they found it contained about 1.5 percent water by weight. That percentage might sound small, but scaled up to the entire layer where ringwoodite forms—the transition zone between the upper and lower mantle—it suggests an ocean's worth of water bound up in rock. The water isn't liquid. It exists as hydroxide ions locked in the mineral's crystal lattice, only detectable through sophisticated spectroscopy. But the implications are profound. The deep Earth may cycle water between the surface and the interior over geological timescales. Subducting tectonic plates carry water down; volcanic eruptions bring some back up. The process may regulate how much water remains on Earth's surface. The underground ocean also changes our understanding of Earth's history. Where did Earth's surface water come from? One theory held that comets delivered it; another suggested it outgassed from volcanoes. The ringwoodite discovery supports a third option: the water was always here, locked in rocks, slowly released over billions of years. We are explorers living on a thin wet skin atop an ocean we never knew existed.`,
    design_config: {"thumbnailColor":"#1565C0","titlePage":{"backgroundColor":"#1565C0","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#1565C0","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#1565C0"},{"background":"#64B5F6","text":"#000000"}],"imagePlaceholderColors":["#1565C0","#64B5F6"],"imageAspectRatios":[1.3,0.85],"imageColorOffset":0,"imagePositionSeed":3}
  },
  {
    slug: "map-predicted-continents-piri-reis",
    title: "The Map That Knew Too Much",
    description: "A chart that predicted Antarctica",
    category: "Exploration",
    thumbnail_color: "#795548",
    body_text: `In 1929, scholars examining old documents in Istanbul found a map that seemed to show the coastline of Antarctica—three centuries before the continent was officially discovered. The Piri Reis map, drawn in 1513 by an Ottoman admiral, has sparked controversy ever since. Was it evidence of ancient knowledge, or simply a coincidence? The map depicts the western coast of Africa, the eastern coast of South America, and what appears to be a landmass below them. Piri Reis noted on the map that he had compiled it from older source maps, some dating to the time of Alexander the Great. Conspiracy theorists seized on this detail, arguing that ancient civilizations must have mapped Antarctica before ice covered it. The reality is more mundane but still fascinating. Most scholars believe the southern landmass on the map represents South America, distorted and extended southward to fit the mapmaker's assumptions about what lay beyond explored waters. The resemblance to Antarctica is superficial—the actual Antarctic coastline doesn't match the map's details when examined closely. What the Piri Reis map actually shows is how Renaissance cartographers worked: they compiled information from multiple sources, often contradictory, and made their best guesses about unexplored regions. The map includes accurate details of Brazil—based on recent Portuguese explorations—alongside fanciful monsters in the ocean and imaginary islands. But the controversy has given the map an outsized cultural presence. It appears in countless documentaries about "forbidden history" and ancient mysteries. The Ottoman admiral who drew it as a practical navigation tool could never have imagined that five centuries later, people would study his work not for where to sail, but for evidence of lost civilizations.`,
    design_config: {"thumbnailColor":"#795548","titlePage":{"backgroundColor":"#795548","textColor":"#FFD60A"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#795548","text":"#FFFFFF"},{"background":"#FFD60A","text":"#000000"},{"background":"#FFFFFF","text":"#795548"}],"imagePlaceholderColors":["#795548","#FFD60A"],"imageAspectRatios":[1.5,0.9],"imageColorOffset":1,"imagePositionSeed":4}
  },
  {
    slug: "stranded-by-fame-explorer",
    title: "Stranded by Her Own Fame",
    description: "Success became her prison",
    category: "Exploration",
    thumbnail_color: "#6A1B9A",
    body_text: `Ada Blackjack was supposed to be a seamstress on a routine Arctic expedition. Instead, she became the sole survivor of a disaster on Wrangel Island—and then found that her fame as a castaway prevented her from ever being taken seriously as an explorer again. In 1921, Blackjack, a young Inupiat woman, joined an expedition to claim Wrangel Island for Canada. She needed money for her sick son's medical care and thought the job would be temporary. Within months, everything went wrong. The ship that was supposed to resupply them never came. The four male explorers made a desperate attempt to walk across the frozen sea to Siberia; three died and one was never seen again. Blackjack survived alone on the island for nearly two years, teaching herself to hunt seals, trap foxes, and fend off polar bears—skills she had never learned before. When a rescue ship finally arrived, she was healthy and composed, having kept herself alive through sheer determination. The world hailed her as a hero, the "Female Robinson Crusoe." And then the world moved on. Blackjack wanted to return to the Arctic, to use the survival skills she had painfully acquired. But no expedition would hire her. She was too famous as a victim, too associated with disaster. Her identity as a survivor overshadowed any identity as an explorer. She spent the rest of her life in poverty, her moment of fame providing neither wealth nor opportunities. She died in 1983, largely forgotten, having never returned to the ice that had made her a legend. Her story became a footnote, overwhelmed by the male explorers whose deaths she had outlived.`,
    design_config: {"thumbnailColor":"#6A1B9A","titlePage":{"backgroundColor":"#6A1B9A","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#6A1B9A","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#6A1B9A"},{"background":"#CE93D8","text":"#000000"}],"imagePlaceholderColors":["#6A1B9A","#CE93D8"],"imageAspectRatios":[1.4,0.85],"imageColorOffset":0,"imagePositionSeed":2}
  },
  {
    slug: "island-evolutionary-rules-socotra",
    title: "The Island That Rewrote Evolution",
    description: "Life evolved differently here",
    category: "Exploration",
    thumbnail_color: "#00838F",
    body_text: `Socotra Island sits in the Arabian Sea, 250 miles from the coast of Yemen, and contains life forms found nowhere else on Earth. Over a third of its plant species exist only on this one island—evolutionary experiments that have been running for millions of years in isolation. The island broke away from the African continent approximately 20 million years ago and has been isolated ever since. In that time, its plants and animals evolved along paths unavailable elsewhere. The dragon blood tree, with its umbrella-shaped canopy and blood-red sap, looks like something from an alien planet. The desert rose grows in bulbous, twisted shapes that seem designed by surrealist artists. Scientists call Socotra the "Galapagos of the Indian Ocean," and the comparison is apt. Like Darwin's famous islands, Socotra provides a natural laboratory for studying how isolation shapes life. But where the Galapagos illustrates evolution through animals—tortoises, finches, iguanas—Socotra's story is largely botanical. Its 900 plant species include 307 found nowhere else, the highest ratio of endemic plants of any island on Earth. The human history is equally distinctive. Socotrans speak a language unrelated to Arabic, preserving words that date back to the island's earliest inhabitants. Until recently, their isolation was nearly as complete as the island's flora—few outsiders visited, and few Socotrans left. Climate change and modern development now threaten Socotra's unique ecosystem. The dragon blood trees are not reproducing, and changing rainfall patterns stress species adapted to specific conditions. The island that spent millions of years evolving in isolation may not survive its first century of contact with the wider world.`,
    design_config: {"thumbnailColor":"#00838F","titlePage":{"backgroundColor":"#00838F","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#00838F","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#00838F"},{"background":"#B2EBF2","text":"#000000"}],"imagePlaceholderColors":["#00838F","#B2EBF2"],"imageAspectRatios":[1.3,0.9],"imageColorOffset":1,"imagePositionSeed":3}
  },
  {
    slug: "cave-paintings-found-by-dog",
    title: "Lascaux Found by a Lost Dog",
    description: "A pet discovered ancient art",
    category: "Exploration",
    thumbnail_color: "#8D6E63",
    body_text: `On September 12, 1940, four teenage boys followed a dog named Robot into a hole in the hills of southwestern France. They emerged having discovered the most spectacular cave paintings in the world—17,000-year-old masterpieces that had been sealed in darkness since the last Ice Age. The boys—Marcel Ravidat, Jacques Marsal, Georges Agnel, and Simon Coencas—had been exploring near the village of Montignac when Robot disappeared down a hole left by an uprooted tree. Ravidat widened the opening and slid inside. What he found by the light of his lamp stunned him: hundreds of painted animals covering the walls and ceiling, so vivid they seemed to move in the flickering shadows. The paintings of Lascaux depict horses, bulls, deer, and mysterious symbols in colors that remain bright after 170 centuries. The cave's sealed environment had preserved pigments made from iron oxides and manganese, applied with techniques that modern artists still study. Some paintings are 17 feet long; others fill spaces so cramped that the artists must have painted lying down. The boys initially kept their discovery secret, visiting the cave repeatedly to explore. When they finally told an adult, the teacher Simon Léon brought in archaeologist Henri Breuil, who declared it one of the most important archaeological finds of the century. Within months, the cave was famous worldwide. But fame brought danger. After Lascaux opened to visitors in 1948, the paintings began to deteriorate. Carbon dioxide from breathing, algae introduced by artificial lights, and temperature changes from body heat all damaged the ancient art. The cave was closed to the public in 1963, reopening only as a carefully monitored replica nearby. Robot the dog had found something too precious for humans to touch.`,
    design_config: {"thumbnailColor":"#8D6E63","titlePage":{"backgroundColor":"#8D6E63","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#8D6E63","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#8D6E63"},{"background":"#D7CCC8","text":"#000000"}],"imagePlaceholderColors":["#8D6E63","#D7CCC8"],"imageAspectRatios":[1.5,0.85],"imageColorOffset":0,"imagePositionSeed":4}
  },
  {
    slug: "deepest-hole-kola-borehole",
    title: "The Deepest Hole Ever Dug",
    description: "Drilling to the edge of hell",
    category: "Exploration",
    thumbnail_color: "#37474F",
    body_text: `In 1970, Soviet scientists began drilling a hole in Russia's Kola Peninsula with a simple goal: go deeper than anyone had ever gone before. Twenty-four years later, they had created the deepest artificial point on Earth—and discovered things they never expected to find. The Kola Superdeep Borehole reached 40,230 feet, or about 7.6 miles straight down. That's deeper than the deepest part of the ocean and well into Earth's crust. At the bottom, temperatures reached 356 degrees Fahrenheit—far hotter than models had predicted. Rocks that were supposed to be dry contained water that had been trapped for billions of years. The drilling revealed surprises at nearly every depth. Scientists found microscopic fossils of plankton two miles down, in rocks 2 billion years old. They found hydrogen gas flowing upward in quantities no one had expected. The boundary between granite and basalt that geologists had assumed would be sharp and distinct turned out to be gradual and complex. Eventually, the heat defeated them. The rocks at the bottom of the hole became almost plastic, flowing rather than fracturing. Drill bits wore out rapidly, and each replacement required hauling miles of pipe to the surface. The project was abandoned in 1992 when funding collapsed along with the Soviet Union. The hole remains today, capped by a rusty metal lid in an abandoned industrial complex. Urban legends claim the scientists drilled so deep they broke into hell—a hoax spread by a fabricated audio recording of supposed "screams of the damned." The reality is less dramatic but more fascinating: we drilled seven miles into our own planet and found we barely understood what lay beneath our feet.`,
    design_config: {"thumbnailColor":"#37474F","titlePage":{"backgroundColor":"#37474F","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#37474F","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#37474F"},{"background":"#FF6F00","text":"#FFFFFF"}],"imagePlaceholderColors":["#37474F","#FF6F00"],"imageAspectRatios":[1.4,0.9],"imageColorOffset":1,"imagePositionSeed":2}
  },
  {
    slug: "underwater-river-cenote",
    title: "The River Inside the Ocean",
    description: "A stream flowing underwater",
    category: "Exploration",
    thumbnail_color: "#006064",
    body_text: `In Mexico's Yucatan Peninsula, divers have discovered something that seems impossible: rivers flowing along the bottom of underwater caves, complete with banks, trees, and even waterfalls. These subterranean streams exist because of chemistry—dense hydrogen sulfide-rich water sinks beneath lighter fresh water, creating the illusion of a separate river flowing through the sea. The phenomenon occurs in cenotes, the sinkholes that dot the Yucatan landscape. When divers descend through fresh water and reach a layer of hydrogen sulfide, they encounter a distinct boundary that looks exactly like a water surface—except they're already underwater. Below this false surface, the denser, toxic water flows like a river, carving channels and carrying debris. The most famous of these underwater rivers was documented by Russian photographer Anatoly Beloshchin, whose images went viral online. They show divers apparently floating above a misty river, surrounded by dead trees that have fallen into the cenote over centuries. The effect is surreal, like a landscape from a dream. The hydrogen sulfide comes from decaying organic matter. Leaves, branches, and animal remains sink to the bottom and decompose, releasing gas that dissolves in water. Because hydrogen sulfide-rich water is denser than plain water, it settles into the lowest points, creating distinct layers that barely mix. Divers who explore these underwater rivers need specialized training. The hydrogen sulfide layer is toxic—exposure causes eye irritation and breathing problems. The boundary between fresh water and hydrogen sulfide can be disorienting, and divers have died after becoming confused in the strange underwater landscape. The rivers that flow beneath the water's surface remain among Earth's strangest environments.`,
    design_config: {"thumbnailColor":"#006064","titlePage":{"backgroundColor":"#006064","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#006064","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#006064"},{"background":"#80DEEA","text":"#000000"}],"imagePlaceholderColors":["#006064","#80DEEA"],"imageAspectRatios":[1.3,0.85],"imageColorOffset":0,"imagePositionSeed":3}
  },
  {
    slug: "volcano-explored-inside-thrihnukagigur",
    title: "The Volcano You Can Enter",
    description: "Descending into a magma chamber",
    category: "Exploration",
    thumbnail_color: "#BF360C",
    body_text: `In Iceland, a volcano called Thrihnukagigur offers something found nowhere else on Earth: the opportunity to descend into an empty magma chamber. Visitors ride an open cable lift 400 feet down into the heart of a dormant volcano, surrounded by walls painted in reds, oranges, and purples by ancient lava flows. The experience shouldn't be possible. Magma chambers are normally either full of molten rock or collapsed into themselves after eruptions. Thrihnukagigur is unique because its magma drained away through underground channels rather than exploding outward, leaving the chamber intact and accessible. Scientists aren't entirely sure why this happened, making the volcano both a tourist destination and a geological mystery. The chamber is enormous—large enough to fit the Statue of Liberty with room to spare. Its walls display layers of solidified magma in colors that change with mineral content: iron produces reds, copper creates greens and blues, sulfur adds yellows. The effect is like descending into an abstract painting created by the Earth itself. Exploration of the chamber began in 1974 when a local doctor named Árni B. Stefánsson rappelled inside, becoming the first person to enter a magma chamber voluntarily. He spent years advocating for public access, which finally opened in 2012 with the installation of a cable lift system. The volcano last erupted about 4,000 years ago. Geologists believe it could erupt again, though probably not for centuries. When it does, the chamber that tourists now visit will fill with lava once more, erasing the colors and formations that make it unique. For now, the world's only accessible magma chamber remains open for business—a window into the fires that shaped our planet.`,
    design_config: {"thumbnailColor":"#BF360C","titlePage":{"backgroundColor":"#BF360C","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#BF360C","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#BF360C"},{"background":"#FFAB91","text":"#000000"}],"imagePlaceholderColors":["#BF360C","#FFAB91"],"imageAspectRatios":[1.5,0.9],"imageColorOffset":1,"imagePositionSeed":4}
  },
  {
    slug: "jungle-swallowed-civilization-angkor",
    title: "The Jungle That Ate a City",
    description: "Angkor vanished into the trees",
    category: "Exploration",
    thumbnail_color: "#2E7D32",
    body_text: `When French explorer Henri Mouhot stumbled upon Angkor Wat in 1860, he found temples being strangled by tree roots, their towers barely visible above the jungle canopy. The largest religious monument ever built had been swallowed by the forest, unknown to the outside world for centuries. At its peak around 1150 AD, Angkor was the largest city on Earth. Its population may have exceeded one million—more than any European city of the time. The Khmer Empire built hundreds of temples, reservoirs, and canals across an area larger than modern Paris. Then it collapsed, and the jungle took over. The decline happened gradually. Climate studies suggest extended droughts weakened the empire's agricultural base. Thai invasions forced the capital to move. By the 1400s, Angkor was largely abandoned, its population scattered and its monuments left to the forest. Trees grew into the stonework. Roots cracked apart temples. Vines covered walls carved with thousands of figures. What Mouhot "discovered" was actually well known to local Cambodians, who had never forgotten Angkor. Buddhist monks had maintained some temples continuously. But his accounts introduced Angkor to European audiences, sparking archaeological interest that continues today. The relationship between jungle and temple has become part of Angkor's identity. At Ta Prohm, conservators deliberately left the trees in place, their roots draped over doorways like frozen waterfalls. The ruin has become more famous than any restoration could be—a monument to the power of nature to reclaim what humans build. Satellite surveys have revealed that Angkor was even larger than archaeologists suspected, with suburbs stretching for miles. The jungle didn't just eat a city; it swallowed a civilization.`,
    design_config: {"thumbnailColor":"#2E7D32","titlePage":{"backgroundColor":"#2E7D32","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#2E7D32","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#2E7D32"},{"background":"#A5D6A7","text":"#000000"}],"imagePlaceholderColors":["#2E7D32","#A5D6A7"],"imageAspectRatios":[1.4,0.85],"imageColorOffset":0,"imagePositionSeed":2}
  }
];

async function uploadStory(story) {
  const response = await fetch(`${SUPABASE_URL}/rest/v1/stories`, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      "apikey": SUPABASE_KEY,
      "Authorization": `Bearer ${SUPABASE_KEY}`,
      "Prefer": "resolution=merge-duplicates,return=minimal"
    },
    body: JSON.stringify({
      slug: story.slug,
      title: story.title,
      description: story.description,
      category: story.category,
      thumbnail_color: story.thumbnail_color,
      published: true,
      published_at: new Date().toISOString(),
      body_text: story.body_text,
      design_config: story.design_config,
      updated_at: new Date().toISOString()
    })
  });

  if (!response.ok) {
    const text = await response.text();
    throw new Error(`${response.status}: ${text}`);
  }
}

async function main() {
  console.log(`Uploading ${stories.length} Exploration "Did You Know" stories to Supabase...\n`);

  let success = 0;
  let failed = 0;

  for (const story of stories) {
    try {
      process.stdout.write(`Uploading: ${story.title}... `);
      await uploadStory(story);
      console.log("Done!");
      success++;
    } catch (error) {
      console.log(`Error: ${error.message}`);
      failed++;
    }
  }

  console.log(`\nComplete! ${success} succeeded, ${failed} failed.`);
}

main();
