/**
 * Medieval Category - 25 "Did You Know" Stories
 * Usage: node scripts/new-content-dyk/medieval-dyk.mjs
 */

const SUPABASE_URL = "https://egfwisgqdyhzpmeoracb.supabase.co";
const SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVnZndpc2dxZHloenBtZW9yYWNiIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2ODQyNzM0OSwiZXhwIjoyMDg0MDAzMzQ5fQ.S8h1fIepxWb44gPSPpWQ8fE0Q-SCYfL0QcBRUV7fXgs";

const stories = [
  {
    slug: "king-died-laughing",
    title: "The King Who Died Laughing",
    description: "A fatal joke in medieval Aragon",
    category: "Medieval",
    thumbnail_color: "#6B4C9A",
    body_text: `Martin I of Aragon died laughing in 1410, making him one of the only monarchs in history to be killed by humor. The exact joke that ended his life has been debated for six centuries, but the circumstances are well documented. Martin had been suffering from indigestion after eating an entire goose for dinner. His jester, a man known only as Borra, entered the royal chambers to cheer up the ailing king. What Borra said next would prove fatal. According to the most reliable account, the king asked Borra where he had been. The jester replied that he had been in the vineyard, where he saw a young deer hanging by its tail from a tree, and the deer was being chased by the hounds below while it hung there helplessly. The absurdity of the image—or perhaps some additional jest lost to history—struck Martin as unbearably funny. He began to laugh and could not stop. For hours, the king convulsed with uncontrollable laughter. His weakened digestive system could not handle the strain. Medical attendants tried everything to calm him, but Martin kept laughing. By morning, he was dead. His death created a succession crisis that nearly tore the Crown of Aragon apart. Martin left no legitimate heirs, and the resulting dispute over the throne led to years of political turmoil. All because of a joke about a deer. Modern medicine recognizes that death by laughter, while extremely rare, is possible. Extended laughing fits can cause cardiac arrest, asphyxiation, or brain hemorrhages in vulnerable individuals. Martin, already weakened by illness, was particularly susceptible. The jester Borra was not punished—after all, he had only been doing his job. But he earned a place in history as the man who killed a king with comedy.`,
    design_config: {"thumbnailColor":"#6B4C9A","titlePage":{"backgroundColor":"#6B4C9A","textColor":"#FFD60A"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#6B4C9A","text":"#FFFFFF"},{"background":"#FFD60A","text":"#000000"},{"background":"#C4B39A","text":"#000000"}],"imagePlaceholderColors":["#6B4C9A","#FFD60A"],"imageAspectRatios":[1.4,0.85],"imageColorOffset":0,"imagePositionSeed":2}
  },
  {
    slug: "battle-decided-by-fart",
    title: "The Battle Won by a Fart",
    description: "When gas changed military history",
    category: "Medieval",
    thumbnail_color: "#4E342E",
    body_text: `The Battle of Civitate in 1053 may have hinged on the most embarrassing moment in military history. According to medieval chroniclers, the decisive charge that routed Pope Leo IX's army began when a Norman knight's horse was startled by his own flatulence. The knight, unable to control his mount, charged directly at the papal lines. His fellow Normans, assuming this was the signal to attack, followed him. The papal army broke and fled, and the Pope himself was captured. While this account may be embellished, the Norman victory at Civitate was real and consequential. It established Norman dominance in southern Italy and eventually led to the creation of the Kingdom of Sicily. The Normans would go on to produce some of the most formidable warriors of the medieval period. Flatulence played a surprisingly significant role in medieval warfare psychology. Knights in heavy armor could not easily relieve themselves during battle, and the combination of fear, exertion, and rich food made intestinal distress common. Some military manuals actually addressed the issue, recommending specific diets before combat. The Normans themselves had a reputation for crude humor and bodily frankness that shocked their more refined enemies. Their sagas and chronicles are filled with earthy jokes that later Victorian historians carefully omitted from translations. The accidental charge at Civitate would have been entirely in character for these rough warriors. Whether the story is literally true or a later embellishment, it captured something real about medieval battle. War was chaotic, terrifying, and often decided by absurd accidents. The knight whose flatulence may have changed history was never identified by name, perhaps mercifully. He had done enough.`,
    design_config: {"thumbnailColor":"#4E342E","titlePage":{"backgroundColor":"#4E342E","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#4E342E","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#4E342E"},{"background":"#FFD60A","text":"#000000"}],"imagePlaceholderColors":["#4E342E","#FFD60A"],"imageAspectRatios":[1.3,0.9],"imageColorOffset":1,"imagePositionSeed":3}
  },
  {
    slug: "alchemist-made-gold",
    title: "The Alchemist Who Made Gold",
    description: "Did he actually transmute metal?",
    category: "Medieval",
    thumbnail_color: "#FFD700",
    body_text: `Edward Kelley claimed to have turned base metal into gold in 1586, and the strangest part is that multiple credible witnesses said they saw him do it. Kelley, an English alchemist working at the court of Holy Roman Emperor Rudolf II in Prague, performed demonstrations that baffled the finest minds of his era. In one famous experiment, conducted before a skeptical audience of nobles and scholars, Kelley heated a piece of lead with a small amount of red powder he claimed to have discovered in a Welsh ruin. The lead appeared to transform into gold. The gold was tested by the emperor's own assayers. It passed every test known to sixteenth-century metallurgy. Rudolf was so impressed that he made Kelley a baron and gave him estates worth a fortune. Other witnesses reported similar experiments with similar results. Kelley produced gold multiple times over several years, always using the same mysterious red powder. He claimed the powder was the legendary philosopher's stone, capable of transmuting any base metal into gold. The catch was that Kelley said his supply was limited and he did not know how to make more. Modern analysis suggests several possibilities. Kelley may have used sophisticated sleight of hand, substituting pre-made gold for the lead through clever misdirection. He may have exploited impurities in the lead that contained trace amounts of gold, which his process extracted and concentrated. Or he may have genuinely discovered some chemical process that mimicked transmutation without actually being supernatural. What we know for certain is that Kelley eventually fell out of favor when he could not produce the philosopher's stone itself for Rudolf. He died attempting to escape from prison in 1597. His secret, whatever it was, died with him. The gold he made—if he made it—has never been explained.`,
    design_config: {"thumbnailColor":"#FFD700","titlePage":{"backgroundColor":"#FFD700","textColor":"#000000"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#FFD700","text":"#000000"},{"background":"#FFFFFF","text":"#6B4C9A"},{"background":"#6B4C9A","text":"#FFFFFF"}],"imagePlaceholderColors":["#FFD700","#6B4C9A"],"imageAspectRatios":[1.5,0.8],"imageColorOffset":0,"imagePositionSeed":2}
  },
  {
    slug: "trial-dead-pope",
    title: "The Trial of a Dead Pope",
    description: "When they dug up a corpse to judge it",
    category: "Medieval",
    thumbnail_color: "#3E2723",
    body_text: `In January 897, Pope Stephen VI put his predecessor on trial. The problem was that the defendant, Pope Formosus, had been dead for seven months. Stephen had the corpse exhumed, dressed in papal vestments, and propped up on a throne. A deacon was appointed to answer for the dead pope since the corpse could not speak for itself. The trial, known as the Cadaver Synod, was one of the most macabre spectacles in Church history. Stephen accused the rotting corpse of perjury, coveting the papacy, and violating canon law. The deacon defending Formosus could offer little resistance against the ranting Stephen. The verdict was predetermined. Formosus was found guilty. His papal vestments were stripped from the corpse. The three fingers on his right hand used for blessing were cut off. All his papal acts were declared invalid—including the ordinations of priests and bishops, which threw the Church into chaos. The body was briefly buried in a common grave, then dug up again and thrown into the Tiber River. But the story did not end there. The Roman public was horrified by the spectacle. Rumors spread that Formosus's corpse had washed ashore and was performing miracles. A mob rose against Stephen, captured him, and had him strangled in prison. Subsequent popes reversed the Cadaver Synod's verdict and rehabilitated Formosus. The whole affair became a cautionary tale about papal politics. The Cadaver Synod revealed the depths of medieval political vendettas. Stephen had personal reasons for hating Formosus—the dead pope had ordained a bishop that Stephen considered a rival. In the ninth century, even death was no escape from your enemies.`,
    design_config: {"thumbnailColor":"#3E2723","titlePage":{"backgroundColor":"#3E2723","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#3E2723","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#3E2723"},{"background":"#C4B39A","text":"#000000"}],"imagePlaceholderColors":["#3E2723","#C4B39A"],"imageAspectRatios":[1.4,0.9],"imageColorOffset":1,"imagePositionSeed":4}
  },
  {
    slug: "feast-killed-two-thousand",
    title: "The Feast That Killed 2000",
    description: "Medieval dining turned deadly",
    category: "Medieval",
    thumbnail_color: "#B71C1C",
    body_text: `In 1212, the Count of Champagne held a wedding feast that ended in the deaths of over two thousand guests. The celebration for the marriage of Philip, son of Louis VIII of France, was meant to be the most magnificent party the region had ever seen. It became one of the worst disasters in medieval history. The feast was held in a massive temporary structure built to accommodate the thousands of nobles, knights, and servants in attendance. The building was constructed of wood and canvas, with torches and candles providing light for the evening festivities. Multiple courses of rich food were served, and wine flowed freely. No one knows exactly how the fire started. Some accounts blame an overturned candle. Others suggest cooking fires spread out of control. What is certain is that flames erupted during the height of the celebration, when the building was packed with revelers. The structure became an inferno within minutes. The exits were inadequate for the crowd. Guests in their heavy formal robes could not move quickly. Many were trampled trying to escape. Others were trapped when sections of the building collapsed. The fire burned so hot that many bodies were never identified. Contemporary chroniclers struggled to count the dead. Estimates ranged from one thousand to three thousand, with two thousand being the most commonly cited figure. Among the dead were some of the most prominent nobles in France. The disaster cast a pall over the royal marriage it was meant to celebrate. Medieval festivals were always dangerous. Temporary structures were common, fire was everywhere, crowds were packed tightly, and there were no safety regulations. But the wedding feast of 1212 stood out even by the standards of the time. It led to some of the first attempts to regulate large gatherings, though enforcement remained spotty for centuries.`,
    design_config: {"thumbnailColor":"#B71C1C","titlePage":{"backgroundColor":"#B71C1C","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#B71C1C","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#B71C1C"},{"background":"#FFD60A","text":"#000000"}],"imagePlaceholderColors":["#B71C1C","#FFD60A"],"imageAspectRatios":[1.3,0.85],"imageColorOffset":0,"imagePositionSeed":3}
  },
  {
    slug: "medieval-women-more-rights",
    title: "Medieval Women Had More Rights",
    description: "Victorian ladies lost ground",
    category: "Medieval",
    thumbnail_color: "#7B1FA2",
    body_text: `Medieval women could own property, run businesses, and sue in court. By the Victorian era, married women had lost almost all these rights. The myth of continuous progress from darkness to enlightenment does not hold up when you examine the actual legal history. In medieval England, women regularly appear in court records as property owners, guild members, and business operators. Widows inherited their husbands' estates and ran them independently. Some women became wealthy merchants in their own right. Femme sole status allowed married women to conduct business separately from their husbands, a legal category that would vanish by the nineteenth century. The decline began gradually. As common law developed in the sixteenth and seventeenth centuries, the doctrine of coverture became more rigidly enforced. Under coverture, a married woman's legal identity was absorbed into her husband's. She could not own property, sign contracts, or keep her own earnings. Everything belonged to him. By the Victorian era, the situation had become absurd. A woman who had managed her own affairs as a spinster lost all legal autonomy the moment she married. Her property, her income, even her clothing legally belonged to her husband. She could not testify against him in court or refuse him access to her body. Reform came slowly. The Married Women's Property Acts, beginning in 1870, gradually restored rights that medieval women had taken for granted. It was not until the twentieth century that English women achieved the legal equality that would have seemed unremarkable to their medieval ancestors. The arc of history does not always bend toward justice. Sometimes it loops back on itself, and rights that seem secure can vanish for centuries before being rediscovered.`,
    design_config: {"thumbnailColor":"#7B1FA2","titlePage":{"backgroundColor":"#7B1FA2","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#7B1FA2","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#7B1FA2"},{"background":"#FFD60A","text":"#000000"}],"imagePlaceholderColors":["#7B1FA2","#FFD60A"],"imageAspectRatios":[1.5,0.9],"imageColorOffset":1,"imagePositionSeed":2}
  },
  {
    slug: "vikings-discovered-america",
    title: "Vikings Beat Columbus by 500 Years",
    description: "The first Europeans in America",
    category: "Medieval",
    thumbnail_color: "#0D47A1",
    body_text: `Leif Erikson reached North America around the year 1000, nearly five centuries before Columbus sailed. The Vikings established a settlement at a place they called Vinland, and archaeological evidence proves they were there. For centuries, the Viking voyages to America were dismissed as legend. The Norse sagas described expeditions to lands west of Greenland, but scholars assumed these were mythological. Then, in 1960, archaeologists discovered the remains of a Norse settlement at L'Anse aux Meadows in Newfoundland, Canada. The site contained the foundations of eight buildings, including a forge where iron was worked. Radiocarbon dating placed the settlement around 1000 CE. Artifacts found at the site included a bronze pin of distinctly Norse design, iron nails made in the Viking style, and butternuts that do not grow in Newfoundland—evidence that the Vikings had explored further south. The settlement was small, probably housing between thirty and one hundred people. It appeared to be a base camp for expeditions rather than a permanent colony. The Vikings explored the coastline, gathering timber and possibly trading with indigenous peoples. The sagas describe both peaceful encounters and violent conflicts with the people they called Skraelings. Why did the Viking settlement fail while later European colonies succeeded? The Vikings were too few, too far from their supply lines in Greenland and Iceland. They could not maintain a permanent presence against the resistance of indigenous populations who vastly outnumbered them. The colony was abandoned within a few decades. Columbus knew nothing of the Viking voyages when he sailed in 1492. Neither did most Europeans. The Norse had kept their discovery largely to themselves, and the Greenland colony that could have provided a link to the knowledge eventually died out. The first European discovery of America was forgotten until archaeologists rediscovered it nearly a thousand years later.`,
    design_config: {"thumbnailColor":"#0D47A1","titlePage":{"backgroundColor":"#0D47A1","textColor":"#FFD60A"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#0D47A1","text":"#FFFFFF"},{"background":"#FFD60A","text":"#000000"},{"background":"#FFFFFF","text":"#0D47A1"}],"imagePlaceholderColors":["#0D47A1","#FFD60A"],"imageAspectRatios":[1.4,0.85],"imageColorOffset":0,"imagePositionSeed":4}
  },
  {
    slug: "knight-fought-at-eighty",
    title: "The Knight Who Fought at 80",
    description: "Trial by combat with a grandfather",
    category: "Medieval",
    thumbnail_color: "#5D4037",
    body_text: `Jean de Carrouges was nearly sixty when he fought a judicial duel to the death in 1386. His opponent was younger, stronger, and widely considered the better fighter. Carrouges won anyway, and the duel became one of the most famous trials by combat in medieval history. The case began when Carrouges's wife, Marguerite, accused a squire named Jacques Le Gris of raping her while Carrouges was away. Le Gris denied everything. Without witnesses, the case came down to her word against his. Carrouges demanded trial by combat, putting his life on the line to prove his wife's accusation. The duel was a spectacle. King Charles VI of France presided. Thousands of spectators packed the arena. If Carrouges lost, he would die in the arena, and his wife would be burned alive as a false accuser. The stakes could not have been higher. Le Gris was the younger man, favored by the betting public. But Carrouges fought with desperate fury. After a brutal exchange on horseback, both men fell to the ground and continued fighting on foot. Carrouges eventually pinned Le Gris and demanded he confess. Le Gris refused, maintaining his innocence even as Carrouges's sword hovered at his throat. Carrouges killed him anyway. Under the rules of trial by combat, God had rendered His verdict. Le Gris was guilty, Marguerite was vindicated, and Carrouges was a hero. He lived another decade, dying in his seventies during a crusade in Turkey. Modern historians debate whether Marguerite told the truth. Some evidence suggests Le Gris might have been innocent. But in 1386, the duel settled the matter. An aging knight had defeated a younger opponent and proven his wife's honor through blood.`,
    design_config: {"thumbnailColor":"#5D4037","titlePage":{"backgroundColor":"#5D4037","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#5D4037","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#5D4037"},{"background":"#C4B39A","text":"#000000"}],"imagePlaceholderColors":["#5D4037","#C4B39A"],"imageAspectRatios":[1.3,0.9],"imageColorOffset":1,"imagePositionSeed":3}
  },
  {
    slug: "medieval-football-violence",
    title: "Medieval Football Was Brutal",
    description: "The sport that kings tried to ban",
    category: "Medieval",
    thumbnail_color: "#1B5E20",
    body_text: `Medieval football had no rules, no field boundaries, and frequently ended in riots and deaths. English kings banned the sport repeatedly for centuries because it was too violent and distracted men from practicing archery. The game bore almost no resemblance to modern soccer. Two villages or neighborhoods would compete to move a leather ball to a goal that might be miles away. There were no teams in the modern sense—everyone from the community participated, sometimes hundreds of people on each side. The only rule was that murder was technically forbidden, though manslaughter in the heat of play was often overlooked. Matches lasted for hours, sometimes entire days. Players ran through streets, crashed into buildings, forded rivers, and trampled farms. Shops closed when a football match came through town because the mob would destroy anything in its path. Injuries were constant: broken bones, crushed ribs, gouged eyes, and occasional deaths. Kings tried to stop it. Edward II banned football in 1314 because it interfered with archery practice. Edward III, Richard II, and Henry IV all issued similar bans. None of them worked. The common people loved their brutal sport too much to give it up. Local authorities looked the other way. The violence was part of the appeal. Football provided an outlet for tensions between communities, a way for young men to prove themselves, and entertainment in a world with few diversions. The authorities eventually gave up trying to ban it entirely and instead began imposing rules. By the nineteenth century, these rules had evolved into the codified games we know today. Modern football fans who complain about hooliganism should remember that the sport was born in blood. The founders of soccer and rugby were not creating violence—they were trying to contain it.`,
    design_config: {"thumbnailColor":"#1B5E20","titlePage":{"backgroundColor":"#1B5E20","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#1B5E20","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#1B5E20"},{"background":"#8D6E63","text":"#FFFFFF"}],"imagePlaceholderColors":["#1B5E20","#8D6E63"],"imageAspectRatios":[1.5,0.85],"imageColorOffset":0,"imagePositionSeed":2}
  },
  {
    slug: "animals-put-on-trial",
    title: "The Pig Sentenced to Death",
    description: "Medieval courts tried animals",
    category: "Medieval",
    thumbnail_color: "#795548",
    body_text: `In 1386, a pig in Falaise, France was tried for the murder of a child, found guilty, and publicly executed. The pig was dressed in human clothes for its hanging. This was not unusual—medieval courts regularly tried animals for crimes. The practice seems absurd to modern minds, but it made perfect sense within medieval legal philosophy. Animals, like humans, were part of God's moral order. If an animal killed a person, it had violated that order and must be punished. The alternative—letting a murderer go unpunished simply because it was a pig—seemed equally absurd to medieval thinkers. Animals received full legal proceedings. They were assigned defense attorneys who mounted serious arguments. In one famous case, a lawyer successfully defended a swarm of rats against charges of destroying crops by arguing that his clients could not safely travel to court due to the presence of cats along the route. The court accepted this argument and dismissed the case. Pigs were the most commonly tried animals, probably because they roamed freely and occasionally attacked children. But courts also tried horses, bulls, roosters, and even insects. Swarms of locusts were excommunicated. Weevils were sued. A rooster was burned alive for laying an egg, which was considered proof of demonic possession. The trials served multiple purposes beyond justice. They reassured communities that dangerous animals would be removed. They provided public spectacle. They reinforced the idea that law and morality applied to all of God's creatures. And they allowed humans to process the trauma of animal attacks through familiar legal rituals. The practice gradually died out as Enlightenment rationalism took hold. By the eighteenth century, most educated Europeans considered animal trials barbaric superstition. But for several centuries, pigs and their lawyers had their day in court.`,
    design_config: {"thumbnailColor":"#795548","titlePage":{"backgroundColor":"#795548","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#795548","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#795548"},{"background":"#FFD60A","text":"#000000"}],"imagePlaceholderColors":["#795548","#FFD60A"],"imageAspectRatios":[1.4,0.9],"imageColorOffset":1,"imagePositionSeed":4}
  },
  {
    slug: "plague-doctor-masks-useless",
    title: "Plague Masks Did Nothing",
    description: "The iconic beaks were useless",
    category: "Medieval",
    thumbnail_color: "#212121",
    body_text: `The iconic beaked masks worn by plague doctors were invented too late to affect the Black Death and did not work anyway. The image most associated with medieval plague—the sinister bird-faced figure in black robes—comes from the seventeenth century, three hundred years after the worst pandemic in European history. The mask was designed by Charles de Lorme, a French physician, in 1619. The beak was meant to hold aromatic substances: dried flowers, herbs, camphor, and spices. The theory was that plague spread through "miasma," or bad air. If you filtered the air through pleasant-smelling herbs, you would be protected. This was completely wrong. Plague is caused by bacteria spread by flea bites, not by breathing bad smells. The beak-filtered air did nothing whatsoever to prevent infection. The doctors who wore these masks were not safer than anyone else. Many of them died. The rest of the outfit—the long robe, the gloves, the hat—probably helped somewhat by creating a barrier against infected fleas. But the distinctive beak was pure theater, based on a medical theory that had no connection to reality. The Black Death of 1347-1351 killed between thirty and sixty percent of Europe's population. At the time, doctors wore ordinary clothing and had no effective treatments. They bled patients, prescribed prayers, and watched them die. The beaked mask came later, when plague was still serious but no longer apocalyptic. The image became iconic precisely because it was dramatic. The blank eyes, the bird-like face, the funereal black—it looked like death itself stalking the streets. Artists and filmmakers have used it ever since to represent plague, medieval medicine, and general menace. But the real plague doctors of the fourteenth century looked nothing like the costume we associate with them. They wore their ordinary clothes and died in their ordinary thousands.`,
    design_config: {"thumbnailColor":"#212121","titlePage":{"backgroundColor":"#212121","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#212121","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#212121"},{"background":"#C4B39A","text":"#000000"}],"imagePlaceholderColors":["#212121","#C4B39A"],"imageAspectRatios":[1.3,0.85],"imageColorOffset":0,"imagePositionSeed":3}
  },
  {
    slug: "childrens-crusade-disaster",
    title: "The Children's Crusade Disaster",
    description: "When kids marched to their doom",
    category: "Medieval",
    thumbnail_color: "#D32F2F",
    body_text: `In 1212, thousands of children set out to conquer Jerusalem. Most of them died before reaching the Mediterranean, and those who survived may have been sold into slavery. The Children's Crusade remains one of the strangest episodes in medieval history. The movement began in France and Germany almost simultaneously. In France, a shepherd boy named Stephen claimed to have received a letter from Christ commanding him to lead a crusade. In Germany, a boy named Nicholas made similar claims. Both attracted massive followings of young people who believed they could succeed where adult crusaders had failed—through purity and faith rather than violence. The children marched south toward the Mediterranean, expecting it to part for them as the Red Sea had parted for Moses. Contemporary chronicles describe crowds of thousands, though the numbers are certainly exaggerated. Many were not actually children but poor peasants of all ages swept up in religious fervor. The crusade was doomed from the start. Children traveling without supplies, without military protection, and without realistic plans died by the hundreds. Some starved. Others fell victim to bandits. Disease swept through their camps. The survivors who reached Mediterranean ports found that the sea did not part for them. What happened next is disputed. Some accounts say the children gave up and tried to walk home, dying along the way. Others claim that merchants offered to transport them to the Holy Land, then sold them to Muslim slave traders in North Africa. This darker version may be legend, but the outcome was tragic either way. The Children's Crusade became a symbol of misguided idealism, a reminder that faith alone cannot overcome the brutal realities of the medieval world.`,
    design_config: {"thumbnailColor":"#D32F2F","titlePage":{"backgroundColor":"#D32F2F","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#D32F2F","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#D32F2F"},{"background":"#FFD60A","text":"#000000"}],"imagePlaceholderColors":["#D32F2F","#FFD60A"],"imageAspectRatios":[1.5,0.9],"imageColorOffset":1,"imagePositionSeed":2}
  },
  {
    slug: "castle-designed-indefensible",
    title: "The Castle Built to Fall",
    description: "A fortress designed for failure",
    category: "Medieval",
    thumbnail_color: "#455A64",
    body_text: `Bodiam Castle in England is one of the most photographed medieval fortresses in the world. It is also nearly useless as a military installation. The castle was designed to look impressive, not to withstand a siege. Edward Dalyngrigge built Bodiam in 1385, ostensibly to defend against French raids during the Hundred Years' War. The castle has all the elements visitors expect: a moat, towers, battlements, and a gatehouse. But look closer and the design makes no military sense. The walls are too thin to resist artillery. The towers lack proper fighting platforms. The gun loops are positioned at angles that limit their field of fire. The moat, while picturesque, is too shallow to prevent attackers from wading across. Most damningly, the castle has enormous windows facing outward—architectural features that look beautiful but would provide convenient entry points for any serious attacker. Military historians now believe Bodiam was built primarily for show. Dalyngrigge was a newly wealthy knight who needed to display his status. A grand castle announced his importance and justified his position among the gentry. The defensive features were theater, designed to impress visitors rather than repel invaders. The castle was never seriously attacked during the medieval period. By the time the English Civil War arrived in the seventeenth century, the garrison surrendered without a fight—perhaps recognizing that the walls could not withstand modern cannon. Today Bodiam survives as a romantic ruin, its reflection shimmering in the moat, its towers silhouetted against the English sky. It is exactly what Dalyngrigge wanted: a picture-perfect castle that never had to prove itself in battle.`,
    design_config: {"thumbnailColor":"#455A64","titlePage":{"backgroundColor":"#455A64","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#455A64","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#455A64"},{"background":"#C4B39A","text":"#000000"}],"imagePlaceholderColors":["#455A64","#C4B39A"],"imageAspectRatios":[1.4,0.85],"imageColorOffset":0,"imagePositionSeed":4}
  },
  {
    slug: "beer-safer-than-water",
    title: "Beer Was Safer Than Water",
    description: "Why everyone drank all day",
    category: "Medieval",
    thumbnail_color: "#F57C00",
    body_text: `Medieval people drank beer for breakfast because it was safer than water. The brewing process killed pathogens that made untreated water deadly. Even children drank weak ale, and abstaining from alcohol was considered dangerous. Water in medieval cities was genuinely hazardous. Wells were often contaminated with human and animal waste. Rivers that provided drinking water also received sewage. People noticed that those who drank water frequently got sick, while those who drank beer did not. They attributed this to mysterious properties of alcohol rather than understanding germs, but their practical conclusion was correct. The solution was "small beer," a low-alcohol beverage that everyone consumed throughout the day. Small beer typically contained around one to three percent alcohol—enough to prevent bacterial growth but not enough to impair function. Workers drank it on the job. Monks brewed it in their monasteries. Households produced it as routinely as they baked bread. The brewing process accomplished two things. First, boiling the water killed bacteria. Second, the alcohol and hops provided ongoing antimicrobial effects. Even beer that sat for days remained safer than fresh water from a well. Some historians argue that chronic mild intoxication was simply normal in medieval Europe. The effects would have been subtle—people were accustomed to small beer from childhood—but the population was never entirely sober. This may explain some of the apparent impulsivity and violence of medieval society, though cultural factors were certainly more important. Clean water only became available in European cities during the nineteenth century, when modern sanitation systems were built. Until then, the medieval solution remained practical: if you wanted to stay healthy, you drank beer. The water would kill you.`,
    design_config: {"thumbnailColor":"#F57C00","titlePage":{"backgroundColor":"#F57C00","textColor":"#000000"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#F57C00","text":"#000000"},{"background":"#FFFFFF","text":"#F57C00"},{"background":"#5D4037","text":"#FFFFFF"}],"imagePlaceholderColors":["#F57C00","#5D4037"],"imageAspectRatios":[1.3,0.9],"imageColorOffset":1,"imagePositionSeed":3}
  },
  {
    slug: "king-thought-he-was-glass",
    title: "The King Made of Glass",
    description: "Charles VI's bizarre delusion",
    category: "Medieval",
    thumbnail_color: "#81D4FA",
    body_text: `Charles VI of France believed he was made of glass and would shatter if anyone touched him. He had reinforced clothing made with iron ribs to protect his fragile body. He refused to let people come near him. And he ruled France for over forty years in this condition. Charles's first psychotic episode struck in 1392 when he was just twenty-three. He attacked and killed several of his own knights before being subdued. From then on, he experienced periods of lucidity alternating with complete madness. During his worst episodes, he did not recognize his wife, forgot he was king, and ran wildly through the halls of his palace. The glass delusion became his most famous symptom. Charles insisted that his body was made of glass and could break at any moment. He would not allow himself to be touched. He required special protective garments. When forced to move, he walked with exaggerated care, terrified of falling and shattering. The delusion was not unique to Charles. "Glass delusion" was recognized as a specific form of madness in the late medieval and early modern periods. Other sufferers included Princess Alexandra of Bavaria and the Dutch scholar Caspar Barlaeus. Doctors debated whether it was caused by excessive humors, demonic possession, or simply extreme fragility of the nerves. Charles's madness had devastating political consequences. His inability to rule allowed competing factions to tear France apart. The English invaded during his periods of incapacity, leading to military disasters including the Battle of Agincourt. Joan of Arc would eventually rally France, but the chaos of Charles's reign took decades to repair. The glass king remained on his throne until his death in 1422, never fully recovered, forever believing he might shatter at any moment.`,
    design_config: {"thumbnailColor":"#81D4FA","titlePage":{"backgroundColor":"#81D4FA","textColor":"#000000"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#81D4FA","text":"#000000"},{"background":"#FFFFFF","text":"#6B4C9A"},{"background":"#6B4C9A","text":"#FFFFFF"}],"imagePlaceholderColors":["#81D4FA","#6B4C9A"],"imageAspectRatios":[1.5,0.85],"imageColorOffset":0,"imagePositionSeed":2}
  },
  {
    slug: "medieval-dentistry-advanced",
    title: "Medieval Dentists Were Skilled",
    description: "Surprisingly sophisticated tooth care",
    category: "Medieval",
    thumbnail_color: "#607D8B",
    body_text: `Medieval dentistry was far more advanced than most people assume. Practitioners filled cavities with gold leaf, used wire braces to straighten teeth, and performed root canals that show sophisticated understanding of dental anatomy. The image of the barber-surgeon yanking teeth with pliers is only part of the story. Islamic and Byzantine medical texts preserved dental knowledge from antiquity and developed new techniques. These texts eventually reached Western Europe, where university-trained physicians incorporated them into practice. By the thirteenth century, some European practitioners were performing complex dental surgeries. Archaeological evidence supports this. Skulls from medieval cemeteries show drilled teeth filled with metal, wax, or resin. Some show evidence of healed surgical interventions—proof that patients survived the procedures. Others show deliberately filed teeth, possibly for cosmetic reasons or to treat decay. Medieval people cared about their teeth more than stereotypes suggest. Toothbrushes made from twigs existed in various forms. Recipes for tooth powders included ingredients like salt, crushed seashells, and herbs with genuine antimicrobial properties. Mouthwashes combined wine or vinegar with honey and spices. These remedies were not as effective as modern products, but they were not useless either. The main limitation was anesthesia. Medieval dentists had only alcohol and opium-based preparations to dull pain, making surgery excruciating for patients. This discouraged people from seeking treatment until problems became severe, leading to the tooth loss that we associate with the period. Wealthy patients could afford gold fillings and careful treatment. Poor patients got their teeth pulled by traveling barbers with little training. The gap between elite and popular dentistry was enormous. But the best medieval dentistry rivaled techniques that would not become common again until the nineteenth century.`,
    design_config: {"thumbnailColor":"#607D8B","titlePage":{"backgroundColor":"#607D8B","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#607D8B","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#607D8B"},{"background":"#C4B39A","text":"#000000"}],"imagePlaceholderColors":["#607D8B","#C4B39A"],"imageAspectRatios":[1.4,0.9],"imageColorOffset":1,"imagePositionSeed":4}
  },
  {
    slug: "nuns-wrote-erotic-poetry",
    title: "Medieval Nuns Wrote Erotica",
    description: "Passionate poetry from the convent",
    category: "Medieval",
    thumbnail_color: "#AD1457",
    body_text: `Some of the most passionate love poetry of the medieval period was written by nuns. These women, cloistered from the world and theoretically devoted to spiritual pursuits, produced verses of startling sensuality addressed to both Christ and to other women. The most famous example is Hildegard of Bingen, a twelfth-century abbess whose letters to the nun Richardis von Stade express intense emotional attachment. Hildegard wrote of her soul being "devastated" when Richardis was transferred to another convent. Other letters describe spiritual ecstasy in terms indistinguishable from physical passion. Modern scholars debate how to interpret this material. Some argue that medieval language of spiritual love simply used erotic vocabulary without erotic intent. The "bride of Christ" metaphor invited sensual imagery even in purely religious contexts. Others contend that some nuns experienced genuine romantic and physical attraction to their sisters and expressed it through acceptable spiritual frameworks. The nuns of the Helfta convent in thirteenth-century Germany produced particularly striking texts. Mechthild of Magdeburg wrote "The Flowing Light of the Godhead," which describes mystical union with God in explicitly physical terms. Gertrude of Helfta wrote devotional exercises that imagine kissing and embracing Christ in ways that modern readers find startling. Convents were paradoxical spaces. They offered women education, intellectual community, and freedom from marriage and childbearing. But they also confined passionate individuals in close quarters for their entire lives. Some channeled that passion into art and mysticism. Others apparently found human objects for their affection. The Church authorities occasionally noticed and disapproved. But the poetry survived, preserved by the very institutions that officially condemned its implications.`,
    design_config: {"thumbnailColor":"#AD1457","titlePage":{"backgroundColor":"#AD1457","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#AD1457","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#AD1457"},{"background":"#FFD60A","text":"#000000"}],"imagePlaceholderColors":["#AD1457","#FFD60A"],"imageAspectRatios":[1.3,0.85],"imageColorOffset":0,"imagePositionSeed":3}
  },
  {
    slug: "knights-obsessed-fashion",
    title: "Knights Were Fashion Obsessed",
    description: "Vanity in shining armor",
    category: "Medieval",
    thumbnail_color: "#FF8F00",
    body_text: `Medieval knights spent fortunes on clothing and accessories. Their obsession with fashion shocked moralists, bankrupted families, and drove innovation in textile manufacturing. A knight's wardrobe might cost more than a peasant village earned in a decade. The stereotype of the knight in plain steel armor misses the reality. Yes, armor was essential, but what mattered socially was everything else: the surcoat of finest silk, the jeweled sword belt, the pointed shoes that extended so far they had to be chained to the knee, the cape lined with exotic fur from Russia or the Baltic. Fashion changed constantly. In the twelfth century, fashionable men wore their hair long and their robes flowing. By the fourteenth century, styles demanded short fitted jackets called doublets, tight hose that left nothing to the imagination, and shoes with points stuffed to exaggerated lengths. Moralists condemned these changes as evidence of moral decay. Sumptuary laws tried to restrict who could wear what. Kings decreed that only nobles could wear certain furs, certain colors, certain fabrics. These laws were routinely ignored. The newly wealthy bourgeoisie dressed as richly as they could afford, prompting ever more elaborate dress from nobles who needed to distinguish themselves. The practical effects were significant. Demand for luxury textiles drove international trade. Florentine bankers made fortunes financing the cloth industry. Flemish weavers produced the finest woolens in Europe. Wars were fought over trade routes for silk and spices used in fashionable dress. Knights who neglected fashion risked social ruin. Being poorly dressed at court was almost as damaging as cowardice in battle. A lord's followers reflected his status—if they looked shabby, so did he. Fashion was serious business, and medieval knights took it seriously indeed.`,
    design_config: {"thumbnailColor":"#FF8F00","titlePage":{"backgroundColor":"#FF8F00","textColor":"#000000"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#FF8F00","text":"#000000"},{"background":"#FFFFFF","text":"#FF8F00"},{"background":"#6B4C9A","text":"#FFFFFF"}],"imagePlaceholderColors":["#FF8F00","#6B4C9A"],"imageAspectRatios":[1.5,0.9],"imageColorOffset":1,"imagePositionSeed":2}
  },
  {
    slug: "medieval-cats-bad-reputation",
    title: "Medieval Cats Were Despised",
    description: "Felines had a terrible reputation",
    category: "Medieval",
    thumbnail_color: "#3E2723",
    body_text: `Medieval Europeans associated cats with witchcraft, heresy, and the devil. People killed cats in massive numbers, and some historians believe this worsened the Black Death by allowing rat populations to explode. Cats had been valued in antiquity. The Egyptians worshipped them; the Romans kept them for pest control. But medieval Christian authorities grew suspicious of the animals. Cats were nocturnal, secretive, and associated with pagan traditions. Their glowing eyes in darkness suggested demonic connection. Pope Gregory IX's papal bull of 1233 specifically linked cats to devil worship. Inquisitors reported that heretics kissed cats' hindquarters as part of satanic rituals. Whether anyone actually did this is doubtful, but the association stuck. Cats became symbols of evil throughout Catholic Europe. The consequences were severe. People killed cats as a religious duty. Some towns organized annual cat massacres as public entertainment. Cats were burned in bonfires, thrown from towers, and tortured in elaborate public ceremonies. The populations declined drastically in many areas. Some scholars argue that fewer cats meant more rats, and more rats meant more fleas carrying plague bacteria. The Black Death of 1347-1351 killed a third of Europe. If cat persecution contributed to the rat population explosion that spread the disease, medieval superstition may have killed tens of millions of people. This theory is debated—plague would have spread regardless of cat populations—but the irony is striking. Not all cats were persecuted. Monastery cats were often protected because they guarded grain stores from mice. Some regions of Europe retained healthier attitudes toward felines. But the overall trend was unmistakable: medieval Christians killed cats, and they may have paid for it with their lives.`,
    design_config: {"thumbnailColor":"#3E2723","titlePage":{"backgroundColor":"#3E2723","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#3E2723","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#3E2723"},{"background":"#FFD60A","text":"#000000"}],"imagePlaceholderColors":["#3E2723","#FFD60A"],"imageAspectRatios":[1.4,0.85],"imageColorOffset":0,"imagePositionSeed":4}
  },
  {
    slug: "pope-joan-myth",
    title: "The Pope Who Was a Woman",
    description: "The legend of Pope Joan",
    category: "Medieval",
    thumbnail_color: "#6B4C9A",
    body_text: `For centuries, Catholics and Protestants alike believed that a woman had once been pope. Pope Joan supposedly reigned in the ninth century, her sex undetected until she gave birth during a papal procession. The story is almost certainly false, but it circulated as fact for five hundred years. The legend first appeared in chronicles from the thirteenth century, claiming that a learned woman from Germany had disguised herself as a man and risen through Church ranks until she reached the papacy. She reigned for two years under the name John. Her downfall came when she unexpectedly went into labor during a procession from St. Peter's to the Lateran. She gave birth in the street and died shortly after, either from childbirth complications or from mob violence. Medieval writers treated Pope Joan as historical fact. They included her in lists of popes. They claimed that subsequent papal processions avoided the street where she had given birth. They even invented a special chair with a hole in the seat, supposedly used to verify the sex of future popes through direct inspection. Protestants loved the story. What better proof of Catholic corruption than a secret female pope? Catholic authorities eventually investigated and concluded that Pope Joan was fictional—the papal records showed no gap that could accommodate her reign. Modern historians agree: the story was invented long after it supposedly occurred, and no contemporary evidence supports it. But the legend persisted because it served various purposes: anti-papal propaganda, titillation, and perhaps some genuine belief that women could achieve anything if sufficiently determined. Pope Joan became a symbol of hidden female power, remembered long after she was proven never to have existed.`,
    design_config: {"thumbnailColor":"#6B4C9A","titlePage":{"backgroundColor":"#6B4C9A","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#6B4C9A","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#6B4C9A"},{"background":"#C4B39A","text":"#000000"}],"imagePlaceholderColors":["#6B4C9A","#C4B39A"],"imageAspectRatios":[1.3,0.9],"imageColorOffset":1,"imagePositionSeed":3}
  },
  {
    slug: "monks-invented-champagne",
    title: "Monks Invented Champagne by Accident",
    description: "The bubbles they couldn't explain",
    category: "Medieval",
    thumbnail_color: "#FDD835",
    body_text: `Medieval monks considered the bubbles in champagne to be a fault—proof that their wine had failed. For centuries, winemakers in the Champagne region tried desperately to prevent the fizzing that we now prize. The problem was the cold climate. Champagne lies at the northern edge of wine-growing territory. Winters were cold enough to stop fermentation before it was complete. When spring warmed the cellars, the dormant yeast woke up and resumed fermenting, producing carbon dioxide that had no way to escape from sealed bottles. The pressure built up until bottles exploded. Workers in champagne cellars wore iron masks to protect their faces from flying glass. A chain reaction could destroy an entire vintage in minutes—one bottle's explosion would trigger the bottles around it. Winemakers called champagne "the devil's wine" because of its unpredictable violence. Dom Perignon, the Benedictine monk often credited with inventing champagne, actually spent most of his career trying to prevent bubbles. His innovations—careful blending of grapes, gentle pressing, and improved bottle technology—were designed to make still wine, not sparkling. The myth that he exclaimed "I am drinking the stars!" upon tasting champagne is a nineteenth-century invention. The taste for bubbles emerged gradually. English drinkers in the seventeenth century began to appreciate the fizzy wine that French producers considered ruined. English glassmakers developed stronger bottles that could withstand the pressure. Eventually, French producers realized that foreigners would pay premium prices for their accidents. By the eighteenth century, champagne production was deliberate. But for centuries before that, the monks who made it considered every bubble evidence of failure—a devil's trick that ruined good wine.`,
    design_config: {"thumbnailColor":"#FDD835","titlePage":{"backgroundColor":"#FDD835","textColor":"#000000"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#FDD835","text":"#000000"},{"background":"#FFFFFF","text":"#6B4C9A"},{"background":"#6B4C9A","text":"#FFFFFF"}],"imagePlaceholderColors":["#FDD835","#6B4C9A"],"imageAspectRatios":[1.5,0.85],"imageColorOffset":0,"imagePositionSeed":2}
  },
  {
    slug: "medieval-unicorn-obsession",
    title: "The Unicorn Obsession",
    description: "They really believed unicorns existed",
    category: "Medieval",
    thumbnail_color: "#E1BEE7",
    body_text: `Medieval Europeans genuinely believed unicorns existed. They traded unicorn horns for vast sums, kept them in royal treasuries, and used them to detect poison. The horns were actually narwhal tusks, but no one in Europe knew that. The unicorn myth came from classical antiquity, filtered through Christian symbolism. Medieval bestiaries described unicorns as real animals, fierce and wild, capturable only by virgin maidens. Their horns supposedly had miraculous properties: dipped in poisoned water, they would purify it; touched to a wound, they would heal it. European nobles paid enormous prices for alicorn—unicorn horn. A single horn might cost ten times its weight in gold. Royalty displayed them in their treasuries alongside crown jewels. The Habsburg emperors possessed several. Pope Clement VII reportedly paid the equivalent of a small fortune for one. The horns came from narwhals, Arctic whales with long spiral tusks. Vikings and other northern traders brought them to European markets, where buyers assumed they came from unicorns. The traders saw no reason to correct this profitable misunderstanding. Some skeptics existed. In 1636, a Danish scientist examined what was called a unicorn horn and identified it as coming from a marine animal. But belief persisted for decades afterward. People wanted unicorns to be real. The idea of testing poisons with alicorn powder was too comforting to abandon. Churches displayed supposed unicorn horns as relics. Artists painted unicorns in religious allegories. Tapestries depicted the hunt for the magical creature. The unicorn became so embedded in European culture that its nonexistence hardly mattered. We still use unicorn imagery today, centuries after anyone believed the animals were real.`,
    design_config: {"thumbnailColor":"#E1BEE7","titlePage":{"backgroundColor":"#E1BEE7","textColor":"#000000"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#E1BEE7","text":"#000000"},{"background":"#FFFFFF","text":"#6B4C9A"},{"background":"#6B4C9A","text":"#FFFFFF"}],"imagePlaceholderColors":["#E1BEE7","#6B4C9A"],"imageAspectRatios":[1.4,0.9],"imageColorOffset":1,"imagePositionSeed":4}
  },
  {
    slug: "lepers-had-rights",
    title: "Lepers Had Legal Protections",
    description: "Outcasts with surprising rights",
    category: "Medieval",
    thumbnail_color: "#78909C",
    body_text: `Medieval lepers were forced to live apart from society, forbidden to touch healthy people, and required to ring bells announcing their approach. Yet they also had legal protections that many peasants lacked, including the right to receive charity and guaranteed care in leprosariums. The disease we now call Hansen's disease was widespread in medieval Europe. Victims were declared legally dead—their property distributed, their marriages dissolved—and expelled from normal society. They had to wear distinctive clothing, carry clappers or bells, and stand downwind of healthy people. In theory, they were untouchables. In practice, their status was more complicated. Leprosariums—institutions for leper care—were among the most numerous charitable foundations of the medieval period. At their peak, England alone had over three hundred. These institutions provided food, shelter, and religious services to their residents. Funding came from donations that wealthy patrons gave to ensure their own spiritual salvation. Lepers were also permitted to beg, and giving to them was considered particularly meritorious. Some lepers accumulated significant wealth through charity. Others received regular payments from family members or civic authorities. The image of the destitute leper abandoned to die was not universal—many received better care than the general poor. Legal codes protected lepers from certain abuses. They could not be arbitrarily expelled from leprosariums. They retained some property rights within their colonies. Courts occasionally intervened when healthy people cheated or abused them. Paradoxically, the very visible suffering of lepers gave them a kind of social leverage. The disease was considered divine punishment, but also divine trial. Those who endured it patiently were thought to be earning their salvation. Medieval society expelled its lepers—then felt obligated to care for them.`,
    design_config: {"thumbnailColor":"#78909C","titlePage":{"backgroundColor":"#78909C","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#78909C","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#78909C"},{"background":"#C4B39A","text":"#000000"}],"imagePlaceholderColors":["#78909C","#C4B39A"],"imageAspectRatios":[1.3,0.85],"imageColorOffset":0,"imagePositionSeed":3}
  },
  {
    slug: "king-never-bathed",
    title: "The King Who Never Bathed",
    description: "Louis XIV's legendary filth",
    category: "Medieval",
    thumbnail_color: "#4527A0",
    body_text: `Louis XIV of France, the Sun King who built Versailles and dominated Europe for seventy years, reportedly took only three baths in his entire adult life. His doctors advised against more frequent washing. They believed it was dangerous. The theory behind this advice was humoral medicine. Physicians thought that water opened the pores and allowed disease to enter the body. Hot baths were particularly dangerous—they allegedly weakened the constitution and made people vulnerable to plague. Cold baths were slightly better but still risky. The safest course was to avoid immersion entirely. Instead of bathing, Louis and his courtiers wiped themselves with dry cloths and changed their linen frequently. The emphasis was on clean undergarments rather than clean skin. A gentleman might change his shirt several times a day while never once immersing himself in water. Perfume became essential. The French court was famous for its heavy use of scent to mask body odor. Courtiers doused themselves in fragrances and carried scented handkerchiefs. The elaborate gardens of Versailles were partly designed to provide pleasant smells to cover the stench of unwashed aristocrats. Louis's personal habits were legendary. Visitors noted that approaching the king required strong stomachs. His mouth was particularly offensive—he lost most of his teeth to decay and his breath was reportedly unbearable. Yet courtiers competed for the privilege of standing near him. The medical consensus began to shift only in the eighteenth century. New theories suggested that bathing might actually be healthy. By the nineteenth century, regular bathing became a mark of respectability. But Louis XIV lived and died by the old rules, ruling Europe from his magnificent palace while rarely touching water.`,
    design_config: {"thumbnailColor":"#4527A0","titlePage":{"backgroundColor":"#4527A0","textColor":"#FFD60A"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#4527A0","text":"#FFFFFF"},{"background":"#FFD60A","text":"#000000"},{"background":"#FFFFFF","text":"#4527A0"}],"imagePlaceholderColors":["#4527A0","#FFD60A"],"imageAspectRatios":[1.5,0.9],"imageColorOffset":1,"imagePositionSeed":2}
  },
  {
    slug: "medieval-ice-skating-warfare",
    title: "Ice Skating Was Medieval Warfare",
    description: "Frozen battles in northern Europe",
    category: "Medieval",
    thumbnail_color: "#0288D1",
    body_text: `Medieval Scandinavians and Russians strapped animal bones to their feet to fight battles on frozen lakes. Ice skating was not recreation—it was a military technology that gave northern armies crucial advantages in winter warfare. The first skates were made from the leg bones of horses, cattle, or elk, ground flat on the bottom and attached to shoes with leather straps. These bone skates did not allow for the pushing motion of modern skating. Instead, skaters propelled themselves with pointed poles, like cross-country skiing but on ice. The technique was less elegant but perfectly effective for rapid movement across frozen terrain. Winter campaigns in the Baltic region often hinged on control of frozen waters. Lakes and rivers that blocked armies in summer became highways in winter. Forces that could move quickly on ice could strike where enemies least expected, then retreat before opposition could mobilize. The Teutonic Knights learned this lesson painfully in 1242 at the Battle on the Ice, where Russian forces under Alexander Nevsky defeated the German crusaders on the frozen surface of Lake Peipus. According to legend, the ice broke under the weight of the heavily armored knights, drowning many of them. Modern historians doubt this account—the ice would have been thick enough to support far greater weight—but the battle demonstrated that northern armies understood winter warfare better than their German opponents. Bone skates remained in use for centuries. Even after iron blades were developed in the thirteenth century, many communities continued using bone because it was cheaper and readily available. The transition to modern recreational skating only occurred in the seventeenth century, when Dutch craftsmen developed steel blades and the curved blade shape that allows modern skating techniques. For medieval warriors, skating was serious business.`,
    design_config: {"thumbnailColor":"#0288D1","titlePage":{"backgroundColor":"#0288D1","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#0288D1","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#0288D1"},{"background":"#B3E5FC","text":"#000000"}],"imagePlaceholderColors":["#0288D1","#B3E5FC"],"imageAspectRatios":[1.4,0.85],"imageColorOffset":0,"imagePositionSeed":4}
  }
];

async function uploadStory(story) {
  const response = await fetch(`${SUPABASE_URL}/rest/v1/stories`, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      "apikey": SUPABASE_KEY,
      "Authorization": `Bearer ${SUPABASE_KEY}`,
      "Prefer": "resolution=merge-duplicates,return=minimal"
    },
    body: JSON.stringify({
      slug: story.slug,
      title: story.title,
      description: story.description,
      category: story.category,
      thumbnail_color: story.thumbnail_color,
      published: true,
      published_at: new Date().toISOString(),
      body_text: story.body_text,
      design_config: story.design_config,
      updated_at: new Date().toISOString()
    })
  });

  if (!response.ok) {
    const text = await response.text();
    throw new Error(`${response.status}: ${text}`);
  }
}

async function main() {
  console.log(`Uploading ${stories.length} Medieval "Did You Know" stories to Supabase...\n`);

  let success = 0;
  let failed = 0;

  for (const story of stories) {
    try {
      process.stdout.write(`Uploading: ${story.title}... `);
      await uploadStory(story);
      console.log("Done!");
      success++;
    } catch (error) {
      console.log(`Error: ${error.message}`);
      failed++;
    }
  }

  console.log(`\nComplete! ${success} succeeded, ${failed} failed.`);
}

main();
