/**
 * Science Category - 25 "Did You Know" Stories
 * Usage: node scripts/new-content-dyk/science-dyk.mjs
 */

const SUPABASE_URL = "https://egfwisgqdyhzpmeoracb.supabase.co";
const SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVnZndpc2dxZHloenBtZW9yYWNiIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2ODQyNzM0OSwiZXhwIjoyMDg0MDAzMzQ5fQ.S8h1fIepxWb44gPSPpWQ8fE0Q-SCYfL0QcBRUV7fXgs";

const stories = [
  {
    slug: "scientist-drank-cholera-bacteria",
    title: "He Drank a Glass of Cholera",
    description: "The doctor who proved bacteria cause disease",
    category: "Science",
    thumbnail_color: "#1976D2",
    body_text: `In 1892, Max von Pettenkofer raised a flask of cloudy liquid to his lips and drank. The flask contained enough cholera bacteria to kill several people. He was trying to prove a point, and he was spectacularly wrong. Pettenkofer was one of the most respected scientists in Germany, a pioneer of public health who had improved sanitation across Europe. But he believed cholera was caused by miasma—bad air from rotting matter—not by germs. Robert Koch had just identified the cholera bacterium and demonstrated that it caused the disease. Pettenkofer thought this was nonsense. To prove Koch wrong, he obtained a fresh culture of cholera bacteria from Koch's own laboratory. Then he drank it. The quantity was enormous—one milliliter of broth containing a billion cholera vibrios, enough bacteria to infect entire city blocks during an epidemic. Pettenkofer's assistants watched in horror. By every calculation, he should have been dead within days. What happened next baffled everyone. Pettenkofer developed mild diarrhea for about a week, then recovered completely. He declared victory. The bacteria, he announced, were clearly not dangerous. He published his self-experiment as proof that Koch's germ theory was wrong. Koch was not convinced. Modern scientists believe Pettenkofer survived because he had been exposed to cholera before, giving him partial immunity, or because his stomach acid killed most of the bacteria before they reached his intestine. His survival was luck, not evidence. The irony is tragic. Pettenkofer's prestige delayed acceptance of germ theory in Germany for years. His self-experiment convinced many that hand-washing and water treatment were unnecessary. How many people died because a famous scientist survived drinking cholera through sheer luck? No one can calculate the cost of his survival.`,
    design_config: {"thumbnailColor":"#1976D2","titlePage":{"backgroundColor":"#1976D2","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#1976D2","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#1976D2"},{"background":"#FFD60A","text":"#000000"}],"imagePlaceholderColors":["#1976D2","#FFD60A"],"imageAspectRatios":[1.4,0.85],"imageColorOffset":0,"imagePositionSeed":2}
  },
  {
    slug: "doctor-operated-on-himself",
    title: "The Surgeon Who Removed His Appendix",
    description: "Self-surgery in Antarctica saved his life",
    category: "Science",
    thumbnail_color: "#D32F2F",
    body_text: `On April 30, 1961, Leonid Rogozov felt a familiar pain in his lower right abdomen. As the only doctor at a Soviet Antarctic research station, he knew exactly what it meant: acute appendicitis. Without surgery, he would die. The nearest hospital was thousands of miles away across frozen ocean. Evacuation was impossible—a blizzard had grounded all aircraft. Rogozov had one option: operate on himself. He prepared the station's meteorologist and mechanical engineer to serve as assistants. Neither had any medical training. He positioned a mirror to see his own abdomen, then injected local anesthetic into his abdominal wall. Lying on his left side, he made the first incision at 2:00 AM. The operation took nearly two hours. Rogozov worked mostly by touch, since the mirror reversed his movements and the angle made direct vision difficult. Several times he nearly fainted from pain and shock. His assistants fed him pills and held his instruments. When he finally located the appendix, it was already gangrenous—another day and it would have ruptured, killing him. He removed it, cleaned the cavity, and sewed himself shut with twenty stitches. Rogozov was back at work within two weeks. He remained in Antarctica for another year, eventually returning to the Soviet Union as a modest hero. He rarely spoke about the operation, preferring to discuss his scientific research on polar medicine. The self-surgery became more famous than he ever intended. It has been studied by space agencies planning long-duration missions where emergency evacuation is impossible. If humans ever travel to Mars, the protocols for self-surgery will owe something to a young doctor who had no choice but to cut himself open in the coldest place on Earth.`,
    design_config: {"thumbnailColor":"#D32F2F","titlePage":{"backgroundColor":"#D32F2F","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#D32F2F","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#D32F2F"},{"background":"#B3E5FC","text":"#000000"}],"imagePlaceholderColors":["#D32F2F","#B3E5FC"],"imageAspectRatios":[1.3,0.9],"imageColorOffset":1,"imagePositionSeed":3}
  },
  {
    slug: "penicillin-discovered-power-outage",
    title: "The Mold That Saved Millions",
    description: "A forgotten experiment changed medicine",
    category: "Science",
    thumbnail_color: "#4CAF50",
    body_text: `Alexander Fleming did not discover penicillin through careful research. He discovered it because he was messy, took long vacations, and got lucky with the weather. In September 1928, Fleming returned to his laboratory at St. Mary's Hospital in London after a month-long holiday. He had left stacks of petri dishes containing staphylococcus bacteria unwashed in his haste to leave. Opening the lab, he began sorting through the mess. Most dishes were ruined by various mold contaminations—a common problem in the pre-air-conditioned hospital. Then he noticed something strange. In one dish, a blob of blue-green mold had grown in the corner. Around this mold, the bacteria had died. There was a clear zone where nothing could survive near the fungal colony. "That's funny," Fleming reportedly said. Most scientists would have thrown away the contaminated dish. Fleming kept it. The mold was Penicillium notatum, and it was producing a substance that killed bacteria without harming human tissue. Fleming called this substance penicillin. But here's what makes the discovery truly miraculous: penicillin mold spores had drifted up from a laboratory one floor below, where a mycologist was studying fungi. They had landed on Fleming's dish during the one week of that summer when London's temperature was perfect for both mold growth and bacterial stagnation. A few degrees warmer and the bacteria would have overgrown the mold. A few degrees cooler and the mold wouldn't have produced penicillin. Fleming was too casual a scientist to develop penicillin into a usable drug—that work took another decade and other scientists. But without his messy lab, his long vacation, and London's August weather, the antibiotic revolution might have been delayed by years. Sometimes the greatest discoveries happen to those who aren't looking.`,
    design_config: {"thumbnailColor":"#4CAF50","titlePage":{"backgroundColor":"#4CAF50","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#4CAF50","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#4CAF50"},{"background":"#1976D2","text":"#FFFFFF"}],"imagePlaceholderColors":["#4CAF50","#1976D2"],"imageAspectRatios":[1.5,0.85],"imageColorOffset":0,"imagePositionSeed":4}
  },
  {
    slug: "immortal-jellyfish-turritopsis",
    title: "The Jellyfish That Cannot Die",
    description: "Nature's secret to eternal life",
    category: "Science",
    thumbnail_color: "#00BCD4",
    body_text: `There is a creature on Earth that is biologically immortal. Turritopsis dohrnii, a tiny jellyfish smaller than a fingernail, can reverse its own aging process indefinitely. When injured, sick, or simply old, it transforms back into a younger version of itself and starts life over again. The process is called transdifferentiation. When stressed, the adult jellyfish sinks to the seafloor and its cells begin to change. The bell collapses into a blob. The tentacles are reabsorbed. Over a few days, the blob reorganizes itself into a polyp—the juvenile form of a jellyfish—genetically identical to the adult but physiologically young again. From this polyp, a new adult jellyfish buds and swims away. Scientists have observed this regeneration cycle multiple times in laboratory tanks. There appears to be no limit to how many times the jellyfish can revert. In theory, a single Turritopsis could have been cycling through this process since before the dinosaurs went extinct. Whether any individual has actually achieved such longevity in the wild is unknown. The immortal jellyfish is not invulnerable. It can be eaten by predators, killed by disease, or destroyed by environmental changes. Its immortality is only potential, not guaranteed. But the mechanism itself has captured the attention of medical researchers worldwide. If we understood how Turritopsis reprograms its cells to become younger, we might find ways to repair aging human tissue. The jellyfish regenerates by activating genes that most animals turn off after embryonic development. Somehow it remembers how to be young. This tiny, transparent creature, pulsing through warm oceans around the world, may hold secrets that could transform human medicine. For now, it remains the only known animal that has found a biological escape from death.`,
    design_config: {"thumbnailColor":"#00BCD4","titlePage":{"backgroundColor":"#00BCD4","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#00BCD4","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#00BCD4"},{"background":"#E1F5FE","text":"#000000"}],"imagePlaceholderColors":["#00BCD4","#E1F5FE"],"imageAspectRatios":[1.4,0.9],"imageColorOffset":1,"imagePositionSeed":2}
  },
  {
    slug: "tardigrades-survive-space",
    title: "The Animal That Survives Space",
    description: "Microscopic creatures defy all limits",
    category: "Science",
    thumbnail_color: "#7B1FA2",
    body_text: `In 2007, scientists sent tardigrades into the vacuum of space and left them there for ten days. When the tiny creatures returned to Earth, they were fine. Some had even laid eggs in orbit. Tardigrades, also called water bears for their lumbering gait under a microscope, are eight-legged micro-animals about half a millimeter long. They live everywhere on Earth: in Antarctic ice, in hot springs, in the sediment of ocean trenches, in the moisture between roof tiles. They have been found alive after being frozen at temperatures near absolute zero. They have survived pressures six times greater than the deepest ocean. They have endured radiation doses hundreds of times higher than would kill a human. The space experiment pushed their limits further. The European Space Agency exposed tardigrades to the complete vacuum of space, unfiltered solar radiation, and cosmic rays. Most organisms would have their internal fluids boil instantly in vacuum. Radiation would shatter their DNA. The tardigrades survived by entering a state called cryptobiosis. They expelled all water from their bodies, contracted into tiny husks called tuns, and essentially suspended their metabolism entirely. In this state, they needed no oxygen, no food, no protection. When rehydrated back on Earth, they woke up and continued living. Scientists have since found that tardigrades possess unusual proteins that form a glassy shell around their cells during desiccation, protecting vital structures from damage. They also have extraordinary DNA repair mechanisms that can fix radiation damage that would kill other organisms. No one is certain why tardigrades evolved such extreme survival abilities. Nothing in their normal environment requires them. Perhaps they developed these powers gradually, adapting to increasingly harsh microhabitats over millions of years. Whatever the reason, tardigrades have become symbols of life's astonishing resilience.`,
    design_config: {"thumbnailColor":"#7B1FA2","titlePage":{"backgroundColor":"#7B1FA2","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#7B1FA2","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#7B1FA2"},{"background":"#FFD60A","text":"#000000"}],"imagePlaceholderColors":["#7B1FA2","#FFD60A"],"imageAspectRatios":[1.3,0.85],"imageColorOffset":0,"imagePositionSeed":3}
  },
  {
    slug: "man-hole-in-stomach-digestion",
    title: "The Man With a Window to His Stomach",
    description: "An accident revealed how digestion works",
    category: "Science",
    thumbnail_color: "#FF5722",
    body_text: `In 1822, a fur trapper named Alexis St. Martin was accidentally shot in the stomach at close range. The wound was massive—you could see directly into his stomach through a hole in his side. Against all odds, he survived. The hole never closed. Dr. William Beaumont, an Army surgeon who treated St. Martin, realized he had an unprecedented opportunity. For the first time in history, someone could observe human digestion directly. Beaumont could insert food samples into St. Martin's stomach and withdraw them later to study how they changed. He could watch gastric juices flow and see the stomach walls contract. The trapper became an unwilling laboratory subject for nearly a decade. Beaumont conducted hundreds of experiments on St. Martin's exposed digestive system. He discovered that digestion was primarily a chemical process, not mechanical grinding as previously believed. He identified gastric acid as the key component and measured how long different foods took to break down. His work revolutionized understanding of human digestion. The relationship between doctor and patient was troubled from the start. St. Martin repeatedly fled Beaumont's custody, only to be tracked down and returned to continue the experiments. He was legally bound to Beaumont through a contract that seems exploitative by modern standards. St. Martin never consented enthusiastically to being studied. Despite everything, St. Martin outlived Beaumont by nearly thirty years, dying in 1880 at age eighty-three—with the hole in his stomach still open. His family, fearful that scientists would try to acquire his body for study, let his corpse decompose before burial and buried him eight feet deep to prevent grave robbers. The window into his stomach finally closed forever.`,
    design_config: {"thumbnailColor":"#FF5722","titlePage":{"backgroundColor":"#FF5722","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#FF5722","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#FF5722"},{"background":"#FFF3E0","text":"#000000"}],"imagePlaceholderColors":["#FF5722","#FFF3E0"],"imageAspectRatios":[1.5,0.9],"imageColorOffset":1,"imagePositionSeed":4}
  },
  {
    slug: "scientists-tasted-discoveries",
    title: "When Scientists Tasted Everything",
    description: "The dangerous tradition of licking research",
    category: "Science",
    thumbnail_color: "#FFC107",
    body_text: `For centuries, tasting was a standard scientific technique. Chemists routinely put unknown substances in their mouths to identify them. The practice killed some scientists and gave others lasting health problems. A few got lucky and discovered sweetness. Saccharin, the first artificial sweetener, was discovered in 1879 when chemist Constantin Fahlberg forgot to wash his hands before dinner. His bread tasted sweet; he traced the sweetness to a compound he had synthesized that day from coal tar derivatives. He had been working with potentially toxic chemicals and simply licked his fingers without thinking. The discovery made him wealthy. Aspartame was found through similar carelessness in 1965 when James Schlatter licked his finger while working on an anti-ulcer drug. Sucralose was discovered when a researcher misheard instructions to "test" a compound and "tasted" it instead. All three discoveries depended on scientists putting experimental substances in their mouths. The tradition goes back to the origins of chemistry. Alchemists tasted their creations routinely. Robert Boyle, one of the founders of modern chemistry, recommended tasting as a standard analytical technique. The great Swedish chemist Carl Wilhelm Scheele tasted every new substance he created, including hydrogen cyanide and mercury compounds. He died at forty-three. Some famous taste tests proved crucial. Humphry Davy tasted nitrous oxide and discovered its anesthetic properties. A physician named Thomas Willis tasted diabetic urine and noted it was sweet, leading to the discovery of glucose in diabetic blood. Other taste tests ended badly. Several chemists died from tasting cyanide compounds. Others developed chronic poisoning from repeated exposure to lead, mercury, and arsenic. Modern laboratory safety rules forbid tasting anything, ever. But many discoveries we take for granted came from scientists who were willing to put science on their tongues.`,
    design_config: {"thumbnailColor":"#FFC107","titlePage":{"backgroundColor":"#FFC107","textColor":"#000000"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#FFC107","text":"#000000"},{"background":"#FFFFFF","text":"#FFC107"},{"background":"#1976D2","text":"#FFFFFF"}],"imagePlaceholderColors":["#FFC107","#1976D2"],"imageAspectRatios":[1.4,0.85],"imageColorOffset":0,"imagePositionSeed":2}
  },
  {
    slug: "magenta-color-doesnt-exist",
    title: "Magenta Is Not Real",
    description: "Your brain invented a color",
    category: "Science",
    thumbnail_color: "#E91E63",
    body_text: `Magenta does not exist on the visible light spectrum. It has no wavelength. Your brain simply invents it to fill a gap, and you have been seeing an impossible color your entire life. The visible spectrum runs from red at one end to violet at the other. Every color you see corresponds to a specific wavelength of light—except magenta. Look at a rainbow: red fades to orange to yellow to green to blue to violet. There is no magenta. The spectrum doesn't loop back around. Yet when your eyes receive both red light and blue light simultaneously, with no green in between, your brain refuses to average them into the expected result (which would be green, the middle wavelength). Instead, it invents magenta—a color that literally doesn't exist in physics. Your visual system treats the color wheel as a continuous loop, connecting red and violet with magenta even though no physical light corresponds to that connection. It's a neurological hack, a workaround your brain uses to make sense of conflicting information. Some philosophers argue this makes magenta a pure qualia—a subjective experience with no objective reality. The color exists only in minds, never in the physical world. Every magenta object you see is actually reflecting a combination of wavelengths that your brain interprets as something that cannot be. Other colors have their own oddities. Yellow, as you perceive it, is produced by your brain averaging red and green signals—but pure yellow light also exists and looks identical. Your brain cannot tell the difference between actual yellow and simulated yellow. Television screens exploit this by mixing red, green, and blue pixels to create every color you see, including the impossible magenta. You trust your eyes to show you reality. But your visual system is constantly inventing, interpolating, and lying to you in ways you cannot detect. Magenta is just the most obvious example.`,
    design_config: {"thumbnailColor":"#E91E63","titlePage":{"backgroundColor":"#E91E63","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#E91E63","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#E91E63"},{"background":"#00BCD4","text":"#FFFFFF"}],"imagePlaceholderColors":["#E91E63","#00BCD4"],"imageAspectRatios":[1.3,0.9],"imageColorOffset":1,"imagePositionSeed":3}
  },
  {
    slug: "lobsters-biologically-immortal",
    title: "Lobsters Don't Age",
    description: "The crustaceans that defy death",
    category: "Science",
    thumbnail_color: "#F44336",
    body_text: `Lobsters do not show typical signs of aging. They don't slow down, weaken, or lose fertility as they grow older. A fifty-year-old lobster is just as capable as a five-year-old one—only bigger. This phenomenon, called negligible senescence, means lobsters appear to have no maximum lifespan determined by biology. The secret lies in their telomeres. In most animals, including humans, telomeres—the protective caps on chromosomes—shorten with each cell division. When they become too short, cells can no longer divide, and aging accelerates. Lobsters produce an enzyme called telomerase throughout their bodies and throughout their lives. This enzyme rebuilds telomeres, essentially resetting the aging clock with every cell division. Lobsters keep growing indefinitely, molting their shells and expanding year after year. The largest lobster ever caught weighed over forty-four pounds and was estimated to be over a hundred years old. Some marine biologists believe lobsters could potentially live for centuries if they avoided predators, disease, and human fishermen. But there's a cruel twist. Lobsters don't die of old age, but they do die of molting. As a lobster grows larger, each molt requires more energy. Eventually, many old lobsters become too exhausted to complete the molting process and die trapped in their own shells, or they develop shell disease from accumulating damage. Their immortality is theoretical rather than practical. Scientists have studied lobster telomerase hoping to understand whether similar mechanisms could slow human aging. So far, the research has produced more questions than answers. Human cells with artificially enhanced telomerase tend to become cancerous—eternal youth comes with eternal cell division, which is exactly what cancer is. The lobster has solved a problem we cannot yet crack: how to keep living without the cells becoming destructive. Until we understand their secret fully, lobsters remain nature's tantalizing hint that aging might be optional.`,
    design_config: {"thumbnailColor":"#F44336","titlePage":{"backgroundColor":"#F44336","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#F44336","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#F44336"},{"background":"#FFCDD2","text":"#000000"}],"imagePlaceholderColors":["#F44336","#FFCDD2"],"imageAspectRatios":[1.5,0.85],"imageColorOffset":0,"imagePositionSeed":4}
  },
  {
    slug: "placebo-effect-works-anyway",
    title: "Placebos Work Even When You Know",
    description: "The power of believing in nothing",
    category: "Science",
    thumbnail_color: "#9C27B0",
    body_text: `Here is something that should be impossible: placebos work even when patients know they're taking placebos. Tell someone you're giving them a sugar pill with no active ingredients, explain that it's pharmacologically inert, and many of them will still feel better. This is called the open-label placebo effect, and it's forcing scientists to reconsider everything they thought they knew about the mind-body connection. In 2010, Harvard researchers gave patients with irritable bowel syndrome pills clearly labeled "placebo." The patients were explicitly told the pills contained no medicine. Fifty-nine percent reported significant symptom improvement—nearly double the rate of patients who received no treatment at all. Similar studies have found open-label placebos effective for chronic pain, cancer-related fatigue, and allergic rhinitis. The effects are not imaginary. Brain scans show that placebos trigger real neurological changes, releasing endorphins and activating the same neural pathways as actual drugs. When patients expect to feel better, their brains make it happen—even when they consciously know there's no chemical reason for improvement. This creates a paradox for medicine. If placebos work through expectation, and open-label placebos generate expectation despite the patient knowing they're fake, then what exactly is going on? Some researchers believe the ritual of taking medicine matters as much as the medicine itself. The act of swallowing a pill, the attention from a healthcare provider, the psychological framing of treatment—all these factors may activate healing responses independent of any drug. Others suggest that different parts of the brain process the knowledge "this is fake" and the expectation "taking pills helps me feel better" separately, allowing both to be true simultaneously. The implications are profound. Perhaps we could harness placebo effects deliberately, prescribing open-label placebos for conditions where they're effective and reserving active drugs for more serious cases. The mind, it turns out, has powers we are only beginning to understand.`,
    design_config: {"thumbnailColor":"#9C27B0","titlePage":{"backgroundColor":"#9C27B0","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#9C27B0","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#9C27B0"},{"background":"#E1BEE7","text":"#000000"}],"imagePlaceholderColors":["#9C27B0","#E1BEE7"],"imageAspectRatios":[1.4,0.9],"imageColorOffset":1,"imagePositionSeed":2}
  },
  {
    slug: "bananas-are-radioactive",
    title: "Bananas Are Radioactive",
    description: "The fruit that sets off detectors",
    category: "Science",
    thumbnail_color: "#FFEB3B",
    body_text: `Every banana you eat is radioactive. The yellow fruit contains potassium, and a small fraction of all potassium is the radioactive isotope potassium-40. A single banana emits about fifteen becquerels of radiation. This sounds alarming until you understand the scale. Radiation experts actually use a measurement called the "banana equivalent dose" to help the public understand radiation exposure. One banana equals about 0.1 microsieverts. You would need to eat ten million bananas in a short period to receive a lethal dose of radiation. The radiation in bananas, like all potassium-40 radiation, passes through your body without accumulating. Your system maintains a constant potassium level regardless of how many bananas you eat. Shipping bananas has occasionally triggered radiation detectors at ports and border crossings. Large shipments of bananas set off alarms designed to detect nuclear materials. Security personnel have learned to recognize the signature of potassium-40 and distinguish it from more dangerous sources. Bananas aren't even the most radioactive common food. Brazil nuts contain radium-226, making them significantly more radioactive than bananas. Potatoes, beans, and carrots all contain potassium-40. Your own body is radioactive too—the average human contains about 7,000 becquerels of radiation from natural potassium and other elements. The background radiation on Earth means every living thing is constantly exposed to small amounts of radiation. The banana's radioactivity is trivial compared to cosmic rays, radon in the air, and radiation from rocks and soil. The "banana equivalent dose" became popular precisely because it demonstrates how insignificant most radiation exposures really are. The next time someone mentions radiation danger, remember the banana. Everything in the universe is slightly radioactive. The question is always how much, and bananas remind us that the answer is usually not enough to matter.`,
    design_config: {"thumbnailColor":"#FFEB3B","titlePage":{"backgroundColor":"#FFEB3B","textColor":"#000000"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#FFEB3B","text":"#000000"},{"background":"#FFFFFF","text":"#FFEB3B"},{"background":"#4CAF50","text":"#FFFFFF"}],"imagePlaceholderColors":["#FFEB3B","#4CAF50"],"imageAspectRatios":[1.3,0.85],"imageColorOffset":0,"imagePositionSeed":3}
  },
  {
    slug: "bacteria-outnumber-human-cells",
    title: "You Are Mostly Not You",
    description: "Bacteria outnumber your cells",
    category: "Science",
    thumbnail_color: "#8BC34A",
    body_text: `For decades, scientists believed that bacterial cells in the human body outnumbered human cells by ten to one. The reality, discovered through more careful counting, is less dramatic but still unsettling: the ratio is roughly one to one. You carry about thirty-eight trillion bacterial cells alongside thirty-seven trillion human cells. You are, in terms of cell count, approximately half bacteria. The weight disparity is more reassuring. Human cells are much larger than bacterial cells, so all that bacteria weighs only about two hundred grams—less than half a pound. Your microbiome, as this bacterial community is called, lives primarily in your gut, but also on your skin, in your mouth, and in various body cavities. These organisms are not passive passengers. Your gut bacteria digest food you couldn't otherwise process, synthesize vitamins your body can't make, train your immune system, and influence your mood through neural connections to the brain. The relationship is symbiotic: you provide them a home and nutrients; they provide services you cannot survive without. When your microbiome is disrupted—by antibiotics, illness, or dietary changes—the effects can be severe. Depression, obesity, allergies, and autoimmune diseases have all been linked to microbiome imbalances. Fecal transplants, which transfer gut bacteria from healthy donors, have proven effective for treating certain infections that don't respond to other treatments. The concept of individual identity gets complicated when half your cells belong to other species. The bacteria in your gut have their own DNA, their own metabolism, their own evolutionary interests. Some researchers argue that the human body should be understood as an ecosystem rather than a single organism. "You" are actually a collaboration of trillions of living things that happen to be using the same body. The boundary between self and other turns out to be far blurrier than we ever imagined.`,
    design_config: {"thumbnailColor":"#8BC34A","titlePage":{"backgroundColor":"#8BC34A","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#8BC34A","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#8BC34A"},{"background":"#DCEDC8","text":"#000000"}],"imagePlaceholderColors":["#8BC34A","#DCEDC8"],"imageAspectRatios":[1.5,0.9],"imageColorOffset":1,"imagePositionSeed":4}
  },
  {
    slug: "humans-share-dna-with-bananas",
    title: "You Are 60% Banana",
    description: "The genes you share with fruit",
    category: "Science",
    thumbnail_color: "#FFC107",
    body_text: `Humans share approximately sixty percent of their DNA with bananas. This fact sounds absurd until you understand what DNA actually does. Most of the genetic code in any complex organism handles basic cellular functions—energy production, cell division, protein synthesis. These fundamental processes evolved billions of years ago, before plants and animals diverged, and have been conserved ever since because they work. The shared DNA doesn't make you partly banana. It makes you partly the same as the common ancestor of all complex life on Earth. Bananas and humans inherited the same genetic machinery for running a cell because we're both descendants of ancient single-celled organisms that figured out these biochemical tricks a billion years ago. The similarities go deeper than you might expect. Humans share about eighty-five percent of their DNA with mice, ninety-six percent with chimpanzees, and about fifty percent with a fruit fly. We share significant genetic overlap with yeast, roundworms, and even bacteria. Life on Earth is fundamentally one related family, using variations on the same molecular toolkit. What makes humans different from bananas isn't the bulk of our DNA—it's the small percentage that codes for structural proteins, regulatory genes, and developmental timing. The instructions for making neurons, bones, and opposable thumbs occupy a surprisingly small fraction of the genome. Most of our DNA is doing the same job as a banana's DNA: keeping cells alive. This genetic relatedness has practical implications for science. Researchers study fruit flies and roundworms because their basic biology resembles ours. Medications are tested in mice because mouse biochemistry predicts human reactions. The universality of DNA means discoveries in one species often translate to others. The next time you eat a banana, consider that you're consuming a distant relative. Every living thing on Earth is family, connected by an unbroken chain of inheritance stretching back to the origin of life itself.`,
    design_config: {"thumbnailColor":"#FFC107","titlePage":{"backgroundColor":"#FFC107","textColor":"#000000"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#FFC107","text":"#000000"},{"background":"#FFFFFF","text":"#FFC107"},{"background":"#1976D2","text":"#FFFFFF"}],"imagePlaceholderColors":["#FFC107","#1976D2"],"imageAspectRatios":[1.4,0.85],"imageColorOffset":0,"imagePositionSeed":2}
  },
  {
    slug: "trees-communicate-fungal-networks",
    title: "Trees Talk Underground",
    description: "The forest's hidden communication system",
    category: "Science",
    thumbnail_color: "#2E7D32",
    body_text: `Beneath every forest floor lies an internet made of fungi. Trees use this network to share nutrients, send warning signals, and support their offspring—a system scientists have nicknamed the "Wood Wide Web." The network consists of mycorrhizal fungi that connect to tree roots, forming a symbiotic relationship. The fungi receive sugars from the trees; in exchange, they extend the trees' effective root systems by miles and facilitate transfers between trees. A single tree can be connected to hundreds of other trees through this underground mesh. The communication is surprisingly sophisticated. When a tree is attacked by insects, it can send chemical signals through the fungal network to warn neighboring trees, which then increase their own defensive compounds before the insects arrive. Mother trees—the largest and oldest in a forest—preferentially send nutrients to their own offspring, recognizing them by chemical signatures and supporting them more than unrelated seedlings. When a tree is dying, it sometimes dumps its remaining resources into the network, distributing its carbon and nutrients to its neighbors. Ecologist Suzanne Simard, who pioneered much of this research, found that forests function less like collections of individual trees and more like single superorganisms. The biggest trees serve as hubs, connecting dozens of other trees. When these hub trees are removed by logging, the network degrades and surrounding trees suffer. This understanding is changing forestry practices. Clear-cutting destroys the fungal networks that support forest regeneration. Selective harvesting that preserves mother trees allows forests to recover faster. The trees that remain can nurse seedlings through the network, providing resources until they can photosynthesize independently. The image of a tree as a solitary individual turns out to be wrong. Trees are social organisms, dependent on community and cooperation, communicating in ways we are only beginning to understand.`,
    design_config: {"thumbnailColor":"#2E7D32","titlePage":{"backgroundColor":"#2E7D32","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#2E7D32","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#2E7D32"},{"background":"#8D6E63","text":"#FFFFFF"}],"imagePlaceholderColors":["#2E7D32","#8D6E63"],"imageAspectRatios":[1.3,0.9],"imageColorOffset":1,"imagePositionSeed":3}
  },
  {
    slug: "human-body-not-human",
    title: "Most of Your Body Isn't Human",
    description: "The aliens living inside you",
    category: "Science",
    thumbnail_color: "#00897B",
    body_text: `If you counted every gene in your body, the overwhelming majority would not be human. For every human gene, you carry approximately one hundred fifty microbial genes. The genetic information running your body is less than one percent human. This doesn't mean you're mostly bacteria in terms of function or identity. Human cells are vastly larger and more complex than bacterial cells. But the sheer genetic diversity inside you comes from the trillions of microorganisms that call your body home. Your microbiome contains over a thousand different species, each with its own genome, collectively encoding millions of genes that interact with your bodily systems. These foreign genes perform functions your human genome cannot. They break down plant fibers into digestible sugars. They synthesize vitamins K and B12. They metabolize drugs, influencing how medications affect you. They produce neurotransmitters that affect your mood and behavior. In a real sense, these microbial genes are part of your operating system. The composition of your microbiome is unique to you, like a fingerprint. Twins raised in the same household have different microbial communities. Your microbiome changes with your diet, your environment, the people you live with, even your stress levels. It's constantly in flux, responding to your life in ways your human genome cannot. Some researchers now argue that evolution selected not for individual humans but for human-microbe partnerships. Our ancestors who hosted beneficial microbiomes survived better than those who didn't. Over millions of years, we co-evolved with our microbial passengers, becoming dependent on genes that were never part of our own DNA. The boundary of "self" dissolves when you examine it closely. You are a walking ecosystem, a genetic chimera, a collaboration of species so intimate that separating them would kill you. The aliens inside you are essential to who you are.`,
    design_config: {"thumbnailColor":"#00897B","titlePage":{"backgroundColor":"#00897B","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#00897B","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#00897B"},{"background":"#B2DFDB","text":"#000000"}],"imagePlaceholderColors":["#00897B","#B2DFDB"],"imageAspectRatios":[1.5,0.85],"imageColorOffset":0,"imagePositionSeed":4}
  },
  {
    slug: "universe-smells-rum-raspberries",
    title: "Space Smells Like Rum",
    description: "The surprising scent of the cosmos",
    category: "Science",
    thumbnail_color: "#3F51B5",
    body_text: `The center of our galaxy smells like rum and tastes like raspberries. Or it would, if you could survive long enough to sniff it. Astronomers have detected a molecule called ethyl formate in the massive dust cloud Sagittarius B2, near the galactic core. This chemical compound is responsible for the flavor of raspberries and the smell of rum. There's enough of it in that one cloud to fill three hundred billion billion billion liters of the drink. Space is filled with surprising molecular complexity. Using radio telescopes that detect the unique spectral signatures of different chemicals, astronomers have identified over two hundred molecules drifting between the stars. They've found alcohol, sugar, amino acids, and complex organic compounds that form the building blocks of life. The inventory keeps growing as telescopes become more sensitive. Ethyl formate was discovered in 2009 by researchers searching for amino acids—the components of proteins. They found glycine, the simplest amino acid, confirming that the building blocks of life exist beyond Earth. The raspberry smell was an unexpected bonus, generating headlines about the delicious galaxy. The molecules in space form through slow chemical reactions in dust clouds where temperatures hover near absolute zero. Cosmic rays provide energy that drives reactions between simpler compounds. Over millions of years, increasingly complex molecules accumulate, eventually seeding planets and asteroids with organic chemistry. Some scientists believe Earth's original organic compounds came from space. Meteorites have delivered amino acids, sugars, and nucleobases—the components of DNA—to our planet. The chemistry of life may have originated in the cold, dark spaces between stars, assembled atom by atom over cosmic timescales. The universe, it turns out, has been brewing the ingredients for life since long before our sun existed. The rum-scented raspberry cloud is just one example of a cosmos far more chemically creative than we once imagined.`,
    design_config: {"thumbnailColor":"#3F51B5","titlePage":{"backgroundColor":"#3F51B5","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#3F51B5","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#3F51B5"},{"background":"#E91E63","text":"#FFFFFF"}],"imagePlaceholderColors":["#3F51B5","#E91E63"],"imageAspectRatios":[1.4,0.9],"imageColorOffset":1,"imagePositionSeed":2}
  },
  {
    slug: "honey-never-spoils",
    title: "Honey Lasts Forever",
    description: "The food that cannot go bad",
    category: "Science",
    thumbnail_color: "#FF8F00",
    body_text: `Archaeologists have found honey in Egyptian tombs over three thousand years old. It was still perfectly edible. Honey is the only food that never spoils, maintaining its nutritional and antibacterial properties essentially forever. The secret lies in honey's chemistry. It is extremely low in moisture—about seventeen percent water—creating an environment where bacteria cannot grow. Most spoilage organisms need water to survive, and honey is simply too dry for them. Any bacteria that land on honey have their water sucked out through osmosis and die. But low moisture alone isn't enough. Many dried foods still spoil. Honey also contains hydrogen peroxide, produced by an enzyme that bees add during the honey-making process. When bees regurgitate nectar into the hive, they mix it with glucose oxidase from their stomachs. This enzyme breaks down glucose into gluconic acid and hydrogen peroxide, creating a mildly acidic, antiseptic environment. The acidity itself helps preserve honey. With a pH between three and four, honey is too acidic for most microorganisms. Combined with the low moisture and the hydrogen peroxide, the environment inside a jar of honey is actively hostile to life. Nothing can survive there long enough to reproduce. Ancient cultures discovered honey's preservative properties empirically. Egyptians used it to embalm bodies and preserve food for the afterlife. Greeks and Romans used it to treat wounds, a practice that continued until antibiotics became available. Modern medical research has confirmed that honey—particularly certain varieties like Manuka—can treat antibiotic-resistant infections. The catch is that honey must be properly sealed. If exposed to humidity, honey absorbs water from the air, eventually reaching a moisture level where fermentation becomes possible. The three-thousand-year-old Egyptian honey survived because it was sealed in jars and stored in the dry desert climate of tombs. Keep your honey dry, and it will outlast you, your grandchildren, and possibly human civilization itself.`,
    design_config: {"thumbnailColor":"#FF8F00","titlePage":{"backgroundColor":"#FF8F00","textColor":"#000000"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#FF8F00","text":"#000000"},{"background":"#FFFFFF","text":"#FF8F00"},{"background":"#5D4037","text":"#FFFFFF"}],"imagePlaceholderColors":["#FF8F00","#5D4037"],"imageAspectRatios":[1.3,0.85],"imageColorOffset":0,"imagePositionSeed":3}
  },
  {
    slug: "glass-is-not-liquid",
    title: "Glass Isn't Really a Liquid",
    description: "Debunking a persistent myth",
    category: "Science",
    thumbnail_color: "#607D8B",
    body_text: `You may have heard that glass is actually a liquid that flows very slowly. The evidence seems compelling: medieval cathedral windows are thicker at the bottom than at the top, apparently because the glass has flowed downward over centuries. This explanation is completely wrong. Glass is not a liquid. Those old windows are thicker at the bottom because medieval glassmakers couldn't produce perfectly flat panes. When installing wavy glass, builders sensibly placed the thicker edge at the bottom for stability. The "flowing glass" myth refuses to die, partly because glass does have unusual properties that blur the line between solid and liquid. Glass is an amorphous solid, meaning its molecules are arranged randomly like a liquid rather than in the regular crystalline structure of most solids. This gives glass some liquid-like characteristics without actually making it a liquid. If glass flowed at room temperature, even incredibly slowly, we could calculate how much it should flow over a given time. The mathematics of viscous flow is well understood. When scientists run these calculations for glass at room temperature, the answer is that glass would need longer than the age of the universe to flow a visible amount. Medieval windows haven't had nearly enough time. Other evidence confirms glass doesn't flow. Ancient Egyptian and Roman glassware thousands of years old shows no distortion. Telescope mirrors ground to precise specifications decades ago maintain their shapes perfectly. Fiber optic cables, which would malfunction if glass flowed even slightly, work indefinitely. The confusion arises from glass's transition between solid and liquid states. When heated, glass doesn't melt at a specific temperature like ice does. Instead, it gradually softens over a temperature range. This gradual transition makes the boundary between solid glass and liquid glass fuzzy. But at room temperature, the glass in your windows is as solid as any rock.`,
    design_config: {"thumbnailColor":"#607D8B","titlePage":{"backgroundColor":"#607D8B","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#607D8B","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#607D8B"},{"background":"#B0BEC5","text":"#000000"}],"imagePlaceholderColors":["#607D8B","#B0BEC5"],"imageAspectRatios":[1.5,0.9],"imageColorOffset":1,"imagePositionSeed":4}
  },
  {
    slug: "humans-cannot-multitask",
    title: "Multitasking Is a Myth",
    description: "Your brain can only do one thing",
    category: "Science",
    thumbnail_color: "#673AB7",
    body_text: `When you think you're multitasking, you're actually task-switching—rapidly shifting attention between different activities. Your brain cannot truly do two cognitive tasks simultaneously. This limitation is hardwired into your neural architecture and cannot be overcome through practice. Neuroscientists have measured what happens when people attempt to multitask. Brain imaging shows that attention functions as a bottleneck: only one stream of information at a time can be consciously processed. When you text while listening to someone speak, you're actually alternating between the two tasks so quickly that it feels simultaneous. Neither task gets your full attention. The costs of task-switching are significant and measurable. Every time you switch tasks, your brain needs time to load the mental context of the new activity and suppress the old one. This "switching cost" typically takes several tenths of a second. When you're rapidly switching—as in texting while driving—these costs accumulate, significantly degrading performance on both tasks. Studies of multitasking have consistently found that people who do it frequently actually become worse at it over time. Heavy multitaskers show reduced ability to filter irrelevant information, greater susceptibility to distraction, and impaired working memory. The constant task-switching seems to train the brain for distraction rather than focus. There are narrow exceptions to the one-task-at-a-time rule. Activities that are completely automatic—walking, chewing, breathing—can run in parallel with conscious thought. That's why you can walk and talk at the same time. But the moment either task requires attention (navigating an unfamiliar route, having a difficult conversation), the other suffers. The myth of effective multitasking persists because it feels productive. Jumping between email, documents, and messages creates a sense of busyness and engagement. But the science is clear: doing one thing at a time produces better results faster than trying to do everything at once.`,
    design_config: {"thumbnailColor":"#673AB7","titlePage":{"backgroundColor":"#673AB7","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#673AB7","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#673AB7"},{"background":"#D1C4E9","text":"#000000"}],"imagePlaceholderColors":["#673AB7","#D1C4E9"],"imageAspectRatios":[1.4,0.85],"imageColorOffset":0,"imagePositionSeed":2}
  },
  {
    slug: "sleep-deprivation-kills-faster",
    title: "No Sleep Kills Faster Than No Food",
    description: "The lethal power of staying awake",
    category: "Science",
    thumbnail_color: "#1A237E",
    body_text: `You can survive without food for several weeks. You cannot survive without sleep for much longer than eleven days. Sleep deprivation is one of the fastest ways to die, though scientists still don't fully understand why. The longest documented case of intentional sleeplessness is 264 hours—eleven days—achieved by a high school student named Randy Gardner in 1964 as a science fair project. By the end, Gardner was hallucinating, paranoid, and barely functional. Supervised by doctors, he recovered fully after sleeping for fourteen hours. Others haven't been so lucky. Fatal familial insomnia is a rare genetic disease that destroys the brain's ability to sleep. Patients progress through increasingly severe insomnia until they cannot sleep at all. Death follows within months. No treatment exists. The disease demonstrates that sleep isn't optional; it's a fundamental requirement for survival. Animal studies confirm the lethality of sleeplessness. Rats deprived of sleep die within about two weeks—faster than rats deprived of food. Their bodies deteriorate rapidly: immune systems fail, skin develops lesions, body temperature becomes unstable. Something about sustained wakefulness is actively destructive to living organisms. The reasons remain mysterious. Sleep appears necessary for clearing toxic waste products from the brain, consolidating memories, repairing cellular damage, and regulating hormones. But none of these functions, when disrupted individually, causes the rapid death seen in total sleep deprivation. The fatal factor, whatever it is, hasn't been identified. What we know is that the brain forces sleep when it needs it. Sleep-deprived people experience "microsleeps"—brief moments of unconsciousness lasting seconds that occur involuntarily. The brain will take sleep even if you don't give it willingly. Fighting this reflex, as patients with fatal insomnia discover, is ultimately impossible. Sleep is not a luxury or a weakness. It is as essential to life as oxygen or water.`,
    design_config: {"thumbnailColor":"#1A237E","titlePage":{"backgroundColor":"#1A237E","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#1A237E","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#1A237E"},{"background":"#C5CAE9","text":"#000000"}],"imagePlaceholderColors":["#1A237E","#C5CAE9"],"imageAspectRatios":[1.3,0.9],"imageColorOffset":1,"imagePositionSeed":3}
  },
  {
    slug: "stomach-lining-regenerates",
    title: "Your Stomach Remakes Itself Weekly",
    description: "The organ that never stops rebuilding",
    category: "Science",
    thumbnail_color: "#E64A19",
    body_text: `Your stomach lining is constantly digesting itself and constantly regenerating. The entire inner surface is replaced every few days. Without this relentless renewal, your stomach acid would eat through the organ and kill you. Gastric acid is powerful enough to dissolve metal. It has a pH of about 1.5 to 3.5—similar to battery acid. This extreme acidity is necessary to break down food and kill bacteria, but it creates a dangerous situation: the stomach must contain a substance that would destroy it on contact. The solution is a thick layer of mucus that coats the stomach lining, creating a barrier between the acid and the cells beneath. This mucus layer is about half a millimeter thick, but it's enough to neutralize the acid before it reaches living tissue. Bicarbonate ions released by the stomach cells help maintain a higher pH within the mucus layer itself. Even with this protection, stomach cells take damage. The innermost layer of cells is continually sloughed off and replaced by new cells pushing up from below. The entire epithelium regenerates every three to four days. It's one of the fastest cell turnover rates in the human body. When this system fails, ulcers develop. For decades, doctors believed stress and diet caused ulcers by disrupting the mucus barrier. Then, in 1982, Australian doctors Barry Marshall and Robin Warren discovered that most ulcers were actually caused by bacteria—Helicobacter pylori—that could survive the acidic environment and damage the stomach lining. Marshall famously proved his theory by drinking a culture of H. pylori and developing ulcers. The discovery revolutionized treatment: what had been a chronic condition requiring surgery could often be cured with antibiotics. But the fundamental vulnerability remains. Your stomach is locked in a constant battle with its own digestive fluids, rebuilding faster than it can be destroyed.`,
    design_config: {"thumbnailColor":"#E64A19","titlePage":{"backgroundColor":"#E64A19","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#E64A19","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#E64A19"},{"background":"#FFCCBC","text":"#000000"}],"imagePlaceholderColors":["#E64A19","#FFCCBC"],"imageAspectRatios":[1.5,0.85],"imageColorOffset":0,"imagePositionSeed":4}
  },
  {
    slug: "octopus-three-hearts-blue-blood",
    title: "Octopuses Have Three Hearts",
    description: "The aliens already living on Earth",
    category: "Science",
    thumbnail_color: "#AD1457",
    body_text: `Octopuses are so strange they seem like creatures from another planet. They have three hearts, blue blood, and a nervous system so distributed that their arms can act independently even after being severed from the body. Two of their hearts pump blood to the gills, while the third pumps it through the rest of the body. When an octopus swims, this systemic heart actually stops beating—which is why octopuses prefer to crawl rather than swim. Swimming exhausts them. Their blood is blue because it uses copper-based hemocyanin instead of the iron-based hemoglobin in human blood. Hemocyanin is less efficient at transporting oxygen but works better in cold, low-oxygen environments like the deep ocean. The blue color is simply copper-oxygen compounds rather than iron-oxygen compounds. But the strangest feature is their nervous system. Two-thirds of an octopus's neurons are in its arms, not its brain. Each arm can taste, touch, and make decisions independently. A severed octopus arm will continue to reach for food and bring it toward where the mouth would be. The arms seem to have their own minds. Researchers have found that octopus arms can solve problems—like opening jars—even when they can't communicate with the central brain. The octopus essentially operates as a collective of semi-independent intelligences coordinating through a central processor. Nothing else on Earth works quite this way. Octopuses also have the largest brains of any invertebrate, can use tools, recognize individual humans, and escape from apparently secure tanks by learning how locks work. They have demonstrated what appears to be playful behavior—the clearest sign of complex cognition. Some scientists argue that if we ever encounter alien intelligence, octopuses show us it might look nothing like human minds. Intelligence can evolve in radically different architectures. The aliens aren't in space; they've been in our oceans for hundreds of millions of years.`,
    design_config: {"thumbnailColor":"#AD1457","titlePage":{"backgroundColor":"#AD1457","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#AD1457","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#AD1457"},{"background":"#00BCD4","text":"#FFFFFF"}],"imagePlaceholderColors":["#AD1457","#00BCD4"],"imageAspectRatios":[1.4,0.9],"imageColorOffset":1,"imagePositionSeed":2}
  },
  {
    slug: "moon-moving-away-from-earth",
    title: "The Moon Is Escaping",
    description: "Earth is slowly losing its companion",
    category: "Science",
    thumbnail_color: "#455A64",
    body_text: `The Moon is drifting away from Earth at a rate of about 3.8 centimeters per year—roughly the speed at which fingernails grow. In another six hundred million years, the Moon will be too far away to fully eclipse the Sun. We live in the only era of Earth's history when total solar eclipses are possible. The Moon's retreat is caused by tidal forces. Earth's gravity pulls on the Moon, but the Moon's gravity also pulls on Earth, creating tides. These tides create bulges in Earth's oceans that are slightly ahead of the Moon's position because Earth rotates faster than the Moon orbits. The gravitational pull between this bulge and the Moon acts like a rope, transferring energy from Earth's rotation to the Moon's orbit. As the Moon gains energy, it moves to a higher orbit—farther from Earth. Meanwhile, Earth's rotation slows down. Days are getting longer by about 1.4 milliseconds per century. Four hundred million years ago, a day was only about twenty-two hours long. Eventually, billions of years from now, Earth and Moon will become tidally locked, with Earth always showing the same face to the Moon, just as the Moon already shows the same face to Earth. Days and months will be equal—both about forty-seven current days long. We know the Moon is receding because astronauts left reflectors on its surface. Scientists bounce lasers off these reflectors and measure the return time to within a few centimeters. The measurements have continued for over fifty years, documenting the Moon's slow escape with extraordinary precision. The Moon won't leave entirely. It will eventually settle into a stable orbit at about 1.4 times its current distance. But the celestial clockwork that gives us eclipses, seasons, and stable axis tilt will be different. Our descendants, if they still exist, will see a smaller Moon in a darker sky.`,
    design_config: {"thumbnailColor":"#455A64","titlePage":{"backgroundColor":"#455A64","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#455A64","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#455A64"},{"background":"#CFD8DC","text":"#000000"}],"imagePlaceholderColors":["#455A64","#CFD8DC"],"imageAspectRatios":[1.3,0.85],"imageColorOffset":0,"imagePositionSeed":3}
  },
  {
    slug: "sharks-older-than-trees",
    title: "Sharks Are Older Than Trees",
    description: "Ancient predators of an alien world",
    category: "Science",
    thumbnail_color: "#546E7A",
    body_text: `Sharks have existed for at least 450 million years. Trees have existed for about 350 million years. For one hundred million years, sharks swam in oceans surrounded by continents with no forests at all—just barren rock and simple plants. The first sharks evolved during the Ordovician period, before life had even fully colonized land. The oceans were already full of complex ecosystems while the continents were largely sterile. Sharks hunted their prey in waters that lapped against shores where nothing grew taller than moss. When trees finally evolved in the late Devonian period, they transformed the planet. Forests absorbed carbon dioxide, released oxygen, and created the first true soil. But sharks barely noticed. They had already survived several mass extinctions by then and would survive several more. The dinosaurs came and went. The sharks remained. Modern sharks are not unchanged from their ancient ancestors—evolution continued, producing the hundreds of species we see today. But the basic shark body plan has proven so successful that it hasn't needed major revision. Sharks were apex predators before, during, and after the dinosaurs. The great white shark's ancestors were hunting in the seas when tyrannosaurs walked the land. What makes sharks so durable? Their cartilage skeletons are lighter and more flexible than bone. Their multiple rows of replaceable teeth ensure they're never without weapons. Their electroreceptors can detect the electrical fields of prey even buried in sand. Their lateral line system senses vibrations in water from enormous distances. Every feature has been honed by hundreds of millions of years of refinement. Next time you see a shark—even in a photograph—you're looking at a design older than trees, older than flowers, older than the concept of a forest. They are relics of a world we can barely imagine, still swimming among us.`,
    design_config: {"thumbnailColor":"#546E7A","titlePage":{"backgroundColor":"#546E7A","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#546E7A","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#546E7A"},{"background":"#2E7D32","text":"#FFFFFF"}],"imagePlaceholderColors":["#546E7A","#2E7D32"],"imageAspectRatios":[1.5,0.9],"imageColorOffset":1,"imagePositionSeed":4}
  },
  {
    slug: "humans-glow-bioluminescence",
    title: "You Glow in the Dark",
    description: "The light your body emits",
    category: "Science",
    thumbnail_color: "#00695C",
    body_text: `The human body emits visible light. You are literally glowing right now, producing photons through chemical reactions in your cells. The glow is just too faint for your eyes to see—about one thousand times weaker than what human vision can detect. Japanese scientists first documented human bioluminescence in 2009 using extraordinarily sensitive cameras that could detect single photons. They photographed volunteers in complete darkness over twenty-four hours, finding that the body's glow fluctuated rhythmically, brightest in the afternoon and faintest at night. The face glowed most intensely, particularly around the mouth and cheeks. The light comes from metabolic reactions involving free radicals and fluorescent molecules in the skin. These reactions produce energy in the form of photons—the same basic process that makes fireflies glow, just much, much dimmer. Every living cell produces some light as a byproduct of metabolism, but usually at levels far below detection. This bioluminescence is not the same as body heat. Thermal radiation is infrared, invisible to the human eye, and much more intense than the visible photons your body emits. The visible glow is a separate phenomenon, a true emission of light in wavelengths we could theoretically see if our eyes were sensitive enough. Some animals have eyes that can detect extremely faint light. Certain deep-sea fish can see bioluminescent signals a billion times dimmer than what humans perceive. If such creatures looked at you, they might see you glowing. The human aura, reported by psychics and mystics throughout history, might have some basis in this real phenomenon—even if the spiritual interpretations are unfounded. Your body really does emit light. The "aura" is just metabolism, not magic. We are all, in a very literal sense, beings of light. The glow is too dim for romance and too weak for reading, but it's real. You have been shining your entire life without knowing it.`,
    design_config: {"thumbnailColor":"#00695C","titlePage":{"backgroundColor":"#00695C","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#00695C","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#00695C"},{"background":"#E0F2F1","text":"#000000"}],"imagePlaceholderColors":["#00695C","#E0F2F1"],"imageAspectRatios":[1.4,0.85],"imageColorOffset":0,"imagePositionSeed":2}
  }
];

async function uploadStory(story) {
  const response = await fetch(`${SUPABASE_URL}/rest/v1/stories`, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      "apikey": SUPABASE_KEY,
      "Authorization": `Bearer ${SUPABASE_KEY}`,
      "Prefer": "resolution=merge-duplicates,return=minimal"
    },
    body: JSON.stringify({
      slug: story.slug,
      title: story.title,
      description: story.description,
      category: story.category,
      thumbnail_color: story.thumbnail_color,
      published: true,
      published_at: new Date().toISOString(),
      body_text: story.body_text,
      design_config: story.design_config,
      updated_at: new Date().toISOString()
    })
  });

  if (!response.ok) {
    const text = await response.text();
    throw new Error(`${response.status}: ${text}`);
  }
}

async function main() {
  console.log(`Uploading ${stories.length} Science "Did You Know" stories to Supabase...\n`);

  let success = 0;
  let failed = 0;

  for (const story of stories) {
    try {
      process.stdout.write(`Uploading: ${story.title}... `);
      await uploadStory(story);
      console.log("Done!");
      success++;
    } catch (error) {
      console.log(`Error: ${error.message}`);
      failed++;
    }
  }

  console.log(`\nComplete! ${success} succeeded, ${failed} failed.`);
}

main();
