/**
 * War Category - 25 "Did You Know" Stories
 * Usage: node scripts/new-content-dyk/war-dyk.mjs
 */

const SUPABASE_URL = "https://egfwisgqdyhzpmeoracb.supabase.co";
const SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVnZndpc2dxZHloenBtZW9yYWNiIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2ODQyNzM0OSwiZXhwIjoyMDg0MDAzMzQ5fQ.S8h1fIepxWb44gPSPpWQ8fE0Q-SCYfL0QcBRUV7fXgs";

const stories = [
  {
    slug: "war-started-over-bucket",
    title: "The War Started Over a Bucket",
    description: "Medieval Italy's strangest conflict",
    category: "War",
    thumbnail_color: "#8D6E63",
    body_text: `In 1325, the city-states of Bologna and Modena went to war over a stolen wooden bucket. The bucket still exists today, displayed in the basement of Modena's cathedral tower like a trophy of the absurd. The War of the Bucket, as it came to be known, killed over two thousand soldiers. The actual conflict had deeper roots, of course. Bologna and Modena had been rivals for decades, representing opposing sides in the eternal Italian struggle between the Guelph faction, loyal to the Pope, and the Ghibellines, who supported the Holy Roman Emperor. Tensions had been building through border skirmishes, trade disputes, and wounded civic pride. The bucket was merely the spark. A group of Modenese soldiers raided the Bolognese town well during a skirmish and carried off the oaken bucket as a trophy. Bologna demanded its return. Modena refused. Both cities mobilized for war. The resulting Battle of Zappolino was one of the largest battles in medieval Italian history. Bologna fielded an army of over thirty thousand men, including two thousand knights. Modena had perhaps half that number. Against all odds, the smaller Modenese force won a crushing victory, capturing flags, prisoners, and considerable territory. They kept the bucket. Bologna sued for peace but never got its bucket back. Seven centuries later, the rivalry continues in gentler form. The two cities are now united as part of Italy, but Modenese citizens still joke about the bucket their ancestors stole. The original sits in its basement shrine, a reminder that wars can start over anything—and that the reasons given are rarely the real reasons.`,
    design_config: {"thumbnailColor":"#8D6E63","titlePage":{"backgroundColor":"#8D6E63","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#8D6E63","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#8D6E63"},{"background":"#5D4037","text":"#FFFFFF"}],"imagePlaceholderColors":["#8D6E63","#5D4037"],"imageAspectRatios":[1.4,0.85],"imageColorOffset":0,"imagePositionSeed":2}
  },
  {
    slug: "soldier-fought-alone-30-years",
    title: "He Fought WWII for 30 Years",
    description: "The soldier who never surrendered",
    category: "War",
    thumbnail_color: "#2E7D32",
    body_text: `Hiroo Onoda was still fighting World War II in 1974, nearly thirty years after Japan's surrender. The Japanese army intelligence officer had been stationed in the Philippine jungle in 1944 with orders to conduct guerrilla warfare and never surrender. He followed those orders to the letter. For three decades, Onoda lived in the mountains of Lubang Island, surviving on coconuts, bananas, and stolen cattle. He conducted raids on local farms and police outposts, believing the war was still ongoing. His companions died or surrendered one by one, but Onoda remained convinced that Japan was still fighting. Search parties came for him repeatedly. Leaflets were dropped explaining that the war had ended. Family members broadcast messages over loudspeakers. Onoda dismissed it all as enemy propaganda, too clever to fall for Allied tricks. His training had prepared him to resist psychological warfare, and he resisted perfectly. In 1974, a Japanese college dropout named Norio Suzuki went looking for Onoda as part of a personal quest to find "Lieutenant Onoda, a panda, and the Abominable Snowman." Incredibly, he found Onoda within four days. The two men talked, and Suzuki convinced Onoda to stay put while he went to get proof of the war's end. Suzuki returned with Onoda's former commanding officer, now an elderly bookseller. Only when Major Yoshimi Taniguchi formally relieved him of duty did Onoda finally surrender. He emerged from the jungle in his tattered uniform, carrying a sword, a rifle that still worked, and five hundred rounds of ammunition. The Philippines pardoned him for the killings he had committed. He returned to Japan a hero, though he found the modern country unrecognizable. Onoda died in 2014, having lived the last four decades in peace.`,
    design_config: {"thumbnailColor":"#2E7D32","titlePage":{"backgroundColor":"#2E7D32","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#2E7D32","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#2E7D32"},{"background":"#FFD60A","text":"#000000"}],"imagePlaceholderColors":["#2E7D32","#FFD60A"],"imageAspectRatios":[1.3,0.9],"imageColorOffset":1,"imagePositionSeed":3}
  },
  {
    slug: "spanish-armada-weather-defeat",
    title: "The Storm That Saved England",
    description: "Weather destroyed the Spanish Armada",
    category: "War",
    thumbnail_color: "#1565C0",
    body_text: `The Spanish Armada of 1588 was the largest invasion fleet Europe had ever seen: 130 ships carrying 30,000 men, sent by King Philip II of Spain to conquer Protestant England and restore Catholic rule. It was destroyed not by English cannons but by the weather. The initial naval battles in the English Channel were inconclusive. English ships, smaller and more maneuverable, harassed the Armada but couldn't break its crescent formation. Then the English sent fireships—vessels stuffed with gunpowder and set ablaze—into the anchored Spanish fleet at Calais. Panicked captains cut their anchor cables and scattered into the night. The formation was broken, but the fleet was still largely intact. What doomed the Armada was the decision to sail home around Scotland and Ireland rather than back through the English Channel, where English ships waited. The Spanish commanders didn't know that autumn storms in the North Atlantic are among the most violent on Earth. Hurricane-force winds struck the fleet off the coast of Scotland. Ships were dashed against Irish cliffs. Sailors who made it to shore were often killed by English soldiers or local Irish who stripped the bodies for valuables. Of the 130 ships that sailed from Spain, only 67 returned. Perhaps 20,000 men died, most of them from storms, shipwreck, and starvation rather than combat. England celebrated with medals inscribed "God blew and they were scattered." The victory cemented England's rise as a naval power and preserved the Protestant Reformation. But it was won not by admirals but by Atlantic gales that arrived at precisely the wrong moment for Spain.`,
    design_config: {"thumbnailColor":"#1565C0","titlePage":{"backgroundColor":"#1565C0","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#1565C0","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#1565C0"},{"background":"#37474F","text":"#FFFFFF"}],"imagePlaceholderColors":["#1565C0","#37474F"],"imageAspectRatios":[1.5,0.85],"imageColorOffset":0,"imagePositionSeed":4}
  },
  {
    slug: "invasion-stopped-by-bees",
    title: "The Invasion Stopped by Bees",
    description: "When insects defeated an army",
    category: "War",
    thumbnail_color: "#FFC107",
    body_text: `In 1914, German colonial forces in East Africa were advancing on a British position when they encountered an unexpected enemy: bees. Thousands of African honeybees, disturbed by the commotion of marching troops, swarmed the German column and sent soldiers fleeing in panic. The incident was not unique. Bees have been used as weapons of war for thousands of years, and they have decided battles more than once. Ancient armies catapulted beehives over city walls. Medieval defenders dropped hives on attackers climbing siege ladders. The Romans used bees against enemies in tunnels. But the African honeybee is particularly fearsome. More aggressive than European varieties, these bees attack in massive swarms when their hives are disturbed. A single hive can contain 60,000 bees, each capable of stinging multiple times. The resulting chaos can incapacitate entire military units. During the East Africa campaign of World War I, both sides learned to fear the bees. Soldiers avoided areas known to contain hives. Some commanders deliberately destroyed hives in the path of enemy advances, creating living minefields. The bees didn't care about politics—they attacked anyone who disturbed them. Similar incidents occurred in other conflicts. During the Vietnam War, Viet Cong fighters reportedly used beehives as booby traps. In the Mau Mau uprising in Kenya, rebels weaponized bees against British forces. Even modern militaries have studied bees as potential biological weapons, though international law now prohibits such use. The 1914 attack remains the most famous example of bees influencing a military operation. The German advance was halted, the troops scattered, and the bees returned to their normal business of making honey.`,
    design_config: {"thumbnailColor":"#FFC107","titlePage":{"backgroundColor":"#FFC107","textColor":"#000000"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#FFC107","text":"#000000"},{"background":"#FFFFFF","text":"#FFC107"},{"background":"#5D4037","text":"#FFFFFF"}],"imagePlaceholderColors":["#FFC107","#5D4037"],"imageAspectRatios":[1.4,0.9],"imageColorOffset":1,"imagePositionSeed":2}
  },
  {
    slug: "war-lasted-38-minutes",
    title: "The 38-Minute War",
    description: "History's shortest military conflict",
    category: "War",
    thumbnail_color: "#D32F2F",
    body_text: `The Anglo-Zanzibar War of 1896 lasted between 38 and 45 minutes, making it the shortest war in recorded history. It began at 9:02 AM on August 27 and was effectively over by 9:40 AM, when the Zanzibar flag was shot down and the sultan's palace lay in ruins. The conflict arose from a succession crisis. When the pro-British Sultan Hamad bin Thuwaini died suddenly, his cousin Khalid bin Barghash seized power without British approval. The British had their own preferred candidate and gave Khalid an ultimatum: step down by 9:00 AM on August 27 or face war. Khalid refused, barricading himself in the palace with about 2,800 defenders. The British assembled a fleet of five warships in the harbor, aimed directly at the palace. At 9:02 AM, precisely when the ultimatum expired, the ships opened fire. The bombardment was devastating. British shells tore through the palace walls. Khalid's only ship, an aging royal yacht, was sunk almost immediately. The defenders' artillery, mostly outdated bronze cannons, couldn't penetrate the armored British vessels. Within minutes, the palace was on fire and the defenses collapsed. Khalid fled to the German consulate and eventually escaped to German East Africa. The British installed their chosen sultan and declared victory. Approximately 500 Zanzibaris were killed or wounded; the British suffered one casualty, a petty officer who was injured. The war was less a military conflict than a demonstration of imperial power. Britain controlled Zanzibar already; the bombardment was meant to show what happened when local rulers defied British wishes. The message was received clearly throughout East Africa and beyond.`,
    design_config: {"thumbnailColor":"#D32F2F","titlePage":{"backgroundColor":"#D32F2F","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#D32F2F","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#D32F2F"},{"background":"#1565C0","text":"#FFFFFF"}],"imagePlaceholderColors":["#D32F2F","#1565C0"],"imageAspectRatios":[1.3,0.85],"imageColorOffset":0,"imagePositionSeed":3}
  },
  {
    slug: "ghost-army-inflatable-tanks",
    title: "The Army Made of Rubber",
    description: "WWII's strangest deception unit",
    category: "War",
    thumbnail_color: "#4E342E",
    body_text: `The 23rd Headquarters Special Troops was a U.S. Army unit whose job was to lie. Consisting of about 1,100 men, including artists, actors, and sound engineers, the "Ghost Army" used inflatable tanks, fake radio transmissions, and theatrical performances to deceive German forces about American troop positions and strengths. The unit deployed from 1944 to 1945, staging over twenty deception operations across France, Luxembourg, Belgium, and Germany. Their inflatable tanks, made of rubber and weighing only 93 pounds each, could be set up in minutes and looked completely real from a distance or from aerial reconnaissance. Soldiers would move them at night to simulate armored divisions on the move. But the deceptions went far beyond rubber tanks. The unit's sound company played recordings of tank engines, troop movements, and construction equipment through powerful speakers, creating the illusion of massive military operations miles away. Radio operators sent fake traffic, impersonating real units and maintaining consistent fake communications that enemy intelligence would intercept and believe. The theatrical element was equally important. Ghost Army soldiers would go to local cafes wearing insignia of fake divisions, dropping hints about upcoming operations. They sewed fake patches, created counterfeit documents, and even impersonated generals. One operation involved convincing German forces that an entire armored division was preparing to cross the Rhine in one location while the real crossing happened elsewhere. The unit's operations remained classified for over forty years. Many of the soldiers were artists who went on to prominent careers—including fashion designer Bill Blass and painter Ellsworth Kelly. They had spent the war creating the most elaborate art installation in military history.`,
    design_config: {"thumbnailColor":"#4E342E","titlePage":{"backgroundColor":"#4E342E","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#4E342E","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#4E342E"},{"background":"#2E7D32","text":"#FFFFFF"}],"imagePlaceholderColors":["#4E342E","#2E7D32"],"imageAspectRatios":[1.5,0.9],"imageColorOffset":1,"imagePositionSeed":4}
  },
  {
    slug: "carrier-pigeon-saved-200-soldiers",
    title: "The Pigeon That Saved 200 Lives",
    description: "Cher Ami flew through gunfire",
    category: "War",
    thumbnail_color: "#795548",
    body_text: `On October 4, 1918, a carrier pigeon named Cher Ami flew through a barrage of German gunfire to deliver a message that saved nearly 200 American soldiers trapped behind enemy lines. The bird was shot through the breast, blinded in one eye, and had a leg hanging by a tendon, but she completed her mission. The men she saved were the famous "Lost Battalion" of the 77th Infantry Division. Cut off in the Argonne Forest during the Meuse-Argonne Offensive, they were surrounded by German forces and, even worse, being shelled by their own artillery, which didn't know their position. Major Charles Whittlesey had already sent two pigeons with messages; both were shot down. Cher Ami was his last bird. The message she carried was desperate: "We are along the road parallel to 276.4. Our own artillery is dropping a barrage directly on us. For heaven's sake stop it." When the pigeon was released, German soldiers immediately opened fire. Witnesses saw her hit and tumble, then somehow recover and fly on, covering twenty-five miles in sixty-five minutes despite her wounds. When she arrived at division headquarters, the message capsule was dangling from her shattered leg. Army medics worked to save the bird's life. They couldn't save her leg, but they carved her a wooden one. Cher Ami was awarded the French Croix de Guerre and became a celebrity. When she died in 1919, her body was preserved and displayed at the Smithsonian Institution, where it remains today. The Lost Battalion was rescued the day after her flight. Of the original 554 men who had been trapped, 194 walked out alive.`,
    design_config: {"thumbnailColor":"#795548","titlePage":{"backgroundColor":"#795548","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#795548","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#795548"},{"background":"#1565C0","text":"#FFFFFF"}],"imagePlaceholderColors":["#795548","#1565C0"],"imageAspectRatios":[1.4,0.85],"imageColorOffset":0,"imagePositionSeed":2}
  },
  {
    slug: "war-declared-never-fought",
    title: "The War That Never Happened",
    description: "Berwick forgot to make peace",
    category: "War",
    thumbnail_color: "#607D8B",
    body_text: `For over 100 years, the small English town of Berwick-upon-Tweed was technically at war with Russia. The conflict was entirely on paper, the result of a bureaucratic oversight that nobody bothered to fix until 1966. The story begins with the Crimean War of 1853-1856. Berwick-upon-Tweed, sitting on the Scottish border, had a complicated legal status and was sometimes listed separately from England in official documents. When Queen Victoria declared war on Russia in 1853, the declaration reportedly read "Victoria, Queen of Great Britain, Ireland, Berwick-upon-Tweed, and all British Dominions." When the Treaty of Paris ended the Crimean War in 1856, Berwick was allegedly left off the list of signatories. This meant that technically, the town remained at war with Russia for the next century. The story may be apocryphal. Historians have found no conclusive evidence that Berwick was actually mentioned separately in the war declaration. But the legend persisted, and in 1966, a Soviet official decided to address it. A Russian diplomat visited Berwick to sign a peace treaty, ending the supposed state of war. The mayor reportedly told him, "Please tell the Russian people that they can now sleep peacefully in their beds." The incident became a charming footnote in Cold War history, a reminder that bureaucracy can create absurd situations. Whether the war was real or legendary, it illustrated how formal declarations and paperwork can take on lives of their own. Berwick, which had changed hands between England and Scotland thirteen times before becoming definitively English, had apparently been at war with Russia longer than it had been peaceful.`,
    design_config: {"thumbnailColor":"#607D8B","titlePage":{"backgroundColor":"#607D8B","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#607D8B","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#607D8B"},{"background":"#D32F2F","text":"#FFFFFF"}],"imagePlaceholderColors":["#607D8B","#D32F2F"],"imageAspectRatios":[1.3,0.9],"imageColorOffset":1,"imagePositionSeed":3}
  },
  {
    slug: "alvin-york-captured-132-enemies",
    title: "One Man Captured 132 Soldiers",
    description: "Alvin York's impossible feat",
    category: "War",
    thumbnail_color: "#5D4037",
    body_text: `On October 8, 1918, Corporal Alvin York and sixteen other American soldiers attacked a German machine gun position in the Argonne Forest. By the time it was over, York had killed at least 25 German soldiers and captured 132 more, almost single-handedly. It remains one of the most extraordinary individual combat achievements in military history. The patrol had stumbled into a German battalion headquarters, initially capturing several soldiers. Then German machine guns on the ridge above opened fire, killing six Americans and wounding three others. The survivors took cover in a depression in the ground as bullets swept overhead. York, a skilled hunter from the Tennessee mountains, began picking off German gunners one by one. Using his rifle, he shot them with the accuracy he had developed hunting turkeys back home. When a German officer led a bayonet charge of six men, York dropped all six with his pistol, shooting the last man first so the others wouldn't see their comrades falling. The German major in command, seeing his men being systematically killed, offered to surrender if York would stop shooting. York agreed. What followed was surreal: Corporal York marched 132 German prisoners back to American lines, gathering more surrendering soldiers along the way. His commanding officer famously said, "Well, York, I hear you have captured the whole German Army." York's response: "No sir, I only got 132." York received the Medal of Honor and became one of the most celebrated American heroes of World War I. A deeply religious man, he had initially been a conscientious objector before concluding that fighting to save lives was morally justified. He returned to Tennessee and spent the rest of his life helping establish schools in rural Appalachia.`,
    design_config: {"thumbnailColor":"#5D4037","titlePage":{"backgroundColor":"#5D4037","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#5D4037","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#5D4037"},{"background":"#2E7D32","text":"#FFFFFF"}],"imagePlaceholderColors":["#5D4037","#2E7D32"],"imageAspectRatios":[1.5,0.85],"imageColorOffset":0,"imagePositionSeed":4}
  },
  {
    slug: "christmas-truce-1914",
    title: "The Night They Stopped Fighting",
    description: "Christmas 1914 in the trenches",
    category: "War",
    thumbnail_color: "#1B5E20",
    body_text: `On Christmas Eve 1914, something extraordinary happened along the Western Front. German soldiers began placing candles on trees and singing carols. British soldiers responded with songs of their own. Then men from both sides walked into no man's land to shake hands, exchange gifts, and bury their dead. The Christmas Truce of 1914 was not organized by generals or politicians. It emerged spontaneously from exhausted soldiers who had been killing each other for months. In some sectors, the truce lasted only Christmas Day. In others, it continued until New Year's. In a few places, soldiers refused to resume fighting at all and had to be replaced. The truce took many forms along the four-hundred-mile front. Some units only agreed to cease fire. Others met in no man's land to trade cigarettes, chocolate, and souvenirs. There are credible accounts of soccer matches between enemies, though the famous games may be more legend than fact. Photographs and letters confirm that thousands of soldiers participated. Military commanders were appalled. High command on both sides issued strict orders against fraternization. Soldiers who refused to fight were threatened with court-martial. By 1915, artillery bombardments were ordered on Christmas Eve specifically to prevent any repeat of the truce. There were small, unofficial truces in later years, but nothing like 1914. The Christmas Truce became a symbol of the humanity that persists even in war, and of the tragedy of men ordered to kill people they had no personal quarrel with. For one night, soldiers chose peace. Then they went back to their trenches and continued a war that would kill millions.`,
    design_config: {"thumbnailColor":"#1B5E20","titlePage":{"backgroundColor":"#1B5E20","textColor":"#FFD60A"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#1B5E20","text":"#FFFFFF"},{"background":"#FFD60A","text":"#000000"},{"background":"#FFFFFF","text":"#1B5E20"}],"imagePlaceholderColors":["#1B5E20","#FFD60A"],"imageAspectRatios":[1.4,0.9],"imageColorOffset":1,"imagePositionSeed":2}
  },
  {
    slug: "war-started-over-soccer-game",
    title: "The Soccer Game That Started a War",
    description: "Football diplomacy gone wrong",
    category: "War",
    thumbnail_color: "#2196F3",
    body_text: `In June 1969, El Salvador and Honduras went to war. The immediate trigger was a series of soccer matches during World Cup qualifying, leading journalists to call it the "Football War." But the real causes ran much deeper, and the conflict killed over 3,000 people. Tensions between the two Central American nations had been building for years. Honduras, larger and less densely populated, had absorbed hundreds of thousands of Salvadoran migrants seeking farmland. Honduran nationalists blamed immigrants for economic problems and began expelling Salvadoran settlers from their homes, often violently. The soccer matches became flashpoints for this hostility. During the first qualifying match in Tegucigalpa, Honduran fans kept the Salvadoran team awake all night with noise. An eighteen-year-old Salvadoran girl shot herself after Honduras won, and her funeral became a national event. When the teams met in San Salvador for the second match, Honduran fans were attacked and the Honduran flag was burned. The third match, held in Mexico City, was won by El Salvador. That same week, El Salvador broke diplomatic relations with Honduras, citing the persecution of Salvadoran migrants. Days later, Salvadoran forces invaded. The war lasted only four days before the Organization of American States negotiated a ceasefire, but the brief conflict killed thousands and displaced over 100,000 people. The economic disruption lasted for years, and a peace treaty wasn't signed until 1980. Soccer didn't cause the war. But it provided a stage where existing grievances could explode into violence. The Football War remains a reminder of how sport can both unite and divide, and how tensions between nations can find unexpected outlets.`,
    design_config: {"thumbnailColor":"#2196F3","titlePage":{"backgroundColor":"#2196F3","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#2196F3","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#2196F3"},{"background":"#FFD60A","text":"#000000"}],"imagePlaceholderColors":["#2196F3","#FFD60A"],"imageAspectRatios":[1.3,0.85],"imageColorOffset":0,"imagePositionSeed":3}
  },
  {
    slug: "battle-won-by-dead-general",
    title: "The Dead General Who Won",
    description: "El Cid's final victory",
    category: "War",
    thumbnail_color: "#BF360C",
    body_text: `Rodrigo Diaz de Vivar, the legendary Spanish warrior known as El Cid, won his last battle while dead. In 1099, his corpse was strapped to his horse and sent into combat against the Almoravid army besieging Valencia. The sight of the terrifying warrior they thought they had killed sent the enemy fleeing in panic. El Cid had died of natural causes while Valencia was under siege. His wife, Jimena, knew that news of his death would demoralize the defenders and embolden the attackers. So she conceived a plan that would become one of the most famous legends in Spanish history. The corpse was embalmed, dressed in armor, and mounted on El Cid's famous warhorse, Babieca. According to legend, his body was propped upright with a special wooden frame. When the gates opened and the dead champion rode out at the head of his army, the Almoravids believed they were seeing a ghost—or worse, that they had somehow failed to kill him. They broke and ran. The historical accuracy of this story is debated. The earliest accounts of El Cid's life were written decades after his death and mix fact with legend. What is certain is that El Cid was a real person who captured Valencia from the Moors in 1094 and held it until his death, and that his wife continued to defend the city for three years after he died. Whether the corpse cavalry charge actually happened is less clear. But the legend persisted because it captured something true about El Cid's reputation: he was so feared that even his dead body could win battles. His name itself—El Cid, from the Arabic al-sayyid, meaning "the lord"—was given to him by his Moorish enemies.`,
    design_config: {"thumbnailColor":"#BF360C","titlePage":{"backgroundColor":"#BF360C","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#BF360C","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#BF360C"},{"background":"#FFD60A","text":"#000000"}],"imagePlaceholderColors":["#BF360C","#FFD60A"],"imageAspectRatios":[1.5,0.9],"imageColorOffset":1,"imagePositionSeed":4}
  },
  {
    slug: "soldier-survived-firing-squad",
    title: "He Survived His Own Execution",
    description: "The man bullets couldn't kill",
    category: "War",
    thumbnail_color: "#424242",
    body_text: `Wenceslao Moguel was captured during the Mexican Revolution and sentenced to death by firing squad. On March 18, 1915, a squad of soldiers shot him nine times, including a coup de grace to the head at point-blank range. He survived and lived for another sixty years. Moguel, who fought for Pancho Villa, was captured by federal forces and sentenced to execution without trial, which was common during the brutal revolution. The firing squad's bullets struck him throughout his body. When he fell, an officer walked up and shot him in the head to ensure he was dead. Somehow, the final bullet entered his face at an angle that avoided his brain. Left for dead, Moguel regained consciousness hours later. He managed to crawl to safety and eventually received medical care. The wounds left him severely disfigured—his face was a mass of scar tissue, and he was partially blind—but he was alive. Moguel became famous decades later when he appeared on the American radio program "Ripley's Believe It or Not" in 1937. Robert Ripley, fascinated by unusual stories, brought him to the United States to tell his tale. Photographs of Moguel's scarred face were published worldwide, and his story became one of the most famous survivor tales of the twentieth century. Some historians question whether the story was exactly as Moguel told it. Military records from the period are incomplete, and some details may have been embellished over years of retelling. But his scars were real, and something terrible had clearly happened to him. He lived until 1976, dying peacefully at approximately eighty-five years old—sixty-one years after he should have died.`,
    design_config: {"thumbnailColor":"#424242","titlePage":{"backgroundColor":"#424242","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#424242","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#424242"},{"background":"#D32F2F","text":"#FFFFFF"}],"imagePlaceholderColors":["#424242","#D32F2F"],"imageAspectRatios":[1.4,0.85],"imageColorOffset":0,"imagePositionSeed":2}
  },
  {
    slug: "war-where-everyone-deserted",
    title: "The War Everyone Abandoned",
    description: "When both armies went home",
    category: "War",
    thumbnail_color: "#6D4C41",
    body_text: `The War of the Triple Alliance (1864-1870) was so devastating that by its end, Paraguay had lost up to 90% of its male population. But even before that catastrophe, there was a brief, bizarre moment when soldiers on both sides simply refused to fight and went home. In the early stages of the war, Paraguayan forces invaded the Brazilian province of Mato Grosso. They expected local resistance but found something unexpected: the Brazilian garrison and many settlers had already fled. Meanwhile, some Paraguayan soldiers, far from home and unsupplied, began deserting en masse. For a period, the territory was effectively abandoned by both armies. The war eventually became one of the bloodiest in South American history. Paraguay, led by the dictator Francisco Solano Lopez, fought against the combined forces of Brazil, Argentina, and Uruguay. Lopez refused to surrender even as his country was destroyed around him, conscripting children and old men when adult soldiers were gone. Modern estimates suggest Paraguay's population fell from around 525,000 to perhaps 221,000, with males reduced to about 28,000. The devastation was so complete that Paraguay allowed polygamy afterward simply to rebuild the population. The country didn't recover for generations. The early desertions were forgotten in the overwhelming tragedy that followed. But they reveal something often overlooked in military history: soldiers are human beings who can choose not to fight. When conditions become bad enough—when supplies run out, when the cause seems lost, when home seems more important than victory—armies can simply dissolve. Paraguay's tragedy was that its soldiers eventually had no home left to desert to.`,
    design_config: {"thumbnailColor":"#6D4C41","titlePage":{"backgroundColor":"#6D4C41","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#6D4C41","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#6D4C41"},{"background":"#2E7D32","text":"#FFFFFF"}],"imagePlaceholderColors":["#6D4C41","#2E7D32"],"imageAspectRatios":[1.3,0.9],"imageColorOffset":1,"imagePositionSeed":3}
  },
  {
    slug: "battle-decided-by-single-arrow",
    title: "The Arrow That Killed a King",
    description: "Hastings and the eye of Harold",
    category: "War",
    thumbnail_color: "#5D4037",
    body_text: `The Battle of Hastings in 1066 changed the history of England forever, and it may have been decided by a single arrow. According to legend, King Harold II was killed when an arrow struck him in the eye, ending English resistance and allowing William the Conqueror to seize the throne. The battle had been closely fought all day. Harold's English army held the high ground at Senlac Hill, their shield wall repelling repeated Norman cavalry charges. William's forces were exhausted and running low on arrows. Some Normans panicked and began to flee, spreading rumors that William himself had been killed. The Norman duke had to lift his helmet to show his face and rally his troops. As evening approached, William ordered his archers to shoot high, sending arrows arcing down behind the English shields. One of these arrows allegedly struck Harold in the eye. The king fell, and with him fell English hopes. Norman knights charged through the broken shield wall and cut down the remaining defenders. The famous image of Harold with an arrow in his eye comes from the Bayeux Tapestry, created about fifteen years after the battle. Some historians question whether the tapestry actually shows Harold being struck, or whether the figure with the arrow is someone else entirely. Other accounts say Harold was hacked to death by Norman knights, not killed by an arrow. What's certain is that Harold died at Hastings, ending the Anglo-Saxon dynasty that had ruled England for six centuries. William was crowned king on Christmas Day 1066, and England was never the same. Whether an arrow actually struck Harold's eye, the image became the defining symbol of England's conquest.`,
    design_config: {"thumbnailColor":"#5D4037","titlePage":{"backgroundColor":"#5D4037","textColor":"#FFD60A"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#5D4037","text":"#FFFFFF"},{"background":"#FFD60A","text":"#000000"},{"background":"#FFFFFF","text":"#5D4037"}],"imagePlaceholderColors":["#5D4037","#FFD60A"],"imageAspectRatios":[1.5,0.85],"imageColorOffset":0,"imagePositionSeed":4}
  },
  {
    slug: "army-surrendered-to-sheep",
    title: "The Army That Surrendered to Sheep",
    description: "When nature defeated Napoleon",
    category: "War",
    thumbnail_color: "#8D6E63",
    body_text: `In 1807, a detachment of Napoleon's Grande Armee was forced to surrender to an unlikely enemy: a flock of sheep. The incident occurred during Napoleon's campaign in Poland, when French soldiers foraging for food encountered more resistance than they expected—from livestock. The soldiers had been sent to requisition supplies from local farms. Poland in winter was brutal, and Napoleon's supply lines were stretched thin. When the foragers tried to round up sheep from a peasant's flock, the animals panicked and charged. In the confusion, the French soldiers were knocked down, trampled, and scattered across the frozen fields. According to the account, several soldiers were injured by hooves and horns. The sheep, numbering in the hundreds, proved impossible to control. The peasants, seeing their opportunity, grabbed farming tools and drove off the remaining French soldiers. The foraging party returned to camp empty-handed and humiliated, having been defeated by the very animals they came to steal. The story may be embellished—wartime accounts often are—but it reflects a real problem Napoleon faced in Eastern Europe. His armies depended on living off the land, but the land was poor, the winters were harsh, and the locals were hostile. Soldiers who wandered too far from their units often disappeared, killed by peasants, weather, or the general chaos of the campaign. Napoleon would learn this lesson more painfully in 1812, when his invasion of Russia ended in catastrophe. The Russian winter, partisan resistance, and the vast empty landscape destroyed his army more thoroughly than any battle. The sheep incident was a small preview of the disasters to come.`,
    design_config: {"thumbnailColor":"#8D6E63","titlePage":{"backgroundColor":"#8D6E63","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#8D6E63","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#8D6E63"},{"background":"#FFD60A","text":"#000000"}],"imagePlaceholderColors":["#8D6E63","#FFD60A"],"imageAspectRatios":[1.4,0.9],"imageColorOffset":1,"imagePositionSeed":2}
  },
  {
    slug: "war-fought-with-kites",
    title: "Soldiers Who Fought with Kites",
    description: "Ancient China's aerial warfare",
    category: "War",
    thumbnail_color: "#C62828",
    body_text: `Long before aircraft, Chinese armies used kites as weapons of war. They carried messages over enemy lines, dropped bombs on fortifications, and—according to legend—even lifted spies into the air to observe enemy positions. Kite warfare may be as old as kites themselves. Chinese records from the fifth century BC describe kites used for military signaling. By the Han Dynasty, generals were using kites to measure distances to enemy fortifications and calculate the length of tunnels needed for siege operations. The most ambitious military use of kites involved lifting soldiers. Historical accounts describe man-carrying kites used for reconnaissance, allowing observers to survey enemy positions from above. Whether these accounts are exaggerated is debated, but the Chinese certainly understood the principles involved. Their kites were large, sophisticated, and capable of generating significant lift. Fire kites were simpler but potentially devastating. Soldiers attached flaming materials to kites and flew them over enemy camps or cities, hoping to start fires. The effectiveness varied with wind conditions, but the psychological impact was considerable. Enemies who saw flames descending from the sky had reason to be frightened. Other cultures adapted kite warfare for their own purposes. Polynesian warriors used kites to carry incendiary devices. Korean armies flew kites with noisemakers to terrify enemies. The Japanese developed kite traditions that may have included military applications. The age of the kite warrior ended with the development of powered aircraft, but their legacy persists. Military drones, which carry cameras and weapons over enemy territory, are essentially sophisticated descendants of the reconnaissance kites Chinese generals flew two thousand years ago.`,
    design_config: {"thumbnailColor":"#C62828","titlePage":{"backgroundColor":"#C62828","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#C62828","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#C62828"},{"background":"#1565C0","text":"#FFFFFF"}],"imagePlaceholderColors":["#C62828","#1565C0"],"imageAspectRatios":[1.3,0.85],"imageColorOffset":0,"imagePositionSeed":3}
  },
  {
    slug: "promoted-while-prisoner-of-war",
    title: "Promoted While a Prisoner",
    description: "The POW who made general",
    category: "War",
    thumbnail_color: "#37474F",
    body_text: `Jonathan Wainwright was a prisoner of the Japanese for over three years. During that time, he was promoted from major general to full general, awarded the Medal of Honor, and became one of the most celebrated American commanders of World War II—all while languishing in enemy prison camps. Wainwright's ordeal began in May 1942, when he was forced to surrender American and Filipino forces in the Philippines after the fall of Corregidor. He had held out for months after Douglas MacArthur's evacuation, fighting a hopeless defensive campaign with dwindling supplies. The surrender was agonizing, but there was no alternative. As a prisoner, Wainwright was moved between camps in the Philippines, Formosa, and Manchuria. He endured the same brutal conditions as other POWs: starvation rations, forced labor, disease, and routine beatings. The Japanese treated him harshly specifically because of his rank, holding him responsible for the fierce American resistance. Meanwhile, his reputation grew in America. Newspapers celebrated his heroic defense of Corregidor. Congress debated awarding him the Medal of Honor. President Roosevelt promoted him to four-star general, though Wainwright wouldn't learn of the promotion until after his liberation. When American forces liberated his camp in August 1945, Wainwright was barely recognizable—a gaunt, elderly-looking figure weighing less than 130 pounds. He was rushed to Tokyo to be present at the formal Japanese surrender aboard the USS Missouri, standing behind MacArthur as the documents were signed. After the war, Wainwright received his Medal of Honor from President Truman. The citation praised his "intrepid leadership" during "the most difficult battles ever fought by American forces." He had earned his stars in prison.`,
    design_config: {"thumbnailColor":"#37474F","titlePage":{"backgroundColor":"#37474F","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#37474F","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#37474F"},{"background":"#FFD60A","text":"#000000"}],"imagePlaceholderColors":["#37474F","#FFD60A"],"imageAspectRatios":[1.5,0.9],"imageColorOffset":1,"imagePositionSeed":4}
  },
  {
    slug: "battle-won-by-throwing-bees",
    title: "They Won By Throwing Beehives",
    description: "Africa's buzzing defenders",
    category: "War",
    thumbnail_color: "#FFA000",
    body_text: `During the Roman siege of Hatra in 198 AD, the defenders threw clay pots filled with scorpions, wasps, and other venomous creatures at the attacking legions. The Romans, among the finest soldiers in the world, were driven back by insects and arachnids. It wasn't the first or last time such tactics proved effective. The use of stinging insects as weapons stretches back to antiquity. The Mayans kept bees in hollow gourds that could be thrown at enemies during battle. African tribes from various regions used beehives as defensive weapons against invaders, including European colonizers. The psychological impact was as significant as the physical damage. The defense of Hatra is one of the best-documented cases. Emperor Septimius Severus led two sieges of the city, in 198 and 199 AD. Both failed, partly due to the garrison's unconventional tactics. Besides the insect bombs, defenders poured burning oil and threw containers of caustic chemicals. The Romans, accustomed to conventional siege warfare, had no counter for attackers that flew through the air. Modern military forces have studied insect weapons, though international conventions now prohibit biological warfare. During World War II, Japan's Unit 731 experimented with releasing plague-infected fleas on Chinese cities. The United States researched using insects as vectors for disease during the Cold War. But the simplest application—throwing a hive of angry bees at your enemies—remains remarkably effective. Bees attack anything that threatens their hive, stinging repeatedly until the threat is eliminated. Against armored soldiers who cannot flee quickly, a swarm can be devastating. The defenders of Hatra understood what modern generals sometimes forget: nature provides weapons that technology cannot match.`,
    design_config: {"thumbnailColor":"#FFA000","titlePage":{"backgroundColor":"#FFA000","textColor":"#000000"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#FFA000","text":"#000000"},{"background":"#FFFFFF","text":"#FFA000"},{"background":"#5D4037","text":"#FFFFFF"}],"imagePlaceholderColors":["#FFA000","#5D4037"],"imageAspectRatios":[1.4,0.85],"imageColorOffset":0,"imagePositionSeed":2}
  },
  {
    slug: "war-that-created-time-zones",
    title: "The War That Made Time Zones",
    description: "How railroads changed warfare",
    category: "War",
    thumbnail_color: "#455A64",
    body_text: `The American Civil War didn't create time zones, but it revealed why they were necessary. The massive logistical challenge of moving troops by rail across a continent exposed the chaos of having every city set its own time. When the war ended, the railroads demanded—and eventually got—standardized time. Before the 1880s, every American town set its clocks to local noon, when the sun was at its highest point in the sky. This meant that when it was noon in Washington, it was 12:08 in Philadelphia and 11:55 in Baltimore. Small differences, but they added up. Railroads operating on tight schedules couldn't function when every station along the route had a different time. During the Civil War, this problem became acute. Moving armies required precise coordination across hundreds of miles. Telegraphed orders had to specify which "noon" they meant. Supply trains running on different local times risked collision. The Union army, which depended heavily on railroads, struggled constantly with the confusion. After the war, the railroad companies took matters into their own hands. In 1883, they divided the country into four time zones—Eastern, Central, Mountain, and Pacific—and synchronized all their clocks accordingly. Most cities adopted railroad time immediately; the alternative was being unable to coordinate train schedules. The federal government didn't officially adopt time zones until 1918, when the Standard Time Act made them law. But the change had really happened decades earlier, driven by the military and economic necessity of moving men and material across vast distances. The Civil War revealed that modern industrial warfare required standardized time, and the railroads delivered it.`,
    design_config: {"thumbnailColor":"#455A64","titlePage":{"backgroundColor":"#455A64","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#455A64","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#455A64"},{"background":"#FFD60A","text":"#000000"}],"imagePlaceholderColors":["#455A64","#FFD60A"],"imageAspectRatios":[1.3,0.9],"imageColorOffset":1,"imagePositionSeed":3}
  },
  {
    slug: "escaped-three-pow-camps",
    title: "He Escaped Three Prison Camps",
    description: "The pilot who wouldn't stay caught",
    category: "War",
    thumbnail_color: "#1565C0",
    body_text: `Roger Bushell escaped from German custody so many times that the Nazis eventually murdered him to stop him trying again. A British fighter pilot shot down in 1940, Bushell spent five years as a prisoner of war and became the mastermind behind the most famous prison escape of World War II: the "Great Escape" from Stalag Luft III. Bushell's first escape came within days of his capture. He and a Czech pilot slipped away during a transfer between camps and made it to the Swiss border before being caught. His second escape took him to Prague, where he lived for eight months hidden by a Czech family before the Gestapo tracked him down. The third time would be the last. At Stalag Luft III, Bushell became "Big X," the leader of an elaborate escape organization. Under his direction, prisoners dug three tunnels—nicknamed Tom, Dick, and Harry—using bed boards, tin cans, and smuggled materials. The tunnels were engineering marvels, complete with electric lighting, ventilation systems, and even a railway to move dirt. On the night of March 24, 1944, seventy-six men crawled through Harry and emerged in the forest beyond the wire. It was the largest escape from a German POW camp in the war. The Nazis were humiliated and furious. Hitler ordered that most recaptured escapers be executed. Fifty men, including Bushell, were shot by the Gestapo, their deaths disguised as killings during attempted re-escape. Only three men made it to freedom. The executions violated the Geneva Convention and were prosecuted as war crimes after the war. Bushell had known the risks. He once told fellow prisoners, "Everyone here in this room is living on borrowed time." He escaped three times anyway.`,
    design_config: {"thumbnailColor":"#1565C0","titlePage":{"backgroundColor":"#1565C0","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#1565C0","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#1565C0"},{"background":"#D32F2F","text":"#FFFFFF"}],"imagePlaceholderColors":["#1565C0","#D32F2F"],"imageAspectRatios":[1.5,0.85],"imageColorOffset":0,"imagePositionSeed":4}
  },
  {
    slug: "battle-fought-in-fog-confusion",
    title: "The Battle Lost in the Fog",
    description: "When no one could see the enemy",
    category: "War",
    thumbnail_color: "#78909C",
    body_text: `The Battle of Barnet in 1471 was decided by fog so thick that soldiers couldn't tell friend from foe. When the Lancastrian Earl of Oxford's men charged back from pursuit, their own allies mistook them for enemies and attacked. The confusion destroyed the Lancastrian army and changed English history. The battle was fought during the Wars of the Roses, the brutal civil war between the houses of York and Lancaster for the English throne. Edward IV, the Yorkist king, faced a Lancastrian army led by the Earl of Warwick, once his ally, now his deadliest enemy. The armies met on Easter Sunday in dense fog. The fog made the battle chaotic from the start. The armies' lines were misaligned; neither side could see the other's full deployment. When fighting began, each wing engaged without knowing what was happening elsewhere. The Earl of Oxford, commanding the Lancastrian right, routed the Yorkist left and pursued them for miles. His fatal error came on the return. Oxford's men wore a badge showing a star with rays—the de Vere family symbol. In the fog, it looked remarkably similar to Edward IV's badge, the sun in splendour. When Oxford's victorious troops appeared out of the murk, Warwick's men saw the symbol, assumed they were enemies, and loosed a volley of arrows. Oxford's men, believing they had been betrayed, fled shouting "Treason!" The cry spread through the Lancastrian ranks. Men who had been winning suddenly believed they were surrounded by traitors. The army collapsed. Warwick was killed trying to reach his horse. Edward IV won the crown, and the fog at Barnet became legendary—a reminder that in war, what soldiers cannot see may matter more than what they can.`,
    design_config: {"thumbnailColor":"#78909C","titlePage":{"backgroundColor":"#78909C","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#78909C","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#78909C"},{"background":"#5D4037","text":"#FFFFFF"}],"imagePlaceholderColors":["#78909C","#5D4037"],"imageAspectRatios":[1.4,0.9],"imageColorOffset":1,"imagePositionSeed":2}
  },
  {
    slug: "accidental-bombing-switzerland",
    title: "The Day We Bombed Switzerland",
    description: "WWII's most awkward mistake",
    category: "War",
    thumbnail_color: "#D32F2F",
    body_text: `During World War II, the United States accidentally bombed neutral Switzerland at least several times, killing dozens of civilians and destroying property in a country that wasn't even at war. The most serious incident, in April 1944, killed forty people and damaged factories, homes, and a medieval church. The bombers weren't trying to hit Switzerland. They were targeting industrial facilities in Germany and Austria. But navigation was difficult over blacked-out Europe, especially when weather obscured landmarks. Crews relied on dead reckoning and sometimes inadequate maps. Switzerland, surrounded by Axis territory, was easy to confuse with nearby German cities. Schaffhausen, bombed in April 1944, was sometimes mistaken for the German city of Ludwigshafen. Zurich received bombs meant for Stuttgart. Basel, right on the German border, was hit multiple times by crews who miscalculated their position by mere miles. Swiss anti-aircraft guns shot down several American aircraft, killing crew members—which created the awkward situation of a neutral country killing Allied servicemen. The United States apologized repeatedly and eventually paid compensation. The Swiss government was caught in an impossible position: too weak to defend against American air power, too valuable as a neutral state for either side to seriously alienate. They protested diplomatically but knew they couldn't do more. After the war, the U.S. paid Switzerland over four million dollars in compensation for the accidental bombings—a significant sum in 1945 dollars, but hardly adequate for the lives lost and the damage done. The incidents remain a footnote to the war, an embarrassing reminder that even the most powerful military makes mistakes.`,
    design_config: {"thumbnailColor":"#D32F2F","titlePage":{"backgroundColor":"#D32F2F","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#D32F2F","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#D32F2F"},{"background":"#1565C0","text":"#FFFFFF"}],"imagePlaceholderColors":["#D32F2F","#1565C0"],"imageAspectRatios":[1.3,0.85],"imageColorOffset":0,"imagePositionSeed":3}
  },
  {
    slug: "war-declared-by-computer-error",
    title: "The Computer That Almost Started WWIII",
    description: "When the machines saw ghosts",
    category: "War",
    thumbnail_color: "#212121",
    body_text: `On November 9, 1979, computers at NORAD detected a massive Soviet nuclear attack heading toward the United States. Missiles were prepared for launch. Bombers scrambled. The president's emergency aircraft was ordered into the air. Then someone discovered it was all a mistake: a training tape had been accidentally loaded into the live warning system. The 1979 incident was one of several terrifying false alarms during the Cold War. In 1980, a faulty computer chip caused NORAD to report a submarine-launched missile attack. In 1983, a Soviet early warning satellite mistook sunlight reflecting off clouds for American ICBMs, and only the skepticism of a single Soviet officer prevented retaliation. Each incident revealed how close the superpowers came to accidental nuclear war. Both sides had systems designed to ensure rapid response to attack—which meant they had only minutes to decide whether a warning was real. The technology that was supposed to protect them could also destroy them. The 1979 false alarm lasted about six minutes. During that time, the U.S. military went to the highest peacetime alert level. National Security Advisor Zbigniew Brzezinski was awakened and told that 250 Soviet missiles were inbound. He was about to call President Carter when a second call informed him the attack count had risen to 2,200 missiles—a full-scale strike. Before Brzezinski could reach the president, a third call confirmed it was a false alarm. The training tape, designed to simulate a Soviet attack for exercises, had somehow been inserted into the live system. The false alarm demonstrated that the human element was both the greatest weakness and the greatest safety feature in nuclear command systems. Computers saw an attack. Humans questioned it. This time, the humans were right.`,
    design_config: {"thumbnailColor":"#212121","titlePage":{"backgroundColor":"#212121","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#212121","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#212121"},{"background":"#D32F2F","text":"#FFFFFF"}],"imagePlaceholderColors":["#212121","#D32F2F"],"imageAspectRatios":[1.5,0.9],"imageColorOffset":1,"imagePositionSeed":4}
  },
  {
    slug: "medieval-weapons-in-wwii",
    title: "They Fought WWII With Swords",
    description: "The last cavalry charges in history",
    category: "War",
    thumbnail_color: "#6D4C41",
    body_text: `In 1942, a British officer named Jack Churchill stormed a Nazi position in Norway armed with a longbow, a Scottish broadsword, and bagpipes. He was not insane—or not entirely. Churchill was simply convinced that "any officer who goes into action without his sword is improperly dressed." Churchill, known as "Mad Jack," was the only British soldier credited with a longbow kill during World War II. He shot a German sergeant with an arrow during a 1940 ambush in France. He carried the sword into battle repeatedly, capturing forty-two German prisoners with it during a raid in Sicily. The bagpipes he played during attacks to terrify the enemy. He wasn't alone in using medieval weapons. Polish cavalry charged German tanks in 1939—not out of ignorance, as Nazi propaganda claimed, but because they were caught in the open by armored units they hadn't expected. The charges were desperate, not stupid, and some Polish lancers did manage to engage German infantry. The Italians conducted one of the last cavalry charges in history at Izbushensky, Russia, in 1942, with 600 horsemen armed with sabers and hand grenades overrunning a Soviet position. Even the Germans used horses extensively throughout the war, though primarily for transport rather than combat. And Japanese officers carried ancestral katanas into battle, sometimes using them in the desperate banzai charges of the Pacific war. Mad Jack Churchill survived the entire war, including capture by the Nazis and escape from a concentration camp. When asked why he carried a sword to a gunfight, he reportedly said the sword scared the enemy more than a rifle. He may have been right.`,
    design_config: {"thumbnailColor":"#6D4C41","titlePage":{"backgroundColor":"#6D4C41","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#6D4C41","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#6D4C41"},{"background":"#8D6E63","text":"#FFFFFF"}],"imagePlaceholderColors":["#6D4C41","#8D6E63"],"imageAspectRatios":[1.4,0.85],"imageColorOffset":0,"imagePositionSeed":2}
  }
];

async function uploadStory(story) {
  const response = await fetch(`${SUPABASE_URL}/rest/v1/stories`, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      "apikey": SUPABASE_KEY,
      "Authorization": `Bearer ${SUPABASE_KEY}`,
      "Prefer": "resolution=merge-duplicates,return=minimal"
    },
    body: JSON.stringify({
      slug: story.slug,
      title: story.title,
      description: story.description,
      category: story.category,
      thumbnail_color: story.thumbnail_color,
      published: true,
      published_at: new Date().toISOString(),
      body_text: story.body_text,
      design_config: story.design_config,
      updated_at: new Date().toISOString()
    })
  });

  if (!response.ok) {
    const text = await response.text();
    throw new Error(`${response.status}: ${text}`);
  }
}

async function main() {
  console.log(`Uploading ${stories.length} War "Did You Know" stories to Supabase...\n`);

  let success = 0;
  let failed = 0;

  for (const story of stories) {
    try {
      process.stdout.write(`Uploading: ${story.title}... `);
      await uploadStory(story);
      console.log("Done!");
      success++;
    } catch (error) {
      console.log(`Error: ${error.message}`);
      failed++;
    }
  }

  console.log(`\nComplete! ${success} succeeded, ${failed} failed.`);
}

main();
