/**
 * Art Category - 25 New Stories
 * Usage: node scripts/new-content/art-new.mjs
 */

const SUPABASE_URL = "https://egfwisgqdyhzpmeoracb.supabase.co";
const SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVnZndpc2dxZHloenBtZW9yYWNiIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2ODQyNzM0OSwiZXhwIjoyMDg0MDAzMzQ5fQ.S8h1fIepxWb44gPSPpWQ8fE0Q-SCYfL0QcBRUV7fXgs";

const stories = [
  {
    slug: "lascaux-cave-discovery",
    title: "The Discovery of Lascaux",
    description: "17,000 years of art found by teenagers",
    category: "Art",
    thumbnail_color: "#5D4037",
    body_text: `In September 1940, four teenagers and a dog stumbled upon the most important prehistoric art discovery in history. Robot, a dog belonging to eighteen-year-old Marcel Ravidat, had fallen into a hole in the woods near Montignac, France. When Marcel and his friends widened the opening and lowered themselves inside, they found themselves in a vast underground gallery covered with paintings. The walls were alive with images. Massive bulls charged across the limestone. Horses galloped in herds. Deer swam across what appeared to be a river. The paintings were executed with a sophistication that seemed impossible for their age. Carbon dating would eventually confirm they were approximately seventeen thousand years old, created by humans during the last Ice Age. The boys had discovered Lascaux, the Sistine Chapel of prehistory. The cave was opened to the public in 1948 and immediately became a sensation. Visitors came by the thousands, eager to see proof that artistic genius was not a modern invention. But their breath and body heat began destroying what had survived seventeen millennia. Algae bloomed on the walls. Fungi spread across the paintings. By 1963, the damage was so severe that the cave was closed permanently. The original Lascaux remains sealed today, visited only by conservators monitoring its slow deterioration. A replica, Lascaux II, was built nearby for tourists. The technology has improved with each iteration. Lascaux IV, opened in 2016, reproduces every mark with digital precision. But something is lost in the copy. The original cave, with its uneven walls and flickering torchlight, offered a connection across time that no reproduction can match. Those anonymous artists, painting by firelight in a world of mammoths and glaciers, created something that moved people seventeen thousand years later. We built museums to protect it and loved it to death anyway.`,
    design_config: {"thumbnailColor":"#5D4037","titlePage":{"backgroundColor":"#5D4037","textColor":"#FFD60A"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#5D4037","text":"#FFFFFF"},{"background":"#FFD60A","text":"#000000"},{"background":"#C4B39A","text":"#000000"},{"background":"#8D6E63","text":"#FFFFFF"}],"imagePlaceholderColors":["#5D4037","#FFD60A","#8D6E63"],"imageAspectRatios":[1.4,0.85],"imageColorOffset":0,"imagePositionSeed":2}
  },
  {
    slug: "warhol-factory",
    title: "Andy Warhol's Factory",
    description: "The studio that redefined American art",
    category: "Art",
    thumbnail_color: "#E91E63",
    body_text: `From 1962 to 1968, the most influential art studio in America was a silver-covered loft in midtown Manhattan. Andy Warhol called it the Factory, and the name was literal. Art was produced there on an industrial scale, with assistants silk-screening Campbell's soup cans and Marilyn Monroe portraits while Warhol supervised from his desk. But the Factory was more than a workshop. It was a social experiment, a round-the-clock party where drag queens mingled with society heiresses, where underground filmmakers shot movies in the corner while musicians rehearsed nearby. Warhol documented everything, filming hundreds of hours of footage that captured the chaos. The regulars called themselves Superstars. Edie Sedgwick, a troubled debutante with a pixie cut, became Warhol's muse and appeared in his films before spiraling into addiction. Lou Reed and the Velvet Underground became the house band, creating music that would influence generations of artists. Candy Darling and Jackie Curtis pioneered a new kind of celebrity, famous simply for being themselves. The atmosphere was electric and dangerous. Speed was the drug of choice. Paranoia ran high. In June 1968, a writer named Valerie Solanas walked into the Factory and shot Warhol three times. He was clinically dead for ninety seconds before surgeons revived him. Solanas, who believed Warhol was controlling her life, was arrested at Times Square hours later. Warhol survived but was never the same. The original Factory closed. Security tightened. The open-door policy ended. The silver walls were painted white. Warhol continued producing art for another two decades, but the anarchic energy of those early years was gone forever. The Factory had proved that art could be mass-produced without losing its power, that celebrity could be manufactured, that the boundaries between high and low culture were artificial. Warhol had predicted everyone would be famous for fifteen minutes. The Factory made it possible.`,
    design_config: {"thumbnailColor":"#E91E63","titlePage":{"backgroundColor":"#E91E63","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#E91E63","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#E91E63"},{"background":"#9C27B0","text":"#FFFFFF"},{"background":"#FFD60A","text":"#000000"}],"imagePlaceholderColors":["#E91E63","#9C27B0","#FFD60A"],"imageAspectRatios":[1.3,0.9],"imageColorOffset":1,"imagePositionSeed":3}
  },
  {
    slug: "armory-show-1913",
    title: "The Armory Show",
    description: "The exhibition that shocked America",
    category: "Art",
    thumbnail_color: "#3F51B5",
    body_text: `In February 1913, Americans lined up around the block to see an exhibition that would change their understanding of art forever. The International Exhibition of Modern Art, held in a National Guard armory on Lexington Avenue in New York, introduced the American public to movements they had never seen: Cubism, Fauvism, Post-Impressionism. Nothing had prepared them for what they found inside. Marcel Duchamp's "Nude Descending a Staircase, No. 2" became the show's most controversial work. Critics called it an explosion in a shingle factory. One newspaper ran a contest to find the nude, offering prizes to readers who could identify a human figure in the fractured planes. Former President Theodore Roosevelt visited and declared the painting was less realistic than a Navajo rug. The public was outraged, fascinated, and divided. Over the show's one-month run, approximately 87,000 people paid admission to see 1,300 works by 300 artists. They came to mock and stayed to argue. Matisse's bold colors scandalized viewers accustomed to academic realism. Cézanne's distorted perspectives seemed like deliberate insults. A group of students at the Art Institute of Chicago burned copies of the most offensive works in effigy. But something shifted. American collectors began buying modern art. Young American artists realized there were alternatives to the European traditions they had been taught to imitate. The Armory Show didn't just display modern art—it legitimized it. Within a decade, museums that had refused to show anything more radical than Impressionism were acquiring Picassos and Braques. The shock of 1913 became the mainstream of 1930. America had entered the twentieth century, kicking and screaming.`,
    design_config: {"thumbnailColor":"#3F51B5","titlePage":{"backgroundColor":"#3F51B5","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#3F51B5","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#3F51B5"},{"background":"#FFD60A","text":"#000000"},{"background":"#E8E8E8","text":"#000000"}],"imagePlaceholderColors":["#3F51B5","#FFD60A","#E8E8E8"],"imageAspectRatios":[1.5,0.8],"imageColorOffset":0,"imagePositionSeed":2}
  },
  {
    slug: "caravaggio-dark-life",
    title: "Caravaggio's Violent Life",
    description: "The murderer who revolutionized painting",
    category: "Art",
    thumbnail_color: "#4A148C",
    body_text: `Michelangelo Merisi da Caravaggio revolutionized Western painting and spent most of his adult life running from the law. His technique of dramatic illumination, figures emerging from absolute darkness into pools of light, influenced every major artist who followed. His personal life was a catalog of violence that would end in exile and early death. In Rome, where he established his reputation, Caravaggio was arrested repeatedly for carrying weapons, throwing artichokes at a waiter, and attacking various enemies with swords. His temper was legendary. Witnesses described him as quarrelsome, proud, and always ready to fight. He painted masterpieces between court appearances. On May 29, 1606, everything changed. During a tennis match that escalated into a street brawl, Caravaggio killed a man named Ranuccio Tomassoni. The exact circumstances remain unclear. Some historians believe it was a duel over a woman. Others suggest a gambling debt. What's certain is that Caravaggio fled Rome with a death sentence on his head. For the remaining four years of his life, Caravaggio wandered the Mediterranean, painting wherever he could find patrons while staying ahead of papal authorities. In Malta, he was knighted, then imprisoned, then escaped under mysterious circumstances. In Naples, unknown assailants attacked him and slashed his face. He kept painting. His late works grew darker, more brutal, more emotionally intense. The condemned man was creating his greatest art. In 1610, word came that the Pope might grant him a pardon. Caravaggio sailed for Rome, carrying paintings he hoped would secure his forgiveness. He never arrived. He died of fever in a coastal town called Porto Ercole, alone and delirious, just days before the pardon was signed. He was thirty-eight years old. The paintings he carried disappeared, their fate unknown. Caravaggio's body was buried in an unmarked grave, lost for four centuries until archaeologists located probable remains in 2010.`,
    design_config: {"thumbnailColor":"#4A148C","titlePage":{"backgroundColor":"#4A148C","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#4A148C","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#4A148C"},{"background":"#B71C1C","text":"#FFFFFF"},{"background":"#FFD60A","text":"#000000"}],"imagePlaceholderColors":["#4A148C","#B71C1C","#FFD60A"],"imageAspectRatios":[1.3,0.85],"imageColorOffset":1,"imagePositionSeed":3}
  },
  {
    slug: "amber-room-mystery",
    title: "The Amber Room",
    description: "The eighth wonder of the world, lost",
    category: "Art",
    thumbnail_color: "#FF8F00",
    body_text: `In the Catherine Palace near St. Petersburg, an entire room was made of amber. Six tons of it, carved into intricate panels and backed with gold leaf and mirrors. When candlelight hit the walls, the chamber glowed like it was alive, honey-colored light radiating from every surface. Visitors called it the eighth wonder of the world. No one knows where it is now. The Amber Room was created in Prussia in the early eighteenth century and later gifted to Peter the Great of Russia. For two centuries it remained one of the treasures of the Romanov dynasty. When Nazi Germany invaded the Soviet Union in 1941, soldiers dismantled the room in just thirty-six hours and shipped it to Königsberg, where it was reassembled in a castle museum. Then the war turned. As Soviet forces advanced in 1945, the Amber Room vanished. What happened next remains one of the greatest art mysteries in history. Some believe the room was destroyed when Allied bombs set the castle ablaze. Others claim it was hidden in underground bunkers or evacuated on ships that later sank. Treasure hunters have searched abandoned mines, sunken vessels, and sealed tunnels throughout Eastern Europe. Nothing confirmed has ever been found. The theories multiply with each decade. Perhaps the panels are still in Königsberg, now the Russian city of Kaliningrad, buried beneath modern construction. Perhaps they were secretly transported to South America. Perhaps Soviet soldiers found them first and they've been hidden ever since. Russia built a replica room, completed in 2003 after twenty-five years of work. It glows just as the original must have, amber catching the light in a thousand shades of gold and copper. But somewhere, possibly, the real Amber Room still exists, waiting in darkness to be found.`,
    design_config: {"thumbnailColor":"#FF8F00","titlePage":{"backgroundColor":"#FF8F00","textColor":"#000000"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#FF8F00","text":"#000000"},{"background":"#FFFFFF","text":"#FF8F00"},{"background":"#4A148C","text":"#FFFFFF"},{"background":"#FFD60A","text":"#000000"}],"imagePlaceholderColors":["#FF8F00","#4A148C","#FFD60A"],"imageAspectRatios":[1.4,0.9],"imageColorOffset":0,"imagePositionSeed":2}
  },
  {
    slug: "diego-rivera-rockefeller",
    title: "Rivera vs. Rockefeller",
    description: "The mural destroyed for its politics",
    category: "Art",
    thumbnail_color: "#D32F2F",
    body_text: `In 1932, Nelson Rockefeller commissioned Diego Rivera to paint a mural in the lobby of 30 Rockefeller Plaza, the crown jewel of his family's new skyscraper complex in Manhattan. Rivera was the most famous muralist in the world, a communist who had decorated buildings across Mexico with images of workers and revolution. Rockefeller wanted prestige. What he got was a political crisis. The mural, titled "Man at the Crossroads," was supposed to celebrate human potential. Rivera's preliminary sketches showed workers and scientists, industry and nature balanced in modernist harmony. Rockefeller approved them. But as Rivera painted, the composition evolved. A portrait of Lenin appeared on the right side of the mural, leading a crowd of workers. When newspapers reported the addition, outrage followed. Rockefeller asked Rivera to replace Lenin's face with an anonymous figure. Rivera refused. The situation escalated quickly. On May 9, 1933, guards ordered Rivera off the scaffold and covered the unfinished mural with canvas. Rivera was paid in full and escorted from the building. That night, he led a protest march through Manhattan. The covered mural became a cause célèbre for the left. Newspapers ran editorials. Artists organized boycotts. Rockefeller claimed he would preserve the work and perhaps move it elsewhere. It was a lie. In February 1934, workers destroyed the mural with hammers, reducing Rivera's vision to rubble. Rivera had anticipated the destruction. Using photographs taken during the painting, he recreated a smaller version of the mural in Mexico City's Palace of Fine Arts. It survives today, Lenin's portrait intact. The Rockefeller Center lobby now holds a different mural by a different artist, carefully inoffensive. Rivera never worked in the United States again. The battle between art and commerce had a winner, but the story of the loser endured.`,
    design_config: {"thumbnailColor":"#D32F2F","titlePage":{"backgroundColor":"#D32F2F","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#D32F2F","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#D32F2F"},{"background":"#1A237E","text":"#FFFFFF"},{"background":"#FFD60A","text":"#000000"}],"imagePlaceholderColors":["#D32F2F","#1A237E","#FFD60A"],"imageAspectRatios":[1.6,0.85],"imageColorOffset":1,"imagePositionSeed":4}
  },
  {
    slug: "theft-of-the-scream",
    title: "The Theft of The Scream",
    description: "Stolen twice, recovered twice",
    category: "Art",
    thumbnail_color: "#FF5722",
    body_text: `Edvard Munch's "The Scream" is one of the most recognizable images in art history. It has also been stolen twice. The first theft occurred on February 12, 1994, the opening day of the Winter Olympics in Lillehammer. While Norway celebrated, two men propped a ladder against the National Gallery in Oslo, broke a window, climbed inside, and removed the painting from the wall. They left a note: "Thanks for the poor security." The Norwegian police were humiliated. Tips poured in from around the world. A sting operation three months later recovered the painting undamaged. The thieves were caught, convicted, and served short sentences. Then it happened again. On August 22, 2004, armed men walked into the Munch Museum in Oslo in broad daylight, threatened guards with guns, and took "The Scream" along with another Munch painting, "Madonna." This time, recovery took two years. The paintings were found in a raid on a drug dealer's property, damaged but repairable. The museum closed for ten months for security upgrades. Munch himself might have appreciated the chaos. He created four versions of "The Scream" between 1893 and 1910, each showing the same agonized figure against a blood-red sky. The image came to him during a walk at sunset when he suddenly felt a wave of anxiety and seemed to hear an endless scream passing through nature. The painting became an icon of modern anxiety, reproduced on everything from coffee mugs to emoji. Its fame made it a target. Museums around the world tightened security after each Oslo theft. The most stolen painting in history taught institutions that their greatest works required protection. Today, the painting hangs behind bulletproof glass, watched by cameras, secure but somehow diminished by the cage.`,
    design_config: {"thumbnailColor":"#FF5722","titlePage":{"backgroundColor":"#FF5722","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#FF5722","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#FF5722"},{"background":"#0D47A1","text":"#FFFFFF"},{"background":"#FFD60A","text":"#000000"}],"imagePlaceholderColors":["#FF5722","#0D47A1","#FFD60A"],"imageAspectRatios":[0.8,1.4],"imageColorOffset":0,"imagePositionSeed":3}
  },
  {
    slug: "elgin-marbles-controversy",
    title: "The Elgin Marbles",
    description: "The 200-year fight over stolen sculptures",
    category: "Art",
    thumbnail_color: "#607D8B",
    body_text: `Between 1801 and 1812, the British diplomat Lord Elgin removed approximately half the surviving sculptures from the Parthenon in Athens. He claimed he had permission from the Ottoman authorities who then controlled Greece. He called it preservation. Greece has called it theft for two centuries. The marbles are staggering in their beauty. Carved around 440 BCE under the direction of the sculptor Phidias, they once decorated the greatest temple of ancient Athens. Horsemen process along friezes. Gods and giants battle in metopes. Fragments of the goddesses who watched over the city survive with their robes still flowing. Elgin sold the marbles to the British Museum in 1816, where they remain today. Greece gained independence in the 1830s and almost immediately began requesting their return. The requests continue. Every Greek government has demanded repatriation. The British Museum has refused, arguing that the marbles are safer in London, that they belong to world heritage, that returning them would set a dangerous precedent for museums everywhere. The debate has intensified in recent decades. Greece built a new Acropolis Museum in 2009, specifically designed to house the marbles. Empty spaces show exactly where the sculptures would fit, a permanent accusation. The museum sits at the foot of the Parthenon itself, where visitors can see the temple while viewing what remains. Arguments against return have weakened. Claims of Ottoman permission are disputed. The idea that London's climate better preserves the marble is undercut by pollution damage visible on the sculptures. Even the precedent argument falters as other institutions have returned artifacts. The British Museum holds firm. The marbles stay in Room 18, behind glass, separated from their original context by two thousand miles and an unbridged political divide.`,
    design_config: {"thumbnailColor":"#607D8B","titlePage":{"backgroundColor":"#607D8B","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#607D8B","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#607D8B"},{"background":"#C4B39A","text":"#000000"},{"background":"#14213D","text":"#FFFFFF"}],"imagePlaceholderColors":["#607D8B","#C4B39A","#14213D"],"imageAspectRatios":[1.5,0.9],"imageColorOffset":1,"imagePositionSeed":2}
  },
  {
    slug: "citizen-kane-making",
    title: "The Making of Citizen Kane",
    description: "How a 25-year-old made the greatest film",
    category: "Art",
    thumbnail_color: "#212121",
    body_text: `In 1940, RKO Pictures gave a twenty-five-year-old theater director complete creative control over his first film. Orson Welles had never directed a movie before. He used the freedom to reinvent cinema. Citizen Kane, released in 1941, employed techniques that seemed impossible. Deep focus photography kept foreground and background equally sharp. Ceilings appeared in shots for the first time, making rooms feel claustrophobic. The narrative fractured across time, with multiple unreliable narrators offering contradictory accounts of the same man's life. Welles and cinematographer Gregg Toland worked for months to achieve effects other filmmakers hadn't attempted. The story was equally revolutionary: a thinly veiled portrait of newspaper magnate William Randolph Hearst, tracing his rise from idealistic youth to lonely old age. Hearst recognized himself immediately and tried to destroy the film. His newspapers refused to review or advertise it. Theater chains he influenced declined to show it. Rumors spread that Hearst would expose Hollywood scandals if the film wasn't suppressed. RKO nearly burned the negative. Citizen Kane opened to strong reviews but disappointing box office. It won only one Academy Award, for its screenplay. Welles, who had been promised unlimited resources, saw his contract renegotiated and his next films taken from him and recut. His career in Hollywood never recovered. The film's reputation grew slowly. Each new generation of critics and filmmakers discovered its innovations. By the 1960s, Citizen Kane was routinely named the greatest film ever made. The techniques Welles invented became the vocabulary of cinema. Every film student studies it. Every director borrows from it. Welles spent the rest of his life struggling to finish projects, remembered as a genius whose first film was also his best. He died in 1985, having never matched Citizen Kane. Perhaps no one could.`,
    design_config: {"thumbnailColor":"#212121","titlePage":{"backgroundColor":"#212121","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#212121","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#212121"},{"background":"#4A4A4A","text":"#FFFFFF"},{"background":"#E8E8E8","text":"#000000"}],"imagePlaceholderColors":["#212121","#4A4A4A","#E8E8E8"],"imageAspectRatios":[1.6,0.9],"imageColorOffset":0,"imagePositionSeed":3}
  },
  {
    slug: "vermeer-forgotten-master",
    title: "Vermeer's Forgotten Legacy",
    description: "The master who vanished for 200 years",
    category: "Art",
    thumbnail_color: "#1976D2",
    body_text: `Johannes Vermeer died in 1675 and was almost entirely forgotten for two centuries. Today he's considered one of the greatest painters in history. In his own time, he was a moderately successful artist in the Dutch city of Delft, known locally but never famous beyond it. He produced fewer than forty paintings in his career—an astonishingly small output that may explain why his reputation faded so quickly after his death. His widow had to sell paintings to pay debts. His name rarely appeared in art histories. The few works that survived were often attributed to other artists. Then, in 1866, a French art critic named Théophile Thoré-Bürger published a series of articles arguing that Vermeer was a neglected genius. Thoré-Bürger had spent years tracking down paintings scattered across European collections, recognizing the same distinctive style in works attributed to different hands. He compiled a catalog of seventy paintings he believed were Vermeer's. The number was too high, but the rediscovery was genuine. The art world slowly woke up. By the early twentieth century, Vermeer had become a cult figure. His paintings commanded astronomical prices. His technique—the way light pooled on surfaces, the stillness of domestic scenes, the mysterious expressions of his subjects—seemed modern in ways his contemporaries did not. Museums competed for his rare works. The small number of surviving paintings only increased their value. Now Vermeer ranks among the most beloved of all painters. His "Girl with a Pearl Earring" is as famous as any image in art. Exhibitions of his work draw hundreds of thousands of visitors. The painter who couldn't support his family in life became priceless in death. We nearly lost him. If not for one critic's obsession, Vermeer might still be a footnote, his paintings hanging unrecognized in private collections, his genius unknown.`,
    design_config: {"thumbnailColor":"#1976D2","titlePage":{"backgroundColor":"#1976D2","textColor":"#FFD60A"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#1976D2","text":"#FFFFFF"},{"background":"#FFD60A","text":"#000000"},{"background":"#FFFFFF","text":"#1976D2"},{"background":"#14213D","text":"#FFFFFF"}],"imagePlaceholderColors":["#1976D2","#FFD60A","#14213D"],"imageAspectRatios":[1.3,0.85],"imageColorOffset":1,"imagePositionSeed":2}
  },
  {
    slug: "last-supper-deterioration",
    title: "The Last Supper's Decay",
    description: "Leonardo's masterpiece was ruined from the start",
    category: "Art",
    thumbnail_color: "#8D6E63",
    body_text: `Leonardo da Vinci finished painting The Last Supper in 1498. By 1517, it was already deteriorating. The problem was Leonardo's ambition. Traditional frescoes were painted on wet plaster, bonding pigment to wall. Leonardo wanted more time to perfect his work, so he experimented with oil and tempera on dry plaster. The technique allowed him to add details and make revisions. It also meant the paint began flaking off almost immediately. The refectory wall in Milan where The Last Supper hangs faces south and absorbs moisture. Within fifty years, the painting had become a ruin. Travelers described figures barely visible through layers of mold and decay. In 1652, monks cut a door through the bottom center of the mural, destroying Jesus's feet. Restoration attempts over the centuries made things worse. Well-meaning conservators repainted faded sections, adding their own interpretations to Leonardo's design. By the twentieth century, more than half the visible surface was restoration work, not original. Napoleon's troops used the refectory as a stable and threw bricks at the apostles' heads. Allied bombing in 1943 destroyed the rest of the building while sandbags protected the wall. Through it all, The Last Supper endured, barely. A twenty-year restoration completed in 1999 removed centuries of overpainting, revealing what remains of Leonardo's original work. The result is ghostly—shadows of figures, hints of color, fragments of the genius that once covered the wall. Visitors must now book tickets months in advance for fifteen-minute appointments. Air filtration systems struggle to prevent further decay. The painting continues to deteriorate despite every precaution. Leonardo created something that couldn't last. We're still trying to save what's left.`,
    design_config: {"thumbnailColor":"#8D6E63","titlePage":{"backgroundColor":"#8D6E63","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#8D6E63","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#8D6E63"},{"background":"#C4B39A","text":"#000000"},{"background":"#5D4037","text":"#FFFFFF"}],"imagePlaceholderColors":["#8D6E63","#C4B39A","#5D4037"],"imageAspectRatios":[1.6,0.8],"imageColorOffset":0,"imagePositionSeed":4}
  },
  {
    slug: "michelangelo-david",
    title: "Michelangelo's David",
    description: "The statue carved from a ruined block",
    category: "Art",
    thumbnail_color: "#BDBDBD",
    body_text: `The marble block that became David had already defeated two sculptors. Quarried from Carrara in 1464, the eighteen-foot slab of stone sat unused for over a decade before Agostino di Duccio began carving a figure of the biblical hero. He gave up. Another sculptor, Antonio Rossellino, tried and failed. The block, now partially carved and strangely proportioned, was abandoned in the courtyard of Florence's cathedral workshop, exposed to weather for twenty-five years. In 1501, the cathedral authorities decided to try again. Michelangelo, just twenty-six years old but already famous for his Pietà in Rome, won the commission. He would have to work within the constraints of the botched earlier attempts—a thin block with rough cuts already made. Most sculptors would have refused. Michelangelo saw possibility. He worked for two years, carving David from the compromised marble. The statue's unusual proportions—the oversized head and hands, the narrow depth—were solutions to the material's limitations. Michelangelo positioned the figure in a slight twist that minimized the stone's thinness while creating dynamic tension. The result seems to breathe. When David was completed in 1504, it was too beautiful to place on the cathedral rooftop as originally planned. A committee of artists, including Leonardo da Vinci, debated where it should stand. They chose the Piazza della Signoria, Florence's political heart. The statue became a symbol of the republic's defiance against larger powers. David stood outdoors for over three hundred years, battered by weather and riots. A chair thrown from a window during political unrest broke his arm in 1527. Acid rain ate at his surface. In 1873, he was finally moved indoors to the Accademia Gallery. A replica stands in the piazza now. The original remains inside, protected but somehow diminished. David was meant to stand against the sky.`,
    design_config: {"thumbnailColor":"#BDBDBD","titlePage":{"backgroundColor":"#BDBDBD","textColor":"#000000"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#BDBDBD","text":"#000000"},{"background":"#FFFFFF","text":"#000000"},{"background":"#4A4A4A","text":"#FFFFFF"},{"background":"#E8E8E8","text":"#000000"}],"imagePlaceholderColors":["#BDBDBD","#4A4A4A","#E8E8E8"],"imageAspectRatios":[0.75,1.5],"imageColorOffset":1,"imagePositionSeed":3}
  },
  {
    slug: "impressionist-rejection",
    title: "The Impressionist Rejection",
    description: "When the art world laughed at genius",
    category: "Art",
    thumbnail_color: "#81D4FA",
    body_text: `In 1874, a group of French painters rented a photographer's studio in Paris and held their own exhibition. They had been rejected by the official Salon, the annual showcase that could make or break an artist's career. If the establishment wouldn't show their work, they would show it themselves. Critics came to mock. The term "Impressionism" was coined as an insult, derived from Claude Monet's painting "Impression, Sunrise." One reviewer sarcastically noted that wallpaper in its embryonic state was more finished than that seascape. Another declared the painters had declared war on beauty. The public agreed. Visitors laughed at canvases that seemed unfinished, at colors that clashed, at subjects that were merely ordinary—train stations, cafés, people walking in parks. The group included Monet, Renoir, Degas, Cézanne, Pissarro, Morisot, and others now considered masters. At the time, they struggled to sell paintings for enough to buy supplies. Monet was so poor he had to beg friends for money. Cézanne was repeatedly rejected by the Salon and ridiculed when his work appeared elsewhere. Pissarro lived in such poverty that some of his children died from diseases related to malnutrition. They held eight exhibitions over twelve years, slowly building an audience. Collectors emerged, at first a handful of eccentric Americans and Russians willing to pay modest prices. The Impressionists never achieved official acceptance in their lifetimes. The French state didn't collect their work until after most were dead. Then everything changed. By the twentieth century, Impressionist paintings were the most popular art in the world. Museums competed for acquisitions. Prices reached tens of millions. The revolution that critics had mocked became the mainstream they couldn't imagine. The laughingstock became the standard. Every generation of artists since has been shaped by those rejected painters.`,
    design_config: {"thumbnailColor":"#81D4FA","titlePage":{"backgroundColor":"#81D4FA","textColor":"#000000"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#81D4FA","text":"#000000"},{"background":"#FFFFFF","text":"#1976D2"},{"background":"#FFD60A","text":"#000000"},{"background":"#4CAF50","text":"#FFFFFF"}],"imagePlaceholderColors":["#81D4FA","#FFD60A","#4CAF50"],"imageAspectRatios":[1.4,0.9],"imageColorOffset":0,"imagePositionSeed":2}
  },
  {
    slug: "rodin-gates-of-hell",
    title: "Rodin's Gates of Hell",
    description: "The 37-year project that was never finished",
    category: "Art",
    thumbnail_color: "#4E342E",
    body_text: `In 1880, the French government commissioned Auguste Rodin to create a monumental bronze door for a new museum of decorative arts. Rodin proposed a sculptural interpretation of Dante's Inferno, twenty feet tall and covered with writhing figures of the damned. He worked on The Gates of Hell for the rest of his life. The museum was never built. The doors were never installed. The commission became an obsession that consumed thirty-seven years. Rodin kept adding figures, refining details, reimagining the composition. The doors grew into a laboratory for his ideas, spawning works that became famous in their own right. The Thinker, now one of the most recognized sculptures in the world, was originally a small figure perched above the gates, representing Dante contemplating the damned below. The Three Shades, The Kiss, and dozens of other works originated as studies for the project. Rodin enlarged them, cast them separately, exhibited them as independent pieces. The Gates themselves remained in his studio, perpetually unfinished, changing with each visit. When Rodin died in 1917, he left plaster casts but no final bronze version. The first bronze Gates were cast posthumously in 1926. Seven more authorized casts followed over the decades, each faithful to the state of the plaster at Rodin's death. They stand now in museums from Philadelphia to Tokyo, perpetually incomplete, perpetually powerful. Over 180 figures swarm across the doors. Some reach toward a heaven they'll never reach. Others fall into darkness. At the top, The Thinker broods over the chaos below. Rodin never declared the work finished because it was unfinishable—like Dante's vision, like human suffering itself. The thirty-seven-year project achieved a kind of perfection in its incompleteness.`,
    design_config: {"thumbnailColor":"#4E342E","titlePage":{"backgroundColor":"#4E342E","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#4E342E","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#4E342E"},{"background":"#B71C1C","text":"#FFFFFF"},{"background":"#4A4A4A","text":"#FFFFFF"}],"imagePlaceholderColors":["#4E342E","#B71C1C","#4A4A4A"],"imageAspectRatios":[0.8,1.5],"imageColorOffset":1,"imagePositionSeed":4}
  },
  {
    slug: "venus-de-milo-discovery",
    title: "The Venus de Milo",
    description: "The armless goddess who conquered the Louvre",
    category: "Art",
    thumbnail_color: "#CFD8DC",
    body_text: `On April 8, 1820, a Greek farmer digging in his field on the island of Milos uncovered the top half of a marble statue. French naval officers exploring the island learned of the find and tracked down the lower half in a nearby cave. The two pieces, when joined, revealed a nearly complete female figure of extraordinary beauty. She was missing both arms. The French officers immediately recognized the statue's importance and scrambled to acquire it. The Ottoman authorities who controlled Greece wanted it too. A bidding war ensued, complicated by local politics and rival claims. The French won, partly through aggressive negotiation and partly because their ship arrived first. The statue reached France in 1821 and was presented to Louis XVIII, who donated it to the Louvre. The timing was fortunate. France had recently been forced to return the Medici Venus to Italy after Napoleon's defeat. The nation needed a replacement masterpiece. The Venus de Milo filled the gap perfectly. Art historians debated her origins. Was she Greek or Roman? Classical or Hellenistic? What did her arms hold before they broke off? The questions only increased her mystique. She became the symbol of classical beauty, reproduced in countless copies and referenced in art and advertising for two centuries. Recent scholarship suggests she was carved around 130 BCE, during the Hellenistic period, possibly as a depiction of Aphrodite holding the golden apple of Paris. The missing arms may have held a shield in which she admired her reflection. We'll never know for certain. The fragments that might have revealed her original pose disappeared in 1820, possibly lost in the scramble to acquire her. The Venus de Milo remains incomplete, her mystery part of her power.`,
    design_config: {"thumbnailColor":"#CFD8DC","titlePage":{"backgroundColor":"#CFD8DC","textColor":"#000000"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#CFD8DC","text":"#000000"},{"background":"#FFFFFF","text":"#000000"},{"background":"#1976D2","text":"#FFFFFF"},{"background":"#E8E8E8","text":"#000000"}],"imagePlaceholderColors":["#CFD8DC","#1976D2","#E8E8E8"],"imageAspectRatios":[0.75,1.4],"imageColorOffset":0,"imagePositionSeed":2}
  },
  {
    slug: "jackson-pollock-death",
    title: "Jackson Pollock's Final Drive",
    description: "The crash that ended abstract expressionism",
    category: "Art",
    thumbnail_color: "#000000",
    body_text: `On the night of August 11, 1956, Jackson Pollock drove his Oldsmobile convertible into an oak tree less than a mile from his home on Long Island. He was forty-four years old and drunk. The crash killed him instantly. It also killed one of his passengers, a young woman named Edith Metzger. The other passenger, Pollock's girlfriend Ruth Kligman, was thrown from the car and survived. Pollock had been the most famous artist in America, the face of Abstract Expressionism, the first American painter to rival the European masters in influence and price. His drip paintings, created by dripping and pouring house paint onto canvases laid on the floor, had transformed what art could be. Life magazine had asked, "Is he the greatest living painter in the United States?" Collectors paid fortunes. Museums fought for exhibitions. But Pollock was falling apart. Alcoholism had plagued him since his twenties. After four years of sobriety in the early 1950s, he had relapsed and stopped painting. His marriage to the artist Lee Krasner was crumbling. He was depressed, drinking heavily, and threatening suicide. The night of the crash, Krasner was in Europe, and Pollock had been drinking at a local bar. The death was not quite suicide but not quite accident either. Pollock knew he was too drunk to drive. He took the wheel anyway and accelerated into the curve that killed him. The art world mourned and moved on. Abstract Expressionism had already begun to fade as Pop Art emerged. Pollock's death sealed his legend and fixed his prices. Works that sold for a few thousand in his lifetime now fetch hundreds of millions. The drunk who crashed his car became the most expensive American artist in history. The tragedy became myth.`,
    design_config: {"thumbnailColor":"#000000","titlePage":{"backgroundColor":"#000000","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#4A4A4A","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#000000"},{"background":"#B71C1C","text":"#FFFFFF"},{"background":"#FFD60A","text":"#000000"}],"imagePlaceholderColors":["#000000","#B71C1C","#FFD60A"],"imageAspectRatios":[1.6,0.9],"imageColorOffset":1,"imagePositionSeed":3}
  },
  {
    slug: "vienna-secession",
    title: "The Vienna Secession",
    description: "When artists declared war on tradition",
    category: "Art",
    thumbnail_color: "#FFD700",
    body_text: `In 1897, a group of Austrian artists resigned from the official artists' association and founded their own movement. They called it the Secession. Their motto, inscribed above the door of their new exhibition hall, was "To every age its art, to art its freedom." The leader was Gustav Klimt, already Vienna's most successful portrait painter. The members included architects, designers, and painters who rejected the academic conservatism that dominated Austrian culture. They wanted to unite all arts—painting, architecture, sculpture, design—into a single aesthetic vision. They wanted to tear down the boundaries between fine art and craft. The Secession building itself was a manifesto. Josef Maria Olbrich designed a gleaming white cube topped with a golden dome of interlaced laurel leaves. Viennese critics called it "the golden cabbage." The public was outraged, fascinated, and eventually won over. The building still stands today, a landmark of Art Nouveau architecture. Klimt's work defined the movement. His "Beethoven Frieze," created for a Secession exhibition in 1902, wrapped around three walls in a symphony of gold leaf and allegory. His portraits of Viennese society women, with their ornamental backgrounds and hypnotic gazes, became icons of the era. The infamous "Judith and the Head of Holofernes" scandalized viewers with its blend of violence and sexuality. The Secession lasted only about eight years as a unified movement. Klimt and others left in 1905 after internal disputes. But its influence spread throughout Europe and America. Art Deco borrowed its geometric patterns. The Bauhaus inherited its philosophy of integrating art and design. Klimt's gold-leaf technique inspired artists for a century. The rebels who seceded from tradition became tradition themselves. Their radical vision became the mainstream of modern design.`,
    design_config: {"thumbnailColor":"#FFD700","titlePage":{"backgroundColor":"#FFD700","textColor":"#000000"},"colorPalette":[{"background":"#000000","text":"#FFD700"},{"background":"#FFD700","text":"#000000"},{"background":"#FFFFFF","text":"#000000"},{"background":"#4A148C","text":"#FFFFFF"},{"background":"#E8E8E8","text":"#000000"}],"imagePlaceholderColors":["#FFD700","#4A148C","#E8E8E8"],"imageAspectRatios":[1.4,0.85],"imageColorOffset":0,"imagePositionSeed":2}
  },
  {
    slug: "salvator-mundi-mystery",
    title: "The Salvator Mundi Mystery",
    description: "The $450 million painting that vanished",
    category: "Art",
    thumbnail_color: "#1A237E",
    body_text: `In November 2017, Christie's sold a painting of Christ holding a crystal orb for $450.3 million, the highest price ever paid for a work of art. The buyer was later revealed to be Saudi Crown Prince Mohammed bin Salman. The painting was identified as Leonardo da Vinci's "Salvator Mundi." Then it disappeared. The Salvator Mundi's history is murky. It may have been painted around 1500 for the King of France. It passed through various collections over the centuries, eventually ending up in the estate of a Louisiana businessman who paid $60 for it in the 1950s, believing it to be a copy. In 2005, a consortium of art dealers bought it for around $10,000. After extensive restoration, they had it examined by experts, several of whom attributed it to Leonardo. The attribution was controversial. Some scholars saw Leonardo's hand throughout. Others noted crude passages that seemed inconsistent with his technique, suggesting the work of a student with Leonardo's partial involvement. The painting's condition—heavily restored, repainted in places, damaged by centuries of neglect—made certainty impossible. Christie's marketed it as "the last da Vinci," the final major work by the artist still in private hands. The auction was a spectacle, broadcast live online, with bids climbing by tens of millions. When the hammer fell at $450.3 million, the art world gasped. Since then, no one has publicly seen the painting. It was supposed to be unveiled at the Louvre Abu Dhabi in 2018, but the exhibition was postponed indefinitely without explanation. Reports suggest it may be on Mohammed bin Salman's yacht. Its location remains officially unknown. The most expensive painting in history has vanished, its authenticity still debated, its whereabouts a secret.`,
    design_config: {"thumbnailColor":"#1A237E","titlePage":{"backgroundColor":"#1A237E","textColor":"#FFD60A"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#1A237E","text":"#FFFFFF"},{"background":"#FFD60A","text":"#000000"},{"background":"#FFFFFF","text":"#1A237E"},{"background":"#4A4A4A","text":"#FFFFFF"}],"imagePlaceholderColors":["#1A237E","#FFD60A","#4A4A4A"],"imageAspectRatios":[0.75,1.4],"imageColorOffset":1,"imagePositionSeed":3}
  },
  {
    slug: "pre-raphaelite-brotherhood",
    title: "The Pre-Raphaelite Brotherhood",
    description: "The secret society that changed British art",
    category: "Art",
    thumbnail_color: "#7B1FA2",
    body_text: `In 1848, three young British painters formed a secret society dedicated to overthrowing the art establishment. They called themselves the Pre-Raphaelite Brotherhood and signed their paintings with the mysterious initials "PRB." Their target was the Royal Academy and everything it represented: the slavish imitation of Raphael and the Renaissance masters, the dark varnishes and idealized forms that had dominated British art for generations. John Everett Millais, William Holman Hunt, and Dante Gabriel Rossetti were all in their early twenties, talented, ambitious, and determined to start a revolution. They wanted to return to the vivid colors and minute detail of art before Raphael, to paint directly from nature rather than following academic formulas. Their early exhibitions caused scandals. Critics attacked their paintings as ugly, their techniques as primitive, their subjects as inappropriately realistic. Charles Dickens savaged Millais' depiction of the Virgin Mary as resembling "a hideous, wry-necked, blubbering, red-headed boy in a nightgown." The PRB seemed doomed. Then John Ruskin, the most influential critic in England, published a defense of the young painters. Tastes shifted. Millais' "Ophelia," showing the drowned Shakespearean heroine floating among flowers painted with botanical precision, became one of the most beloved images in British art. Collectors began buying. The revolution had succeeded. The Brotherhood itself lasted only five years before its members went separate ways. Millais became president of the Royal Academy he had once opposed. Rossetti founded a second wave of Pre-Raphaelitism focused on sensuous beauty. Hunt spent decades painting religious subjects in the Holy Land. Their movement influenced Art Nouveau, Symbolism, and the Arts and Crafts movement. The secret society that signed its paintings PRB had changed everything.`,
    design_config: {"thumbnailColor":"#7B1FA2","titlePage":{"backgroundColor":"#7B1FA2","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#7B1FA2","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#7B1FA2"},{"background":"#1B4332","text":"#FFFFFF"},{"background":"#FFD60A","text":"#000000"}],"imagePlaceholderColors":["#7B1FA2","#1B4332","#FFD60A"],"imageAspectRatios":[1.3,0.9],"imageColorOffset":0,"imagePositionSeed":4}
  },
  {
    slug: "sphinx-nose-mystery",
    title: "Who Broke the Sphinx's Nose?",
    description: "The real story behind the missing face",
    category: "Art",
    thumbnail_color: "#D4A36A",
    body_text: `Napoleon's troops did not shoot off the Sphinx's nose. This popular myth has been repeated for centuries, but drawings made before Napoleon reached Egypt in 1798 already show the Sphinx without its nose. The damage was done much earlier, though exactly when and by whom remains uncertain. The Sphinx at Giza is one of the oldest and largest sculptures in the world, carved from a single ridge of limestone around 2500 BCE. Its human face, thought to represent the pharaoh Khafre, originally wore a royal beard and was painted in bright colors. At some point, someone deliberately removed the nose. The most credible historical account comes from a fifteenth-century Arab historian named al-Maqrizi. He recorded that a Sufi zealot named Muhammad Sa'im al-Dahr was outraged to see Egyptian peasants making offerings to the Sphinx, seeking its favor for their crops. In 1378, he destroyed the nose to discourage what he considered idolatry. The mob then lynched him for vandalism. The story has the ring of truth. The Sphinx's nose wasn't broken by weathering or accidental damage—tool marks show it was pried off with chisels. The act was deliberate. But al-Maqrizi wrote decades after the supposed event, and no contemporary account survives. Other theories suggest the damage occurred even earlier, perhaps during the Arab conquest of Egypt or during medieval religious iconoclasm. The mystery may never be solved. What remains is a monument transformed by its wounds. The noseless Sphinx has become more famous than the intact original ever was. Its damaged face stares eastward toward the rising sun, keeping its secrets for another five thousand years.`,
    design_config: {"thumbnailColor":"#D4A36A","titlePage":{"backgroundColor":"#D4A36A","textColor":"#000000"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#D4A36A","text":"#000000"},{"background":"#FFFFFF","text":"#5D4037"},{"background":"#5D4037","text":"#FFFFFF"},{"background":"#C4B39A","text":"#000000"}],"imagePlaceholderColors":["#D4A36A","#5D4037","#C4B39A"],"imageAspectRatios":[1.5,0.85],"imageColorOffset":1,"imagePositionSeed":2}
  },
  {
    slug: "terracotta-army-discovery",
    title: "The Terracotta Army",
    description: "8,000 soldiers buried for 2,000 years",
    category: "Art",
    thumbnail_color: "#795548",
    body_text: `In March 1974, farmers digging a well near Xi'an, China, struck something hard about four feet down. They had found the head of a terracotta warrior. Further excavation revealed an entire underground army: more than eight thousand life-sized soldiers, horses, and chariots, buried for over two thousand years to guard the tomb of China's first emperor. Qin Shi Huang unified China in 221 BCE and immediately began preparing for eternity. He conscripted seven hundred thousand workers to build his mausoleum, a project that took nearly four decades. The terracotta army was just one component, positioned to defend his tomb from enemies in the afterlife. Each warrior is unique. Faces show individual features—different noses, ears, expressions. Hairstyles indicate military rank. The figures originally carried real bronze weapons and were painted in vivid colors that have mostly faded since excavation. Archaeologists have identified infantry, cavalry, archers, officers, and generals, organized in battle formation as if awaiting orders. The emperor's actual tomb remains unexcavated. Ancient texts describe a underground palace with rivers of mercury and a ceiling studded with pearls to represent the stars. Soil samples showing elevated mercury levels suggest these accounts may be accurate. Chinese authorities have declined to open the tomb, citing preservation concerns and the technology needed to protect whatever lies within. The terracotta army has become one of China's greatest tourist attractions. Millions visit each year to see the ranks of silent soldiers, still standing guard. Three pits have been excavated; a fourth is known to exist but remains untouched. The farmers who found the first head were initially concerned they had disturbed spirits. They had discovered the greatest archaeological find of the twentieth century.`,
    design_config: {"thumbnailColor":"#795548","titlePage":{"backgroundColor":"#795548","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#795548","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#795548"},{"background":"#C4B39A","text":"#000000"},{"background":"#4A4A4A","text":"#FFFFFF"}],"imagePlaceholderColors":["#795548","#C4B39A","#4A4A4A"],"imageAspectRatios":[1.4,0.9],"imageColorOffset":0,"imagePositionSeed":3}
  },
  {
    slug: "night-watch-attack",
    title: "The Night Watch Attacks",
    description: "The masterpiece vandals couldn't destroy",
    category: "Art",
    thumbnail_color: "#3E2723",
    body_text: `Rembrandt's "The Night Watch" has survived over three centuries in Amsterdam's Rijksmuseum. It has also survived multiple violent attacks. In 1911, a man attempted to cut the painting with a shoemaker's knife. He was stopped before causing serious damage. In 1975, a unemployed teacher named Wilhelmus de Rijk approached the painting during visiting hours and slashed it repeatedly with a bread knife. He screamed about being sent by the Lord as he cut. Guards subdued him, but the damage was extensive—a series of deep zigzag cuts across the lower portion of the canvas. Restoration took four years. The painting was returned to display in 1976, the repairs invisible to casual viewers but detectable under specialized imaging. De Rijk was committed to a psychiatric institution and never explained his motivation beyond religious delusions. Then, in 1990, a man sprayed acid on the painting. Guards responded within seconds, dousing the canvas with water. The acid had time only to penetrate the varnish layer; the paint beneath was saved. The attacker was also committed to psychiatric care. Each attack forced the museum to improve security. The painting now hangs behind bulletproof glass, watched by guards and cameras, protected by protocols developed through hard experience. The measures that protect "The Night Watch" have become standard for major works worldwide. Rembrandt painted it in 1642 as a group portrait of a militia company. The dramatic lighting and dynamic composition made it revolutionary. The painting is enormous—twelve feet tall—and dominates any room it occupies. Three and a half centuries later, it remains the Rijksmuseum's most treasured possession, surviving threats that would have destroyed lesser works. The painting endures. The attackers are forgotten.`,
    design_config: {"thumbnailColor":"#3E2723","titlePage":{"backgroundColor":"#3E2723","textColor":"#FFD60A"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#3E2723","text":"#FFFFFF"},{"background":"#FFD60A","text":"#000000"},{"background":"#FFFFFF","text":"#3E2723"},{"background":"#8D6E63","text":"#FFFFFF"}],"imagePlaceholderColors":["#3E2723","#FFD60A","#8D6E63"],"imageAspectRatios":[1.6,0.85],"imageColorOffset":1,"imagePositionSeed":4}
  },
  {
    slug: "picasso-blue-period",
    title: "Picasso's Blue Period",
    description: "When tragedy created masterpieces",
    category: "Art",
    thumbnail_color: "#1565C0",
    body_text: `On February 17, 1901, Pablo Picasso's closest friend shot himself in a Paris café. Carlos Casagemas, a young Spanish painter, had fallen desperately in love with a model who rejected him. He fired at her first—missing—then turned the gun on himself. Picasso, just nineteen years old, was devastated. The death transformed his art. For the next four years, Picasso painted almost exclusively in shades of blue. The subjects were outcasts and sufferers: beggars, prostitutes, blind men, prisoners, the poor and forgotten. The paintings radiated melancholy and isolation. Critics and collectors were baffled. Blue didn't sell. The paintings were too sad, too strange, too monochromatic. Picasso struggled financially, sometimes burning his own work to heat his studio. The Blue Period was a commercial disaster but an artistic breakthrough. In "La Vie," painted in 1903, Casagemas appears as a naked man, his face unmistakable, confronting mortality and loss. "The Old Guitarist" shows a blind musician hunched over his instrument, blue flesh stretched over visible bones, creating beauty from poverty. These paintings would later sell for tens of millions of dollars. The Blue Period ended around 1904, replaced by the warmer tones of the Rose Period and eventually by the geometric experiments of Cubism. Picasso would live another seven decades and create tens of thousands of works in every imaginable style. But the Blue Period remains among his most beloved. The young man mourning his dead friend, broke and isolated in Paris, created images of human suffering that still move viewers over a century later. Tragedy, it seems, can produce its own kind of beauty.`,
    design_config: {"thumbnailColor":"#1565C0","titlePage":{"backgroundColor":"#1565C0","textColor":"#FFFFFF"},"colorPalette":[{"background":"#0D47A1","text":"#FFFFFF"},{"background":"#1565C0","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#1565C0"},{"background":"#000000","text":"#FFFFFF"},{"background":"#90CAF9","text":"#000000"}],"imagePlaceholderColors":["#1565C0","#0D47A1","#90CAF9"],"imageAspectRatios":[1.3,0.85],"imageColorOffset":0,"imagePositionSeed":2}
  },
  {
    slug: "jaws-making",
    title: "The Making of Jaws",
    description: "The nightmare shoot that invented blockbusters",
    category: "Art",
    thumbnail_color: "#0D47A1",
    body_text: `Steven Spielberg was twenty-seven years old and convinced his career was over. The mechanical shark wouldn't work. The budget had tripled. The shooting schedule, originally planned for fifty-five days, stretched past five months. Every morning brought new disasters. The young director had been hired to adapt Peter Benchley's bestseller about a great white shark terrorizing a beach community. The plan was simple: build a mechanical shark, film it eating people, wrap in time for summer. The shark, nicknamed Bruce after Spielberg's lawyer, had other ideas. Designed to operate in a controlled tank, Bruce was deployed in the open ocean off Martha's Vineyard, where saltwater corroded his hydraulics. He sank repeatedly. His skin ripped. His jaws jammed. Most days, he simply didn't work at all. Spielberg was forced to improvise. Unable to show the shark, he suggested its presence through camera angles, music, and the reactions of actors. Yellow barrels attached to the shark became a visual shorthand. John Williams' two-note theme signaled danger without requiring mechanical effects. The invisible shark became more frightening than any rubber model could be. The production was so troubled that Universal executives considered shutting it down. Crew members called the film "Flaws." By the time shooting wrapped, everyone assumed it would be a disaster. Instead, Jaws became the first film to earn $100 million at the box office. It invented the summer blockbuster and changed Hollywood forever. The techniques Spielberg developed to hide his broken shark became models for suspense filmmaking. The young director whose career seemed finished went on to become the most commercially successful filmmaker in history. The disaster became a masterclass in creative problem-solving.`,
    design_config: {"thumbnailColor":"#0D47A1","titlePage":{"backgroundColor":"#0D47A1","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#0D47A1","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#0D47A1"},{"background":"#B71C1C","text":"#FFFFFF"},{"background":"#E8E8E8","text":"#000000"}],"imagePlaceholderColors":["#0D47A1","#B71C1C","#E8E8E8"],"imageAspectRatios":[1.6,0.9],"imageColorOffset":1,"imagePositionSeed":3}
  }
];

async function uploadStory(story) {
  const response = await fetch(`${SUPABASE_URL}/rest/v1/stories`, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      "apikey": SUPABASE_KEY,
      "Authorization": `Bearer ${SUPABASE_KEY}`,
      "Prefer": "resolution=merge-duplicates,return=minimal"
    },
    body: JSON.stringify({
      slug: story.slug,
      title: story.title,
      description: story.description,
      category: story.category,
      thumbnail_color: story.thumbnail_color,
      published: true,
      published_at: new Date().toISOString(),
      body_text: story.body_text,
      design_config: story.design_config,
      updated_at: new Date().toISOString()
    })
  });

  if (!response.ok) {
    const text = await response.text();
    throw new Error(`${response.status}: ${text}`);
  }
}

async function main() {
  console.log(`Uploading ${stories.length} Art stories to Supabase...\n`);

  let success = 0;
  let failed = 0;

  for (const story of stories) {
    try {
      process.stdout.write(`Uploading: ${story.title}... `);
      await uploadStory(story);
      console.log("Done!");
      success++;
    } catch (error) {
      console.log(`Error: ${error.message}`);
      failed++;
    }
  }

  console.log(`\nComplete! ${success} succeeded, ${failed} failed.`);
}

main();
