/**
 * Crime Category - 25 New Stories
 * Usage: node scripts/new-content/crime-new.mjs
 */

const SUPABASE_URL = "https://egfwisgqdyhzpmeoracb.supabase.co";
const SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVnZndpc2dxZHloenBtZW9yYWNiIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2ODQyNzM0OSwiZXhwIjoyMDg0MDAzMzQ5fQ.S8h1fIepxWb44gPSPpWQ8fE0Q-SCYfL0QcBRUV7fXgs";

const stories = [
  {
    slug: "jack-the-ripper",
    title: "Jack the Ripper",
    description: "The killer who was never caught",
    category: "Crime",
    thumbnail_color: "#212121",
    body_text: `In the autumn of 1888, someone began murdering women in the Whitechapel district of London. The killer was never identified, never caught, never named. The newspapers called him Jack the Ripper. Over eleven weeks, five women were killed with surgical precision. All were prostitutes working the foggy streets of London's poorest neighborhood. All were found with their throats cut and their bodies mutilated in ways that suggested anatomical knowledge. The police received hundreds of letters claiming to be from the killer. Most were hoaxes, but one, posted with a kidney supposedly taken from a victim, has never been definitively dismissed. The letter taunted authorities and promised more killings. London panicked. Queen Victoria demanded action. Vigilante groups patrolled the streets. Suspicious foreigners were attacked by mobs. The police questioned hundreds of suspects but made no arrests. Then the killings stopped as suddenly as they had begun. The Ripper simply vanished, leaving behind five confirmed victims and a mystery that has never been solved. Over a century later, amateur detectives and professional criminologists continue proposing suspects. A royal prince. A famous painter. A doctor. A Polish immigrant. DNA evidence has been cited and disputed. No theory has gained universal acceptance. The case remains officially open with the Metropolitan Police. Jack the Ripper achieved something rare: he became more famous in death than any of his victims were in life. His anonymous cruelty created the template for the modern serial killer and spawned an industry of Ripperology that shows no sign of fading. We still don't know who he was. We probably never will.`,
    design_config: {"thumbnailColor":"#212121","titlePage":{"backgroundColor":"#212121","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#212121","text":"#FFFFFF"},{"background":"#B71C1C","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#212121"},{"background":"#4A4A4A","text":"#FFFFFF"}],"imagePlaceholderColors":["#212121","#B71C1C","#4A4A4A"],"imageAspectRatios":[1.3,0.85],"imageColorOffset":0,"imagePositionSeed":2}
  },
  {
    slug: "lufthansa-heist",
    title: "The Lufthansa Heist",
    description: "The robbery that inspired Goodfellas",
    category: "Crime",
    thumbnail_color: "#1565C0",
    body_text: `On December 11, 1978, a team of masked men walked into the Lufthansa cargo terminal at JFK Airport and walked out with $5 million in cash and $875,000 in jewelry. Adjusted for inflation, it remains one of the largest cash robberies in American history. The heist was planned by Jimmy Burke, a legendary figure in New York's organized crime world. Burke had spent months cultivating an inside man, a Lufthansa employee named Louis Werner who provided details about security procedures and the timing of cash shipments. The robbery itself took just sixty-four minutes. Six armed men, wearing ski masks and dark clothing, entered through an employee entrance. They rounded up the night shift workers and forced them to load currency from the vault into their van. No shots were fired. No one was seriously hurt. The robbers drove away with more money than anyone had ever stolen from an American airport. Then things went wrong. Burke had promised to share the proceeds among his crew. Instead, he began eliminating anyone who might connect him to the crime. Within six months, most of the participants were dead, killed by Burke's associates before they could spend their share or talk to investigators. Bodies turned up in dumpsters, in car trunks, in the back of a meat locker. Louis Werner was identified and convicted, but he had been cut out of the gang and knew nothing useful. The money was never recovered. Most of the perpetrators were never charged. Burke eventually went to prison for an unrelated murder and died there in 1996. The Lufthansa heist became part of mob legend, immortalized in the film Goodfellas as the pinnacle of a certain kind of criminal ambition. The perfect robbery, followed by the inevitable betrayal.`,
    design_config: {"thumbnailColor":"#1565C0","titlePage":{"backgroundColor":"#1565C0","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#1565C0","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#1565C0"},{"background":"#FFD60A","text":"#000000"},{"background":"#4A4A4A","text":"#FFFFFF"}],"imagePlaceholderColors":["#1565C0","#FFD60A","#4A4A4A"],"imageAspectRatios":[1.5,0.9],"imageColorOffset":1,"imagePositionSeed":3}
  },
  {
    slug: "ponzi-scheme-original",
    title: "The Original Ponzi Scheme",
    description: "The con artist who gave fraud his name",
    category: "Crime",
    thumbnail_color: "#2E7D32",
    body_text: `Charles Ponzi promised investors he could double their money in ninety days. He was telling the truth about the returns—early investors did receive exactly what he promised. He was lying about everything else. In 1919, Ponzi discovered a quirk in the international postal system. Reply coupons, purchased in one country and redeemed in another, could theoretically generate small profits due to exchange rate differences. Ponzi told investors he had perfected a method to exploit this at scale. He had done nothing of the sort. The actual arbitrage was too slow and too small to generate meaningful returns. Instead, Ponzi paid early investors with money from later investors, creating the illusion of a profitable business while actually running a mathematical impossibility. The scheme worked spectacularly well—for a while. Within months, Ponzi was taking in a million dollars a week. Crowds lined up outside his Boston office. Investors mortgaged their homes. Police officers invested their pensions. Ponzi bought a mansion, employed servants, and lived like the millionaire he was rapidly becoming. Journalists grew suspicious. A reporter for the Boston Post discovered that Ponzi had a criminal record for forgery in Canada. Financial experts calculated that his scheme would require more reply coupons than actually existed in the entire world. In August 1920, authorities moved in. They found that Ponzi had only sixty-one dollars in reply coupons. His investors had given him nearly $20 million. The collapse ruined thousands of families. Ponzi served three and a half years in federal prison, then nine years in Massachusetts for state charges. He was deported to Italy in 1934 and died penniless in Brazil in 1949. His name became synonymous with a type of fraud that continues to claim victims today. Bernie Madoff ran a Ponzi scheme for decades. So did countless smaller operators. The basic con—pay old investors with new investors' money—remains effective because people want to believe in easy profits.`,
    design_config: {"thumbnailColor":"#2E7D32","titlePage":{"backgroundColor":"#2E7D32","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#2E7D32","text":"#FFFFFF"},{"background":"#FFD60A","text":"#000000"},{"background":"#FFFFFF","text":"#2E7D32"},{"background":"#4A4A4A","text":"#FFFFFF"}],"imagePlaceholderColors":["#2E7D32","#FFD60A","#4A4A4A"],"imageAspectRatios":[1.4,0.85],"imageColorOffset":0,"imagePositionSeed":2}
  },
  {
    slug: "whitey-bulger-fbi",
    title: "Whitey Bulger and the FBI",
    description: "When the mob ran the bureau",
    category: "Crime",
    thumbnail_color: "#37474F",
    body_text: `For nearly two decades, the FBI's most wanted man was also the FBI's most valuable informant. James "Whitey" Bulger ran the Winter Hill Gang, the dominant organized crime group in Boston, while simultaneously passing information to the bureau about his rivals in the Italian Mafia. The arrangement was mutually beneficial and completely corrupt. Bulger used his FBI connection to eliminate competition. His handler, Agent John Connolly, warned him about investigations, leaked the identities of witnesses, and protected Bulger from prosecution while he ran a criminal empire that included drug trafficking, extortion, and murder. In exchange, Bulger provided intelligence that helped the FBI dismantle the Boston Mafia. The partnership lasted from 1975 until 1994, when Bulger learned he was about to be indicted. Connolly tipped him off, and Bulger disappeared. He spent sixteen years on the run, eventually captured in Santa Monica in 2011, living under a false name with his longtime girlfriend. He was eighty-one years old. The trial that followed exposed the depth of FBI corruption. Connolly was convicted of racketeering and murder. Evidence showed that FBI supervisors had ignored or covered up Bulger's crimes for years. Witnesses described murders Bulger committed while under federal protection, including the killing of informants whose identities had been leaked to him by his handlers. Bulger was convicted of eleven murders and sentenced to two consecutive life terms. In 2018, he was beaten to death by fellow inmates at a federal penitentiary in West Virginia, just hours after his transfer there. He was eighty-nine. The case remains one of the worst corruption scandals in FBI history. The bureau that hunted organized crime had become part of organized crime.`,
    design_config: {"thumbnailColor":"#37474F","titlePage":{"backgroundColor":"#37474F","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#37474F","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#37474F"},{"background":"#B71C1C","text":"#FFFFFF"},{"background":"#E8E8E8","text":"#000000"}],"imagePlaceholderColors":["#37474F","#B71C1C","#E8E8E8"],"imageAspectRatios":[1.3,0.9],"imageColorOffset":1,"imagePositionSeed":4}
  },
  {
    slug: "lizzie-borden-trial",
    title: "The Lizzie Borden Trial",
    description: "Did she really take an axe?",
    category: "Crime",
    thumbnail_color: "#5D4037",
    body_text: `On the morning of August 4, 1892, someone took a hatchet to Andrew and Abby Borden in their home in Fall River, Massachusetts. Andrew received eleven blows to the face. Abby received nineteen to the back of her head. The only other person in the house was Andrew's thirty-two-year-old daughter Lizzie. She claimed she had been in the barn during the murders and discovered her father's body upon returning to the house. Police found her story implausible. There were no signs of forced entry or robbery. The killer had apparently lingered in the house for ninety minutes between the two murders. Lizzie's relationship with her stepmother was notoriously hostile. She had tried to buy poison at a local pharmacy the day before. Lizzie was arrested and charged with double murder. The trial became a national sensation. Victorian society couldn't quite believe that a respectable woman from a prominent family could commit such brutal violence. Lizzie was well-spoken and appeared grief-stricken. Her lawyers portrayed her as a victim of overzealous prosecution. The jury deliberated for ninety minutes and found her not guilty. Lizzie Borden walked free, inherited her father's substantial estate, and lived another thirty-four years in Fall River. She never married. Neighbors shunned her. Children sang rhymes about her taking an axe. She died in 1927, maintaining her innocence to the end. Modern forensic analysis suggests she almost certainly did it. The timing, the locked doors, the missing murder weapon, the burned dress—everything points to Lizzie. But in 1892, a proper lady with a good lawyer could apparently get away with murder. The case became a template for the media circus that surrounds spectacular crimes, and the rhyme about forty whacks remains part of American folklore.`,
    design_config: {"thumbnailColor":"#5D4037","titlePage":{"backgroundColor":"#5D4037","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#5D4037","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#5D4037"},{"background":"#B71C1C","text":"#FFFFFF"},{"background":"#C4B39A","text":"#000000"}],"imagePlaceholderColors":["#5D4037","#B71C1C","#C4B39A"],"imageAspectRatios":[1.4,0.85],"imageColorOffset":0,"imagePositionSeed":3}
  },
  {
    slug: "bonnie-and-clyde",
    title: "Bonnie and Clyde",
    description: "The lovers who became legends",
    category: "Crime",
    thumbnail_color: "#795548",
    body_text: `They killed at least nine police officers and committed dozens of robberies across the American Southwest. They were also young, photogenic, and deeply in love. Bonnie Parker and Clyde Barrow became the most famous outlaws of the Depression era, their violent crime spree transformed by newspapers into a twisted romance. Clyde was a small-time Texas criminal when he met Bonnie in 1930. She was nineteen, married to a man serving time for murder, working as a waitress. Their connection was immediate. When Clyde was sent to prison for burglary, Bonnie smuggled him a gun. He escaped, was recaptured, and emerged from prison two years later hardened and ready for violence. The gang they assembled never numbered more than five or six people at a time. They robbed gas stations, grocery stores, and small banks, rarely netting more than a few hundred dollars. The take was negligible; the body count was not. Clyde shot his way out of encounters with police and had no hesitation about killing lawmen who got in his way. Bonnie and Clyde understood publicity. They posed for photographs with their weapons, sent images to newspapers, and cultivated an image of glamorous rebellion against the system. In a country devastated by economic collapse, where banks were foreclosing on farms and the government seemed helpless, the outlaws who robbed banks became folk heroes. The end came on May 23, 1934, in rural Louisiana. A posse of lawmen, acting on information from a gang associate, ambushed the couple's car. They fired approximately 130 rounds, hitting Bonnie and Clyde over fifty times each. The bodies were put on public display. Thousands came to view them. The legend of the beautiful outlaws, doomed and defiant, only grew stronger in death.`,
    design_config: {"thumbnailColor":"#795548","titlePage":{"backgroundColor":"#795548","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#795548","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#795548"},{"background":"#FFD60A","text":"#000000"},{"background":"#8D6E63","text":"#FFFFFF"}],"imagePlaceholderColors":["#795548","#FFD60A","#8D6E63"],"imageAspectRatios":[1.5,0.9],"imageColorOffset":1,"imagePositionSeed":2}
  },
  {
    slug: "the-hillside-stranglers",
    title: "The Hillside Stranglers",
    description: "The cousins who terrorized Los Angeles",
    category: "Crime",
    thumbnail_color: "#4A148C",
    body_text: `Between October 1977 and February 1978, ten young women were found dead on the hillsides of Los Angeles. Their bodies were displayed deliberately, posed to shock whoever found them. The killer—or killers—seemed to be taunting the city. Police formed a task force. The media dubbed the unknown perpetrator the Hillside Strangler. Women across Los Angeles lived in fear. The killings stopped as suddenly as they had begun. For over a year, the case went cold. Then, in January 1979, two young women were found murdered in Bellingham, Washington, strangled in a manner strikingly similar to the Los Angeles victims. Local police arrested Kenneth Bianchi, a security guard who had recently moved from California. Under hypnosis, Bianchi revealed a second personality who confessed to the killings—and implicated his cousin, Angelo Buono, as his partner. The revelation stunned investigators. Two killers had worked together, using their combined advantages to abduct victims. Bianchi had posed as a police officer or a talent scout. Buono ran an upholstery shop where victims were tortured. The cousins had raped and murdered women ranging in age from twelve to twenty-eight, then dumped their bodies where they would be found. Bianchi pleaded guilty and testified against Buono. The trial lasted two years, the longest in California history at that time. Both men were convicted. Bianchi remains in prison in Washington state. Buono died in his cell in 2002. The case demonstrated that serial killing wasn't always the work of a lone psychopath. Sometimes monsters hunted in pairs, their partnership enabling crimes that neither could have committed alone.`,
    design_config: {"thumbnailColor":"#4A148C","titlePage":{"backgroundColor":"#4A148C","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#4A148C","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#4A148C"},{"background":"#B71C1C","text":"#FFFFFF"},{"background":"#4A4A4A","text":"#FFFFFF"}],"imagePlaceholderColors":["#4A148C","#B71C1C","#4A4A4A"],"imageAspectRatios":[1.3,0.85],"imageColorOffset":0,"imagePositionSeed":3}
  },
  {
    slug: "hatton-garden-heist",
    title: "The Hatton Garden Heist",
    description: "The pensioners who pulled off a record robbery",
    category: "Crime",
    thumbnail_color: "#616161",
    body_text: `Over the Easter weekend of 2015, a group of elderly men broke into the Hatton Garden Safe Deposit Company in London and stole an estimated £14 million in cash, jewelry, and precious stones. The oldest was seventy-six. The youngest was forty-eight. Combined, they had centuries of criminal experience. The plan was audacious. The gang entered through a neighboring building, descended a shaft, and drilled through a concrete vault wall using a heavy-duty drill. The hole wasn't quite large enough for everyone, so the slimmest member—a sixty-year-old known as "Basil"—squeezed through first and disabled the vault from inside. They spent two nights emptying seventy-three safe deposit boxes, working methodically through walls of steel. Security cameras captured their movements, but the footage wasn't monitored in real time. Alarms triggered, but the response was inadequate. The thieves worked undisturbed, leaving with bags full of loot. The investigation that followed pieced together the gang's movements through CCTV footage, phone records, and surveillance. The men had been careless, using their regular vehicles and phones, meeting at the same pub to divide the spoils. Detectives listened to their conversations and watched them bicker over the division of the loot. Most of the gang was arrested within months. The ringleader, Brian Reader, was seventy-six and had participated in the famous Brink's-Mat robbery decades earlier. His colleagues were equally seasoned criminals who should have known better than to leave such an obvious trail. About a third of the stolen goods were never recovered. Some ended up in locked safes that the owners refused to open, having their own reasons to avoid police attention. The old thieves went to prison, their final job becoming the subject of documentaries and films.`,
    design_config: {"thumbnailColor":"#616161","titlePage":{"backgroundColor":"#616161","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#616161","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#616161"},{"background":"#FFD60A","text":"#000000"},{"background":"#4A4A4A","text":"#FFFFFF"}],"imagePlaceholderColors":["#616161","#FFD60A","#4A4A4A"],"imageAspectRatios":[1.4,0.9],"imageColorOffset":1,"imagePositionSeed":4}
  },
  {
    slug: "jeffrey-dahmer",
    title: "The Milwaukee Cannibal",
    description: "The serial killer hiding in plain sight",
    category: "Crime",
    thumbnail_color: "#263238",
    body_text: `On July 22, 1991, a man ran from an apartment building in Milwaukee with a handcuff dangling from one wrist. He flagged down a police car and led officers back to apartment 213, where they discovered photographs of dismembered bodies and human remains stored in a barrel of acid. Jeffrey Dahmer, the apartment's occupant, confessed immediately. He had killed seventeen men over thirteen years. Dahmer's method was horrifyingly consistent. He would meet young men at bars or bus stops, lure them to his apartment with offers of money or alcohol, drug them, strangle them, and dismember their bodies. He photographed each stage of the process. He kept body parts as souvenirs. He admitted to cannibalism. The horror was compounded by the missed opportunities to stop him. In May 1991, just two months before his arrest, police found a naked, bleeding fourteen-year-old boy outside Dahmer's building. Dahmer convinced the officers that the boy was his adult boyfriend and they were having a domestic dispute. The police returned the boy to Dahmer's apartment, where Dahmer killed him that night. The officers were later fired. Dahmer's victims were overwhelmingly young men of color, often gay or struggling. He targeted the vulnerable, people whose disappearances might not be aggressively investigated. He lived in a poor neighborhood where complaints about smells from his apartment were ignored. The system failed at every level. Dahmer was sentenced to fifteen consecutive life terms. In November 1994, he was beaten to death by a fellow inmate at the Columbia Correctional Institution in Wisconsin. He was thirty-four years old. The apartment building where he committed his crimes was demolished. The neighborhood has tried to forget.`,
    design_config: {"thumbnailColor":"#263238","titlePage":{"backgroundColor":"#263238","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#263238","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#263238"},{"background":"#B71C1C","text":"#FFFFFF"},{"background":"#4A4A4A","text":"#FFFFFF"}],"imagePlaceholderColors":["#263238","#B71C1C","#4A4A4A"],"imageAspectRatios":[1.3,0.85],"imageColorOffset":0,"imagePositionSeed":2}
  },
  {
    slug: "great-diamond-authority",
    title: "The London Diamond Robbery",
    description: "The heist from the De Beers vault",
    category: "Crime",
    thumbnail_color: "#90CAF9",
    body_text: `In the year 2000, a man named Leonardo Notarbartolo walked into the Antwerp Diamond Centre, one of the most secure buildings in the world, and joined as a tenant. He rented a small office, made small talk with security guards, and spent two years studying every aspect of the building's defenses. Then he robbed it blind. The vault was protected by ten layers of security: heat detectors, motion sensors, a combination lock, a key lock, a magnetic seal, seismic sensors, and three-ton door that could only be opened by a specific sequence of actions. On the weekend of February 15, 2003, Notarbartolo and his team bypassed every single one. They used hairspray to blind the heat sensors. They taped over the motion detectors. They had copied the vault combination by watching the caretaker on hidden cameras. One by one, the defenses fell. Inside, they found 160 safe deposit boxes crammed with diamonds, gold, and cash. They left with an estimated $100 million in valuables—possibly much more, since many box owners never reported their losses. It was the largest diamond heist in history. The gang might have gotten away clean if not for a single mistake. Instead of disposing of their waste properly, they dumped bags of evidence in a forest outside Antwerp. A hunter found them and called police. The bags contained videotapes, receipts, and DNA. Notarbartolo was arrested within weeks. He was convicted and sentenced to ten years. Most of the diamonds were never recovered. Notarbartolo later claimed he had been set up, that the heist was actually an inside job designed to cover insurance fraud. The truth may never be known. What's certain is that a small team of thieves defeated the most sophisticated security system in the diamond industry and made off with a fortune that remains mostly missing.`,
    design_config: {"thumbnailColor":"#90CAF9","titlePage":{"backgroundColor":"#90CAF9","textColor":"#000000"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#90CAF9","text":"#000000"},{"background":"#FFFFFF","text":"#1565C0"},{"background":"#1565C0","text":"#FFFFFF"},{"background":"#E8E8E8","text":"#000000"}],"imagePlaceholderColors":["#90CAF9","#1565C0","#E8E8E8"],"imageAspectRatios":[1.5,0.9],"imageColorOffset":1,"imagePositionSeed":3}
  },
  {
    slug: "ted-bundy-escape",
    title: "Ted Bundy's Escapes",
    description: "The serial killer who broke out twice",
    category: "Crime",
    thumbnail_color: "#5D4037",
    body_text: `Ted Bundy escaped from custody twice while awaiting trial for murder. Both times, authorities had underestimated him. Both times, he proved he would kill again. Bundy was charming, intelligent, and handsome—qualities that made him seem incapable of the brutal crimes he had committed. Police, lawyers, and even judges were often disarmed by his articulate manner. When he was captured in Colorado in 1977, charged with the murder of a young woman, he was allowed to serve as his own attorney, giving him access to the law library unsupervised. On June 7, 1977, Bundy jumped from a second-floor window of the Aspen courthouse and disappeared into the mountains. He was recaptured six days later, weakened by hunger and the cold, and returned to jail with heightened security. It wasn't enough. On December 30, Bundy climbed through a hole he had cut in the ceiling of his cell, crawled through the space above, and dropped into the jailer's apartment while the man was out. He stole clothes, walked out the door, and vanished. This time, he stayed free for over a month. He made his way to Florida, where he broke into a sorority house at Florida State University on January 15, 1978. He bludgeoned four women in their beds, killing two. Two weeks later, he kidnapped and murdered a twelve-year-old girl. Bundy was finally captured in February 1978 when a police officer noticed him driving erratically. He was tried, convicted, and sentenced to death. He spent a decade on death row, granting interviews and confessing to additional murders in attempts to delay his execution. On January 24, 1989, he was electrocuted at Florida State Prison. Crowds outside cheered. The escapes had extended his killing spree and cost three more lives.`,
    design_config: {"thumbnailColor":"#5D4037","titlePage":{"backgroundColor":"#5D4037","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#5D4037","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#5D4037"},{"background":"#B71C1C","text":"#FFFFFF"},{"background":"#4A4A4A","text":"#FFFFFF"}],"imagePlaceholderColors":["#5D4037","#B71C1C","#4A4A4A"],"imageAspectRatios":[1.4,0.85],"imageColorOffset":0,"imagePositionSeed":2}
  },
  {
    slug: "albert-fish",
    title: "Albert Fish",
    description: "The Boogeyman who was real",
    category: "Crime",
    thumbnail_color: "#4E342E",
    body_text: `In 1928, a kindly old man named Albert Fish visited the Budd family in New York, claiming to be hiring workers for his farm. He offered to take their ten-year-old daughter Grace to a birthday party. She never came home. Six years later, an anonymous letter arrived at the Budd household. It described, in graphic detail, what Fish had done to their daughter. The letter was his confession and his taunt. He had strangled her and eaten her body. The letter was unsigned but written on stationery from a rooming house. Police traced it to Fish, now sixty-four years old, a grandfatherly figure with white hair and gentle manners. His appearance had allowed him to prey on children for decades. Fish confessed to at least three child murders but hinted at many more. He claimed to have attacked children in every state. Investigators believed he may have killed over a hundred victims, though only three were confirmed. His crimes defied comprehension. He was a practicing cannibal and a severe masochist who had driven needles into his own body—twenty-nine were found in his pelvis during his autopsy. Psychiatrists described him as the most depraved individual they had ever examined. Fish's trial was a sensation. His defense argued insanity; the prosecution countered that knowing right from wrong made him legally sane regardless of his depravities. The jury deliberated for ten minutes and found him guilty. He was sentenced to death and executed in the electric chair at Sing Sing Prison in January 1936. According to legend, he helped guards attach the electrodes. Fish's case influenced child safety practices for generations. The stranger danger warnings that became standard in American parenting can be traced to the horror he left behind.`,
    design_config: {"thumbnailColor":"#4E342E","titlePage":{"backgroundColor":"#4E342E","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#4E342E","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#4E342E"},{"background":"#B71C1C","text":"#FFFFFF"},{"background":"#8D6E63","text":"#FFFFFF"}],"imagePlaceholderColors":["#4E342E","#B71C1C","#8D6E63"],"imageAspectRatios":[1.3,0.85],"imageColorOffset":1,"imagePositionSeed":4}
  },
  {
    slug: "unabomber-manifesto",
    title: "The Unabomber",
    description: "The terrorist caught by his own words",
    category: "Crime",
    thumbnail_color: "#33691E",
    body_text: `For seventeen years, a serial bomber terrorized universities and airlines across America. He killed three people and injured twenty-three more with homemade explosive devices. The FBI called him UNABOM, for university and airline bomber. The press called him the Unabomber. His identity remained unknown until his own brother turned him in. Ted Kaczynski was a former mathematics prodigy who had earned his PhD at twenty-five and joined the Berkeley faculty at twenty-six. In 1969, he abruptly resigned and withdrew from society, eventually settling in a primitive cabin in Montana with no electricity or running water. There, he began building bombs. His first device exploded at Northwestern University in 1978. Over the following years, packages arrived at universities and corporate offices, some detonating, some not. The bombs grew more sophisticated and more deadly. A computer store owner in Sacramento was killed in 1985. A geneticist lost several fingers. An advertising executive died in 1994. The FBI's investigation was the most expensive in the bureau's history, yet after a decade and a half they had no solid suspects. Then, in 1995, Kaczynski sent a 35,000-word manifesto to major newspapers, threatening more violence unless they published it. The Washington Post and New York Times complied. David Kaczynski, Ted's brother, read the manifesto and recognized the writing style and ideas. He contacted the FBI with his suspicions. Agents arrested Ted Kaczynski at his Montana cabin in April 1996. Inside, they found bomb-making materials, journals detailing his crimes, and a live explosive device ready for mailing. Kaczynski pleaded guilty to avoid the death penalty and was sentenced to life without parole. He died by suicide in a federal prison medical facility in June 2023. His manifesto, railing against technology and industrial society, continues to circulate online.`,
    design_config: {"thumbnailColor":"#33691E","titlePage":{"backgroundColor":"#33691E","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#33691E","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#33691E"},{"background":"#5D4037","text":"#FFFFFF"},{"background":"#C4B39A","text":"#000000"}],"imagePlaceholderColors":["#33691E","#5D4037","#C4B39A"],"imageAspectRatios":[1.4,0.9],"imageColorOffset":0,"imagePositionSeed":3}
  },
  {
    slug: "sinaloa-cartel-rise",
    title: "The Rise of El Chapo",
    description: "From poverty to the world's most wanted",
    category: "Crime",
    thumbnail_color: "#BF360C",
    body_text: `Joaquín Guzmán Loera was born into poverty in rural Sinaloa, Mexico, in a region where growing marijuana and opium was often the only path out of destitution. By his twenties, he had joined the drug trade. By his forties, he ran the largest trafficking organization in the world. They called him El Chapo—Shorty—for his five-foot-six frame. El Chapo transformed drug smuggling into an industrial operation. He pioneered the use of tunnels under the US-Mexico border, elaborate passages with rail systems, ventilation, and electricity. He diversified into cocaine, methamphetamine, and heroin. He corrupted government officials at every level, from local police to federal prosecutors. His organization, the Sinaloa Cartel, supplied an estimated quarter of all illegal drugs entering the United States. He was arrested in 1993 and escaped in 2001, reportedly in a laundry cart wheeled out by a prison guard. He was arrested again in 2014 and escaped again in 2015, this time through a mile-long tunnel dug to the shower floor of his cell. He was finally recaptured in 2016 after a shootout in his home state. The trial in New York was extraordinary. Witnesses described murders, bribery reaching the highest levels of Mexican government, and a criminal empire that generated billions of dollars annually. El Chapo's lawyers argued he was a scapegoat for the real cartel leaders. The jury didn't buy it. He was convicted on all counts and sentenced to life plus thirty years. He is currently held at the supermax prison in Florence, Colorado, in conditions designed to prevent any further escapes. The Sinaloa Cartel continues to operate, now under different leadership. The drug trade that made El Chapo rich shows no signs of slowing.`,
    design_config: {"thumbnailColor":"#BF360C","titlePage":{"backgroundColor":"#BF360C","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#BF360C","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#BF360C"},{"background":"#FFD60A","text":"#000000"},{"background":"#4A4A4A","text":"#FFFFFF"}],"imagePlaceholderColors":["#BF360C","#FFD60A","#4A4A4A"],"imageAspectRatios":[1.5,0.85],"imageColorOffset":1,"imagePositionSeed":2}
  },
  {
    slug: "boston-strangler",
    title: "The Boston Strangler",
    description: "The killer who confessed to everything",
    category: "Crime",
    thumbnail_color: "#1A237E",
    body_text: `Between June 1962 and January 1964, thirteen women were murdered in the Boston area. They were found in their apartments, sexually assaulted and strangled, often with stockings tied around their necks in a decorative bow. The killer left no fingerprints and no witnesses. He became known as the Boston Strangler. The city panicked. Women installed extra locks. Sales of guard dogs soared. Police received thousands of tips but made no arrests. Then, in late 1964, a man named Albert DeSalvo, in custody for a series of sexual assaults, confessed to all thirteen murders. DeSalvo was a strange character—charming and intelligent but deeply disturbed, with a long history of break-ins and assaults. He provided details about the murders that seemed to match the crime scenes. He described the apartments, the victims, the methods. Investigators were initially convinced. Then doubts emerged. DeSalvo was never charged with the Strangler murders. The evidence was circumstantial, and some details of his confessions didn't match the facts. Some investigators believed he was confessing to crimes committed by others to gain notoriety and possible profit from book deals. The victims' families were never certain. In 1973, DeSalvo was stabbed to death in prison by a fellow inmate. The motive was never established. For decades, the case remained officially unsolved. In 2013, DNA evidence finally linked DeSalvo to the last victim, a nineteen-year-old found murdered in January 1964. His body was exhumed and the match confirmed. Whether he committed all thirteen murders, or just some, or worked with accomplices, remains debated. The Boston Strangler may have been one man or several. We may never know the full truth.`,
    design_config: {"thumbnailColor":"#1A237E","titlePage":{"backgroundColor":"#1A237E","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#1A237E","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#1A237E"},{"background":"#B71C1C","text":"#FFFFFF"},{"background":"#4A4A4A","text":"#FFFFFF"}],"imagePlaceholderColors":["#1A237E","#B71C1C","#4A4A4A"],"imageAspectRatios":[1.3,0.9],"imageColorOffset":0,"imagePositionSeed":4}
  },
  {
    slug: "enron-scandal",
    title: "The Enron Scandal",
    description: "The company that fooled Wall Street",
    category: "Crime",
    thumbnail_color: "#006064",
    body_text: `At its peak, Enron was the seventh-largest company in America, worth $70 billion, praised by business magazines as the most innovative firm in the country. It was also a fraud. The company's profits were fictional, its balance sheets were lies, and its executives were stealing from investors, employees, and the public. Enron started as a natural gas pipeline company but transformed itself into an energy trading giant in the 1990s. CEO Jeffrey Skilling and founder Kenneth Lay promoted a culture of aggressive deal-making and creative accounting. They created thousands of offshore partnerships to hide debt and inflate profits. Auditors signed off. Wall Street analysts recommended the stock. Regulators looked the other way. The lies accumulated. When energy prices fell in 2001, the house of cards collapsed. Enron filed for bankruptcy in December, the largest in American history at that time. Investors lost billions. Twenty thousand employees lost their jobs and retirement savings, many of which had been invested in company stock. The scandal exposed the failures of the entire financial system. Arthur Andersen, one of the world's largest accounting firms, was destroyed by its role in the fraud. New regulations followed, including the Sarbanes-Oxley Act requiring stricter financial oversight. Executives went to prison. Andrew Fastow, the CFO who created the fraudulent partnerships, served six years. Jeffrey Skilling was sentenced to twenty-four years, later reduced. Kenneth Lay was convicted but died before sentencing. Enron became shorthand for corporate crime, the ultimate example of how greed and deception can masquerade as success until reality catches up.`,
    design_config: {"thumbnailColor":"#006064","titlePage":{"backgroundColor":"#006064","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#006064","text":"#FFFFFF"},{"background":"#FFD60A","text":"#000000"},{"background":"#FFFFFF","text":"#006064"},{"background":"#4A4A4A","text":"#FFFFFF"}],"imagePlaceholderColors":["#006064","#FFD60A","#4A4A4A"],"imageAspectRatios":[1.4,0.85],"imageColorOffset":1,"imagePositionSeed":3}
  },
  {
    slug: "central-park-five",
    title: "The Central Park Five",
    description: "The wrongful conviction that haunted a city",
    category: "Crime",
    thumbnail_color: "#2E7D32",
    body_text: `On April 19, 1989, a woman jogging through Central Park was brutally attacked, raped, and left for dead. She survived but had no memory of the assault. Within days, police arrested five Black and Latino teenagers, ages fourteen to sixteen, and announced they had confessed. The case seemed closed. It was anything but. The five boys—Antron McCray, Kevin Richardson, Yusef Salaam, Raymond Santana, and Korey Wise—were interrogated for hours without parents or lawyers present. They were exhausted, confused, and frightened. They gave videotaped confessions that contradicted each other and the physical evidence. All five recanted, saying they had been coerced. It didn't matter. The confessions were played at trial. The defendants were convicted and sentenced to terms ranging from five to fifteen years. They served their time and were released as convicted sex offenders, their futures destroyed. In 2002, a serial rapist named Matias Reyes confessed to the Central Park attack and provided details only the actual perpetrator could know. DNA evidence confirmed his guilt. He had committed the crime alone. The five convictions were vacated. The men sued the city and eventually received a $41 million settlement. But nothing could give them back their youth, their reputations, or the years they spent in prison for a crime they didn't commit. The case became a landmark in the study of false confessions and wrongful convictions. It exposed how easily innocent people could be pressured into incriminating themselves, how racial bias could influence investigations, and how the justice system could fail the most vulnerable. The Central Park Five are now the Exonerated Five, but the scars remain.`,
    design_config: {"thumbnailColor":"#2E7D32","titlePage":{"backgroundColor":"#2E7D32","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#2E7D32","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#2E7D32"},{"background":"#FFD60A","text":"#000000"},{"background":"#4A4A4A","text":"#FFFFFF"}],"imagePlaceholderColors":["#2E7D32","#FFD60A","#4A4A4A"],"imageAspectRatios":[1.4,0.9],"imageColorOffset":0,"imagePositionSeed":2}
  },
  {
    slug: "tylenol-murders",
    title: "The Tylenol Murders",
    description: "The poisonings that changed packaging forever",
    category: "Crime",
    thumbnail_color: "#C62828",
    body_text: `In late September 1982, seven people in the Chicago area died after taking Tylenol capsules laced with potassium cyanide. The victims ranged in age from twelve to thirty-five. They had no connection to each other except that they had all taken the same over-the-counter pain reliever. Within days, police realized they were dealing with something unprecedented. Someone had purchased Tylenol from local stores, replaced capsules with poison, and returned the contaminated bottles to shelves. The randomness was terrifying. Anyone who had recently bought Tylenol could be at risk. Johnson & Johnson, Tylenol's manufacturer, responded with a massive recall, pulling 31 million bottles from stores at a cost of over $100 million. They established a toll-free hotline and offered exchanges for any Tylenol products. It was the first major product recall in American history. The killer was never caught. The FBI investigated thousands of leads and interviewed hundreds of suspects. One man, James William Lewis, was convicted of extortion after sending a letter demanding $1 million to stop the poisonings, but there was never enough evidence to charge him with murder. The case remains open. The lasting impact was on consumer protection. Within months, Congress passed laws requiring tamper-evident packaging. The triple-sealed bottles and safety caps that are now standard on medications, cosmetics, and food products all trace back to the Tylenol murders. Johnson & Johnson's transparent crisis response became a model for corporate communication. The killer changed how America buys medicine. The price was seven innocent lives.`,
    design_config: {"thumbnailColor":"#C62828","titlePage":{"backgroundColor":"#C62828","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#C62828","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#C62828"},{"background":"#1A237E","text":"#FFFFFF"},{"background":"#E8E8E8","text":"#000000"}],"imagePlaceholderColors":["#C62828","#1A237E","#E8E8E8"],"imageAspectRatios":[1.3,0.85],"imageColorOffset":1,"imagePositionSeed":4}
  },
  {
    slug: "nightstalker-reign",
    title: "The Night Stalker",
    description: "The serial killer who terrorized California",
    category: "Crime",
    thumbnail_color: "#1A1A1A",
    body_text: `During the summer of 1985, residents of Los Angeles and San Francisco lived in fear. A serial killer was entering homes through unlocked doors and windows, attacking the people he found inside. He raped, tortured, and murdered seemingly at random. He left survivors who described a tall, thin man with rotting teeth and a pentagram drawn on his palm. The press called him the Night Stalker. Richard Ramirez was a twenty-five-year-old drifter from Texas who had come to California with nothing but a taste for violence. He had no pattern to his crimes that police could predict. His victims were old and young, male and female, in wealthy neighborhoods and poor ones. He used guns, knives, hammers, and his bare hands. The only common element was opportunity. Ramirez's downfall was a fingerprint. In August 1985, police matched a print from a stolen car to Ramirez's record. His photograph was released to the media. The next day, Ramirez walked into a convenience store in East Los Angeles and saw his face on the front page of every newspaper. He ran. A crowd of local residents chased him through the neighborhood, beating him until police arrived. The trial lasted four years, the longest in California history at that time. Ramirez was convicted of thirteen murders and dozens of other crimes. He was sentenced to death. He spent twenty-three years on death row, receiving fan mail and even marrying a woman who had become obsessed with his case. In 2013, Ramirez died of lymphoma in a prison hospital. He was fifty-three years old. His crimes had changed how Californians thought about safety. Locked windows and doors became standard. The Night Stalker had proved that monsters could walk through any neighborhood.`,
    design_config: {"thumbnailColor":"#1A1A1A","titlePage":{"backgroundColor":"#1A1A1A","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#1A1A1A","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#1A1A1A"},{"background":"#B71C1C","text":"#FFFFFF"},{"background":"#4A4A4A","text":"#FFFFFF"}],"imagePlaceholderColors":["#1A1A1A","#B71C1C","#4A4A4A"],"imageAspectRatios":[1.4,0.85],"imageColorOffset":0,"imagePositionSeed":3}
  },
  {
    slug: "north-hollywood-shootout",
    title: "The North Hollywood Shootout",
    description: "The bank robbery that outgunned the police",
    category: "Crime",
    thumbnail_color: "#455A64",
    body_text: `On February 28, 1997, two heavily armed men attempted to rob a Bank of America branch in North Hollywood, California. They were wearing homemade body armor, carrying fully automatic rifles, and carrying enough ammunition to fight a small war. When police arrived, the robbers didn't run. They opened fire. For forty-four minutes, Larry Phillips Jr. and Emil Mătăsăreanu fought a running gun battle with the Los Angeles Police Department. Their body armor stopped round after round from police handguns. The officers were outgunned, their weapons ineffective against the armored assailants. Desperate cops ran to nearby gun stores to borrow more powerful weapons. The shootout was broadcast live on television. Viewers watched as the two men walked calmly through the parking lot, firing at officers and patrol cars, seemingly invincible. Phillips took a shot that disabled his hand, making it difficult to use his weapon. He was eventually killed by a shot to the head. Mătăsăreanu, wounded dozens of times, bled out in the street after surrendering. Twelve police officers and eight civilians were wounded. Both robbers were killed. No hostages died, though several bank employees were injured. The impact on law enforcement was immediate. Within weeks, police departments across America began equipping patrol officers with rifles and heavier ammunition. The military-style equipment that has become common in American policing traces directly to North Hollywood. The shootout proved that ordinary criminals could outgun ordinary police, and departments responded by upgrading their firepower. The men had acquired their weapons legally under California law at the time. New restrictions followed. The battle that played out on live television changed American policing and gun policy in ways still felt today.`,
    design_config: {"thumbnailColor":"#455A64","titlePage":{"backgroundColor":"#455A64","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#455A64","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#455A64"},{"background":"#B71C1C","text":"#FFFFFF"},{"background":"#FFD60A","text":"#000000"}],"imagePlaceholderColors":["#455A64","#B71C1C","#FFD60A"],"imageAspectRatios":[1.6,0.9],"imageColorOffset":1,"imagePositionSeed":2}
  },
  {
    slug: "john-gotti-teflon-don",
    title: "The Teflon Don",
    description: "The mob boss who couldn't be convicted",
    category: "Crime",
    thumbnail_color: "#37474F",
    body_text: `John Gotti was the last great mob boss in America, a flashy don who ran the Gambino crime family from a social club in Queens while prosecutors tried and failed to convict him. He beat three major cases in a row, earning the nickname "the Teflon Don" because nothing stuck. His luck ran out in 1992. Gotti had risen through the ranks the old-fashioned way, starting as a street enforcer and working up to running one of the Five Families that controlled organized crime in New York. In 1985, he engineered the murder of Paul Castellano, the family boss, and took over the organization. It was the last successful coup in American Mafia history. Unlike the secretive bosses who came before him, Gotti courted attention. He wore expensive suits, spoke to reporters outside his social club, and cultivated a public image as a neighborhood hero. The media loved him. Prosecutors were frustrated. The first three trials ended in acquittals, largely because Gotti bribed or intimidated jurors. His lawyer, Bruce Cutler, was brilliant at creating reasonable doubt. The FBI had Gotti on tape discussing crimes, but they couldn't get convictions. Then Sammy "the Bull" Gravano turned. Gotti's underboss, facing murder charges himself, agreed to testify against his former boss. His testimony, combined with surveillance recordings from an apartment above Gotti's social club, was devastating. In 1992, Gotti was convicted on thirteen counts including murder and sentenced to life without parole. He died in prison in 2002 from throat cancer. The Gambino family never recovered its former power. The era of the celebrity mob boss was over, killed by the same publicity that had made Gotti famous.`,
    design_config: {"thumbnailColor":"#37474F","titlePage":{"backgroundColor":"#37474F","textColor":"#FFD60A"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#37474F","text":"#FFFFFF"},{"background":"#FFD60A","text":"#000000"},{"background":"#FFFFFF","text":"#37474F"},{"background":"#4A4A4A","text":"#FFFFFF"}],"imagePlaceholderColors":["#37474F","#FFD60A","#4A4A4A"],"imageAspectRatios":[1.4,0.85],"imageColorOffset":0,"imagePositionSeed":4}
  },
  {
    slug: "oj-simpson-trial",
    title: "The O.J. Simpson Trial",
    description: "The case that divided America",
    category: "Crime",
    thumbnail_color: "#5D4037",
    body_text: `On June 17, 1994, ninety-five million Americans watched a white Ford Bronco cruise down a Los Angeles freeway. Inside was O.J. Simpson, the former football star, holding a gun to his own head while his friend Al Cowlings drove and police followed. Simpson had been charged with murdering his ex-wife Nicole Brown Simpson and her friend Ron Goldman. Instead of surrendering, he had fled. The slow-speed chase ended peacefully at Simpson's mansion, but the spectacle set the tone for what would become the most watched trial in American history. Simpson had been one of the most beloved athletes in America, a charming pitchman who had crossed over from sports to movies. The idea that he could brutally murder two people seemed impossible to many fans. The evidence, however, was overwhelming: blood at the scene, a bloody glove found at his property, DNA matching all three individuals. The trial lasted over a year. Every moment was televised. The prosecution stumbled when Simpson tried on the bloody glove in court and it appeared too small. Defense attorney Johnnie Cochran built a narrative around racist police officers and planted evidence, telling the jury, "If it doesn't fit, you must acquit." On October 3, 1995, the jury returned a verdict of not guilty after less than four hours of deliberation. Polls showed the country divided starkly along racial lines, with Black Americans largely celebrating and white Americans largely outraged. The trial became a referendum on race, celebrity, and justice in America. The families later won a civil judgment against Simpson for wrongful death, but he never paid. Simpson was eventually imprisoned for an unrelated robbery in 2008 and released in 2017. The murders of Nicole Brown Simpson and Ron Goldman remain officially unsolved.`,
    design_config: {"thumbnailColor":"#5D4037","titlePage":{"backgroundColor":"#5D4037","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#5D4037","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#5D4037"},{"background":"#B71C1C","text":"#FFFFFF"},{"background":"#C4B39A","text":"#000000"}],"imagePlaceholderColors":["#5D4037","#B71C1C","#C4B39A"],"imageAspectRatios":[1.5,0.9],"imageColorOffset":1,"imagePositionSeed":3}
  },
  {
    slug: "silk-road-trial",
    title: "The Silk Road Trial",
    description: "The dark web marketplace that changed crime",
    category: "Crime",
    thumbnail_color: "#1B5E20",
    body_text: `In 2011, a website launched that would transform illegal commerce. The Silk Road was an online marketplace where users could buy and sell drugs, fake documents, and hacking tools using Bitcoin, all hidden behind layers of encryption. Its founder called himself the Dread Pirate Roberts. His real name was Ross Ulbricht. Ulbricht was a young libertarian with a physics degree and big ideas about free markets. He believed drug prohibition was wrong and that people should be able to buy whatever substances they wanted without government interference. The Silk Road was his attempt to prove it could work. And for a while, it did. At its peak, the site had over 100,000 users and was generating millions of dollars in monthly sales. Vendors shipped drugs through the regular mail, packaged to avoid detection. Bitcoin provided anonymity that cash could not. Buyers left reviews like they were shopping on Amazon. The FBI spent two years tracking the Dread Pirate Roberts. The breakthrough came through old-fashioned detective work: they traced a post Ulbricht had made under his real name years earlier, advertising the site before it launched. In October 2013, agents arrested Ulbricht at a San Francisco public library, catching him logged into the Silk Road's administrative systems. The trial revealed that Ulbricht had allegedly commissioned murders to protect his operation, though no bodies were ever found. He was convicted on all counts and sentenced to life without parole. The sentence was widely criticized as excessive for what was essentially a sophisticated drug-dealing website. The Silk Road was shut down, but copycat sites emerged immediately. The dark web drug trade continues, now larger than ever. Ulbricht created a template for anonymous online crime that governments still struggle to combat.`,
    design_config: {"thumbnailColor":"#1B5E20","titlePage":{"backgroundColor":"#1B5E20","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#1B5E20","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#1B5E20"},{"background":"#FFD60A","text":"#000000"},{"background":"#4A4A4A","text":"#FFFFFF"}],"imagePlaceholderColors":["#1B5E20","#FFD60A","#4A4A4A"],"imageAspectRatios":[1.4,0.85],"imageColorOffset":0,"imagePositionSeed":2}
  },
  {
    slug: "martha-stewart-prison",
    title: "Martha Stewart Goes to Prison",
    description: "The homemaking queen behind bars",
    category: "Crime",
    thumbnail_color: "#7CB342",
    body_text: `Martha Stewart built an empire on domestic perfection. Her magazines, television shows, and product lines taught millions of Americans how to cook, decorate, and entertain with style. Then she went to prison for lying to federal investigators about a stock sale. In December 2001, Stewart sold nearly 4,000 shares of ImClone Systems stock, just one day before the FDA announced it was rejecting the company's new cancer drug. The timing was suspicious. Stewart claimed she had a pre-existing agreement to sell if the stock dropped below $60. Prosecutors didn't buy it. The charges weren't for insider trading itself—that proved difficult to establish—but for lying to investigators, conspiracy, and obstruction of justice. Stewart had altered documents and made false statements to cover up what had been a relatively small financial transaction. The cover-up, as so often happens, was worse than the crime. The trial was a media circus. Stewart's lawyers argued she was being singled out because of her fame. Prosecutors countered that she had knowingly obstructed justice and couldn't buy her way out of consequences. The jury convicted her on all counts. Stewart was sentenced to five months in federal prison, five months of home confinement, and two years of supervised release. She served her time at a minimum-security camp in West Virginia, reportedly teaching yoga and crafts to fellow inmates. Her company's stock initially plummeted but recovered after her release. Stewart rebuilt her brand with surprising success. She returned to television, launched new product lines, and became something of a folk hero—the domestic goddess who had survived the federal prison system with her dignity intact. The scandal that was supposed to destroy her became just another chapter in an improbable American success story.`,
    design_config: {"thumbnailColor":"#7CB342","titlePage":{"backgroundColor":"#7CB342","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#7CB342","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#7CB342"},{"background":"#FFD60A","text":"#000000"},{"background":"#E8E8E8","text":"#000000"}],"imagePlaceholderColors":["#7CB342","#FFD60A","#E8E8E8"],"imageAspectRatios":[1.3,0.9],"imageColorOffset":1,"imagePositionSeed":4}
  }
];

async function uploadStory(story) {
  const response = await fetch(`${SUPABASE_URL}/rest/v1/stories`, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      "apikey": SUPABASE_KEY,
      "Authorization": `Bearer ${SUPABASE_KEY}`,
      "Prefer": "resolution=merge-duplicates,return=minimal"
    },
    body: JSON.stringify({
      slug: story.slug,
      title: story.title,
      description: story.description,
      category: story.category,
      thumbnail_color: story.thumbnail_color,
      published: true,
      published_at: new Date().toISOString(),
      body_text: story.body_text,
      design_config: story.design_config,
      updated_at: new Date().toISOString()
    })
  });

  if (!response.ok) {
    const text = await response.text();
    throw new Error(`${response.status}: ${text}`);
  }
}

async function main() {
  console.log(`Uploading ${stories.length} Crime stories to Supabase...\n`);

  let success = 0;
  let failed = 0;

  for (const story of stories) {
    try {
      process.stdout.write(`Uploading: ${story.title}... `);
      await uploadStory(story);
      console.log("Done!");
      success++;
    } catch (error) {
      console.log(`Error: ${error.message}`);
      failed++;
    }
  }

  console.log(`\nComplete! ${success} succeeded, ${failed} failed.`);
}

main();
