/**
 * Economics Category - 25 New Stories
 * Usage: node scripts/new-content/economics-new.mjs
 */

const SUPABASE_URL = "https://egfwisgqdyhzpmeoracb.supabase.co";
const SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVnZndpc2dxZHloenBtZW9yYWNiIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2ODQyNzM0OSwiZXhwIjoyMDg0MDAzMzQ5fQ.S8h1fIepxWb44gPSPpWQ8fE0Q-SCYfL0QcBRUV7fXgs";

const stories = [
  {
    slug: "black-monday-1987",
    title: "Black Monday",
    description: "The day the market lost 22% in hours",
    category: "Economics",
    thumbnail_color: "#212121",
    body_text: `On October 19, 1987, the Dow Jones Industrial Average dropped 508 points, a loss of 22.6 percent in a single trading session. It remains the largest percentage decline in Wall Street history. No one saw it coming. No one could explain it afterward. The crash began in Asian markets overnight and spread westward as trading opened in Europe, then New York. Within the first hour, the Dow had dropped over 200 points. Sell orders overwhelmed the system. Trading desks couldn't keep up. Prices fell so fast that many traders didn't know what their portfolios were worth. The computerized trading systems that had become common in the 1980s amplified the panic. Portfolio insurance, a strategy designed to limit losses, instead accelerated them by automatically selling stocks as prices dropped. The selling triggered more selling in a spiral that seemed unstoppable. By midday, rumors spread that the stock exchange would close. Banks stopped extending credit. The entire financial system seemed on the verge of collapse. Then, around 12:30 PM, a group of major companies announced they would buy back their own stock. The Federal Reserve issued a statement promising to provide liquidity. Slowly, buyers returned. The bleeding stopped. The market never recovered its losses that day, but it didn't get worse. The aftermath was remarkably mild. Unlike the 1929 crash, Black Monday didn't trigger a depression. The economy continued growing. Markets recovered within two years. Regulators implemented circuit breakers to pause trading during extreme drops. The crash became a lesson in market psychology—prices could move faster and further than anyone thought possible, driven by fear and automated systems. The next generation of traders would learn the lesson again.`,
    design_config: {"thumbnailColor":"#212121","titlePage":{"backgroundColor":"#212121","textColor":"#B71C1C"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#212121","text":"#FFFFFF"},{"background":"#B71C1C","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#212121"},{"background":"#4A4A4A","text":"#FFFFFF"}],"imagePlaceholderColors":["#212121","#B71C1C","#4A4A4A"],"imageAspectRatios":[1.4,0.85],"imageColorOffset":0,"imagePositionSeed":2}
  },
  {
    slug: "2008-financial-crisis",
    title: "The 2008 Crash",
    description: "When the banks almost collapsed",
    category: "Economics",
    thumbnail_color: "#1565C0",
    body_text: `In September 2008, the global financial system came within hours of complete collapse. Lehman Brothers, a 158-year-old investment bank, filed for bankruptcy. Credit markets froze. Stock prices plummeted. The United States government scrambled to prevent a second Great Depression. The crisis had been building for years. Banks had created complex financial instruments tied to mortgages, packaging risky loans as safe investments. Rating agencies blessed the products with their highest grades. When the housing market began to decline, the entire edifice crumbled. Those "safe" investments turned out to be toxic. In a single week in September, the impossible kept happening. Lehman Brothers went under. Merrill Lynch sold itself in an emergency deal. The insurance giant AIG required a government bailout of $85 billion. The two largest mortgage companies, Fannie Mae and Freddie Mac, were seized by the federal government. Treasury Secretary Hank Paulson and Federal Reserve Chairman Ben Bernanke told congressional leaders that without immediate action, the entire banking system would fail. They requested $700 billion in emergency funding. Congress initially rejected the plan, sending the Dow plummeting over 700 points. A revised bill passed days later. The bailouts worked in the narrow sense that the banking system survived. But the economic damage was catastrophic. Eight million Americans lost their jobs. Four million families lost their homes to foreclosure. The recovery took nearly a decade. Anger at the bailouts fueled political movements on both left and right. Not a single major banking executive went to prison. The crisis revealed how interconnected global finance had become, and how little regulators understood the risks. It also revealed who would bear the costs when the system failed: ordinary people, not the executives who created the disaster.`,
    design_config: {"thumbnailColor":"#1565C0","titlePage":{"backgroundColor":"#1565C0","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#1565C0","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#1565C0"},{"background":"#B71C1C","text":"#FFFFFF"},{"background":"#FFD60A","text":"#000000"}],"imagePlaceholderColors":["#1565C0","#B71C1C","#FFD60A"],"imageAspectRatios":[1.5,0.9],"imageColorOffset":1,"imagePositionSeed":3}
  },
  {
    slug: "hyperinflation-weimar",
    title: "The Weimar Hyperinflation",
    description: "When money became worthless",
    category: "Economics",
    thumbnail_color: "#5D4037",
    body_text: `In 1923, a loaf of bread in Germany cost 200 billion marks. Workers were paid twice a day so they could spend their money before it lost value. Children played with stacks of worthless currency. The Weimar Republic had experienced the most extreme hyperinflation in modern history. The crisis began with the Treaty of Versailles. Germany was required to pay enormous reparations for World War I in gold and foreign currency, which it didn't have. The government printed money to buy the currency it needed, flooding the economy with marks that grew less valuable by the day. By 1922, inflation was already severe. By January 1923, it was catastrophic. The occupation of the Ruhr by French and Belgian troops, intended to extract reparations by force, triggered a government policy of passive resistance that shut down production while workers continued to be paid with printed money. Prices doubled every few days. People rushed to spend cash before it lost value, which drove prices higher still. Restaurants stopped posting prices because they changed too quickly. Savings accumulated over lifetimes evaporated overnight. Pensioners who had been comfortable became destitute. The middle class was destroyed. The psychological impact exceeded the economic damage. Germans who had worked hard, saved carefully, and trusted their institutions found themselves betrayed by forces they couldn't understand. The trauma created fertile ground for extremism. The Nazi Party, marginal before the hyperinflation, gained its first significant following among the dispossessed middle class. The crisis was eventually resolved through currency reform and international intervention. The new Rentenmark replaced the old currency at a rate of one trillion to one. Stability returned, but trust in institutions did not. A decade later, Hitler came to power.`,
    design_config: {"thumbnailColor":"#5D4037","titlePage":{"backgroundColor":"#5D4037","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#5D4037","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#5D4037"},{"background":"#FFD60A","text":"#000000"},{"background":"#8D6E63","text":"#FFFFFF"}],"imagePlaceholderColors":["#5D4037","#FFD60A","#8D6E63"],"imageAspectRatios":[1.4,0.85],"imageColorOffset":0,"imagePositionSeed":2}
  },
  {
    slug: "british-railway-collapse",
    title: "The British Rail Collapse",
    description: "When privatization went wrong",
    category: "Economics",
    thumbnail_color: "#37474F",
    body_text: `When Britain privatized its railway system in the 1990s, it was supposed to create competition, efficiency, and better service. Instead, it created a fragmented network that struggled to function and collapsed into scandal after scandal. The privatization was ideologically driven and poorly designed. Track infrastructure was separated from train operations. Multiple private companies competed for franchises to run services on different routes. Maintenance was outsourced to contractors who were themselves subcontractors of subcontractors. The result was a system where no one was clearly responsible for anything. Railtrack, the company that owned the infrastructure, prioritized profits over maintenance. Corners were cut. Inspections were reduced. Warning signs were ignored. Then the accidents began. In 1999, thirty-one people died when two trains collided at Ladbroke Grove. Investigation revealed systematic failures in signaling and safety culture. In 2000, four people died when a train derailed at Hatfield due to a cracked rail that had been identified but not repaired. After Hatfield, Railtrack panicked and imposed hundreds of speed restrictions across the network. The railway effectively stopped functioning. Journey times doubled. The economy lost billions. Public outrage forced the government to act. Railtrack was effectively nationalized in 2002, its shareholders compensated but its management disgraced. The company that replaced it operated as a nonprofit, returning infrastructure maintenance to public control. But the franchise system continued, creating perverse incentives and chronic underinvestment. Today, Britain's railways remain among the most expensive and least reliable in Europe. The dream of efficient private-sector management has become a cautionary tale of what happens when market ideology meets public services.`,
    design_config: {"thumbnailColor":"#37474F","titlePage":{"backgroundColor":"#37474F","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#37474F","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#37474F"},{"background":"#B71C1C","text":"#FFFFFF"},{"background":"#4A4A4A","text":"#FFFFFF"}],"imagePlaceholderColors":["#37474F","#B71C1C","#4A4A4A"],"imageAspectRatios":[1.5,0.9],"imageColorOffset":1,"imagePositionSeed":4}
  },
  {
    slug: "argentina-default-2001",
    title: "Argentina's Default",
    description: "When a nation went bankrupt",
    category: "Economics",
    thumbnail_color: "#00BCD4",
    body_text: `On December 23, 2001, Argentina defaulted on $100 billion in debt, the largest sovereign default in history. Within days, the president had resigned, rioters had taken to the streets, and the country had begun the most severe economic collapse of any democracy since the Great Depression. The crisis had deep roots. In 1991, Argentina had pegged its peso to the US dollar, promising that one peso would always equal one dollar. The policy initially brought stability after years of hyperinflation. Foreign investment poured in. The economy boomed. But the peg came with a cost. Argentina couldn't devalue its currency to make exports competitive. It couldn't print money to stimulate growth. When the US dollar strengthened in the late 1990s, Argentina's economy ground to a halt while its debts, denominated in dollars, became impossible to service. The IMF provided bailouts with strings attached: austerity, spending cuts, tax increases. Each round of cuts deepened the recession and shrank the tax base, requiring more cuts. It was a death spiral. By late 2001, Argentines had lost faith in their banks. A run began. The government froze bank accounts, preventing people from withdrawing their own savings. The middle class, seeing their life savings trapped, exploded in rage. Riots erupted across Buenos Aires. Twenty-five people were killed. The president fled in a helicopter. The country went through five presidents in two weeks. The default and devaluation that followed were catastrophic in the short term but allowed recovery to begin. Argentina eventually restructured its debts, paying creditors roughly thirty cents on the dollar. The IMF's austerity prescriptions were widely criticized. The crisis became a symbol of what happens when orthodox economics meets political reality.`,
    design_config: {"thumbnailColor":"#00BCD4","titlePage":{"backgroundColor":"#00BCD4","textColor":"#000000"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#00BCD4","text":"#000000"},{"background":"#FFFFFF","text":"#00BCD4"},{"background":"#FFD60A","text":"#000000"},{"background":"#1A237E","text":"#FFFFFF"}],"imagePlaceholderColors":["#00BCD4","#FFD60A","#1A237E"],"imageAspectRatios":[1.4,0.85],"imageColorOffset":0,"imagePositionSeed":3}
  },
  {
    slug: "enron-collapse",
    title: "Enron's Implosion",
    description: "The corporate fraud that shocked America",
    category: "Economics",
    thumbnail_color: "#006064",
    body_text: `Enron was supposed to be the future of American business. Innovative. Aggressive. Worth $70 billion at its peak. Then it vanished in the largest bankruptcy in American history, exposed as a fraud built on deception and accounting tricks. The company started as a natural gas pipeline operator and transformed itself into an energy trading powerhouse. CEO Jeffrey Skilling preached the gospel of deregulation and mark-to-market accounting, which allowed the company to book projected future profits as current earnings. Revenue that might take years to materialize appeared immediately on the balance sheet. The numbers looked spectacular. Behind them was chaos. Enron created thousands of offshore partnerships to hide debt and inflate profits. CFO Andrew Fastow designed structures so complex that auditors couldn't understand them. The company was essentially a Ponzi scheme in business casual. Warnings emerged. A Fortune reporter questioned how exactly Enron made its money. An internal analyst sent a memo warning of accounting fraud. But the stock price kept rising. The board kept approving. The auditors at Arthur Andersen kept signing off. The collapse came quickly. In October 2001, Enron disclosed a $618 million quarterly loss and revealed that partnerships run by Fastow had cost the company over a billion dollars. The stock, which had traded above $90 a year earlier, plummeted. In December, Enron filed for bankruptcy. Twenty thousand employees lost their jobs. Many lost their retirement savings, which had been invested in company stock. Arthur Andersen, one of the world's largest accounting firms, was destroyed by its role in the scandal. Executives went to prison. Kenneth Lay was convicted but died before sentencing. Jeffrey Skilling served fourteen years. Enron's name became synonymous with corporate greed and fraud.`,
    design_config: {"thumbnailColor":"#006064","titlePage":{"backgroundColor":"#006064","textColor":"#FFD60A"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#006064","text":"#FFFFFF"},{"background":"#FFD60A","text":"#000000"},{"background":"#FFFFFF","text":"#006064"},{"background":"#4A4A4A","text":"#FFFFFF"}],"imagePlaceholderColors":["#006064","#FFD60A","#4A4A4A"],"imageAspectRatios":[1.5,0.9],"imageColorOffset":1,"imagePositionSeed":2}
  },
  {
    slug: "long-term-capital-collapse",
    title: "When Geniuses Failed",
    description: "The hedge fund that almost crashed the world",
    category: "Economics",
    thumbnail_color: "#1A237E",
    body_text: `Long-Term Capital Management was the smartest hedge fund in the world. Its founders included two Nobel Prize winners in economics and some of the most brilliant minds on Wall Street. Their mathematical models were supposed to eliminate risk. In 1998, they nearly destroyed the global financial system. LTCM was founded in 1994 by John Meriwether, a legendary bond trader, and staffed with academics who had revolutionized financial theory. Their strategy was to find small pricing inefficiencies in bond markets and exploit them with massive leverage. The bets were tiny—fractions of a percent—but multiplied by billions of dollars in borrowed money, they generated enormous returns. For four years, the fund delivered consistent annual returns above 40 percent. Investors, including major banks and wealthy individuals, poured money in. LTCM became one of the largest hedge funds in the world, controlling positions worth over $1 trillion. Then Russia defaulted on its debt. The models hadn't accounted for the possibility that investors would panic and sell everything. Prices moved in directions the formulas said were impossible. LTCM lost $4.6 billion in less than four months. Its positions were so large and so interconnected with the rest of the financial system that its collapse threatened to bring down major banks. The Federal Reserve convened an emergency meeting with the heads of Wall Street's biggest firms. They were told that if LTCM failed, the resulting panic could freeze global credit markets. Reluctantly, they agreed to a $3.6 billion bailout that gave them control of the fund. LTCM was wound down over the following years. Its investors lost nearly everything. But the financial system survived. The lesson—that mathematical models can't capture rare, catastrophic events—was promptly forgotten. A decade later, similar overconfidence in quantitative models would contribute to the 2008 financial crisis.`,
    design_config: {"thumbnailColor":"#1A237E","titlePage":{"backgroundColor":"#1A237E","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#1A237E","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#1A237E"},{"background":"#FFD60A","text":"#000000"},{"background":"#4A4A4A","text":"#FFFFFF"}],"imagePlaceholderColors":["#1A237E","#FFD60A","#4A4A4A"],"imageAspectRatios":[1.4,0.85],"imageColorOffset":0,"imagePositionSeed":4}
  },
  {
    slug: "japan-lost-decades",
    title: "Japan's Lost Decades",
    description: "The bubble that still hasn't healed",
    category: "Economics",
    thumbnail_color: "#C62828",
    body_text: `In 1989, the Imperial Palace grounds in Tokyo were theoretically worth more than all the real estate in California. Japanese stocks had risen so high that the Nikkei index reached nearly 39,000. Everyone knew it couldn't last. Almost no one sold. The Japanese economic bubble of the 1980s was fueled by easy money and collective denial. Banks lent against overvalued real estate, which drove prices higher, which justified more lending. Companies borrowed to speculate rather than invest. The government, fearing that any intervention would cause the very crash it sought to prevent, did nothing. On December 29, 1989, the Nikkei peaked. The next day, it began a decline that would continue for over a decade. Real estate followed. Companies that had seemed invincible collapsed. Banks, their balance sheets stuffed with worthless loans, stopped lending. The economy froze. Japan had been expected to overtake the United States as the world's largest economy. Instead, it entered a period of stagnation that continues to this day. The Nikkei wouldn't return to its 1989 high until 2024. Property prices in Tokyo remain below their peak. An entire generation of Japanese workers came of age in an economy that couldn't provide the opportunities their parents had taken for granted. The government tried everything: interest rates at zero, massive public spending, quantitative easing. Nothing worked. Japan became a laboratory for economic policy experiments, many of which were later adopted by Western nations after the 2008 crisis. Economists still debate what went wrong and what should have been done differently. The lost decades demonstrated that even the most successful economies can become trapped, that bubbles can have consequences lasting far longer than anyone expects.`,
    design_config: {"thumbnailColor":"#C62828","titlePage":{"backgroundColor":"#C62828","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#C62828","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#C62828"},{"background":"#FFD60A","text":"#000000"},{"background":"#4A4A4A","text":"#FFFFFF"}],"imagePlaceholderColors":["#C62828","#FFD60A","#4A4A4A"],"imageAspectRatios":[1.5,0.9],"imageColorOffset":1,"imagePositionSeed":3}
  },
  {
    slug: "venezuela-collapse",
    title: "Venezuela's Collapse",
    description: "How an oil giant went broke",
    category: "Economics",
    thumbnail_color: "#BF360C",
    body_text: `Venezuela has the largest proven oil reserves in the world, more than Saudi Arabia. In 2014, a barrel of Venezuelan oil sold for over $100. By 2020, the country's economy had shrunk by 75 percent, inflation exceeded one million percent annually, and millions of Venezuelans had fled the country. The collapse was man-made. Hugo Chávez, who ruled from 1999 until his death in 2013, used oil revenues to fund massive social spending. When oil prices were high, the system worked. Poverty declined. The poor gained access to healthcare and education. Chávez was genuinely popular. But the model depended on ever-increasing oil prices and ever-expanding government control. The oil industry was nationalized and staffed with political loyalists rather than technical experts. Production began declining even before prices crashed. Price controls and currency manipulation created shortages. When oil prices collapsed in 2014, the house of cards fell. Nicolás Maduro, Chávez's chosen successor, responded to the crisis by printing money and tightening authoritarian control. Inflation spiraled. The currency became worthless. Store shelves emptied. Hospitals ran out of medicine. By 2019, an estimated 4.5 million Venezuelans had left the country, one of the largest refugee crises in Latin American history. The middle class disappeared. Those who remained faced daily struggles for food, water, and electricity. The country with more oil than anywhere on Earth couldn't keep the lights on. International sanctions and political isolation have made recovery nearly impossible. Multiple governments have recognized opposition leaders as legitimate while Maduro retains actual power. Venezuela has become a cautionary tale about the resource curse, political mismanagement, and the fragility of economies built on a single commodity.`,
    design_config: {"thumbnailColor":"#BF360C","titlePage":{"backgroundColor":"#BF360C","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#BF360C","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#BF360C"},{"background":"#FFD60A","text":"#000000"},{"background":"#4A4A4A","text":"#FFFFFF"}],"imagePlaceholderColors":["#BF360C","#FFD60A","#4A4A4A"],"imageAspectRatios":[1.4,0.85],"imageColorOffset":0,"imagePositionSeed":2}
  },
  {
    slug: "crypto-winter-2022",
    title: "The Crypto Collapse",
    description: "When digital fortunes vanished",
    category: "Economics",
    thumbnail_color: "#FF9800",
    body_text: `In November 2021, the total value of all cryptocurrencies exceeded $3 trillion. Bitcoin was trading above $65,000. Celebrities and athletes promoted digital coins. Venture capitalists poured billions into crypto startups. It felt like the future of money had arrived. A year later, two-thirds of that value had evaporated. Bitcoin traded below $17,000. Major exchanges had collapsed. Sam Bankman-Fried, the wunderkind who ran FTX, was under arrest for fraud. The crypto winter had arrived. The collapse began with the implosion of Terra, a cryptocurrency that was supposed to maintain a stable value through algorithmic magic. When Terra failed in May 2022, it wiped out $60 billion and triggered a cascade of failures across the crypto ecosystem. Hedge funds that had bet on Terra couldn't meet their obligations. Lenders who had provided them credit went bankrupt. The contagion spread. The FTX collapse in November was the killing blow. Bankman-Fried had been presented as the responsible face of crypto, a young billionaire who slept on a beanbag chair and donated millions to charity. In reality, he had been using customer deposits to fund risky bets at his trading firm. When customers tried to withdraw their money, it wasn't there. The fraud was astonishingly blatant. Billions of dollars in customer funds had vanished. FTX's balance sheet showed $9 billion in liabilities and $900 million in assets. Bankman-Fried was arrested in the Bahamas and extradited to face charges in New York. He was convicted on all counts in November 2023. The crypto industry that remains is smaller, more cautious, and more regulated. The dream of decentralized finance replacing traditional banking seems further away than ever. But true believers insist the next boom is just around the corner.`,
    design_config: {"thumbnailColor":"#FF9800","titlePage":{"backgroundColor":"#FF9800","textColor":"#000000"},"colorPalette":[{"background":"#000000","text":"#FF9800"},{"background":"#FF9800","text":"#000000"},{"background":"#FFFFFF","text":"#FF9800"},{"background":"#1A237E","text":"#FFFFFF"},{"background":"#4A4A4A","text":"#FFFFFF"}],"imagePlaceholderColors":["#FF9800","#1A237E","#4A4A4A"],"imageAspectRatios":[1.5,0.9],"imageColorOffset":1,"imagePositionSeed":4}
  },
  {
    slug: "savings-and-loan-crisis",
    title: "The S&L Crisis",
    description: "The bailout that cost $160 billion",
    category: "Economics",
    thumbnail_color: "#4E342E",
    body_text: `Between 1986 and 1995, more than one thousand American savings and loan associations failed. The cleanup cost taxpayers approximately $160 billion. It was the largest financial scandal in American history—until the 2008 crisis made it look small. Savings and loans were community banks that took deposits and made home loans. They had operated conservatively for decades, subject to tight regulations on what they could do with depositors' money. Then, in the early 1980s, the rules changed. Facing competition from money market funds, the industry won deregulation. S&Ls were freed to make riskier investments while their deposits remained guaranteed by the federal government. The combination was toxic. With depositors protected, S&L managers had every incentive to take risks. If the bets paid off, they got rich. If the bets failed, the government picked up the tab. Fraudsters saw an opportunity. Some S&Ls were looted by their own executives, who made bad loans to friends and business partners, paid themselves lavish salaries, and cooked the books to hide the losses. Others simply made terrible investments that regulatory supervisors were too understaffed or too captured to stop. The collapse accelerated in the late 1980s. Regulators, finally recognizing the scope of the problem, began seizing failed institutions. The Resolution Trust Corporation was created to manage and sell their assets. Property prices in Texas, where many failed S&Ls had made speculative real estate loans, collapsed. Hundreds of executives were prosecuted. Charles Keating, whose Lincoln Savings and Loan became a symbol of the crisis, served four years in prison. The scandal also tainted five senators who had intervened with regulators on Keating's behalf. The "Keating Five" became a symbol of political corruption and helped fuel demand for campaign finance reform.`,
    design_config: {"thumbnailColor":"#4E342E","titlePage":{"backgroundColor":"#4E342E","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#4E342E","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#4E342E"},{"background":"#FFD60A","text":"#000000"},{"background":"#8D6E63","text":"#FFFFFF"}],"imagePlaceholderColors":["#4E342E","#FFD60A","#8D6E63"],"imageAspectRatios":[1.4,0.85],"imageColorOffset":0,"imagePositionSeed":3}
  },
  {
    slug: "greek-debt-crisis",
    title: "The Greek Debt Crisis",
    description: "When Europe almost broke apart",
    category: "Economics",
    thumbnail_color: "#1976D2",
    body_text: `In 2010, Greece revealed that its government had been lying about its finances for years. The deficit wasn't 6 percent of GDP as reported. It was 15 percent. The debt wasn't manageable. It was crushing. The revelation triggered a crisis that threatened to destroy the European Union itself. Greece had joined the euro in 2001, gaining access to cheap credit that came with membership in a major currency union. The government borrowed to fund generous pensions, early retirement, and a bloated public sector. When the 2008 financial crisis exposed the debts, investors fled. Greek bond yields soared. The country couldn't refinance its obligations without help. The European Union and International Monetary Fund provided bailouts, but with brutal conditions attached. Greece was required to cut pensions, fire public workers, raise taxes, and privatize state assets. The economy collapsed. Unemployment exceeded 25 percent. Youth unemployment reached 60 percent. Hospitals ran out of supplies. Suicides spiked. Greeks had been told that membership in the euro would bring prosperity. Instead, it brought depression. Protests filled Athens. Voters swung to radical parties on both left and right. In 2015, a leftist government came to power promising to reject austerity. Within months, it had capitulated, signing an even harsher bailout agreement after European authorities threatened to cut off the banking system. The crisis dragged on for nearly a decade. Greece eventually returned to growth, but only after losing a quarter of its economic output. Young Greeks emigrated in droves. The country that gave birth to democracy became a cautionary tale about what happens when nations surrender monetary sovereignty and live beyond their means.`,
    design_config: {"thumbnailColor":"#1976D2","titlePage":{"backgroundColor":"#1976D2","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#1976D2","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#1976D2"},{"background":"#FFD60A","text":"#000000"},{"background":"#4A4A4A","text":"#FFFFFF"}],"imagePlaceholderColors":["#1976D2","#FFD60A","#4A4A4A"],"imageAspectRatios":[1.5,0.9],"imageColorOffset":1,"imagePositionSeed":2}
  },
  {
    slug: "opec-oil-embargo",
    title: "The OPEC Oil Embargo",
    description: "When the world ran out of gas",
    category: "Economics",
    thumbnail_color: "#212121",
    body_text: `On October 17, 1973, the Arab members of OPEC announced an oil embargo against the United States and other countries that had supported Israel in the Yom Kippur War. Within months, the price of oil had quadrupled. Lines at gas stations stretched for blocks. The postwar era of cheap energy was over. The embargo caught America completely off guard. The country had been the world's largest oil producer for most of the twentieth century but had become increasingly dependent on imports as domestic production peaked and consumption soared. Cars had grown larger and less efficient. Suburban sprawl required ever more driving. No one had seriously considered what would happen if the oil stopped flowing. The answer was chaos. Gas stations ran dry. Speed limits were lowered to conserve fuel. Daylight saving time was extended. Thermostats were turned down. Nixon administration officials talked about invading Saudi Arabia. The economic impact was severe. The combination of high energy prices and slowing growth created "stagflation," a phenomenon economists had thought impossible. Inflation and unemployment rose together. The stock market crashed. The United States entered the worst recession since World War II. The embargo was lifted in March 1974, but oil prices never returned to pre-crisis levels. A second oil shock in 1979, triggered by the Iranian Revolution, drove prices even higher. The era of cheap energy that had fueled postwar prosperity was over. The crisis transformed the global economy. Japan and Europe invested in fuel efficiency and public transportation. Nuclear power expanded. Oil-producing nations grew rich while importing nations struggled. The geopolitics of energy, which had seemed like an abstraction, became the central concern of American foreign policy.`,
    design_config: {"thumbnailColor":"#212121","titlePage":{"backgroundColor":"#212121","textColor":"#FFD60A"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#212121","text":"#FFFFFF"},{"background":"#FFD60A","text":"#000000"},{"background":"#FFFFFF","text":"#212121"},{"background":"#4A4A4A","text":"#FFFFFF"}],"imagePlaceholderColors":["#212121","#FFD60A","#4A4A4A"],"imageAspectRatios":[1.4,0.85],"imageColorOffset":0,"imagePositionSeed":4}
  },
  {
    slug: "iceland-banking-collapse",
    title: "Iceland's Bank Collapse",
    description: "The nation that went bankrupt",
    category: "Economics",
    thumbnail_color: "#0097A7",
    body_text: `In October 2008, Iceland's three largest banks collapsed within a single week. Their combined assets were ten times the country's entire GDP. Iceland became the first developed nation to request IMF assistance since Britain in 1976. The population of 330,000 watched in horror as their country's economy disintegrated. The crisis had been years in the making. Iceland's banks had transformed themselves from small, conservative institutions into aggressive international players. They borrowed heavily in foreign currencies to fund expansion abroad, growing at rates that should have alarmed regulators. Icelandic entrepreneurs bought famous brands like Hamleys and House of Fraser. For a moment, this nation of fishing villages seemed like a financial superpower. The bubble burst spectacularly. When global credit markets froze after Lehman Brothers collapsed, Iceland's banks couldn't roll over their foreign debts. The Icelandic krona lost half its value in days. The stock market dropped 90 percent. Inflation soared. Unemployment tripled. Icelanders who had borrowed in foreign currencies to buy cars and homes found their debts suddenly doubled. The government nationalized the failed banks and refused to bail out foreign depositors. Britain and the Netherlands, whose citizens had deposits in Icelandic bank subsidiaries, were furious. They sued. Iceland held a referendum on whether to repay the money and voted no—twice. The recovery was surprisingly rapid. Iceland devalued its currency, which made exports competitive. Tourism boomed. The country pursued and imprisoned several bankers responsible for the collapse, unlike the United States where no major executives went to jail. By 2015, Iceland had repaid its IMF loans ahead of schedule. The small island that had gone spectacularly bust had also spectacularly recovered.`,
    design_config: {"thumbnailColor":"#0097A7","titlePage":{"backgroundColor":"#0097A7","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#0097A7","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#0097A7"},{"background":"#FFD60A","text":"#000000"},{"background":"#4A4A4A","text":"#FFFFFF"}],"imagePlaceholderColors":["#0097A7","#FFD60A","#4A4A4A"],"imageAspectRatios":[1.5,0.9],"imageColorOffset":1,"imagePositionSeed":3}
  },
  {
    slug: "china-stock-crash-2015",
    title: "China's Stock Market Crash",
    description: "When the party tried to stop a crash",
    category: "Economics",
    thumbnail_color: "#C62828",
    body_text: `In mid-2015, the Chinese stock market lost $3 trillion in three weeks. The government's response was to essentially suspend capitalism: banning large shareholders from selling, ordering state funds to buy stocks, and threatening to arrest journalists who reported on the crash. It didn't work. The bubble had inflated rapidly. Between June 2014 and June 2015, the Shanghai Composite Index more than doubled. State media encouraged citizens to buy stocks as a patriotic duty. Brokerages made it easy to borrow money for speculation. Over 30 million new trading accounts were opened by small investors hoping to get rich. Many were farmers and factory workers who had never owned a stock before. When prices peaked in June 2015, the reversal was brutal. Within weeks, stocks had lost nearly half their value. Margin calls forced leveraged investors to sell, which pushed prices lower, which triggered more margin calls. The spiral seemed unstoppable. The government's intervention was unprecedented in scale and desperation. State-owned firms were ordered to buy and hold stocks. Short-selling was effectively banned. Over half of listed companies suspended trading in their own shares to prevent further declines. The China Securities Regulatory Commission warned that malicious short-sellers would be investigated and punished. For a few weeks, it seemed like the Communist Party was at war with market forces themselves. The market eventually stabilized, but confidence was shattered. Small investors who had been encouraged to buy watched their savings evaporate. The government's credibility, built on decades of managed economic growth, was damaged. Chinese authorities learned that they could control many things but not market sentiment. The crash revealed the tensions between state capitalism and actual markets that continue to define China's economy.`,
    design_config: {"thumbnailColor":"#C62828","titlePage":{"backgroundColor":"#C62828","textColor":"#FFD60A"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#C62828","text":"#FFFFFF"},{"background":"#FFD60A","text":"#000000"},{"background":"#FFFFFF","text":"#C62828"},{"background":"#4A4A4A","text":"#FFFFFF"}],"imagePlaceholderColors":["#C62828","#FFD60A","#4A4A4A"],"imageAspectRatios":[1.4,0.85],"imageColorOffset":0,"imagePositionSeed":2}
  },
  {
    slug: "silicon-valley-bank-collapse",
    title: "Silicon Valley Bank Collapse",
    description: "The bank run that happened in hours",
    category: "Economics",
    thumbnail_color: "#512DA8",
    body_text: `On March 9, 2023, depositors attempted to withdraw $42 billion from Silicon Valley Bank in a single day. It was the fastest bank run in history, enabled by the same technology the bank's customers had created. By the next morning, regulators had seized the bank. In the space of 48 hours, a $200 billion institution had simply ceased to exist. SVB had been the go-to bank for tech startups for forty years. It understood the industry, tolerated losses during early-stage growth, and connected founders with venture capitalists. When interest rates were near zero, the bank was flooded with deposits from flush tech companies that had nowhere else to put their cash. The bank invested those deposits in long-term government bonds—safe, except that their value drops when interest rates rise. When the Federal Reserve raised rates aggressively in 2022 and 2023, SVB's bond portfolio lost billions in value. Startup depositors, nervous about the losses, began pulling money out. The bank tried to raise capital to cover the shortfall, which only accelerated the panic. What made SVB different was the speed. Tech founders communicated through group chats and Twitter. When Peter Thiel's Founders Fund advised companies to withdraw their money, the message spread across Silicon Valley in minutes. By the end of March 9, the bank was insolvent. The federal government guaranteed all deposits, even those above the $250,000 insurance limit, fearing contagion to other banks. Critics argued this was a bailout of wealthy depositors. Supporters said it was necessary to prevent a broader crisis. Two other banks failed in the following days. The 2023 banking panic was brief but revealing: in the age of smartphones and social media, a bank run could happen before regulators had time to finish their morning coffee.`,
    design_config: {"thumbnailColor":"#512DA8","titlePage":{"backgroundColor":"#512DA8","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#512DA8","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#512DA8"},{"background":"#FFD60A","text":"#000000"},{"background":"#4A4A4A","text":"#FFFFFF"}],"imagePlaceholderColors":["#512DA8","#FFD60A","#4A4A4A"],"imageAspectRatios":[1.5,0.9],"imageColorOffset":1,"imagePositionSeed":4}
  },
  {
    slug: "libor-scandal",
    title: "The LIBOR Scandal",
    description: "When banks rigged the world's most important number",
    category: "Economics",
    thumbnail_color: "#37474F",
    body_text: `Every day, banks in London submitted estimates of the interest rates they would charge to borrow from each other. These submissions were averaged to produce LIBOR, the London Interbank Offered Rate, which served as the foundation for hundreds of trillions of dollars in financial contracts worldwide. For years, the banks were lying. LIBOR determined interest rates on mortgages, student loans, and credit cards. It was used to price derivatives worth hundreds of trillions of dollars. Corporations, governments, and individuals all depended on it being accurate. The system relied on banks reporting honestly. They didn't. The manipulation had two forms. During the financial crisis, banks deliberately understated their borrowing costs to appear healthier than they were. If they admitted they had to pay high rates to borrow, it would signal that other banks didn't trust them. The lie became a survival strategy. But traders also manipulated LIBOR for profit, nudging the rate up or down to benefit their trading positions. Internal messages revealed the casual corruption: traders requesting specific rates, rate-setters agreeing to help, small adjustments that translated into millions in profits. When regulators finally investigated, the fines were enormous. Barclays paid $450 million. UBS paid $1.5 billion. Deutsche Bank paid $2.5 billion. Several traders were convicted of crimes. The benchmark itself was reformed, eventually replaced by alternative rates that don't depend on self-reporting. The scandal revealed that one of the most fundamental prices in global finance had been a lie. Every financial contract pegged to LIBOR had potentially been corrupted. The banks that set the rate had treated it as another tool for profit rather than a public trust. The system worked only as long as no one looked too closely.`,
    design_config: {"thumbnailColor":"#37474F","titlePage":{"backgroundColor":"#37474F","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#37474F","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#37474F"},{"background":"#FFD60A","text":"#000000"},{"background":"#4A4A4A","text":"#FFFFFF"}],"imagePlaceholderColors":["#37474F","#FFD60A","#4A4A4A"],"imageAspectRatios":[1.4,0.85],"imageColorOffset":0,"imagePositionSeed":3}
  },
  {
    slug: "gamestop-squeeze",
    title: "The GameStop Squeeze",
    description: "When Reddit took on Wall Street",
    category: "Economics",
    thumbnail_color: "#E64A19",
    body_text: `In January 2021, shares of GameStop, a struggling video game retailer, rose from $20 to nearly $500 in a matter of weeks. The surge wasn't driven by improved business prospects. It was driven by a subreddit called WallStreetBets and a grudge against hedge funds. GameStop had been a popular short target. Hedge funds borrowed shares and sold them, betting the price would fall so they could buy back cheaper and pocket the difference. By late 2020, more than 100 percent of GameStop's available shares had been sold short—a mathematical impossibility that meant some shares had been borrowed and sold multiple times. The WallStreetBets community spotted an opportunity. If they could push the price up, short-sellers would be forced to buy shares to cover their positions, which would push the price higher still, forcing more buying. It was called a short squeeze, and it worked spectacularly. Retail investors, armed with stimulus checks and commission-free trading apps, piled into GameStop. Each price increase forced hedge funds to cover their shorts, driving the price higher. Melvin Capital, a major short-seller, lost 53 percent in January and required a bailout from other hedge funds. The frenzy spread to other heavily shorted stocks. Then Robinhood, the trading app favored by retail investors, restricted buying of GameStop and other volatile stocks. The move was technically justified by capital requirements, but it looked like the establishment protecting itself from populist revolt. Congressional hearings followed. The price eventually collapsed, but not before creating billions in losses for hedge funds and turning a few early investors into millionaires. The GameStop saga became a symbol of something larger: distrust of financial institutions, rage at inequality, and the power of collective action in the internet age.`,
    design_config: {"thumbnailColor":"#E64A19","titlePage":{"backgroundColor":"#E64A19","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#E64A19","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#E64A19"},{"background":"#1A237E","text":"#FFFFFF"},{"background":"#FFD60A","text":"#000000"}],"imagePlaceholderColors":["#E64A19","#1A237E","#FFD60A"],"imageAspectRatios":[1.5,0.9],"imageColorOffset":1,"imagePositionSeed":2}
  },
  {
    slug: "theranos-fraud",
    title: "The Theranos Fraud",
    description: "The blood-testing company that never worked",
    category: "Economics",
    thumbnail_color: "#212121",
    body_text: `Elizabeth Holmes was going to revolutionize medicine. Her company, Theranos, claimed to have developed technology that could run hundreds of medical tests from a single drop of blood. She raised nearly $1 billion from investors, graced magazine covers, and was celebrated as the next Steve Jobs. The technology didn't work. Holmes founded Theranos at nineteen, dropping out of Stanford to pursue her vision. She cultivated an image of genius, wearing black turtlenecks, speaking in a deep voice, and refusing to publish scientific papers or let outsiders examine her machines. Secrecy, she said, protected trade secrets. In reality, it protected lies. The Edison machines Theranos built were wildly inaccurate. Lab workers knew the results were unreliable but were forbidden from speaking up. When the devices failed, Theranos secretly used commercial machines from other companies to process tests, then presented the results as their own. Patients received incorrect diagnoses. People were told they had conditions they didn't have, or didn't have conditions they did. Wall Street Journal reporter John Carreyrou investigated after receiving tips from concerned employees. His 2015 exposé revealed the fraud. Theranos collapsed. Holmes was charged with wire fraud and conspiracy. Her trial in 2022 featured testimony from former employees, investors, and patients harmed by faulty tests. Holmes maintained she had believed in her technology, that she had been a victim of circumstances beyond her control. The jury convicted her on four counts. She was sentenced to more than eleven years in federal prison. Theranos became a cautionary tale about Silicon Valley's culture of fake-it-till-you-make-it, about investors who didn't ask hard questions, and about the danger of believing your own mythology.`,
    design_config: {"thumbnailColor":"#212121","titlePage":{"backgroundColor":"#212121","textColor":"#E64A19"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#212121","text":"#FFFFFF"},{"background":"#E64A19","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#212121"},{"background":"#4A4A4A","text":"#FFFFFF"}],"imagePlaceholderColors":["#212121","#E64A19","#4A4A4A"],"imageAspectRatios":[1.4,0.85],"imageColorOffset":0,"imagePositionSeed":4}
  },
  {
    slug: "madoff-ponzi-scheme",
    title: "The Madoff Ponzi Scheme",
    description: "The $65 billion fraud no one saw",
    category: "Economics",
    thumbnail_color: "#1A237E",
    body_text: `Bernie Madoff ran the largest Ponzi scheme in history for at least seventeen years, possibly longer. He stole an estimated $65 billion from thousands of investors, including charities, pension funds, and individuals who trusted him with their life savings. The fraud was remarkably simple: he just didn't trade. Madoff was a respected figure on Wall Street. He had helped found the NASDAQ stock exchange and served as its chairman. He managed money for wealthy families, charitable foundations, and celebrity clients. His returns were consistently good—not spectacular, but reliably positive, year after year. That reliability should have been a warning sign. The strategy Madoff claimed to use couldn't possibly generate such consistent returns. Financial experts noted the impossibility but assumed he must be doing something clever, perhaps front-running his brokerage clients. They were giving him too much credit. In reality, Madoff was simply taking new money and paying it out to existing investors. The trading records were fabricated. The account statements were fiction. His floor of traders was for show. A small group of employees in a separate part of the office generated the fake paperwork while legitimate business continued upstairs. The scheme collapsed during the 2008 financial crisis when investors tried to withdraw more money than Madoff could provide. He confessed to his sons, who reported him to the FBI. The scale of the fraud shocked even investigators. Madoff was sentenced to 150 years in prison, where he died in 2021. Victims eventually recovered about $14 billion through asset recovery and legal settlements, but many lost everything. Madoff's name became synonymous with financial fraud, a reminder that even the most trusted figures can be criminals.`,
    design_config: {"thumbnailColor":"#1A237E","titlePage":{"backgroundColor":"#1A237E","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#1A237E","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#1A237E"},{"background":"#FFD60A","text":"#000000"},{"background":"#4A4A4A","text":"#FFFFFF"}],"imagePlaceholderColors":["#1A237E","#FFD60A","#4A4A4A"],"imageAspectRatios":[1.5,0.9],"imageColorOffset":1,"imagePositionSeed":3}
  },
  {
    slug: "wirecard-fraud",
    title: "The Wirecard Scandal",
    description: "Germany's greatest corporate fraud",
    category: "Economics",
    thumbnail_color: "#00695C",
    body_text: `Wirecard was a German fintech darling worth $28 billion at its peak. It processed payments for companies around the world and was hailed as Europe's answer to Silicon Valley. Then auditors couldn't find $2.1 billion that was supposed to be in the bank. The money had never existed. For years, Wirecard had been fabricating revenue and profits, creating the illusion of a fast-growing company while insiders looted the business. The fraud was centered on partnerships in Asia that supposedly generated huge profits but were actually fake. Documents were forged. Auditors were deceived. When journalists raised questions, Wirecard attacked them, filing lawsuits and enlisting German regulators to investigate the reporters rather than the company. The collapse came in June 2020, when Wirecard's auditor, EY, refused to sign off on the annual report. The company couldn't locate €1.9 billion supposedly held in Philippine banks. The banks said the accounts didn't exist. Within days, Wirecard had filed for insolvency, the first company ever expelled from Germany's blue-chip DAX index. CEO Markus Braun was arrested. COO Jan Marsalek, suspected of masterminding the fraud, vanished. He is believed to be hiding in Russia, protected by intelligence services, though Wirecard's connections to espionage remain murky. The scandal was an embarrassment for Germany, which had prided itself on rigorous corporate governance. Regulators had defended Wirecard and prosecuted its critics. Politicians had championed the company as a national champion. The entire system had failed. EY, which had audited Wirecard for over a decade, faced lawsuits and criminal investigations. The German regulatory system was overhauled. Trust in European fintech was shaken. Wirecard became proof that fraud can hide in plain sight when enough people want to believe.`,
    design_config: {"thumbnailColor":"#00695C","titlePage":{"backgroundColor":"#00695C","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#00695C","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#00695C"},{"background":"#FFD60A","text":"#000000"},{"background":"#4A4A4A","text":"#FFFFFF"}],"imagePlaceholderColors":["#00695C","#FFD60A","#4A4A4A"],"imageAspectRatios":[1.4,0.85],"imageColorOffset":0,"imagePositionSeed":2}
  },
  {
    slug: "credit-suisse-collapse",
    title: "The Fall of Credit Suisse",
    description: "How a 166-year-old bank died",
    category: "Economics",
    thumbnail_color: "#455A64",
    body_text: `Credit Suisse survived two world wars, the Great Depression, and the 2008 financial crisis. It did not survive a series of scandals and a social media-accelerated bank run in 2023. After 166 years, one of the world's most prestigious banks was absorbed by its rival UBS in an emergency rescue that wiped out $17 billion in bondholder investments. The bank's problems had been accumulating for years. In 2021, Credit Suisse lost $5 billion from the collapse of Archegos Capital, a family office that had made huge leveraged bets on stocks. The same year, its funds that invested in Greensill Capital, a supply-chain finance company, were frozen when Greensill collapsed. Clients lost billions. Each scandal revealed deeper problems: weak risk management, a culture that prioritized revenue over prudence, and leadership that couldn't get control. The bank reported losses year after year. Clients withdrew money. Talented employees left. Credit Suisse became known as the bank where bad things happened. The final crisis came in March 2023. Following the collapse of Silicon Valley Bank, investors grew nervous about banks with troubled reputations. Credit Suisse's largest shareholder, the Saudi National Bank, announced it wouldn't increase its stake. The statement, meant to be neutral, was interpreted as abandonment. In a single day, customers withdrew $10 billion. The Swiss National Bank provided emergency liquidity, but it wasn't enough to restore confidence. Within days, regulators orchestrated a forced merger with UBS. The deal was done over a weekend, without shareholder approval. Bondholders who held contingent convertible bonds—supposedly safer than stock—were wiped out entirely while shareholders received something. The legal and political fallout continues. Credit Suisse's death marked the end of an era of Swiss banking prestige.`,
    design_config: {"thumbnailColor":"#455A64","titlePage":{"backgroundColor":"#455A64","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#455A64","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#455A64"},{"background":"#C62828","text":"#FFFFFF"},{"background":"#4A4A4A","text":"#FFFFFF"}],"imagePlaceholderColors":["#455A64","#C62828","#4A4A4A"],"imageAspectRatios":[1.5,0.9],"imageColorOffset":1,"imagePositionSeed":4}
  },
  {
    slug: "deutsche-bank-decline",
    title: "Deutsche Bank's Decline",
    description: "The fall of Germany's biggest bank",
    category: "Economics",
    thumbnail_color: "#1565C0",
    body_text: `In 2007, Deutsche Bank was the largest bank in the world by assets. It employed over 80,000 people and operated in 70 countries. Two decades later, its stock had lost 90 percent of its value, its workforce had shrunk by half, and it had become a symbol of everything that had gone wrong with European banking. The decline was self-inflicted. Deutsche Bank had transformed itself from a conservative German institution into a global investment bank, competing with Goldman Sachs and JP Morgan in the most aggressive corners of finance. It traded complex derivatives, made risky bets, and cultivated a culture that valued profits over prudence. For a while, it worked. Then came the fines. Deutsche Bank was implicated in seemingly every scandal of the post-crisis era. It paid $7.2 billion for mis-selling mortgage securities. It paid $2.5 billion for manipulating LIBOR. It paid $630 million for laundering Russian money. The penalties accumulated until they threatened the bank's survival. Management churned through a series of CEOs, each promising turnarounds that never materialized. The investment bank that was supposed to be Deutsche's competitive advantage became a millstone. Talented employees left for rivals. Clients moved their business elsewhere. The bank that had aspired to be Europe's answer to Wall Street retreated to its German roots, cutting jobs, closing offices, and abandoning businesses it had spent decades building. Deutsche Bank still exists, still employs tens of thousands, still serves major corporations. But the ambition that drove it to compete with American giants is gone. The attempted transformation nearly killed the institution. The retreat back to basics was an admission of failure that German pride struggled to accept.`,
    design_config: {"thumbnailColor":"#1565C0","titlePage":{"backgroundColor":"#1565C0","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#1565C0","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#1565C0"},{"background":"#FFD60A","text":"#000000"},{"background":"#4A4A4A","text":"#FFFFFF"}],"imagePlaceholderColors":["#1565C0","#FFD60A","#4A4A4A"],"imageAspectRatios":[1.4,0.85],"imageColorOffset":0,"imagePositionSeed":3}
  }
];

async function uploadStory(story) {
  const response = await fetch(`${SUPABASE_URL}/rest/v1/stories`, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      "apikey": SUPABASE_KEY,
      "Authorization": `Bearer ${SUPABASE_KEY}`,
      "Prefer": "resolution=merge-duplicates,return=minimal"
    },
    body: JSON.stringify({
      slug: story.slug,
      title: story.title,
      description: story.description,
      category: story.category,
      thumbnail_color: story.thumbnail_color,
      published: true,
      published_at: new Date().toISOString(),
      body_text: story.body_text,
      design_config: story.design_config,
      updated_at: new Date().toISOString()
    })
  });

  if (!response.ok) {
    const text = await response.text();
    throw new Error(`${response.status}: ${text}`);
  }
}

async function main() {
  console.log(`Uploading ${stories.length} Economics stories to Supabase...\n`);

  let success = 0;
  let failed = 0;

  for (const story of stories) {
    try {
      process.stdout.write(`Uploading: ${story.title}... `);
      await uploadStory(story);
      console.log("Done!");
      success++;
    } catch (error) {
      console.log(`Error: ${error.message}`);
      failed++;
    }
  }

  console.log(`\nComplete! ${success} succeeded, ${failed} failed.`);
}

main();
