/**
 * Exploration Category - 25 New Stories
 * Usage: node scripts/new-content/exploration-new.mjs
 */

const SUPABASE_URL = "https://egfwisgqdyhzpmeoracb.supabase.co";
const SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVnZndpc2dxZHloenBtZW9yYWNiIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2ODQyNzM0OSwiZXhwIjoyMDg0MDAzMzQ5fQ.S8h1fIepxWb44gPSPpWQ8fE0Q-SCYfL0QcBRUV7fXgs";

const stories = [
  {
    slug: "shackleton-endurance",
    title: "Shackleton's Endurance",
    description: "The greatest survival story ever told",
    category: "Exploration",
    thumbnail_color: "#37474F",
    body_text: `In 1914, Ernest Shackleton set out to cross Antarctica on foot. His ship, the Endurance, never reached the continent. Trapped in pack ice, it drifted for ten months before being crushed like a walnut. Shackleton and his twenty-seven men were stranded on the ice with no hope of rescue. They all survived. The expedition had aimed to achieve the first land crossing of Antarctica. Instead, it became a two-year ordeal of endurance that redefined what humans could survive. When the ship sank, the crew was over a thousand miles from the nearest outpost of civilization, with three small boats and whatever supplies they had salvaged. For five months, they camped on drifting ice floes, hunting seals and penguins for food, watching the ice slowly carry them north. When the ice finally broke up, they launched their boats and made for Elephant Island, a desolate rock where they could at least stand on solid ground. Shackleton knew no rescue would come to such a remote place. He and five others set out in a twenty-two-foot boat for South Georgia Island, eight hundred miles across the most violent ocean on Earth. The journey took sixteen days through hurricane-force winds and waves that threatened to swamp them. They navigated by dead reckoning and occasional glimpses of the sun. When they reached South Georgia, they landed on the wrong side of the island and had to cross unmapped mountains and glaciers to reach the whaling station on the other side. Shackleton finally reached help and immediately began organizing a rescue. It took four attempts over three months before ice conditions allowed a ship to reach Elephant Island. Every man was still alive. Shackleton had not lost a single member of his expedition. In an age of heroic failures, he had achieved something remarkable: a triumph of leadership under impossible conditions.`,
    design_config: {"thumbnailColor":"#37474F","titlePage":{"backgroundColor":"#37474F","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#37474F","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#37474F"},{"background":"#90CAF9","text":"#000000"},{"background":"#4A4A4A","text":"#FFFFFF"}],"imagePlaceholderColors":["#37474F","#90CAF9","#4A4A4A"],"imageAspectRatios":[1.5,0.9],"imageColorOffset":0,"imagePositionSeed":2}
  },
  {
    slug: "burke-wills-expedition",
    title: "The Burke and Wills Expedition",
    description: "Australia's deadliest exploration",
    category: "Exploration",
    thumbnail_color: "#BF360C",
    body_text: `In 1860, Robert O'Hara Burke and William John Wills led the largest and best-equipped expedition in Australian history. Their goal was to be the first to cross the continent from south to north. They succeeded—and then they died, within sight of salvation, in one of exploration's most tragic endings. The expedition left Melbourne with eighteen men, twenty-six camels, and enough supplies to last two years. Burke, an Irish police officer with no exploration experience, was an odd choice for leader. He was impatient, prone to rash decisions, and dismissive of anyone who questioned him. These qualities would prove fatal. Burke pushed ahead too fast, abandoning most of his party at various depots, determined to beat a rival expedition to the honor of the first crossing. By the time he reached the Gulf of Carpentaria in February 1861, his group had dwindled to four men. The return journey was a disaster. One man died of exhaustion. The others staggered south, running short of food and water, their camels dying beneath them. They finally reached their base camp at Cooper Creek on April 21, only to find it deserted. The party left to resupply had departed just nine hours earlier, after waiting four months and five weeks beyond the agreed date. Burke and Wills slowly starved over the following months, unable to live off the land despite being surrounded by Indigenous Australians who thrived there. The local Yandruwandha people offered them fish and a flour-like paste made from nardoo seeds, but Burke drove them away with gunfire. Wills died in late June. Burke followed days later. Only one of the four who had reached the Gulf survived, found by a rescue party living with the Yandruwandha who had saved his life. The expedition that should have been a triumph became a monument to arrogance and failure.`,
    design_config: {"thumbnailColor":"#BF360C","titlePage":{"backgroundColor":"#BF360C","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#BF360C","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#BF360C"},{"background":"#FFD60A","text":"#000000"},{"background":"#4A4A4A","text":"#FFFFFF"}],"imagePlaceholderColors":["#BF360C","#FFD60A","#4A4A4A"],"imageAspectRatios":[1.4,0.85],"imageColorOffset":1,"imagePositionSeed":3}
  },
  {
    slug: "franklin-expedition",
    title: "The Lost Franklin Expedition",
    description: "129 men vanished in the Arctic",
    category: "Exploration",
    thumbnail_color: "#263238",
    body_text: `In 1845, Sir John Franklin led two ships and 129 men into the Canadian Arctic in search of the Northwest Passage. They were never seen alive again by European eyes. For over 150 years, the fate of the expedition remained one of history's greatest mysteries. Franklin's ships, HMS Erebus and HMS Terror, were the most advanced vessels of their time, equipped with steam engines, iron-reinforced hulls, and three years of provisions. The expedition was expected to succeed where all others had failed, finally charting a navigable route through the Arctic. They sailed into the ice in the summer of 1845 and vanished. Search parties sent over the following decade found only fragments: a few graves, some scattered equipment, and eventually, chillingly, a note. The message, left in a cairn on King William Island, revealed that the ships had been trapped in ice since 1846. Franklin had died in 1847. The survivors had abandoned ship and tried to walk to safety. None made it. Inuit testimony, long dismissed by Victorian authorities, described men who had resorted to cannibalism, who had dropped dead while walking, who had fallen and not risen. Forensic analysis of bones found in the twentieth century confirmed these accounts. The men had starved, frozen, and eaten each other. Some may have been poisoned by lead from poorly soldered food tins. In 2014 and 2016, Canadian search teams finally located both ships on the seafloor, remarkably preserved by the cold water. The wrecks yielded artifacts but no definitive answers. We know roughly what happened to the Franklin expedition. The question of exactly how so many men could die so completely, so close to potential rescue, haunts the Arctic still.`,
    design_config: {"thumbnailColor":"#263238","titlePage":{"backgroundColor":"#263238","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#263238","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#263238"},{"background":"#90CAF9","text":"#000000"},{"background":"#4A4A4A","text":"#FFFFFF"}],"imagePlaceholderColors":["#263238","#90CAF9","#4A4A4A"],"imageAspectRatios":[1.5,0.9],"imageColorOffset":0,"imagePositionSeed":4}
  },
  {
    slug: "columbus-first-voyage",
    title: "Columbus's First Voyage",
    description: "The journey that changed everything",
    category: "Exploration",
    thumbnail_color: "#1565C0",
    body_text: `On August 3, 1492, Christopher Columbus sailed west from Spain with three ships and a theory. He believed he could reach Asia by crossing the Atlantic. He was wrong about the geography but right about the crossing. Seventy days later, he landed in the Caribbean and changed the world forever. Columbus had spent years trying to fund his expedition. Portuguese experts had correctly calculated that Asia was too far west to reach by ship—the voyage would be impossible with the provisions available. Columbus used different calculations that significantly underestimated the Earth's circumference. His error was fortunate; if the Americas hadn't been in the way, his crew would have starved. The voyage nearly failed anyway. After weeks of open ocean with no land in sight, the crew grew mutinous. Columbus falsified his logs, telling the men they had traveled less distance than they actually had. It didn't help much. By early October, the sailors were openly discussing turning back. Then, on October 12, a lookout on the Pinta spotted land. Columbus went ashore on an island in the Bahamas, claimed it for Spain, and named it San Salvador. He had no idea where he actually was. He explored Cuba and Hispaniola, convinced he had reached islands off the coast of Asia. The native Taíno people he encountered were friendly; within decades, their population would be decimated by disease and enslavement. Columbus returned to Spain a hero. He made three more voyages, never realizing he had found new continents. He died in 1506 still believing he had reached Asia. The world he accidentally discovered would be transformed by disease, conquest, and the exchange of crops, animals, and people between hemispheres. Nothing would ever be the same.`,
    design_config: {"thumbnailColor":"#1565C0","titlePage":{"backgroundColor":"#1565C0","textColor":"#FFD60A"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#1565C0","text":"#FFFFFF"},{"background":"#FFD60A","text":"#000000"},{"background":"#FFFFFF","text":"#1565C0"},{"background":"#4A4A4A","text":"#FFFFFF"}],"imagePlaceholderColors":["#1565C0","#FFD60A","#4A4A4A"],"imageAspectRatios":[1.4,0.85],"imageColorOffset":1,"imagePositionSeed":2}
  },
  {
    slug: "roald-amundsen-northwest-passage",
    title: "Amundsen's Northwest Passage",
    description: "The voyage that took three years",
    category: "Exploration",
    thumbnail_color: "#00695C",
    body_text: `After four centuries of failed attempts, a Norwegian explorer finally navigated the Northwest Passage from Atlantic to Pacific. It took Roald Amundsen three years, two winters frozen in ice, and a willingness to learn from the Indigenous peoples that previous expeditions had ignored. Amundsen had studied the failures of his predecessors. Where Franklin had brought 129 men and massive ships, Amundsen brought six men and a converted herring boat called the Gjøa. Where British expeditions had dismissed Inuit knowledge, Amundsen sought it out. He spent two winters with the Netsilik people, learning to drive dog sleds, build igloos, and dress in caribou furs. These skills would later help him beat Scott to the South Pole. The Gjøa departed Norway in June 1903 and entered the Arctic labyrinth of islands and channels that had claimed so many lives. Amundsen navigated carefully, anchoring at King William Island in September 1903 to wait out the winter. He would remain there for two years, exploring and learning, while his small crew took magnetic observations and mapped the surrounding area. In August 1905, Amundsen resumed his journey. The channels grew shallower—at one point, the Gjøa passed through water just one meter deep. On August 26, they spotted a whaling ship from San Francisco. The passage was complete. The final leg to the Pacific took another year, delayed by ice that trapped the ship within sight of Alaska. Amundsen famously traveled 500 miles overland by dogsled to telegraph news of his success, unwilling to wait for the ice to release him. When the Gjøa finally reached San Francisco in 1906, Amundsen had achieved what generations of explorers had died attempting. The Northwest Passage was navigable—barely, and only with the right knowledge.`,
    design_config: {"thumbnailColor":"#00695C","titlePage":{"backgroundColor":"#00695C","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#00695C","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#00695C"},{"background":"#90CAF9","text":"#000000"},{"background":"#4A4A4A","text":"#FFFFFF"}],"imagePlaceholderColors":["#00695C","#90CAF9","#4A4A4A"],"imageAspectRatios":[1.5,0.9],"imageColorOffset":0,"imagePositionSeed":3}
  },
  {
    slug: "zheng-he-voyages",
    title: "Zheng He's Treasure Fleet",
    description: "China's armada that could have conquered the world",
    category: "Exploration",
    thumbnail_color: "#C62828",
    body_text: `In 1405, the largest fleet the world had ever seen set sail from China. Admiral Zheng He commanded over 300 ships and 28,000 men, including vessels nine times larger than those Columbus would sail nearly a century later. For three decades, Chinese treasure fleets ranged from Japan to Africa. Then China abandoned the sea forever. Zheng He was an unlikely admiral. Born in a Muslim family in southwestern China, he was captured as a child when Ming forces conquered his homeland, castrated, and raised as a servant in the imperial household. He rose through palace ranks to become a trusted adviser to the emperor, who charged him with leading China's maritime expansion. The treasure ships were engineering marvels. The largest measured over 400 feet long with nine masts—far bigger than any European vessel of the era. They carried silk, porcelain, and gold to trade for exotic goods: giraffes from Africa, spices from India, gems from Sri Lanka. Everywhere the fleet went, it demonstrated Chinese power and extracted tribute from local rulers. Over seven voyages spanning nearly three decades, Zheng He visited over thirty countries. His ships reached the Persian Gulf, the Red Sea, and the east coast of Africa. Some historians speculate they may have traveled even further, though evidence is disputed. Then, in 1433, China's maritime era ended abruptly. The new emperor, influenced by Confucian scholars who viewed foreign trade as wasteful and dangerous, ordered the treasure fleet dismantled. Records of the voyages were destroyed. Shipbuilding was restricted. China turned inward just as European powers were beginning their own age of exploration. Had China continued, the map of global colonization might look entirely different. Instead, the greatest navy in history was deliberately forgotten.`,
    design_config: {"thumbnailColor":"#C62828","titlePage":{"backgroundColor":"#C62828","textColor":"#FFD60A"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#C62828","text":"#FFFFFF"},{"background":"#FFD60A","text":"#000000"},{"background":"#FFFFFF","text":"#C62828"},{"background":"#4A4A4A","text":"#FFFFFF"}],"imagePlaceholderColors":["#C62828","#FFD60A","#4A4A4A"],"imageAspectRatios":[1.4,0.85],"imageColorOffset":1,"imagePositionSeed":4}
  },
  {
    slug: "marco-polo-journey",
    title: "Marco Polo's Journey",
    description: "The traveler who revealed the East",
    category: "Exploration",
    thumbnail_color: "#FF8F00",
    body_text: `In 1271, a seventeen-year-old Venetian merchant named Marco Polo set out for China with his father and uncle. He would not return for twenty-four years. The book he later dictated about his travels was so extraordinary that many readers refused to believe it. Some still don't. The Polos traveled overland across Central Asia, through Persia, Afghanistan, and the deserts of western China. Young Marco absorbed everything he saw: the customs of different peoples, the goods they traded, the wonders of cities that Europeans had never imagined. When they reached the court of Kublai Khan, the Mongol emperor who ruled China, Marco entered his service. For seventeen years, Marco served the Khan, traveling throughout his empire as an envoy and administrator. He visited Burma, India, and possibly Southeast Asia. He claimed to have governed a major Chinese city. He observed paper money, coal, and asbestos—things unknown in Europe. When he finally returned to Venice, few believed his stories. The account of his travels, written while he was imprisoned after a naval battle, became one of the most influential books in history. "The Travels of Marco Polo" shaped European understanding of Asia for centuries. Columbus carried a copy on his voyage. Cartographers used it to map regions they had never seen. It inspired countless later explorers to seek the riches of the East. Scholars still debate how much of the book is accurate. Marco never mentioned the Great Wall or tea, oddities that cast doubt on his claims. Others point out that such omissions might simply reflect what he found unremarkable or failed to remember. Whether every detail is true, the book opened European eyes to a world far larger and more sophisticated than they had imagined.`,
    design_config: {"thumbnailColor":"#FF8F00","titlePage":{"backgroundColor":"#FF8F00","textColor":"#000000"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#FF8F00","text":"#000000"},{"background":"#FFFFFF","text":"#FF8F00"},{"background":"#C62828","text":"#FFFFFF"},{"background":"#4A4A4A","text":"#FFFFFF"}],"imagePlaceholderColors":["#FF8F00","#C62828","#4A4A4A"],"imageAspectRatios":[1.5,0.9],"imageColorOffset":0,"imagePositionSeed":2}
  },
  {
    slug: "livingstone-africa",
    title: "Livingstone's African Journeys",
    description: "The missionary who mapped a continent",
    category: "Exploration",
    thumbnail_color: "#33691E",
    body_text: `David Livingstone walked across Africa. Multiple times. Between 1853 and 1856, the Scottish missionary became the first European to traverse the continent from coast to coast. He discovered Victoria Falls, explored the Zambezi River, and contracted malaria over thirty times. He also inadvertently helped launch the Scramble for Africa. Livingstone arrived in Africa in 1841 as a medical missionary. He quickly grew frustrated with traditional mission work and began exploring instead, convinced that opening Africa to commerce and Christianity would naturally end the slave trade that still devastated the continent's interior. He traveled for months with minimal supplies, accompanied only by African companions whose names rarely appear in his journals. His expeditions were often disasters. The Zambezi was supposed to be a highway into Africa's interior; Livingstone discovered it was blocked by impassable rapids he had somehow missed on his first visit. Malaria, dysentery, and hostile encounters nearly killed him repeatedly. Yet he kept walking, mapping rivers, cataloging peoples, and sending reports home that made him famous. In 1866, Livingstone set out to find the source of the Nile. He vanished into the interior and wasn't heard from for years. Newspapers sent Henry Morton Stanley to find him, resulting in the famous encounter at Ujiji in 1871: "Dr. Livingstone, I presume?" Livingstone refused to leave Africa. He died in 1873 in what is now Zambia, still searching. His African companions carried his embalmed body a thousand miles to the coast. He was buried in Westminster Abbey, a national hero. The maps and reports he left behind helped European powers divide Africa among themselves. The continent he loved was colonized, partly because he had revealed its secrets.`,
    design_config: {"thumbnailColor":"#33691E","titlePage":{"backgroundColor":"#33691E","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#33691E","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#33691E"},{"background":"#FFD60A","text":"#000000"},{"background":"#5D4037","text":"#FFFFFF"}],"imagePlaceholderColors":["#33691E","#FFD60A","#5D4037"],"imageAspectRatios":[1.4,0.85],"imageColorOffset":1,"imagePositionSeed":3}
  },
  {
    slug: "apollo-13-disaster",
    title: "Apollo 13",
    description: "The successful failure",
    category: "Exploration",
    thumbnail_color: "#1A237E",
    body_text: `"Houston, we've had a problem." On April 13, 1970, an oxygen tank exploded aboard Apollo 13, crippling the spacecraft 200,000 miles from Earth. The planned moon landing was canceled. The new mission was survival. Three astronauts and thousands of engineers had four days to improvise solutions to problems no one had anticipated. Commander Jim Lovell, Command Module Pilot Jack Swigert, and Lunar Module Pilot Fred Haise were two days into their journey when the explosion occurred. The command module's power supply was failing. Oxygen was venting into space. The crew had minutes to decide whether to abort and try to return directly to Earth or continue around the moon and use its gravity to slingshot home. They chose the longer route, abandoning the command module and cramming into the lunar module, a spacecraft designed for two people for two days, not three people for four days. Mission control worked around the clock to solve cascading problems. The lunar module's carbon dioxide scrubbers were the wrong shape to fit the command module's canisters. Engineers improvised a solution using plastic bags, cardboard, and tape. Power had to be rationed so severely that the spacecraft temperature dropped near freezing. Water consumption was cut to six ounces per person per day. The crew grew dehydrated and exhausted. The critical moment came during reentry. The command module's heat shield might have been damaged in the explosion. The astronauts would have no way to know until they were either safely home or dead. Radio silence during reentry lasted far longer than normal. Then Lovell's voice crackled through: "Okay, Joe." Apollo 13 splashed down safely in the Pacific. The failed mission became NASA's finest hour, proof that human ingenuity could overcome catastrophe.`,
    design_config: {"thumbnailColor":"#1A237E","titlePage":{"backgroundColor":"#1A237E","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#1A237E","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#1A237E"},{"background":"#90CAF9","text":"#000000"},{"background":"#4A4A4A","text":"#FFFFFF"}],"imagePlaceholderColors":["#1A237E","#90CAF9","#4A4A4A"],"imageAspectRatios":[1.5,0.9],"imageColorOffset":0,"imagePositionSeed":4}
  },
  {
    slug: "james-cook-voyages",
    title: "Captain Cook's Voyages",
    description: "The navigator who mapped the Pacific",
    category: "Exploration",
    thumbnail_color: "#0097A7",
    body_text: `James Cook made three voyages that redrew the map of the world. He charted New Zealand and Australia's east coast. He crossed the Antarctic Circle. He explored from Tahiti to Alaska. He was also killed by Hawaiians after an escalating dispute over a stolen boat. Cook rose from humble origins to become the greatest navigator of his era. Born the son of a farm laborer, he educated himself in mathematics and astronomy, learned seamanship in the merchant marine, and joined the Royal Navy in his late twenties. His skill at surveying and mapmaking brought him to the attention of the Admiralty, who chose him to command a scientific expedition to the Pacific. The first voyage (1768-1771) observed the transit of Venus from Tahiti, then sailed south to explore New Zealand and chart Australia's eastern coastline. Cook's meticulous surveys were so accurate that some remained in use for over a century. The second voyage (1772-1775) was meant to find the great southern continent that geographers insisted must exist. Cook circled Antarctica, crossing into the frigid waters beyond the ice pack, and proved that no temperate landmass existed in the southern oceans. He came within a hundred miles of Antarctica itself but was turned back by ice. The third voyage (1776-1779) searched for the Northwest Passage from the Pacific side. Cook explored Hawaii, which he named the Sandwich Islands, then sailed north to Alaska before ice blocked his progress. Returning to Hawaii for repairs, Cook entered a series of disputes with islanders that culminated in his death on a beach in Kealakekua Bay. His body was dismembered; some remains were later returned to his crew for burial at sea. The navigator who had charted so much of the world met his end in a place he had discovered.`,
    design_config: {"thumbnailColor":"#0097A7","titlePage":{"backgroundColor":"#0097A7","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#0097A7","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#0097A7"},{"background":"#FFD60A","text":"#000000"},{"background":"#4A4A4A","text":"#FFFFFF"}],"imagePlaceholderColors":["#0097A7","#FFD60A","#4A4A4A"],"imageAspectRatios":[1.4,0.85],"imageColorOffset":1,"imagePositionSeed":2}
  },
  {
    slug: "yuri-gagarin-space",
    title: "Yuri Gagarin's Flight",
    description: "The first human in space",
    category: "Exploration",
    thumbnail_color: "#1565C0",
    body_text: `On April 12, 1961, Yuri Gagarin became the first human being to travel beyond Earth's atmosphere. His flight lasted 108 minutes. He orbited the planet once, reached an altitude of 203 miles, and transformed humanity's understanding of what was possible. Gagarin was twenty-seven years old, a fighter pilot chosen from thousands of candidates for the Soviet space program. He was selected partly for his skill, partly for his temperament, and partly for his height—at five foot two, he fit comfortably in the cramped Vostok capsule. The mission was extraordinarily dangerous. No one knew how the human body would respond to weightlessness. Some scientists feared that space madness might cause a cosmonaut to seize control and crash the spacecraft. As a precaution, Gagarin's controls were locked; he would need to enter a code to override the automatic systems in an emergency. The launch proceeded smoothly. As the rocket ignited, Gagarin called out "Poyekhali!"—Let's go!—a phrase that became iconic in Russian culture. During his orbit, he reported feeling fine, described the Earth as having a beautiful blue halo, and ate and drank from tubes to demonstrate that humans could survive in zero gravity. Reentry was more dramatic. The service module failed to separate properly, causing the spacecraft to tumble. Gagarin experienced extreme G-forces and watched flames lick past his window as the capsule's heat shield burned. The module finally separated and the descent stabilized. Per the planned procedure, Gagarin ejected from the capsule at 20,000 feet and parachuted to a farm field in rural Russia. He landed near a woman and her granddaughter who were planting potatoes. "I am a friend," he called out, still in his orange spacesuit. "I am a Soviet citizen."`,
    design_config: {"thumbnailColor":"#1565C0","titlePage":{"backgroundColor":"#1565C0","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#1565C0","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#1565C0"},{"background":"#FF5722","text":"#FFFFFF"},{"background":"#4A4A4A","text":"#FFFFFF"}],"imagePlaceholderColors":["#1565C0","#FF5722","#4A4A4A"],"imageAspectRatios":[1.5,0.9],"imageColorOffset":0,"imagePositionSeed":3}
  },
  {
    slug: "norse-vinland-settlement",
    title: "Vikings in America",
    description: "Europeans in the New World, 500 years early",
    category: "Exploration",
    thumbnail_color: "#5D4037",
    body_text: `Around the year 1000 CE, Norse explorers sailed west from Greenland and established a settlement in North America. They called the land Vinland. The colony lasted only a few years before conflict with Indigenous peoples drove them away, but the Vikings had reached the Americas nearly five centuries before Columbus. The sagas that tell this story were long dismissed as legend. Then, in 1960, archaeologists discovered the remains of a Norse settlement at L'Anse aux Meadows in Newfoundland. Carbon dating confirmed it was approximately a thousand years old. The Vikings had really been there. Leif Erikson, son of Erik the Red who had colonized Greenland, is credited with the first landing. According to the sagas, he explored three regions: Helluland (likely Baffin Island), Markland (likely Labrador), and Vinland, where wild grapes grew and salmon filled the rivers. Later expeditions attempted to establish permanent colonies. The most famous was led by Thorfinn Karlsefni, who brought perhaps 160 settlers, including women and cattle. They built houses, traded with the local Skraelings (their term for Indigenous peoples), and at least one child was born in the new land. But the relationship with the Skraelings deteriorated into violence. Outnumbered and far from support, the Norse abandoned their settlement after just a few years. Occasional voyages to Markland for timber continued for centuries, but no further colonization was attempted. The Vikings lacked the numbers, technology, and disease immunity that would later enable European conquest. They came too early. Their discovery was recorded in sagas passed down orally for generations, eventually written down in medieval Iceland. For most of history, scholars considered these tales folklore. Now we know they were memory.`,
    design_config: {"thumbnailColor":"#5D4037","titlePage":{"backgroundColor":"#5D4037","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#5D4037","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#5D4037"},{"background":"#0097A7","text":"#FFFFFF"},{"background":"#4A4A4A","text":"#FFFFFF"}],"imagePlaceholderColors":["#5D4037","#0097A7","#4A4A4A"],"imageAspectRatios":[1.4,0.85],"imageColorOffset":1,"imagePositionSeed":4}
  },
  {
    slug: "vasco-da-gama-india",
    title: "Da Gama Reaches India",
    description: "The voyage that built an empire",
    category: "Exploration",
    thumbnail_color: "#1B5E20",
    body_text: `On May 20, 1498, Vasco da Gama anchored off the coast of India. His arrival completed the quest that had obsessed Portuguese navigators for nearly a century: finding a sea route to the source of the spice trade. The voyage would make Portugal rich and begin Europe's domination of the Indian Ocean. Da Gama left Lisbon in July 1497 with four ships and about 170 men. He sailed down the coast of Africa, rounded the Cape of Good Hope, and headed north into waters no European had ever navigated. Crossing the Indian Ocean, he relied on an Arab pilot who knew the monsoon winds. When he reached Calicut, one of India's great trading ports, he expected to be welcomed as a representative of a powerful Christian kingdom. The reality was humiliating. Calicut was a sophisticated commercial center that had traded with the Arab world for centuries. Da Gama's gifts—cloth, coral, honey—were laughable by local standards. The ruler was unimpressed. Muslim merchants who controlled the existing trade saw the Portuguese as unwelcome competitors. Da Gama obtained a small cargo of spices through hostile negotiations and headed home. The return voyage was disastrous. Monsoon winds trapped the fleet in the Indian Ocean for months. Scurvy killed thirty men. One ship had to be abandoned for lack of crew to sail it. Only 54 of the original crew made it back to Lisbon. Despite the losses, the voyage was a triumph. The spices da Gama brought back were worth sixty times the cost of the expedition. Portugal sent larger fleets the following years, armed with cannons to blast away competitors. Within a decade, they had established fortified trading posts throughout the Indian Ocean. The Age of European empire in Asia had begun.`,
    design_config: {"thumbnailColor":"#1B5E20","titlePage":{"backgroundColor":"#1B5E20","textColor":"#FFD60A"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#1B5E20","text":"#FFFFFF"},{"background":"#FFD60A","text":"#000000"},{"background":"#FFFFFF","text":"#1B5E20"},{"background":"#4A4A4A","text":"#FFFFFF"}],"imagePlaceholderColors":["#1B5E20","#FFD60A","#4A4A4A"],"imageAspectRatios":[1.5,0.9],"imageColorOffset":0,"imagePositionSeed":2}
  },
  {
    slug: "humboldt-expedition",
    title: "Humboldt's Exploration",
    description: "The scientist who invented nature",
    category: "Exploration",
    thumbnail_color: "#2E7D32",
    body_text: `Alexander von Humboldt climbed volcanoes, sailed down the Orinoco, and collected thousands of specimens across South America. His five-year expedition transformed how humans understand the natural world. He invented the concept of ecology and drew connections between climate, geography, and life that scientists still study today. Humboldt was a Prussian aristocrat with insatiable curiosity. In 1799, he convinced the Spanish Crown to grant him access to their American colonies, a privilege rarely extended to foreigners. With French botanist Aimé Bonpland, he spent five years traveling from Venezuela to Peru, gathering data on everything from magnetic fields to plant distribution. The climb of Mount Chimborazo in Ecuador became famous. Humboldt and his companions reached 19,286 feet—higher than any human had documented at that time—before altitude sickness and a crevasse turned them back. On the descent, Humboldt sketched the mountain's vegetation zones, showing how plants changed with elevation in ways that paralleled changes with latitude. It was a revolutionary insight. Humboldt's influence was vast. Darwin read his books obsessively and credited them with inspiring the voyage of the Beagle. Thoreau devoured his works. Simón Bolívar considered him a friend. Scientists from multiple disciplines claimed him as a founder of their fields. He spent three decades writing about his travels. His "Cosmos" attempted to describe the entire physical world in a single work. The project remained unfinished at his death in 1859—the same year Darwin published "On the Origin of Species." Humboldt's name appears on more places and species than any other scientist: currents, mountains, towns, plants, and animals across five continents bear his name. The naturalist who wanted to understand everything became part of the nature he studied.`,
    design_config: {"thumbnailColor":"#2E7D32","titlePage":{"backgroundColor":"#2E7D32","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#2E7D32","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#2E7D32"},{"background":"#FFD60A","text":"#000000"},{"background":"#4A4A4A","text":"#FFFFFF"}],"imagePlaceholderColors":["#2E7D32","#FFD60A","#4A4A4A"],"imageAspectRatios":[1.4,0.85],"imageColorOffset":1,"imagePositionSeed":3}
  },
  {
    slug: "mars-rovers-journey",
    title: "The Mars Rovers",
    description: "The robots that walked another world",
    category: "Exploration",
    thumbnail_color: "#BF360C",
    body_text: `In January 2004, two robots the size of golf carts bounced to a stop on opposite sides of Mars. Spirit and Opportunity were designed for ninety-day missions. Together, they would operate for over twenty years, transforming our understanding of the Red Planet and proving that Mars was once wet. The twin rovers were engineering marvels adapted for an alien environment. Solar panels provided power during the day. Heaters kept their electronics from freezing during nights that dropped to minus 100 degrees. Each carried cameras, spectrometers, and a rock-grinding tool to examine the Martian surface in ways no previous mission had attempted. Spirit landed in Gusev Crater and spent six years exploring before getting stuck in soft soil. Even immobilized, it continued taking measurements until contact was lost in 2010. But Spirit was just the warm-up act. Opportunity exceeded every expectation. Designed to travel about 600 meters, it covered over 28 miles—a marathon on another planet. It found conclusive evidence that liquid water had once flowed on Mars: rippled sedimentary rocks, mineral deposits that could only form in the presence of water, even what appeared to be an ancient shoreline. For fifteen years, Opportunity sent home discoveries. It examined craters, photographed dust devils, and survived Martian winter storms that blocked the sun. In June 2018, a global dust storm darkened the sky so completely that the rover's solar panels couldn't generate power. Mission controllers waited months for the storm to clear, then sent over a thousand recovery commands. There was no response. On February 13, 2019, NASA declared the mission complete. The little rover that was supposed to last ninety days had explored Mars for over 5,000.`,
    design_config: {"thumbnailColor":"#BF360C","titlePage":{"backgroundColor":"#BF360C","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#BF360C","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#BF360C"},{"background":"#FF5722","text":"#FFFFFF"},{"background":"#4A4A4A","text":"#FFFFFF"}],"imagePlaceholderColors":["#BF360C","#FF5722","#4A4A4A"],"imageAspectRatios":[1.5,0.9],"imageColorOffset":0,"imagePositionSeed":4}
  },
  {
    slug: "percy-fawcett-disappearance",
    title: "The Lost City of Z",
    description: "The explorer who vanished in the Amazon",
    category: "Exploration",
    thumbnail_color: "#1B4332",
    body_text: `In 1925, Percy Fawcett walked into the Brazilian jungle searching for a lost city he called Z. He brought his son and his son's best friend. None of them were ever seen again. The mystery of their disappearance has spawned rescue missions, books, films, and over a dozen expeditions that tried and failed to find answers. Fawcett was a British Army officer who had spent years surveying the remote borderlands between Brazil, Bolivia, and Peru. He became convinced that a sophisticated ancient civilization had once existed in the Amazon, a theory that mainstream archaeology dismissed. Where others saw impenetrable jungle, Fawcett imagined hidden cities waiting to be discovered. He called his hypothetical city Z. The 1925 expedition was his eighth journey into the Amazon. At fifty-seven, Fawcett was no longer young, but he believed indigenous guides and small parties traveled more safely than large expeditions. He took only his twenty-one-year-old son Jack and Jack's friend Raleigh Rimell. They entered the Mato Grosso region in April. The last message Fawcett sent was dated May 29, from a place called Dead Horse Camp. It read, in part: "You need have no fear of any failure." Then silence. Over the following decades, more than a hundred people died attempting to find Fawcett or his remains. Various theories emerged: killed by Indians, starved in the wilderness, gone native and lived out his days with a tribe, murdered by his own son. Indigenous oral histories offer conflicting accounts. Modern archaeology has since vindicated Fawcett's central insight. The Amazon did support large, complex societies before European diseases decimated them. The ruins he sought exist, though they look nothing like the cities he imagined. Fawcett was right about the wrong thing, and his bones likely remain somewhere in the forest he loved.`,
    design_config: {"thumbnailColor":"#1B4332","titlePage":{"backgroundColor":"#1B4332","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#1B4332","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#1B4332"},{"background":"#FFD60A","text":"#000000"},{"background":"#4A4A4A","text":"#FFFFFF"}],"imagePlaceholderColors":["#1B4332","#FFD60A","#4A4A4A"],"imageAspectRatios":[1.4,0.85],"imageColorOffset":1,"imagePositionSeed":2}
  },
  {
    slug: "polar-expedition-nansen",
    title: "Nansen's Polar Drift",
    description: "The ship frozen for three years",
    category: "Exploration",
    thumbnail_color: "#37474F",
    body_text: `Fridtjof Nansen had a theory that seemed insane: build a ship strong enough to be frozen into Arctic ice, then drift with the ice across the polar basin. Scientists mocked him. The Norwegian government funded him anyway. The three-year expedition that followed changed everything we knew about the Arctic. Nansen designed the Fram with a rounded hull that would rise when squeezed by ice rather than being crushed. In September 1893, he sailed into the ice northeast of Siberia and let the frozen sea take him. For nearly three years, the Fram drifted, slowly carried by currents that Nansen correctly predicted would lead toward Greenland. The ship survived pressures that would have destroyed any conventional vessel. Scientific observations continued throughout. The crew measured ice thickness, water depth, temperature, and currents. They discovered that the Arctic Ocean was far deeper than anyone had suspected—in some places, over two miles. They found no land under the polar ice, disproving theories of an Arctic continent. In March 1895, with the ship still far from the pole, Nansen and one companion set out on foot and skis to reach 90 degrees north. They reached 86°14'—closer than any human had been—before deteriorating ice and dwindling supplies forced them to turn back. They spent the following winter in a hut they built on Franz Josef Land, surviving on walrus and polar bear until a chance encounter with a British expedition brought them home. The Fram emerged from the ice near Svalbard in August 1896, its crew healthy, its hull intact. Nansen's gamble had worked. The Arctic yielded its secrets to a man willing to let the ice carry him through.`,
    design_config: {"thumbnailColor":"#37474F","titlePage":{"backgroundColor":"#37474F","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#37474F","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#37474F"},{"background":"#90CAF9","text":"#000000"},{"background":"#4A4A4A","text":"#FFFFFF"}],"imagePlaceholderColors":["#37474F","#90CAF9","#4A4A4A"],"imageAspectRatios":[1.5,0.9],"imageColorOffset":0,"imagePositionSeed":3}
  },
  {
    slug: "ibn-battuta-travels",
    title: "Ibn Battuta's Journey",
    description: "The greatest traveler before jets",
    category: "Exploration",
    thumbnail_color: "#5D4037",
    body_text: `In 1325, a twenty-one-year-old law student left his home in Morocco to make the pilgrimage to Mecca. He would not return for twenty-four years. In that time, Ibn Battuta traveled approximately 75,000 miles—more than any other person in history before the age of steam. He visited every Islamic country and many non-Islamic ones, from West Africa to China. Ibn Battuta began with the Hajj but kept going. He crisscrossed the Middle East, sailed down the East African coast, crossed Central Asia to India, and spent years in the service of the Sultan of Delhi. He claimed to have visited Constantinople, Southeast Asia, and China, though some historians question these later journeys. Where Marco Polo's account focused on wonders and commerce, Ibn Battuta's reflects the life of a Muslim scholar traveling through a world connected by faith. He found hospitality wherever he went, staying with fellow scholars and religious figures, accepting positions as a judge, moving through a network of Islamic civilization that stretched from Spain to Indonesia. His descriptions of fourteenth-century life are invaluable. He witnessed the aftermath of the Black Death in Syria. He described Mali's gold trade and the Maldives' coconut economy. He recorded customs, religious practices, and political structures across dozens of societies, many of which left few other contemporary accounts. When Ibn Battuta finally returned to Morocco in 1354, the sultan ordered a scribe to record his memories. The result, the Rihla, is one of the great travel narratives of any era. Its author had seen more of the medieval world than perhaps anyone else who ever lived, carrying his civilization's learning from one end of the known world to the other.`,
    design_config: {"thumbnailColor":"#5D4037","titlePage":{"backgroundColor":"#5D4037","textColor":"#FFD60A"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#5D4037","text":"#FFFFFF"},{"background":"#FFD60A","text":"#000000"},{"background":"#FFFFFF","text":"#5D4037"},{"background":"#4A4A4A","text":"#FFFFFF"}],"imagePlaceholderColors":["#5D4037","#FFD60A","#4A4A4A"],"imageAspectRatios":[1.4,0.85],"imageColorOffset":1,"imagePositionSeed":4}
  },
  {
    slug: "challenger-expedition",
    title: "The Challenger Expedition",
    description: "The voyage that discovered the deep sea",
    category: "Exploration",
    thumbnail_color: "#0D47A1",
    body_text: `In 1872, a converted British warship set out to explore the most unknown territory on Earth: the ocean floor. The four-year voyage of HMS Challenger discovered 4,700 new species, mapped underwater mountain ranges, and proved that life existed at every depth. Modern oceanography begins with this expedition. The Challenger was equipped with laboratories, preserving equipment, and miles of rope for deep-sea dredging. Its crew of scientists, led by naturalist Charles Wyville Thomson, planned to sample the ocean systematically—measuring temperatures, collecting specimens, and charting depths at regular intervals across all major oceans. No one knew what they would find. At the time, many scientists believed the deep sea was a lifeless desert, too cold and dark for anything to survive. The Challenger proved them spectacularly wrong. The first dredge from deep water brought up creatures no human had ever seen: bizarre fish, delicate starfish, worms with bodies like glass. The deepest sounding—26,850 feet in what became known as the Challenger Deep in the Mariana Trench—revealed that ocean floors were far deeper than anyone had imagined. The expedition circumnavigated the globe, stopping at over 300 stations to take measurements and samples. The scientific party fought seasickness, cramped quarters, and the tedium of years at sea. Thomson himself never recovered from the strain and died before the expedition's results were fully published. Those results filled fifty volumes and took twenty years to complete. They described ocean currents, seafloor geology, and thousands of species new to science. The Challenger expedition taught humanity that most of our planet was underwater and that the deep sea teemed with life adapted to conditions we could barely imagine.`,
    design_config: {"thumbnailColor":"#0D47A1","titlePage":{"backgroundColor":"#0D47A1","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#0D47A1","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#0D47A1"},{"background":"#00BCD4","text":"#000000"},{"background":"#4A4A4A","text":"#FFFFFF"}],"imagePlaceholderColors":["#0D47A1","#00BCD4","#4A4A4A"],"imageAspectRatios":[1.5,0.9],"imageColorOffset":0,"imagePositionSeed":2}
  },
  {
    slug: "henry-the-navigator",
    title: "Henry the Navigator",
    description: "The prince who never sailed",
    category: "Exploration",
    thumbnail_color: "#1565C0",
    body_text: `Prince Henry of Portugal never navigated anywhere himself. He barely traveled at all. Yet he launched the European age of exploration, sending expeditions down the African coast that would eventually reach India and open the world to Portuguese trade. From his palace at Sagres, Henry changed history without leaving home. Henry was born in 1394, the third son of the Portuguese king. A successful military campaign against Muslim-held Ceuta in North Africa sparked his lifelong interest in what lay beyond the known world. He began sponsoring voyages down the African coast, pushing his captains to sail further than any European had ventured before. The obstacles were psychological as much as practical. Sailors believed the seas grew hotter as you traveled south, eventually boiling. They thought currents beyond certain points were too strong to sail against. Cape Bojador, a modest headland in what is now Western Sahara, was considered the point of no return. Henry's captains made fifteen attempts to pass it before Gil Eanes finally succeeded in 1434. Once that psychological barrier fell, progress accelerated. Portuguese ships reached modern Senegal, then the Cape Verde Islands, then the Gulf of Guinea. They found gold, slaves, and new trade goods. They brought back knowledge of winds and currents that would enable later voyages. Henry died in 1460, before his captains reached the southern tip of Africa. It would take another forty years before Vasco da Gama finally sailed to India. But the infrastructure Henry built—the shipbuilding techniques, the navigational expertise, the maps and records accumulated over decades—made those later achievements possible. The prince who never sailed to sea launched an empire that would span the globe.`,
    design_config: {"thumbnailColor":"#1565C0","titlePage":{"backgroundColor":"#1565C0","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#1565C0","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#1565C0"},{"background":"#FFD60A","text":"#000000"},{"background":"#4A4A4A","text":"#FFFFFF"}],"imagePlaceholderColors":["#1565C0","#FFD60A","#4A4A4A"],"imageAspectRatios":[1.4,0.85],"imageColorOffset":1,"imagePositionSeed":3}
  },
  {
    slug: "sally-ride-space",
    title: "Sally Ride",
    description: "America's first woman in space",
    category: "Exploration",
    thumbnail_color: "#7B1FA2",
    body_text: `On June 18, 1983, Sally Ride became the first American woman in space. She was thirty-two years old, a physicist, and had applied to NASA after seeing a recruitment ad in the Stanford student newspaper. Her flight aboard the Space Shuttle Challenger made her a reluctant celebrity and a symbol of changing times. Ride had joined NASA in 1978 as part of the first astronaut class to include women. The agency's selection was partly a response to legal pressure—federal law now prohibited sex discrimination—and partly recognition that the shuttle era would need different kinds of astronauts than the test pilots of the Mercury days. Ride was one of six women in a class of thirty-five. Her first flight lasted six days. She operated the shuttle's robotic arm, deploying communications satellites and conducting experiments. The media focused obsessively on her gender, asking questions about makeup, crying, and whether space flight would affect her reproductive system. Ride answered with dry wit and tried to redirect attention to the mission. She flew again in 1984 and was training for a third flight when the Challenger disaster grounded the shuttle program. She served on the commission that investigated the explosion and later led a NASA study on the agency's future direction. After leaving NASA, Ride became a physics professor and founded a company aimed at encouraging girls to study science. She remained intensely private about her personal life; only after her death in 2012 was it publicly revealed that she had been in a twenty-seven-year relationship with Tam O'Shaughnessy, making her the first known LGBT astronaut. Her obituary listed her partner by name. The barrier-breaking continued.`,
    design_config: {"thumbnailColor":"#7B1FA2","titlePage":{"backgroundColor":"#7B1FA2","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#7B1FA2","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#7B1FA2"},{"background":"#FFD60A","text":"#000000"},{"background":"#4A4A4A","text":"#FFFFFF"}],"imagePlaceholderColors":["#7B1FA2","#FFD60A","#4A4A4A"],"imageAspectRatios":[1.5,0.9],"imageColorOffset":0,"imagePositionSeed":4}
  },
  {
    slug: "james-webb-telescope",
    title: "The James Webb Telescope",
    description: "The eye that sees the beginning of time",
    category: "Exploration",
    thumbnail_color: "#FF9800",
    body_text: `On Christmas Day 2021, a telescope the size of a tennis court launched into space. The James Webb Space Telescope had taken three decades to build, survived countless budget crises, and required over three hundred potential failure points to work perfectly during deployment. If anything went wrong, there would be no repair mission. Everything worked. Webb reached its destination a million miles from Earth and began the delicate process of unfolding. Its golden hexagonal mirrors aligned. Its sunshield deployed. The instruments cooled to operating temperature, fifty degrees above absolute zero. On July 12, 2022, NASA released the first images. They showed the universe in ways humans had never seen. Webb's infrared sensors pierce the dust clouds that obscure visible light, revealing stellar nurseries where new stars are forming. Its sensitivity detects light that has traveled over thirteen billion years, showing galaxies as they existed just a few hundred million years after the Big Bang. Its spectroscopic instruments analyze the atmospheres of planets orbiting distant stars, searching for chemical signatures that might indicate life. Early observations have already challenged existing theories. Webb found galaxies in the early universe that appear too large and mature to fit current models of cosmic evolution. It detected water vapor and carbon dioxide in the atmosphere of a planet forty light-years away. It captured images of Jupiter's rings and auroras in unprecedented detail. The telescope is expected to operate for at least twenty years, perhaps longer. Each observation extends humanity's vision deeper into space and further back in time. We built a machine to see the beginning of the universe, and it is showing us wonders we couldn't have imagined.`,
    design_config: {"thumbnailColor":"#FF9800","titlePage":{"backgroundColor":"#FF9800","textColor":"#000000"},"colorPalette":[{"background":"#000000","text":"#FF9800"},{"background":"#FF9800","text":"#000000"},{"background":"#FFFFFF","text":"#FF9800"},{"background":"#1A237E","text":"#FFFFFF"},{"background":"#4A4A4A","text":"#FFFFFF"}],"imagePlaceholderColors":["#FF9800","#1A237E","#4A4A4A"],"imageAspectRatios":[1.4,0.85],"imageColorOffset":1,"imagePositionSeed":2}
  },
  {
    slug: "source-of-nile",
    title: "The Search for the Nile",
    description: "The obsession that consumed explorers",
    category: "Exploration",
    thumbnail_color: "#00695C",
    body_text: `For over two thousand years, finding the source of the Nile was one of geography's great mysteries. The ancient Egyptians didn't know where their life-giving river began. Neither did the Romans, the Arabs, or anyone else until the mid-nineteenth century, when European explorers turned the search into a competition that cost lives and reputations. The Nile flows north through desert where rain almost never falls. The river's annual flood, which fertilized Egyptian fields with nutrient-rich silt, seemed to come from nowhere. Ancient writers speculated about mountain springs, hidden lakes, or divine intervention. The Interior of Africa remained blank on European maps. In 1857, Richard Burton and John Hanning Speke set out from Zanzibar to find the source. They reached Lake Tanganyika, but Burton fell ill, and Speke traveled north alone to discover a vast body of water he named Lake Victoria. He claimed it was the source. Burton disagreed. The rivalry between the two men became bitter and public. Speke died in a hunting accident the day before a scheduled public debate with Burton—possibly suicide, though it was officially ruled accidental. More expeditions followed. David Livingstone searched for years, growing obsessed with proving a connection between the Nile and the Congo River systems. He was wrong, but his exploration added to the map. Samuel Baker confirmed that Lake Victoria's waters flowed north. Henry Morton Stanley circumnavigated the lake and traced the White Nile to its outlet. By the 1870s, the mystery was essentially solved. The Nile's source was Lake Victoria, fed by rivers flowing from the mountains of Burundi and Rwanda. The search was over. The scramble for Africa was just beginning.`,
    design_config: {"thumbnailColor":"#00695C","titlePage":{"backgroundColor":"#00695C","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#00695C","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#00695C"},{"background":"#FFD60A","text":"#000000"},{"background":"#4A4A4A","text":"#FFFFFF"}],"imagePlaceholderColors":["#00695C","#FFD60A","#4A4A4A"],"imageAspectRatios":[1.5,0.9],"imageColorOffset":0,"imagePositionSeed":3}
  },
  {
    slug: "amelia-earhart-disappearance",
    title: "Amelia Earhart's Disappearance",
    description: "The aviator who vanished over the Pacific",
    category: "Exploration",
    thumbnail_color: "#5D4037",
    body_text: `On July 2, 1937, Amelia Earhart and navigator Fred Noonan took off from New Guinea on the longest leg of their attempt to circumnavigate the globe. They were headed for Howland Island, a tiny speck in the Pacific less than two miles long. They never arrived. The most famous woman aviator in history simply disappeared. Earhart had already made history several times over. She was the first woman to fly across the Atlantic, first as a passenger in 1928, then solo in 1932. She set speed and altitude records. She became a celebrity, endorsing products and writing bestselling books about her adventures. The around-the-world flight was meant to be her greatest achievement. The Lockheed Electra she flew was equipped with the best technology of the era, including radio direction-finding equipment that should have guided her to Howland Island. A Coast Guard ship waited at Howland, ready to signal her location. Weather conditions were marginal but manageable. Something went wrong. Radio transmissions from Earhart grew increasingly frantic as she failed to locate the island. "We must be on you but cannot see you," she reported. "Gas is running low." Her last confirmed transmission came at 8:43 AM local time. Then silence. The search that followed was the most expensive and extensive in history to that point. Ships and planes scoured 250,000 square miles of ocean. They found nothing. Earhart was declared dead in absentia in 1939. Theories about her fate have proliferated ever since. She crashed into the ocean and sank. She landed on a deserted island and died as a castaway. She was captured by the Japanese. Each theory has proponents and evidence; none is conclusive. The Pacific keeps its secrets well.`,
    design_config: {"thumbnailColor":"#5D4037","titlePage":{"backgroundColor":"#5D4037","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#5D4037","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#5D4037"},{"background":"#0097A7","text":"#FFFFFF"},{"background":"#4A4A4A","text":"#FFFFFF"}],"imagePlaceholderColors":["#5D4037","#0097A7","#4A4A4A"],"imageAspectRatios":[1.4,0.85],"imageColorOffset":1,"imagePositionSeed":4}
  }
];

async function uploadStory(story) {
  const response = await fetch(`${SUPABASE_URL}/rest/v1/stories`, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      "apikey": SUPABASE_KEY,
      "Authorization": `Bearer ${SUPABASE_KEY}`,
      "Prefer": "resolution=merge-duplicates,return=minimal"
    },
    body: JSON.stringify({
      slug: story.slug,
      title: story.title,
      description: story.description,
      category: story.category,
      thumbnail_color: story.thumbnail_color,
      published: true,
      published_at: new Date().toISOString(),
      body_text: story.body_text,
      design_config: story.design_config,
      updated_at: new Date().toISOString()
    })
  });

  if (!response.ok) {
    const text = await response.text();
    throw new Error(`${response.status}: ${text}`);
  }
}

async function main() {
  console.log(`Uploading ${stories.length} Exploration stories to Supabase...\n`);

  let success = 0;
  let failed = 0;

  for (const story of stories) {
    try {
      process.stdout.write(`Uploading: ${story.title}... `);
      await uploadStory(story);
      console.log("Done!");
      success++;
    } catch (error) {
      console.log(`Error: ${error.message}`);
      failed++;
    }
  }

  console.log(`\nComplete! ${success} succeeded, ${failed} failed.`);
}

main();
