/**
 * Medieval Category - 25 New Stories (500-1500 CE)
 * Usage: node scripts/new-content/medieval-new.mjs
 */

const SUPABASE_URL = "https://egfwisgqdyhzpmeoracb.supabase.co";
const SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVnZndpc2dxZHloenBtZW9yYWNiIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2ODQyNzM0OSwiZXhwIjoyMDg0MDAzMzQ5fQ.S8h1fIepxWb44gPSPpWQ8fE0Q-SCYfL0QcBRUV7fXgs";

const stories = [
  {
    slug: "battle-of-hastings",
    title: "The Battle of Hastings",
    description: "The arrow that changed England forever",
    category: "Medieval",
    thumbnail_color: "#5D4037",
    body_text: `On October 14, 1066, two armies faced each other on a hill near the English coast. By nightfall, the last Anglo-Saxon king would be dead, and England would belong to a French-speaking duke who had crossed the Channel with a claim, an army, and extraordinary luck. The Battle of Hastings would reshape the English language, law, and culture for a thousand years. Harold Godwinson had been king for barely nine months. He had seized the throne after Edward the Confessor died childless, but his claim was contested. Harald Hardrada of Norway invaded from the north. William of Normandy prepared to invade from the south. Harold marched his army north and crushed the Vikings at Stamford Bridge, then turned and force-marched two hundred miles south to meet the Normans. His men were exhausted before the battle began. The English fought on foot, forming a shield wall on Senlac Hill. The Normans attacked with cavalry, archers, and infantry but couldn't break through. For hours, the battle swayed back and forth. Norman horses couldn't climb the steep slope against the wall of shields. Rumors spread that William had fallen. He lifted his helmet to show his face, rallying his troops. The turning point came when Norman cavalry feigned retreat. English soldiers broke formation to pursue, and the Normans turned and cut them down. The shield wall thinned. Late in the afternoon, an arrow struck Harold in the eye, or so the Bayeux Tapestry suggests. He fell, and the English army collapsed. William was crowned on Christmas Day in Westminster Abbey. French became the language of the court. Norman lords replaced Anglo-Saxon nobles. The Domesday Book catalogued every acre of the conquered land. England would never be invaded again, but it would never be the same.`,
    design_config: {"thumbnailColor":"#5D4037","titlePage":{"backgroundColor":"#5D4037","textColor":"#FFD60A"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#5D4037","text":"#FFFFFF"},{"background":"#FFD60A","text":"#000000"},{"background":"#FFFFFF","text":"#5D4037"},{"background":"#8D6E63","text":"#FFFFFF"}],"imagePlaceholderColors":["#5D4037","#FFD60A","#8D6E63"],"imageAspectRatios":[1.4,0.85],"imageColorOffset":0,"imagePositionSeed":2}
  },
  {
    slug: "signing-of-magna-carta",
    title: "The Signing of Magna Carta",
    description: "When a king was forced to bow to law",
    category: "Medieval",
    thumbnail_color: "#1565C0",
    body_text: `On June 15, 1215, King John of England rode to a meadow called Runnymede and affixed his seal to a document that would echo through the centuries. The rebellious barons who had forced this meeting didn't know they were creating the foundation of constitutional government. They just wanted their privileges protected from a king they despised. John was a disaster as a monarch. He had lost Normandy to the French king. He had quarreled with the Pope so badly that England was placed under interdict, with churches closed and sacraments suspended. He had taxed his barons relentlessly to fund failed military campaigns. By 1215, a coalition of nobles had had enough. They captured London and demanded reform. The document they forced John to accept was called the Great Charter, Magna Carta in Latin. Most of its sixty-three clauses addressed specific grievances of the feudal aristocracy. Widows couldn't be forced to remarry. The king couldn't seize property without proper legal process. Taxes required consent. But buried in the legalese were principles that would grow far beyond their original intent. Clause 39 declared that no free man could be imprisoned or stripped of his rights except by the lawful judgment of his peers or the law of the land. Clause 40 promised that the king would not sell, deny, or delay justice. John had no intention of honoring the agreement. Within weeks, he had convinced the Pope to annul it. Civil war erupted. John died the following year, and his young son Henry III reissued the charter to buy peace. Over the following centuries, Magna Carta was repeatedly confirmed and reinterpreted. The American founding fathers cited it when drafting the Constitution. The principle that even kings must obey the law had taken root.`,
    design_config: {"thumbnailColor":"#1565C0","titlePage":{"backgroundColor":"#1565C0","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#1565C0","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#1565C0"},{"background":"#C4B39A","text":"#000000"},{"background":"#14213D","text":"#FFFFFF"}],"imagePlaceholderColors":["#1565C0","#C4B39A","#14213D"],"imageAspectRatios":[1.5,0.9],"imageColorOffset":1,"imagePositionSeed":3}
  },
  {
    slug: "viking-siege-of-paris",
    title: "The Viking Siege of Paris",
    description: "When Northmen attacked the heart of Francia",
    category: "Medieval",
    thumbnail_color: "#37474F",
    body_text: `In November 885, a fleet of seven hundred Viking ships appeared on the Seine, carrying an army of thirty thousand warriors. Their target was Paris, and they would besiege the city for over a year in one of the most dramatic confrontations between the Norse raiders and Christian Europe. Paris in the ninth century was a fraction of its modern size, confined to an island in the river. But it controlled the Seine, and the Vikings needed to pass to raid the rich lands upstream. Count Odo of Paris, commanding a garrison of perhaps two hundred knights, refused to let them through. The Vikings attacked the fortified bridges that blocked their path. They built siege towers and battering rams. They launched fire ships against the wooden structures. The defenders poured boiling oil and threw burning pitch. Both sides fought with desperate determination. The siege dragged on through winter. Disease swept the Viking camp. The bridges held. But no help came from the Carolingian emperor, Charles the Fat, who was busy elsewhere with his own troubles. When Charles finally arrived with an army in the fall of 886, the defenders expected relief. Instead, the emperor negotiated. He paid the Vikings seven hundred pounds of silver and gave them permission to sail upstream and raid Burgundy, which was in rebellion against him anyway. The Vikings got their plunder. Paris survived, but at the cost of imperial prestige. Count Odo emerged as a hero. Within two years, Charles the Fat had been deposed, and Odo was elected king of West Francia. The siege had demonstrated that local lords could defend what distant emperors could not. The age of feudal fragmentation was beginning.`,
    design_config: {"thumbnailColor":"#37474F","titlePage":{"backgroundColor":"#37474F","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#37474F","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#37474F"},{"background":"#5C6BC0","text":"#FFFFFF"},{"background":"#C4B39A","text":"#000000"}],"imagePlaceholderColors":["#37474F","#5C6BC0","#C4B39A"],"imageAspectRatios":[1.4,0.85],"imageColorOffset":0,"imagePositionSeed":4}
  },
  {
    slug: "first-crusade",
    title: "The First Crusade",
    description: "When Europe marched to Jerusalem",
    category: "Medieval",
    thumbnail_color: "#C62828",
    body_text: `In 1095, Pope Urban II stood before a crowd at Clermont and called on the knights of Christendom to liberate Jerusalem from Muslim rule. The response exceeded all expectations. Within three years, a ragged army of European nobles and peasants had crossed a continent, endured unimaginable hardships, and captured the Holy City in a bloodbath that shocked even contemporary observers. The crusade began as a response to Byzantine requests for military assistance against the Seljuk Turks. Urban saw an opportunity to channel the violent energies of European knights toward a holy cause while healing the rift between the Eastern and Western churches. He promised spiritual rewards: crusaders would receive remission of sins, and those who died would be martyrs. Thousands took the cross. Peasant bands set out first, slaughtering Jewish communities in the Rhineland before being annihilated by the Turks in Anatolia. The main army of nobles followed, marching through Constantinople into hostile territory with inadequate supplies and no unified command. They besieged Antioch for eight months, nearly starving before capturing the city. By the time they reached Jerusalem in June 1099, perhaps fifteen thousand crusaders remained from an initial force ten times that size. The siege lasted five weeks. On July 15, the walls were breached. What followed was a massacre. Chronicles report blood running ankle-deep in the streets. Muslim and Jewish inhabitants were slaughtered indiscriminately. The Dome of the Rock was looted. Synagogues filled with refugees were burned. The victors wept with joy at the Church of the Holy Sepulchre, their armor still wet with blood. The crusader states established in the aftermath would survive for two centuries. The religious hatred unleashed that day would endure far longer.`,
    design_config: {"thumbnailColor":"#C62828","titlePage":{"backgroundColor":"#C62828","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#C62828","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#C62828"},{"background":"#FFD60A","text":"#000000"},{"background":"#14213D","text":"#FFFFFF"}],"imagePlaceholderColors":["#C62828","#FFD60A","#14213D"],"imageAspectRatios":[1.5,0.9],"imageColorOffset":1,"imagePositionSeed":2}
  },
  {
    slug: "rise-of-knights-templar",
    title: "The Rise of the Knights Templar",
    description: "Warrior monks who became bankers",
    category: "Medieval",
    thumbnail_color: "#F5F5F5",
    body_text: `In 1119, a French knight named Hugues de Payens founded a small religious order in Jerusalem. Its members took vows of poverty, chastity, and obedience, like monks. They also swore to protect Christian pilgrims traveling to the Holy Land, like soldiers. The Knights Templar would become the most powerful and controversial military order in medieval history. The order grew rapidly. The Church showered it with privileges: exemption from taxes, freedom from local laws, the right to build their own churches. Donations poured in from across Europe. Within decades, the Templars had evolved from a handful of impoverished knights into a multinational organization with thousands of members and vast property holdings. Their military reputation was formidable. Templar knights formed the shock troops of crusader armies, recognizable by their white mantles emblazoned with red crosses. They fought with fanatical courage, forbidden to retreat unless outnumbered at least three to one. They built massive castles throughout the Holy Land. Saladin considered them his most dangerous enemies. But the Templars' greatest innovation was financial. Pilgrims could deposit money at Templar houses in Europe and withdraw it in Jerusalem, avoiding the dangers of carrying wealth across hostile territory. The order became a bank, lending money to kings and managing the finances of kingdoms. Their treasury in Paris was one of the largest in Europe. Success bred envy. When the last crusader territories fell in 1291, the Templars lost their original purpose. King Philip IV of France, deeply in debt to the order, saw an opportunity. In 1307, he had the French Templars arrested en masse and charged with heresy, blasphemy, and sodomy. Under torture, many confessed to fantastic crimes. The Pope dissolved the order in 1312. Its last Grand Master was burned at the stake. The Templars vanished into legend, but speculation about their hidden treasures and secret knowledge has never ceased.`,
    design_config: {"thumbnailColor":"#F5F5F5","titlePage":{"backgroundColor":"#F5F5F5","textColor":"#C62828"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#F5F5F5","text":"#C62828"},{"background":"#C62828","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#000000"},{"background":"#14213D","text":"#FFFFFF"}],"imagePlaceholderColors":["#F5F5F5","#C62828","#14213D"],"imageAspectRatios":[1.4,0.85],"imageColorOffset":0,"imagePositionSeed":3}
  },
  {
    slug: "great-schism-1054",
    title: "The Great Schism",
    description: "When Christianity split in two",
    category: "Medieval",
    thumbnail_color: "#6A1B9A",
    body_text: `On July 16, 1054, a papal legate strode into the Hagia Sophia in Constantinople and laid a document on the altar. It was a bull of excommunication, declaring the Patriarch of Constantinople and his followers cut off from the true Church. The patriarch responded by excommunicating the legate. The Christian world, united in theory for a millennium, was formally divided into Catholic West and Orthodox East. The split had been centuries in the making. Rome and Constantinople had drifted apart as the Western Roman Empire fell and the Eastern Empire evolved into something distinctly Greek. They spoke different languages, followed different customs, and answered to different powers. Theological disputes accumulated: Did the Holy Spirit proceed from the Father alone, or from the Father and the Son? Should priests marry? Should leavened or unleavened bread be used in communion? The immediate crisis centered on politics as much as theology. Pope Leo IX sought to assert Rome's supremacy over the entire Church. Patriarch Michael Cerularius refused to acknowledge papal authority. When Cardinal Humbert arrived as Leo's representative, the confrontation was inevitable. Humbert's excommunication was technically irregular, since Pope Leo had died before it was issued. Cerularius's response was equally problematic. Neither side had really excommunicated the other's entire church, just specific individuals. Yet the breach proved permanent. Attempts at reconciliation foundered on pride and practicality. The crusades deepened the divide, culminating in the Fourth Crusade's sack of Constantinople in 1204. By the time the Byzantine Empire fell to the Ottomans in 1453, centuries of separation had made reunion impossible. The excommunications weren't lifted until 1965. Even then, the churches remained separate. The schism shaped the religious geography of Europe and the Orthodox world that persists today.`,
    design_config: {"thumbnailColor":"#6A1B9A","titlePage":{"backgroundColor":"#6A1B9A","textColor":"#FFD60A"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#6A1B9A","text":"#FFFFFF"},{"background":"#FFD60A","text":"#000000"},{"background":"#FFFFFF","text":"#6A1B9A"},{"background":"#14213D","text":"#FFFFFF"}],"imagePlaceholderColors":["#6A1B9A","#FFD60A","#14213D"],"imageAspectRatios":[1.5,0.9],"imageColorOffset":1,"imagePositionSeed":4}
  },
  {
    slug: "albigensian-crusade",
    title: "The Albigensian Crusade",
    description: "When the Church crusaded against Christians",
    category: "Medieval",
    thumbnail_color: "#BF360C",
    body_text: `In 1209, Pope Innocent III launched a crusade unlike any before. The target wasn't Muslim infidels in the Holy Land but Christian heretics in southern France. Over two decades, the Albigensian Crusade would devastate one of Europe's most cultured regions and establish the Inquisition as a permanent institution of the Church. The Cathars believed the material world was evil, created by a malevolent deity. They rejected the Church's sacraments, its hierarchy, and its wealth. They called their most devoted followers "perfects," who lived lives of extreme asceticism. The faith spread rapidly through Languedoc, attracting nobles and commoners alike, threatening Rome's authority in a prosperous region that had developed its own distinct culture. The Pope tried persuasion first. When his legate was murdered, possibly by a vassal of the Count of Toulouse, he called for a crusade. Northern French knights answered eagerly, drawn by promises of lands and salvation. The first major atrocity came at Beziers, where the crusaders massacred the entire population, perhaps twenty thousand people. Asked how to distinguish Catholics from Cathars, the papal legate allegedly replied, "Kill them all. God will know his own." The war dragged on for decades. Fortified Cathar strongholds fell one by one. The last major fortress, Montsegur, surrendered in 1244 after a ten-month siege. Over two hundred Cathars who refused to recant were burned alive in a single day. The Inquisition hunted the remaining believers for another century. By 1350, Catharism had been exterminated. The distinct culture of Languedoc was absorbed into France. The region that had produced troubadour poetry and religious tolerance had been brought to heel. The Church had proven it could crush dissent with military force, a lesson that would resonate through the religious wars to come.`,
    design_config: {"thumbnailColor":"#BF360C","titlePage":{"backgroundColor":"#BF360C","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#BF360C","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#BF360C"},{"background":"#FFD60A","text":"#000000"},{"background":"#4A4A4A","text":"#FFFFFF"}],"imagePlaceholderColors":["#BF360C","#FFD60A","#4A4A4A"],"imageAspectRatios":[1.4,0.85],"imageColorOffset":0,"imagePositionSeed":2}
  },
  {
    slug: "marco-polo-returns",
    title: "Marco Polo's Return",
    description: "The traveler no one believed",
    category: "Medieval",
    thumbnail_color: "#00695C",
    body_text: `In 1295, three ragged strangers appeared at a palazzo in Venice, claiming to be the Polo family who had departed for China twenty-four years earlier. No one recognized them. Their relatives had long since divided their property, assuming they were dead. When they produced jewels sewn into their Mongol clothing, skepticism gave way to astonishment. The greatest journey in medieval history had ended. Marco Polo had been seventeen when he left Venice with his father and uncle, merchants who had already made one trip to the court of Kublai Khan. They traveled overland along the Silk Road, through deserts and mountain passes, reaching the Mongol capital after three and a half years. Marco would remain in the Khan's service for seventeen years. The Khan sent him on missions throughout his vast empire. Marco saw things no European had ever seen: paper money, coal burned for fuel, asbestos cloth, printing, and the Grand Canal. He described cities larger than any in Europe, where merchants grew wealthy beyond imagination. He traveled to Burma, Vietnam, and possibly to the coast of China's southernmost reaches. When the Polos finally received permission to leave, they escorted a Mongol princess to Persia by sea, a voyage that took two years and killed hundreds of their fellow travelers. They arrived home to find that Venice was at war with Genoa. Marco was captured in a naval battle and imprisoned. In his cell, he dictated his travels to a writer of romances. The resulting book, "The Travels of Marco Polo," was an immediate sensation and an enduring controversy. Critics called him a liar. He had omitted obvious things like the Great Wall and tea. Had he really been to China, or merely collected tales from other travelers? Scholars still debate the question. On his deathbed, asked to admit he had exaggerated, Marco allegedly replied, "I did not tell half of what I saw."`,
    design_config: {"thumbnailColor":"#00695C","titlePage":{"backgroundColor":"#00695C","textColor":"#FFD60A"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#00695C","text":"#FFFFFF"},{"background":"#FFD60A","text":"#000000"},{"background":"#FFFFFF","text":"#00695C"},{"background":"#C4B39A","text":"#000000"}],"imagePlaceholderColors":["#00695C","#FFD60A","#C4B39A"],"imageAspectRatios":[1.5,0.9],"imageColorOffset":1,"imagePositionSeed":3}
  },
  {
    slug: "hundred-years-war-begins",
    title: "The Hundred Years' War Begins",
    description: "The conflict that defined two nations",
    category: "Medieval",
    thumbnail_color: "#1A237E",
    body_text: `In 1337, King Edward III of England claimed the throne of France, launching a dynastic struggle that would last 116 years, devastate the French countryside, transform military technology, and forge the national identities of both England and France. The Hundred Years' War was really a series of wars, punctuated by truces and periods of uneasy peace. Edward's claim came through his mother, daughter of a French king. French lawyers countered that the crown could not pass through the female line. What followed was medieval Europe's longest and bloodiest conflict. The English won early and spectacularly. At Crecy in 1346, English longbowmen slaughtered the flower of French chivalry. Armored knights on horseback, the dominant military force for centuries, were cut down by commoners with bows. At Poitiers in 1356, the English captured the French king himself. A decade later, the Treaty of Bretigny gave Edward vast territories and an enormous ransom. But France refused to stay defeated. Under Charles V, the French avoided pitched battles and slowly reclaimed their territories. The English were reduced to coastal enclaves. A generation of relative peace followed, as both kingdoms struggled with internal conflicts and the Black Death ravaged Europe. The war resumed in 1415 when Henry V invaded and achieved the stunning victory at Agincourt. By 1420, the Treaty of Troyes made him heir to the French throne. But Henry died young, leaving an infant son. France seemed conquered. Then a peasant girl from Lorraine claimed that saints had commanded her to drive out the English. Joan of Arc's brief, incandescent career would turn the tide of the war and create the most enduring legend of the medieval age.`,
    design_config: {"thumbnailColor":"#1A237E","titlePage":{"backgroundColor":"#1A237E","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#1A237E","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#1A237E"},{"background":"#C62828","text":"#FFFFFF"},{"background":"#FFD60A","text":"#000000"}],"imagePlaceholderColors":["#1A237E","#C62828","#FFD60A"],"imageAspectRatios":[1.4,0.85],"imageColorOffset":0,"imagePositionSeed":4}
  },
  {
    slug: "battle-of-agincourt",
    title: "The Battle of Agincourt",
    description: "When the few defeated the many",
    category: "Medieval",
    thumbnail_color: "#2E7D32",
    body_text: `On October 25, 1415, a sick and starving English army faced a French force that outnumbered them perhaps five to one. By nightfall, the flower of French nobility lay dead in the mud, and King Henry V had won one of history's most improbable victories. The Battle of Agincourt would become a symbol of English valor and a template for underdog triumphs forever after. Henry had invaded France to press his claim to the throne, but the campaign had gone badly. Dysentery devastated his army during the siege of Harfleur. When the town finally fell, Henry had barely six thousand men fit to fight. Rather than retreat directly to England, he chose to march to Calais, a gesture of defiance that brought the French army down upon him. The French blocked his path near the village of Agincourt. Their army was fresh, well-fed, and confident. They had learned nothing from Crecy or Poitiers, still believing that armored knights could overwhelm any foe. They positioned themselves in a narrow field between two woods, limiting their own ability to maneuver. Rain had fallen all night, turning the freshly plowed field into a quagmire. Henry placed his longbowmen on the flanks, protected by sharpened stakes. When the French cavalry charged, they were funneled into a killing ground. Horses and men fell in heaps. The mud was so deep that armored knights who stumbled couldn't rise. English archers, dropping their bows, waded into the melee with swords and mallets, slaughtering helpless Frenchmen trapped in the mire. The killing lasted for hours. French casualties may have exceeded ten thousand, including three dukes, ninety nobles, and over fifteen hundred knights. The English lost perhaps a hundred men. Henry V was master of France. Shakespeare would immortalize the victory, putting words in Henry's mouth that would define English self-image: "We few, we happy few, we band of brothers."`,
    design_config: {"thumbnailColor":"#2E7D32","titlePage":{"backgroundColor":"#2E7D32","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#2E7D32","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#2E7D32"},{"background":"#FFD60A","text":"#000000"},{"background":"#1A237E","text":"#FFFFFF"}],"imagePlaceholderColors":["#2E7D32","#FFD60A","#1A237E"],"imageAspectRatios":[1.5,0.9],"imageColorOffset":1,"imagePositionSeed":2}
  },
  {
    slug: "medieval-inquisition",
    title: "The Medieval Inquisition",
    description: "When the Church hunted heresy",
    category: "Medieval",
    thumbnail_color: "#4A148C",
    body_text: `In 1231, Pope Gregory IX established a systematic institution to investigate and prosecute heresy throughout Christendom. The Inquisition would operate for centuries, developing procedures for investigation, torture, and punishment that became templates for state terror. Its legacy haunts debates about religious freedom and the abuse of power to this day. The Inquisition grew from the Church's struggle against the Cathars. Local bishops had proven too lenient or too corrupt to root out heresy effectively. The Pope appointed special investigators, inquisitors, drawn primarily from the new Dominican order. They answered to Rome, not local authorities. Their mandate was to save souls, by any means necessary. The procedures were chillingly methodical. An inquisitor would arrive in a town and proclaim a "period of grace," during which anyone who confessed to heresy would receive a light penance. After the grace period, investigations began. Inquisitors relied on denunciations, often anonymous. The accused were not told who had testified against them. Defense was nearly impossible. Torture was authorized by Pope Innocent IV in 1252 to extract confessions. The methods were carefully regulated to avoid drawing blood or causing death, not from mercy but because the Church technically opposed bloodshed. Confessed heretics who repented received penances ranging from prayers to pilgrimage to life imprisonment. Those who refused to confess, or who relapsed after repenting, were "relaxed to the secular arm," a euphemism meaning they were handed to civil authorities for execution, usually by burning. The Church maintained the fiction that it didn't kill anyone. The Inquisition's power varied by region and era. In some areas, it was relatively restrained. In others, particularly during later periods like the Spanish Inquisition, it became an instrument of systematic persecution. But its core innovation, a bureaucracy dedicated to enforcing ideological conformity, proved terrifyingly durable.`,
    design_config: {"thumbnailColor":"#4A148C","titlePage":{"backgroundColor":"#4A148C","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#4A148C","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#4A148C"},{"background":"#BF360C","text":"#FFFFFF"},{"background":"#14213D","text":"#FFFFFF"}],"imagePlaceholderColors":["#4A148C","#BF360C","#14213D"],"imageAspectRatios":[1.4,0.85],"imageColorOffset":0,"imagePositionSeed":3}
  },
  {
    slug: "charlemagne-crowned-emperor",
    title: "Charlemagne Crowned Emperor",
    description: "The moment Rome was reborn",
    category: "Medieval",
    thumbnail_color: "#FFD60A",
    body_text: `On Christmas Day in the year 800, Pope Leo III placed a crown on the head of Charles, King of the Franks, and declared him Roman Emperor. The crowd in St. Peter's Basilica roared their approval. The Western Roman Empire, dead for over three centuries, had been resurrected. Or so the ceremony proclaimed. Charles, known to history as Charlemagne, had spent thirty years building the largest European empire since antiquity. Through relentless campaigning, he had conquered the Lombards in Italy, the Saxons in Germany, and the Avars in Hungary. His realm stretched from the Atlantic to the Elbe, from the North Sea to Rome. He promoted learning, standardized coinage, and attempted to create a uniform legal system. Whether Charlemagne wanted the title is unclear. Some sources suggest he was surprised by the coronation, though this may have been diplomatic fiction designed to avoid offending the Byzantine emperors, who considered themselves the only legitimate Roman emperors. The Pope had his own motives: placing the crown on Charlemagne's head established that emperors received their authority from the Church. The coronation reshaped European politics for centuries. The idea that there could and should be a universal Christian empire in the West became fixed in the medieval imagination. Charlemagne's successors fought endlessly over the title. The Holy Roman Empire that eventually emerged from his legacy would survive until 1806, though Voltaire famously observed that it was neither holy, nor Roman, nor an empire. The partnership between emperors and popes that began that Christmas Day would define European history for the next seven hundred years, producing both creative collaboration and devastating conflict. The dream of a unified Christian Europe, first embodied in Charlemagne, has never entirely died.`,
    design_config: {"thumbnailColor":"#FFD60A","titlePage":{"backgroundColor":"#FFD60A","textColor":"#1A237E"},"colorPalette":[{"background":"#000000","text":"#FFD60A"},{"background":"#FFD60A","text":"#000000"},{"background":"#1A237E","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#1A237E"},{"background":"#6A1B9A","text":"#FFFFFF"}],"imagePlaceholderColors":["#FFD60A","#1A237E","#6A1B9A"],"imageAspectRatios":[1.5,0.9],"imageColorOffset":1,"imagePositionSeed":4}
  },
  {
    slug: "murder-of-thomas-becket",
    title: "The Murder of Thomas Becket",
    description: "The killing that shocked Christendom",
    category: "Medieval",
    thumbnail_color: "#B71C1C",
    body_text: `On December 29, 1170, four knights rode into Canterbury Cathedral, found the Archbishop of Canterbury at prayer, and hacked him to death before the altar. The murder of Thomas Becket sent shockwaves through medieval Europe. Within three years, he was declared a saint. His shrine became one of Christianity's greatest pilgrimage sites. The king whose careless words had inspired the killing spent the rest of his reign doing penance. Becket and Henry II had once been the closest of friends. Henry, one of the most powerful kings in English history, had appointed his chancellor and drinking companion as Archbishop, expecting Becket to remain loyal. Instead, Becket transformed. He resigned as chancellor, adopted an ascetic lifestyle, and began defending Church privileges against royal authority with inflexible determination. The conflict centered on the question of whether clergy who committed crimes could be tried in royal courts. Becket insisted they could only be judged by Church courts, which imposed lighter sentences. Henry saw this as an invitation to lawlessness. The dispute escalated until Becket fled to France, where he remained in exile for six years. A reconciliation brought him back to England in 1170, but he immediately excommunicated bishops who had sided with Henry. When Henry, then in Normandy, heard the news, he flew into a rage. According to legend, he cried, "Will no one rid me of this turbulent priest?" Four knights took the words as a command. They crossed to England, confronted Becket in his own cathedral, and killed him when he refused to yield. The murder transformed Becket from a stubborn prelate into a martyr. Miracles were reported at his tomb within days. Pilgrims came from across Europe. Henry, facing a papal interdict, performed public penance, walking barefoot through Canterbury while monks flogged him. The Church had won. No king would challenge clerical privilege so directly for another three centuries.`,
    design_config: {"thumbnailColor":"#B71C1C","titlePage":{"backgroundColor":"#B71C1C","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#B71C1C","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#B71C1C"},{"background":"#FFD60A","text":"#000000"},{"background":"#14213D","text":"#FFFFFF"}],"imagePlaceholderColors":["#B71C1C","#FFD60A","#14213D"],"imageAspectRatios":[1.4,0.85],"imageColorOffset":0,"imagePositionSeed":2}
  },
  {
    slug: "norman-conquest-sicily",
    title: "The Norman Conquest of Sicily",
    description: "When Vikings became Mediterranean kings",
    category: "Medieval",
    thumbnail_color: "#FF8F00",
    body_text: `In the early eleventh century, bands of Norman adventurers began arriving in southern Italy, mercenaries looking for employment in the wars between Byzantine Greeks, Lombard princes, and Muslim raiders. Within a century, they had conquered everything in sight and created one of medieval Europe's most remarkable kingdoms. The Viking descendants who had settled in Normandy proved equally adept at conquest wherever they went. The conquest of Sicily began in 1061 when Roger de Hauteville, youngest son of a minor Norman lord, crossed from the Italian mainland with a small army. The island was divided among squabbling Muslim emirs who had ruled for two centuries. Roger played them against each other, conquering piecemeal over three decades. When the last Muslim stronghold fell in 1091, the Normans controlled the most diverse territory in the Mediterranean. What they built was extraordinary. Norman Sicily became a meeting point of three civilizations. Greek, Arabic, and Latin were all official languages. Muslim and Byzantine artists decorated Christian churches. The royal court employed Arab bureaucrats and Greek scholars. Palermo rivaled Constantinople and Cordoba in sophistication. King Roger II, crowned in 1130, presided over a court where Muslim geographers created the most accurate maps in the medieval world and Greek scholars translated Arabic texts into Latin. The kingdom's wealth came from its position at the crossroads of trade routes and from the efficient administration the Normans inherited from their Arab and Byzantine predecessors. For over a century, Norman Sicily demonstrated that cultures often depicted as irreconcilably opposed could coexist and flourish together. The experiment ended when the Hohenstaufen dynasty inherited the kingdom and turned it toward continental European conflicts. But the churches and palaces they left behind, glittering with mosaics that blend Byzantine, Islamic, and Western styles, still testify to one of history's most creative cultural fusions.`,
    design_config: {"thumbnailColor":"#FF8F00","titlePage":{"backgroundColor":"#FF8F00","textColor":"#000000"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#FF8F00","text":"#000000"},{"background":"#FFFFFF","text":"#FF8F00"},{"background":"#1A237E","text":"#FFFFFF"},{"background":"#00695C","text":"#FFFFFF"}],"imagePlaceholderColors":["#FF8F00","#1A237E","#00695C"],"imageAspectRatios":[1.5,0.9],"imageColorOffset":1,"imagePositionSeed":3}
  },
  {
    slug: "fourth-lateran-council",
    title: "The Fourth Lateran Council",
    description: "When the Church remade Europe",
    category: "Medieval",
    thumbnail_color: "#512DA8",
    body_text: `In November 1215, more than four hundred bishops gathered in Rome for the most important Church council of the Middle Ages. Pope Innocent III, the most powerful pontiff since Gregory VII, summoned them to reform Christendom. The seventy canons they enacted would shape Catholic practice for centuries and cast long shadows over the lives of Jews, Muslims, and heretics throughout Europe. The council's decrees touched every aspect of medieval life. It mandated annual confession and communion for all Christians. It defined the doctrine of transubstantiation, declaring that the bread and wine of the Eucharist truly became the body and blood of Christ. It established rules for marriage, burial, and the behavior of clergy. It prohibited new religious orders, concerned that proliferation was causing confusion. More ominously, the council required Jews and Muslims to wear distinctive clothing so they could be identified as non-Christians. It banned them from public office and restricted their ability to charge interest on loans. These provisions, building on earlier restrictions, established a template for systematic discrimination that would intensify in later centuries. The council also decreed a new crusade to reclaim Jerusalem, which had been lost to Saladin in 1187. This crusade would prove disastrous, culminating in the failed Fifth Crusade against Egypt. But the council's most lasting impact was on the ordinary lives of European Christians. The requirement for annual confession created an intimate relationship between priest and parishioner that became central to medieval religious experience. The definition of transubstantiation made the Mass a miraculous event requiring reverence and proper understanding. The Fourth Lateran Council created the medieval Church as most people would experience it: a comprehensive system for regulating belief, behavior, and belonging from birth to death.`,
    design_config: {"thumbnailColor":"#512DA8","titlePage":{"backgroundColor":"#512DA8","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#512DA8","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#512DA8"},{"background":"#FFD60A","text":"#000000"},{"background":"#14213D","text":"#FFFFFF"}],"imagePlaceholderColors":["#512DA8","#FFD60A","#14213D"],"imageAspectRatios":[1.4,0.85],"imageColorOffset":0,"imagePositionSeed":4}
  },
  {
    slug: "genghis-khan-conquers-west",
    title: "Genghis Khan Conquers the West",
    description: "When the Mongols reached Europe's door",
    category: "Medieval",
    thumbnail_color: "#5D4037",
    body_text: `In 1219, Genghis Khan led his army west to punish the Khwarezmian Empire for murdering his ambassadors. What followed was destruction on a scale the world had never seen. Cities that had stood for millennia were erased. Populations that numbered in the millions were reduced to thousands. The Mongol conquests would kill so many people that it took some regions centuries to recover. The Khwarezmian shah had made a catastrophic miscalculation. His empire stretched across modern Iran, Afghanistan, and Central Asia. His army was vast. But Genghis Khan had spent twenty years unifying the Mongol tribes and perfecting a military machine unlike anything the world had ever seen. Mongol cavalry could cover a hundred miles a day, appearing where enemies least expected them. Genghis Khan divided his force and attacked from multiple directions simultaneously, sowing confusion and preventing coordinated resistance. The great cities of Central Asia fell one by one. Bukhara, Samarkand, Nishapur, Herat: names that had been synonymous with civilization became synonyms for massacre. At Nishapur, the Mongols allegedly killed every living thing, including cats and dogs. The skulls were stacked in pyramids. Irrigation systems that had sustained agriculture for centuries were deliberately destroyed. The Khwarezmian Empire ceased to exist. The shah died a fugitive on an island in the Caspian Sea. Genghis Khan returned to Mongolia, but his generals and descendants continued westward. They conquered Russia, destroyed the Abbasid Caliphate, and reached the borders of Western Europe before internal politics halted the advance. The Mongol conquests reshaped Eurasia. The Silk Road reopened under Mongol protection. Plagues spread along trade routes, possibly including the Black Death. The political map was redrawn in ways that would shape the next millennium. And the lesson was clear: no civilization, however ancient or powerful, was safe from the horsemen of the steppe.`,
    design_config: {"thumbnailColor":"#5D4037","titlePage":{"backgroundColor":"#5D4037","textColor":"#FFD60A"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#5D4037","text":"#FFFFFF"},{"background":"#FFD60A","text":"#000000"},{"background":"#FFFFFF","text":"#5D4037"},{"background":"#C62828","text":"#FFFFFF"}],"imagePlaceholderColors":["#5D4037","#FFD60A","#C62828"],"imageAspectRatios":[1.5,0.9],"imageColorOffset":1,"imagePositionSeed":2}
  },
  {
    slug: "fall-of-acre",
    title: "The Fall of Acre",
    description: "The last crusader city falls",
    category: "Medieval",
    thumbnail_color: "#00838F",
    body_text: `On May 18, 1291, the walls of Acre crumbled under the bombardment of Mamluk siege engines. The last major crusader stronghold in the Holy Land fell after a siege of six weeks. Desperate residents crowded onto ships in the harbor, fighting each other for places. Those left behind were killed or enslaved. After two centuries, the crusading movement in the Levant had ended in complete failure. Acre had been the capital of the crusader kingdom since Jerusalem's fall in 1187. It was a cosmopolitan trading city where Venetian, Genoese, and Pisan merchants competed for profits. Italian military orders held their own quarters within the walls. For a century, it had survived through diplomacy, paying tribute to the Mamluks and avoiding provocations. A truce signed in 1289 was supposed to guarantee ten years of peace. A band of newly arrived Italian crusaders broke the truce by massacring Muslim merchants in Acre's marketplace. The Mamluk sultan al-Ashraf Khalil, who had already been planning to finish off the crusader states, had his excuse. He assembled one of the largest armies ever seen in the medieval Middle East, perhaps one hundred thousand men with siege equipment the crusaders couldn't match. The city's population had swelled with refugees from other fallen fortresses. When the walls were breached, the fighting became desperate. The Templars held out in their fortress for ten more days before it collapsed, killing defenders and attackers alike. Smaller crusader outposts fell over the following months. By 1303, the last was gone. Christian pilgrims could still visit Jerusalem under Muslim rule, but the dream of a Christian kingdom in the Holy Land was over. The military orders relocated to Europe and Cyprus. Plans for new crusades were drafted but never executed. The age of crusading had passed, leaving behind a legacy of religious hatred and a transformed Mediterranean world.`,
    design_config: {"thumbnailColor":"#00838F","titlePage":{"backgroundColor":"#00838F","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#00838F","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#00838F"},{"background":"#C62828","text":"#FFFFFF"},{"background":"#FFD60A","text":"#000000"}],"imagePlaceholderColors":["#00838F","#C62828","#FFD60A"],"imageAspectRatios":[1.4,0.85],"imageColorOffset":0,"imagePositionSeed":3}
  },
  {
    slug: "war-of-roses-begins",
    title: "The Wars of the Roses Begin",
    description: "When England's noble houses destroyed each other",
    category: "Medieval",
    thumbnail_color: "#AD1457",
    body_text: `On May 22, 1455, two small armies met at the town of St. Albans. The fighting lasted less than an hour. Perhaps a hundred men died. Yet the First Battle of St. Albans began three decades of dynastic warfare that would kill most of England's nobility and end with a Welsh adventurer on the throne. The Wars of the Roses had begun. The conflict pitted two branches of the royal family against each other. The House of Lancaster, descended from John of Gaunt, held the throne through Henry VI. The House of York, descended from an older son who had died childless, claimed a superior right. The rivalry might have remained political if Henry VI had been a stronger king. Instead, he suffered from bouts of insanity that left the government paralyzed. Richard, Duke of York, served as regent during Henry's episodes but was pushed aside when the king recovered. Henry's queen, Margaret of Anjou, loathed York and worked tirelessly against him. Tensions finally erupted into violence at St. Albans. York claimed he was merely removing evil counselors from the king's side. But when he killed those counselors, including the Duke of Somerset, and captured the king himself, the pretense of loyalty became impossible to maintain. Four more years of uneasy peace followed before full-scale war erupted. The fighting was savage. Prisoners were routinely executed. The normal rules of ransom and chivalry that governed medieval warfare were suspended. Over the following decades, the crown would change hands five times. Both Lancastrian and Yorkist lines would be nearly extinguished. When Henry Tudor, a Lancastrian claimant with a tenuous claim and a Welsh grandfather, invaded in 1485 and killed Richard III at Bosworth Field, England's medieval aristocracy had destroyed itself. The Tudor dynasty would build something new from the wreckage.`,
    design_config: {"thumbnailColor":"#AD1457","titlePage":{"backgroundColor":"#AD1457","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#AD1457","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#AD1457"},{"background":"#FFFFFF","text":"#AD1457"},{"background":"#4A4A4A","text":"#FFFFFF"}],"imagePlaceholderColors":["#AD1457","#FFFFFF","#4A4A4A"],"imageAspectRatios":[1.5,0.9],"imageColorOffset":1,"imagePositionSeed":4}
  },
  {
    slug: "invention-printing-press",
    title: "The Printing Press Arrives",
    description: "The invention that changed everything",
    category: "Medieval",
    thumbnail_color: "#37474F",
    body_text: `Around 1450, in a workshop in Mainz, a goldsmith named Johannes Gutenberg perfected a system for printing books using movable metal type. The technology spread across Europe with astonishing speed. Within fifty years, printing presses operated in over two hundred cities. More books were produced in the first fifty years of printing than in the previous thousand years of manuscript copying combined. The world would never be the same. Printing existed before Gutenberg. The Chinese had invented it centuries earlier. But Gutenberg's innovation was a complete system: durable metal type that could be reused, an oil-based ink that adhered to metal, a press adapted from wine and paper-making technology, and a way to produce type quickly and uniformly. Each component had existed separately; Gutenberg combined them into something revolutionary. His first major project was the Bible. The Gutenberg Bible, completed around 1455, was a masterpiece of craftsmanship, designed to be indistinguishable from a manuscript. Each copy took about three years to produce, compared to over a year for a skilled scribe to copy a Bible by hand. A press could produce hundreds of copies, each identical. The implications were profound. Books became cheaper and more available. Ideas could spread faster than authorities could suppress them. The Reformation would have been impossible without printing; Luther's pamphlets circulated faster than the Church could respond. Scientific knowledge accumulated as each generation built on printed records rather than fragmentary manuscripts. Literacy increased as reading material became available. Gutenberg himself died in relative obscurity, having lost control of his workshop in a lawsuit. But his invention transformed human civilization more completely than any other technology until the internet. The age of manuscript culture was over. The age of print had begun.`,
    design_config: {"thumbnailColor":"#37474F","titlePage":{"backgroundColor":"#37474F","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#37474F","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#37474F"},{"background":"#5D4037","text":"#FFFFFF"},{"background":"#C4B39A","text":"#000000"}],"imagePlaceholderColors":["#37474F","#5D4037","#C4B39A"],"imageAspectRatios":[1.4,0.85],"imageColorOffset":0,"imagePositionSeed":2}
  },
  {
    slug: "black-dinner",
    title: "The Black Dinner",
    description: "Scotland's most infamous betrayal",
    category: "Medieval",
    thumbnail_color: "#212121",
    body_text: `In November 1440, two young Scottish nobles were invited to dine with their ten-year-old king at Edinburgh Castle. William Douglas, the sixth Earl of Douglas, was sixteen years old. His brother David was younger. They came in peace, trusting the royal safe conduct. They would not leave the castle alive. King James II was a child, and Scotland was ruled by regents. The Douglas family had grown too powerful, controlling vast territories and commanding private armies. Sir William Crichton, the chancellor, and Sir Alexander Livingston, the royal guardian, decided the Douglases had to be eliminated. A dinner invitation seemed the perfect trap. The young earls arrived with their retinue and were welcomed warmly. The banquet proceeded pleasantly until, according to legend, a black bull's head was placed on the table before the Douglas brothers. It was a symbol of death. Armed men entered the hall. The Douglases were seized, given a mock trial on charges of treason, and dragged to the castle courtyard. Despite the young king's tearful pleas for mercy, both brothers were beheaded. The Black Dinner, as it came to be known, didn't solve the Douglas problem. The earldom passed to a great-uncle, and within a decade, the family was as powerful as ever. It would take King James II, grown to adulthood, another round of murders to finally break Douglas power. He personally stabbed the eighth earl at another dinner invitation in 1452. Some lessons, it seems, take time to learn. The Black Dinner passed into Scottish legend, a byword for treachery and betrayal. Centuries later, George R.R. Martin would acknowledge it as one inspiration for the Red Wedding in his "Game of Thrones" novels. The horror of violated hospitality echoes across the ages.`,
    design_config: {"thumbnailColor":"#212121","titlePage":{"backgroundColor":"#212121","textColor":"#C62828"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#212121","text":"#FFFFFF"},{"background":"#C62828","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#212121"},{"background":"#4A4A4A","text":"#FFFFFF"}],"imagePlaceholderColors":["#212121","#C62828","#4A4A4A"],"imageAspectRatios":[1.5,0.9],"imageColorOffset":1,"imagePositionSeed":3}
  },
  {
    slug: "foundation-of-oxford",
    title: "The Foundation of Oxford",
    description: "When English scholars came home",
    category: "Medieval",
    thumbnail_color: "#002147",
    body_text: `In 1167, King Henry II banned English students from attending the University of Paris. The reasons were political: Henry was quarreling with both the French king and the exiled Archbishop Thomas Becket. But the unintended consequence was the creation of England's first university. The scholars who returned from Paris settled in Oxford, and a great institution was born. Teaching had occurred in Oxford before 1167, but the influx of Parisian scholars transformed the town into a genuine center of learning. Within decades, Oxford had developed the organizational structures that define a university: colleges, lectures, degrees, and examinations. Students lived in halls under the supervision of masters. Disputes between students and townspeople, the famous "town and gown" conflicts, became regular occurrences. The most violent erupted in 1355 when a tavern brawl escalated into three days of rioting that left dozens dead. The university's early curriculum focused on theology, law, and the liberal arts. Logic and philosophy were taught through the works of Aristotle, newly translated from Arabic. Students debated fine points of doctrine in Latin, the common language of learned Europe. The brightest might spend years earning advanced degrees before joining the clergy, entering royal service, or becoming teachers themselves. Oxford produced some of medieval England's greatest minds: Roger Bacon, who argued for empirical investigation; John Wycliffe, whose biblical translations anticipated the Reformation; William of Ockham, whose philosophical razor still cuts through unnecessary assumptions. When Cambridge was founded a few decades later, partly by scholars fleeing violence in Oxford, England had two universities that would shape intellectual life for centuries. The ancient rivalry between them began almost immediately and shows no signs of ending.`,
    design_config: {"thumbnailColor":"#002147","titlePage":{"backgroundColor":"#002147","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#002147","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#002147"},{"background":"#C4B39A","text":"#000000"},{"background":"#6A1B9A","text":"#FFFFFF"}],"imagePlaceholderColors":["#002147","#C4B39A","#6A1B9A"],"imageAspectRatios":[1.4,0.85],"imageColorOffset":0,"imagePositionSeed":4}
  },
  {
    slug: "battle-of-manzikert",
    title: "The Battle of Manzikert",
    description: "The defeat that doomed an empire",
    category: "Medieval",
    thumbnail_color: "#8D6E63",
    body_text: `On August 26, 1071, the Byzantine Emperor Romanos IV led his army against Seljuk Turkish forces near the town of Manzikert in eastern Anatolia. By nightfall, the emperor was a prisoner, his army was destroyed, and the heartland of the Byzantine Empire lay open to Turkish conquest. Manzikert didn't destroy Byzantium immediately, but it set in motion the decline that would end in Constantinople's fall four centuries later. The Seljuks had arrived in the Middle East only decades earlier, conquering Iran and establishing themselves as protectors of the Abbasid Caliphate. Their raids into Byzantine Anatolia had been devastating, and Romanos assembled a massive army to drive them back permanently. Contemporary estimates of his forces reached one hundred thousand, though the actual number was probably smaller. The campaign was troubled from the start. Romanos's army was a coalition of mercenaries and Byzantine units whose loyalties were uncertain. When he divided his forces to chase what he thought was the main Turkish army, he walked into a trap. The Seljuk sultan, Alp Arslan, had concentrated his horse archers for a decisive engagement. Byzantine cavalry charges couldn't catch the nimble Turkish horsemen. Turkish arrows steadily reduced the Byzantine ranks. When Romanos finally ordered a retreat, his rearguard, commanded by a political rival, simply left the field. The emperor, abandoned by his own forces, fought until his horse was killed and he was captured. Alp Arslan treated his captive with surprising generosity, releasing him after a modest ransom. But Romanos returned to find his throne usurped. He was blinded and died soon after. The civil wars that followed left no one to defend Anatolia. Turkish tribes poured into the peninsula that had been Byzantine for a thousand years. By the end of the century, Byzantium had lost most of its heartland and was appealing desperately to the West for help, setting the stage for the Crusades.`,
    design_config: {"thumbnailColor":"#8D6E63","titlePage":{"backgroundColor":"#8D6E63","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#8D6E63","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#8D6E63"},{"background":"#C62828","text":"#FFFFFF"},{"background":"#FFD60A","text":"#000000"}],"imagePlaceholderColors":["#8D6E63","#C62828","#FFD60A"],"imageAspectRatios":[1.5,0.9],"imageColorOffset":1,"imagePositionSeed":2}
  },
  {
    slug: "founding-of-venice",
    title: "The Founding of Venice",
    description: "The city built on water",
    category: "Medieval",
    thumbnail_color: "#00BCD4",
    body_text: `According to tradition, Venice was founded at noon on March 25, 421, when three consuls from Padua established a trading post on the marshy islands of the Rialto. The precise timing was probably a later invention, but the essential story captures something true: Venice was built not by kings or conquerors but by merchants fleeing violence on the mainland. The islands seemed worthless, uninhabitable. They would become the foundation of an empire. The early Venetians were refugees from the barbarian invasions that had shattered Roman Italy. The shallow lagoon, nearly impossible to navigate without local knowledge, protected them from raiders who could devastate mainland cities at will. What started as scattered fishing villages gradually coalesced into a single community, bound by trade and a fierce determination to remain independent. Venice developed unique institutions. The Doge, elected for life by the nobility, served as head of state but with sharply limited powers. The Great Council, eventually fixed as a hereditary body of noble families, made all major decisions. Checks and balances prevented any single family from seizing control. Conspiracies were ruthlessly suppressed. The system, though oligarchic, proved remarkably stable for over a thousand years. The city grew rich on trade. Venetian merchants connected East and West, bringing spices, silks, and luxuries from Constantinople and beyond to hungry European markets. The Fourth Crusade, which Venice manipulated to sack Constantinople in 1204, brought territorial possessions throughout the Eastern Mediterranean. By the fifteenth century, Venice was one of the wealthiest cities in the world, its red-roofed palaces rising impossibly from the waters of the lagoon. The impossibility was the point. Venice had created itself out of nothing, in a place where no city should exist, and had prospered beyond the dreams of ancient empires. Centuries later, tourists would wonder at the audacity of it all.`,
    design_config: {"thumbnailColor":"#00BCD4","titlePage":{"backgroundColor":"#00BCD4","textColor":"#000000"},"colorPalette":[{"background":"#000000","text":"#00BCD4"},{"background":"#00BCD4","text":"#000000"},{"background":"#FFFFFF","text":"#00BCD4"},{"background":"#C62828","text":"#FFFFFF"},{"background":"#FFD60A","text":"#000000"}],"imagePlaceholderColors":["#00BCD4","#C62828","#FFD60A"],"imageAspectRatios":[1.4,0.85],"imageColorOffset":0,"imagePositionSeed":3}
  },
  {
    slug: "avignon-papacy",
    title: "The Avignon Papacy",
    description: "When the Pope moved to France",
    category: "Medieval",
    thumbnail_color: "#4A148C",
    body_text: `In 1309, Pope Clement V abandoned Rome for Avignon, a city on the French border. He intended to stay temporarily. His successors remained for nearly seventy years, building a magnificent palace and transforming the Church in ways that would spark the Reformation two centuries later. The Avignon Papacy, sometimes called the Babylonian Captivity of the Church, became a symbol of corruption and French domination. The move had political roots. Clement V was a Frenchman, elected after a turbulent conclave and pressured by the French king, Philip IV, who had destroyed the Knights Templar and wanted a pope he could control. Rome was violent and politically unstable. The papal states were in chaos. Avignon, though not part of France, was comfortable and accessible. Why not stay? The Avignon popes were not the dissolute monsters of Protestant propaganda. Several were capable administrators who reformed Church bureaucracy and extended papal authority. They also built a taxation system that generated unprecedented revenue, funding construction projects and a luxurious court. Critics saw simony and greed; the popes saw the resources needed to govern a universal Church. The problem was perception. The papacy claimed to be above national interests, the spiritual authority of all Christendom. From Avignon, under the shadow of French power, that claim rang hollow. England, the German Empire, and Italian city-states all resented paying taxes to enrich what seemed like a French institution. The poet Petrarch denounced Avignon as a "sewer" of corruption. Reformers dreamed of returning to Rome. Pope Gregory XI finally did so in 1377, only to die the following year. The election of his successor split the Church between Roman and Avignon claimants, producing the Great Schism that would further discredit the institution. The years in Avignon had changed everything.`,
    design_config: {"thumbnailColor":"#4A148C","titlePage":{"backgroundColor":"#4A148C","textColor":"#FFD60A"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#4A148C","text":"#FFFFFF"},{"background":"#FFD60A","text":"#000000"},{"background":"#FFFFFF","text":"#4A148C"},{"background":"#14213D","text":"#FFFFFF"}],"imagePlaceholderColors":["#4A148C","#FFD60A","#14213D"],"imageAspectRatios":[1.5,0.9],"imageColorOffset":1,"imagePositionSeed":4}
  },
  {
    slug: "legend-of-prester-john",
    title: "The Legend of Prester John",
    description: "The Christian king who never existed",
    category: "Medieval",
    thumbnail_color: "#1B5E20",
    body_text: `Somewhere beyond the Muslim lands that surrounded Christendom, medieval Europeans believed, lay a powerful Christian kingdom ruled by a priest-king called Prester John. His realm was rich beyond imagination, protected by invincible armies, and waiting to ally with the crusaders against their common enemies. For centuries, explorers searched for this kingdom. It never existed. The legend emerged in the twelfth century, possibly inspired by distorted reports of the Nestorian Christians in Central Asia or the Christian kingdom of Ethiopia. A letter purportedly from Prester John circulated widely, describing wonders that belonged more to fantasy than geography: his kingdom contained the Fountain of Youth, rivers of precious stones, and subjects who lived for centuries. The letter was a forgery, but people believed it because they wanted to. The strategic appeal was obvious. Crusaders struggling to hold the Holy Land dreamed of allies who would attack the Muslims from behind. Each rumor of a great Eastern victory might be Prester John on the march. When the Mongols devastated the Islamic world in the thirteenth century, hopeful Christians wondered if Genghis Khan might be the legendary king or his servant. The hope was misplaced. The Mongols were shamanists, later Buddhist or Muslim, and they had no interest in crusading alliances. Explorers sent to find Prester John found only the Mongol Empire, vast and strange but thoroughly non-Christian. The legend shifted southward to Ethiopia, where a Christian kingdom did exist. When Portuguese explorers finally reached Ethiopia in the sixteenth century, they found a real Christian country but no magical realm of wonders. The search for Prester John had driven some of the great explorations of the age. The failure to find him revealed that the world was larger and stranger than medieval minds had imagined. Reality had finally caught up with legend.`,
    design_config: {"thumbnailColor":"#1B5E20","titlePage":{"backgroundColor":"#1B5E20","textColor":"#FFD60A"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#1B5E20","text":"#FFFFFF"},{"background":"#FFD60A","text":"#000000"},{"background":"#FFFFFF","text":"#1B5E20"},{"background":"#5D4037","text":"#FFFFFF"}],"imagePlaceholderColors":["#1B5E20","#FFD60A","#5D4037"],"imageAspectRatios":[1.4,0.85],"imageColorOffset":0,"imagePositionSeed":2}
  }
];

async function uploadStory(story) {
  const response = await fetch(`${SUPABASE_URL}/rest/v1/stories`, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      "apikey": SUPABASE_KEY,
      "Authorization": `Bearer ${SUPABASE_KEY}`,
      "Prefer": "resolution=merge-duplicates,return=minimal"
    },
    body: JSON.stringify({
      slug: story.slug,
      title: story.title,
      description: story.description,
      category: story.category,
      thumbnail_color: story.thumbnail_color,
      published: true,
      published_at: new Date().toISOString(),
      body_text: story.body_text,
      design_config: story.design_config,
      updated_at: new Date().toISOString()
    })
  });

  if (!response.ok) {
    const text = await response.text();
    throw new Error(`${response.status}: ${text}`);
  }
}

async function main() {
  console.log(`Uploading ${stories.length} Medieval stories to Supabase...\n`);

  let success = 0;
  let failed = 0;

  for (const story of stories) {
    try {
      process.stdout.write(`Uploading: ${story.title}... `);
      await uploadStory(story);
      console.log("Done!");
      success++;
    } catch (error) {
      console.log(`Error: ${error.message}`);
      failed++;
    }
  }

  console.log(`\nComplete! ${success} succeeded, ${failed} failed.`);
}

main();
