/**
 * Science Stories Upload Script - 25 NEW Science stories
 * Usage: node scripts/new-content/science-new.mjs
 */

const SUPABASE_URL = "https://egfwisgqdyhzpmeoracb.supabase.co";
const SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVnZndpc2dxZHloenBtZW9yYWNiIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2ODQyNzM0OSwiZXhwIjoyMDg0MDAzMzQ5fQ.S8h1fIepxWb44gPSPpWQ8fE0Q-SCYfL0QcBRUV7fXgs";

const stories = [
  {
    slug: "manhattan-project",
    title: "The Manhattan Project",
    description: "The secret race to build the atomic bomb",
    category: "Science",
    thumbnail_color: "#263238",
    body_text: "In December 1938, two German scientists split the atom for the first time. The news reached American physicists within weeks. They understood immediately what it meant: a weapon of unimaginable power was now theoretically possible. And Nazi Germany had a head start. Albert Einstein, a pacifist who had fled Hitler's regime, signed a letter to President Roosevelt warning of the danger. The letter reached Roosevelt in October 1939, a month after Germany invaded Poland. The president authorized research that would eventually consume two billion dollars and employ 125,000 people. They called it the Manhattan Project. The project assembled the greatest concentration of scientific genius in history. J. Robert Oppenheimer led the weapons laboratory at Los Alamos, New Mexico. Enrico Fermi built the first nuclear reactor under a squash court at the University of Chicago. Richard Feynman, barely out of graduate school, did calculations that would later win him a Nobel Prize. The secrecy was absolute. Workers at the uranium enrichment plants in Tennessee had no idea what they were making. Wives at Los Alamos knew only that their husbands worked on something important. The nearby city of Santa Fe was told the laboratory was developing electric rockets. On July 16, 1945, the first atomic bomb exploded in the New Mexico desert. The flash was visible two hundred miles away. Oppenheimer later said he thought of a line from Hindu scripture: \"Now I am become Death, the destroyer of worlds.\" Three weeks later, atomic bombs destroyed Hiroshima and Nagasaki, killing over 200,000 people and ending World War II. The Manhattan Project had achieved its goal. It had also opened a door that could never be closed. The nuclear age had begun.",
    design_config: {"thumbnailColor":"#263238","titlePage":{"backgroundColor":"#263238","textColor":"#FFD60A"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#263238","text":"#FFFFFF"},{"background":"#FFD60A","text":"#000000"},{"background":"#FFFFFF","text":"#263238"},{"background":"#E63946","text":"#FFFFFF"}],"imagePlaceholderColors":["#263238","#FFD60A","#E63946"],"imageAspectRatios":[1.4,0.9],"imageColorOffset":0,"imagePositionSeed":2}
  },
  {
    slug: "einsteins-miracle-year",
    title: "Einstein's Miracle Year",
    description: "Four papers that rewrote physics",
    category: "Science",
    thumbnail_color: "#1565C0",
    body_text: "In 1905, Albert Einstein was twenty-six years old, working as a patent clerk in Bern, Switzerland. He had been rejected for academic positions and had no laboratory, no research team, no institutional support. In his spare time, he was about to revolutionize physics. That year, Einstein published four papers in the Annalen der Physik, any one of which would have made him famous. Together, they transformed humanity's understanding of space, time, matter, and energy. The first paper explained the photoelectric effect by proposing that light came in discrete packets called quanta. This insight helped launch quantum mechanics and eventually won Einstein the Nobel Prize. The second paper provided experimental proof that atoms actually existed, explaining the random motion of particles suspended in liquid. The third paper introduced special relativity, demolishing the commonsense notions of absolute time and space that had governed physics since Newton. The fourth paper contained the most famous equation in history: E=mc². Energy equals mass times the speed of light squared. Matter and energy were interchangeable. A small amount of mass could release enormous energy, a truth that would manifest forty years later in nuclear weapons. Einstein wrote these papers while working full-time, raising an infant son, and navigating a troubled marriage. He had no access to academic journals and relied on discussions with a few friends to refine his ideas. The physics establishment initially ignored his work. It took years for scientists to recognize what had happened. A patent clerk, working alone, had seen further into the nature of reality than anyone before him. The miracle year remains unique in scientific history, a reminder that genius can emerge from anywhere.",
    design_config: {"thumbnailColor":"#1565C0","titlePage":{"backgroundColor":"#1565C0","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#1565C0","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#1565C0"},{"background":"#FFD60A","text":"#000000"},{"background":"#14213D","text":"#FFFFFF"}],"imagePlaceholderColors":["#1565C0","#FFD60A","#14213D"],"imageAspectRatios":[1.3,0.85],"imageColorOffset":1,"imagePositionSeed":3}
  },
  {
    slug: "galileos-trial",
    title: "The Trial of Galileo",
    description: "When science confronted the Church",
    category: "Science",
    thumbnail_color: "#5D4037",
    body_text: "In 1633, the most famous scientist in Europe knelt before the Roman Inquisition and renounced his life's work. Galileo Galilei, seventy years old and nearly blind, formally declared that he had been wrong to claim the Earth moved around the Sun. The alternative was torture and death. Galileo had spent decades proving what Copernicus had proposed a century earlier: Earth was not the center of the universe. Through his telescope, he had observed mountains on the Moon, spots on the Sun, moons orbiting Jupiter, and phases of Venus that only made sense if the planets circled the Sun. The evidence was overwhelming. But the Church considered heliocentrism heretical. Scripture said the Sun moved across the sky, and Scripture was the word of God. In 1616, the Church warned Galileo not to teach or defend the Copernican model. He obeyed for years. Then, in 1632, he published a dialogue comparing the Earth-centered and Sun-centered views. Though technically even-handed, the book clearly favored Copernicus. The Pope, once Galileo's friend, felt personally mocked. The Inquisition summoned Galileo to Rome. The trial was brief. Galileo was shown the instruments of torture and given a choice: recant or face the consequences. He chose to live. After his forced confession, legend claims Galileo muttered \"And yet it moves.\" The phrase is almost certainly apocryphal, but it captures something true. Galileo spent the remaining nine years of his life under house arrest, forbidden to publish. But his ideas spread anyway. Within a generation, virtually every serious astronomer accepted heliocentrism. The Church didn't formally acknowledge its error until 1992, 359 years later. Truth, it seems, has a way of outlasting the institutions that suppress it.",
    design_config: {"thumbnailColor":"#5D4037","titlePage":{"backgroundColor":"#5D4037","textColor":"#FFD60A"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#5D4037","text":"#FFFFFF"},{"background":"#FFD60A","text":"#000000"},{"background":"#FFFFFF","text":"#5D4037"},{"background":"#C4B39A","text":"#000000"}],"imagePlaceholderColors":["#5D4037","#FFD60A","#C4B39A"],"imageAspectRatios":[1.5,0.9],"imageColorOffset":0,"imagePositionSeed":2}
  },
  {
    slug: "darwins-voyage",
    title: "Darwin's Voyage on the Beagle",
    description: "The journey that changed biology forever",
    category: "Science",
    thumbnail_color: "#2E7D32",
    body_text: "When Charles Darwin boarded HMS Beagle in December 1831, he was a twenty-two-year-old amateur naturalist with no formal scientific training. His father thought he was wasting his life. Five years later, Darwin returned with the observations that would overthrow humanity's understanding of its own origins. The Beagle's mission was to chart the coastline of South America. Darwin went along as the captain's companion, a gentleman to dine with during the long voyage. His official role was unpaid, and he had to supply his own equipment. But the captain gave him freedom to explore at every port, and Darwin made the most of it. He collected fossils of giant extinct mammals in Argentina. He felt earthquakes in Chile and watched the land rise before his eyes. He studied coral reefs in the Pacific. Everywhere he went, he gathered specimens, took notes, and asked questions. The Galapagos Islands, six hundred miles off the coast of Ecuador, proved decisive. Darwin noticed that finches on different islands had different beaks, each adapted to local food sources. Tortoises varied between islands too. It was as if species changed over time to fit their environments. The implications took decades to work out. Darwin spent twenty years building his case before publishing On the Origin of Species in 1859. By then, the evidence was overwhelming. Species were not fixed creations but evolved through natural selection, the survival and reproduction of individuals best suited to their environment. The theory was controversial. It contradicted religious teachings and implied humans were animals like any other. Some attacks continue to this day. But the voyage of the Beagle had revealed a truth that no amount of controversy could suppress: life on Earth was ancient, dynamic, and connected by common descent.",
    design_config: {"thumbnailColor":"#2E7D32","titlePage":{"backgroundColor":"#2E7D32","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#2E7D32","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#2E7D32"},{"background":"#C4B39A","text":"#000000"},{"background":"#00695C","text":"#FFFFFF"}],"imagePlaceholderColors":["#2E7D32","#C4B39A","#00695C"],"imageAspectRatios":[1.6,0.85],"imageColorOffset":1,"imagePositionSeed":4}
  },
  {
    slug: "discovery-xrays",
    title: "The Discovery of X-Rays",
    description: "The invisible light that sees through flesh",
    category: "Science",
    thumbnail_color: "#00838F",
    body_text: "On November 8, 1895, Wilhelm Roentgen was experimenting with cathode rays in his laboratory in Wurzburg, Germany when he noticed something strange. A fluorescent screen across the room was glowing, even though the cathode tube was covered with black cardboard. No known rays could pass through the cardboard and travel that far. Roentgen had discovered something new. For the next six weeks, he barely left his laboratory, eating and sleeping there while he investigated. He found that the mysterious rays could pass through most materials but were blocked by dense substances like bone and metal. When he placed his wife Anna's hand in front of a photographic plate and turned on the cathode tube, the developed image showed her bones in perfect detail, her wedding ring floating around a skeletal finger. Roentgen called them X-rays because X is the mathematical symbol for an unknown quantity. He published his findings in December, and the world went wild. Within weeks, doctors were using X-rays to locate bullets and diagnose fractures. Scientists everywhere built their own machines. Edison developed a commercial fluoroscope. The public was fascinated and terrified. Newspapers warned that X-rays could see through clothing, and one company marketed X-ray-proof underwear. No one understood the danger. Early X-ray technicians received massive radiation doses. Edison's assistant Clarence Dally died of radiation poisoning, his hands eaten away by cancer. Roentgen himself refused to patent his discovery, believing it should benefit humanity freely. He died in poverty in 1923, having given away his Nobel Prize money during World War I. His name lives on: in German, X-rays are still called Roentgen rays.",
    design_config: {"thumbnailColor":"#00838F","titlePage":{"backgroundColor":"#00838F","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#00838F","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#00838F"},{"background":"#E8E8E8","text":"#000000"},{"background":"#14213D","text":"#FFFFFF"}],"imagePlaceholderColors":["#00838F","#E8E8E8","#14213D"],"imageAspectRatios":[1.3,0.9],"imageColorOffset":0,"imagePositionSeed":3}
  },
  {
    slug: "marie-curie-research",
    title: "Marie Curie's Radium",
    description: "The element that killed its discoverer",
    category: "Science",
    thumbnail_color: "#00695C",
    body_text: "Marie Curie spent four years processing eight tons of pitchblende ore in a leaky shed to isolate one-tenth of a gram of radium. She stirred boiling vats with an iron rod taller than herself, inhaling radioactive dust that would eventually kill her. The element she discovered glowed blue in the dark. By 1903, Curie and her husband Pierre had shared a Nobel Prize in Physics with Henri Becquerel for their work on radioactivity. Marie became the first woman to win a Nobel. Eight years later, after Pierre's death in a traffic accident, she won another Nobel, this time in Chemistry, becoming the only person ever to win Nobel Prizes in two different sciences. She carried test tubes of radioactive isotopes in her pockets and stored them in her desk drawer, admiring their faint glow. No one knew how dangerous they were. The Curies had noticed that radium burned their skin, but the full effects of radiation poisoning were not yet understood. Pierre had even strapped a vial of radium salts to his arm to study the resulting wound. Marie's laboratory notebooks are still so contaminated that researchers must wear protective clothing to handle them. They are kept in lead-lined boxes at the Bibliotheque Nationale in France. Marie herself died in 1934 of aplastic anemia, her bone marrow destroyed by decades of radiation exposure. She was buried in a lead-lined coffin. Her daughter Irene, who followed her into nuclear research, died of leukemia. The element that made Curie famous took her life, and yet she never regretted her work. She had added to human knowledge. That was enough.",
    design_config: {"thumbnailColor":"#00695C","titlePage":{"backgroundColor":"#00695C","textColor":"#00D9FF"},"colorPalette":[{"background":"#000000","text":"#00D9FF"},{"background":"#00695C","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#00695C"},{"background":"#00D9FF","text":"#000000"},{"background":"#14213D","text":"#FFFFFF"}],"imagePlaceholderColors":["#00695C","#00D9FF","#14213D"],"imageAspectRatios":[1.4,0.85],"imageColorOffset":1,"imagePositionSeed":2}
  },
  {
    slug: "tuskegee-experiment",
    title: "The Tuskegee Experiment",
    description: "The study that betrayed its subjects",
    category: "Science",
    thumbnail_color: "#37474F",
    body_text: "For forty years, the United States Public Health Service deliberately withheld treatment from six hundred Black men infected with syphilis. The Tuskegee Study of Untreated Syphilis in the Negro Male began in 1932 and continued until 1972, becoming one of the most shameful episodes in American medical history. The study took place in Macon County, Alabama, one of the poorest places in the country. Researchers recruited 399 men with syphilis and 201 without, promising them free medical care, meals, and burial insurance. The men were told they were being treated for \"bad blood,\" a local term for various ailments. In reality, they received no treatment at all. When penicillin became the standard cure for syphilis in 1947, the researchers actively prevented participants from receiving it. They had local draft boards exclude the men from military service, where they would have been treated. They asked other doctors in the region not to prescribe antibiotics. The goal was purely scientific: to document how syphilis destroys the human body over time. The men were never told they had syphilis. They were never told they could infect their wives and children. They were used as experimental subjects without their knowledge or consent. By the time journalist Jean Heller exposed the study in 1972, at least twenty-eight participants had died directly from syphilis, and another hundred from related complications. Forty wives had been infected. Nineteen children had been born with congenital syphilis. The survivors sued and won a settlement. In 1997, President Clinton formally apologized on behalf of the nation. But the damage extended beyond the victims. The Tuskegee experiment poisoned trust between Black Americans and the medical establishment, a legacy that continues to affect public health campaigns today.",
    design_config: {"thumbnailColor":"#37474F","titlePage":{"backgroundColor":"#37474F","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#37474F","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#37474F"},{"background":"#E63946","text":"#FFFFFF"},{"background":"#4A4A4A","text":"#FFFFFF"}],"imagePlaceholderColors":["#37474F","#E63946","#4A4A4A"],"imageAspectRatios":[1.3,1.0],"imageColorOffset":0,"imagePositionSeed":3}
  },
  {
    slug: "dolly-the-sheep",
    title: "Dolly the Sheep",
    description: "The clone that rewrote the rules of life",
    category: "Science",
    thumbnail_color: "#8BC34A",
    body_text: "On July 5, 1996, a lamb was born in a research facility in Scotland. She looked like any other Finn Dorset sheep, with a white face and wool-covered body. But Dolly was not like any animal that had ever lived. She had no father. Her DNA came entirely from a single cell taken from an adult sheep's mammary gland. She was a clone. The team at the Roslin Institute, led by Ian Wilmut and Keith Campbell, had achieved what many scientists thought impossible. They had taken a cell from a six-year-old ewe, removed its nucleus, inserted it into an egg cell from another sheep, and convinced that egg to develop into a complete animal. After 277 attempts, they succeeded once. The implications were staggering. If mammals could be cloned, so could humans. Religious leaders condemned the research as playing God. Governments rushed to ban human cloning. Scientists debated whether clones would age prematurely or suffer health problems. Dolly herself lived only six years, half the normal lifespan for her breed, and developed arthritis and lung disease. Some speculated her DNA was already \"old\" when she was born, though later research suggested her problems may have been unrelated to cloning. Dolly became the most famous animal in the world. She met with movie stars and politicians. She was photographed for magazine covers. She produced lambs of her own the old-fashioned way, proving that clones could reproduce normally. When she died in 2003, her body was preserved and displayed at the National Museum of Scotland. The technology Dolly represented continues to advance. Scientists have cloned dogs, cats, horses, and endangered species. The boundary between the possible and impossible keeps shifting. Dolly showed us that even the fundamental rules of biology could be rewritten.",
    design_config: {"thumbnailColor":"#8BC34A","titlePage":{"backgroundColor":"#8BC34A","textColor":"#000000"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#8BC34A","text":"#000000"},{"background":"#FFFFFF","text":"#8BC34A"},{"background":"#2E7D32","text":"#FFFFFF"},{"background":"#C4B39A","text":"#000000"}],"imagePlaceholderColors":["#8BC34A","#2E7D32","#C4B39A"],"imageAspectRatios":[1.5,0.85],"imageColorOffset":1,"imagePositionSeed":4}
  },
  {
    slug: "large-hadron-collider",
    title: "The Large Hadron Collider",
    description: "The machine that found the God particle",
    category: "Science",
    thumbnail_color: "#1A237E",
    body_text: "Buried 300 feet beneath the Swiss-French border lies the largest machine ever built. The Large Hadron Collider is a ring of superconducting magnets 17 miles in circumference, designed to smash particles together at nearly the speed of light. It cost ten billion dollars and took over a decade to construct. Its purpose was to answer the most fundamental question in physics: where does mass come from? The search centered on the Higgs boson, a particle first proposed in 1964 by physicist Peter Higgs and others. According to theory, the Higgs field permeates all of space, and particles gain mass by interacting with it. But no one had ever detected the particle that carries this field. Finding it would require energies impossible to achieve with existing machines. The LHC began operations in 2008, immediately suffered a catastrophic magnet failure, and was shut down for repairs for over a year. When it restarted, thousands of scientists from over a hundred countries began analyzing the collisions. They were looking for a needle in a cosmic haystack: a particle that exists for less than a billionth of a billionth of a second before decaying into other particles. On July 4, 2012, CERN announced the discovery. The Higgs boson was real. The standard model of particle physics, which had guided the field for decades, was complete. Peter Higgs, eighty-three years old, wept at the news. The LHC continues to operate, smashing particles and probing the boundaries of physics. Its discoveries may someday explain dark matter, extra dimensions, or phenomena we cannot yet imagine. Humanity had built a cathedral of science at the edge of understanding, and it had found what it sought.",
    design_config: {"thumbnailColor":"#1A237E","titlePage":{"backgroundColor":"#1A237E","textColor":"#00D9FF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#1A237E","text":"#FFFFFF"},{"background":"#00D9FF","text":"#000000"},{"background":"#FFFFFF","text":"#1A237E"},{"background":"#14213D","text":"#FFFFFF"}],"imagePlaceholderColors":["#1A237E","#00D9FF","#14213D"],"imageAspectRatios":[1.6,0.9],"imageColorOffset":0,"imagePositionSeed":2}
  },
  {
    slug: "tutankhamun-discovery",
    title: "The Tomb of Tutankhamun",
    description: "The discovery that launched Egyptomania",
    category: "Science",
    thumbnail_color: "#FFB300",
    body_text: "On November 4, 1922, a water boy digging in the sand outside the tomb of Ramesses VI discovered a stone step. Within hours, archaeologist Howard Carter had uncovered a staircase leading down into the bedrock. Three weeks later, he broke through a sealed doorway and held up a candle to peer inside. His patron Lord Carnarvon asked if he could see anything. \"Yes,\" Carter replied. \"Wonderful things.\" The tomb of Tutankhamun was the most intact royal burial ever found in Egypt. For over three thousand years, it had escaped the tomb robbers who had emptied every other pharaonic grave in the Valley of the Kings. Its treasures included the king's golden death mask, his solid gold inner coffin, and over five thousand artifacts ranging from chariots to board games to sandals. The discovery sparked a worldwide craze for all things Egyptian. Art deco architecture adopted pharaonic motifs. Egyptian-themed movies filled theaters. Hieroglyphics appeared on cigarette cases and cocktail shakers. The \"curse of the pharaohs\" became a popular sensation after Lord Carnarvon died of an infected mosquito bite four months after the tomb's opening. Carter himself dismissed the curse stories. He continued methodically excavating the tomb for the next decade, cataloging every object with painstaking care. He never found another major tomb, but his one discovery was enough for any lifetime. Today the treasures of Tutankhamun are among the most visited museum exhibits in the world. The boy king who died at nineteen after a reign of only nine years has become the most famous pharaoh who ever lived, his golden face the very image of ancient Egypt. All because of a stone step found by a worker fetching water.",
    design_config: {"thumbnailColor":"#FFB300","titlePage":{"backgroundColor":"#FFB300","textColor":"#000000"},"colorPalette":[{"background":"#000000","text":"#FFB300"},{"background":"#FFB300","text":"#000000"},{"background":"#FFFFFF","text":"#FFB300"},{"background":"#5D4037","text":"#FFFFFF"},{"background":"#14213D","text":"#FFFFFF"}],"imagePlaceholderColors":["#FFB300","#5D4037","#14213D"],"imageAspectRatios":[1.4,0.9],"imageColorOffset":1,"imagePositionSeed":3}
  },
  {
    slug: "piltdown-man-hoax",
    title: "The Piltdown Man Hoax",
    description: "The fossil that fooled science for 40 years",
    category: "Science",
    thumbnail_color: "#795548",
    body_text: "In 1912, amateur archaeologist Charles Dawson announced an extraordinary discovery from a gravel pit in Sussex, England. He had found fragments of a skull that appeared to combine a human cranium with an ape-like jaw. Here, at last, was the \"missing link\" between humans and our primate ancestors. The scientific establishment embraced Piltdown Man enthusiastically. British scientists were particularly pleased that the earliest human had been found in England, not in Africa or Asia. The skull was given the scientific name Eoanthropus dawsoni and was displayed proudly at the Natural History Museum. Textbooks included it as a key piece of evidence for human evolution. For forty years, Piltdown Man shaped how scientists thought about human origins. Other discoveries that contradicted it were dismissed or reinterpreted to fit. When fossils in Africa suggested humans had evolved there instead, skeptics pointed to Piltdown as proof that the African specimens were anomalies. The fraud was exposed in 1953 when new dating techniques revealed the jaw was modern, not ancient. Further analysis showed the bones had been stained to look old, the teeth filed to disguise their shape. Someone had deliberately created a fake fossil and planted it in the gravel pit. The identity of the forger remains debated. Dawson is the primary suspect, but others have been accused, including a young museum volunteer named Martin Hinton and even Arthur Conan Doyle, creator of Sherlock Holmes. What's certain is that dozens of scientists examined the skull over four decades without detecting the fraud. They saw what they wanted to see. Piltdown Man became a cautionary tale about the dangers of wishful thinking in science.",
    design_config: {"thumbnailColor":"#795548","titlePage":{"backgroundColor":"#795548","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#795548","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#795548"},{"background":"#C4B39A","text":"#000000"},{"background":"#4A4A4A","text":"#FFFFFF"}],"imagePlaceholderColors":["#795548","#C4B39A","#4A4A4A"],"imageAspectRatios":[1.3,1.0],"imageColorOffset":0,"imagePositionSeed":2}
  },
  {
    slug: "cold-fusion-controversy",
    title: "The Cold Fusion Fiasco",
    description: "The discovery that never was",
    category: "Science",
    thumbnail_color: "#0277BD",
    body_text: "On March 23, 1989, two chemists held a press conference that promised to change the world. Stanley Pons and Martin Fleischmann announced they had achieved nuclear fusion at room temperature in a jar of heavy water. If true, humanity's energy problems were solved. Unlimited clean power was within reach. The announcement bypassed the normal scientific process. Instead of publishing in peer-reviewed journals, Pons and Fleischmann went straight to the media. Their university had rushed them forward, fearing competitors were close to the same discovery. The press went wild. Headlines proclaimed a new age of energy. Stock markets reacted. Governments scrambled to fund replication efforts. Then the problems began. Laboratories around the world tried to reproduce the experiment. Some reported success. Most reported nothing. The claims of excess heat varied wildly. No one could reliably detect the neutron emissions that should accompany fusion. The two chemists couldn't explain the discrepancies. Within months, the consensus turned against cold fusion. Major laboratories concluded the effect was either experimental error or wishful thinking. A Department of Energy review found no evidence to support the claims. Pons and Fleischmann were accused of incompetence or fraud. They left the United States for a laboratory in France, eventually abandoning research entirely. The cold fusion episode damaged careers and wasted resources, but it also revealed how science is supposed to work. Extraordinary claims require extraordinary evidence. When that evidence doesn't materialize, even promising discoveries must be abandoned. Yet true believers persist. A small community of researchers continues to investigate \"low-energy nuclear reactions,\" convinced that something real was glimpsed in 1989. They might be right. Most scientists doubt it.",
    design_config: {"thumbnailColor":"#0277BD","titlePage":{"backgroundColor":"#0277BD","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#0277BD","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#0277BD"},{"background":"#FFD60A","text":"#000000"},{"background":"#14213D","text":"#FFFFFF"}],"imagePlaceholderColors":["#0277BD","#FFD60A","#14213D"],"imageAspectRatios":[1.5,0.85],"imageColorOffset":1,"imagePositionSeed":4}
  },
  {
    slug: "apollo-11-moon-landing",
    title: "Apollo 11: First on the Moon",
    description: "The mission that achieved the impossible",
    category: "Science",
    thumbnail_color: "#263238",
    body_text: "On July 20, 1969, Neil Armstrong and Buzz Aldrin became the first humans to walk on another world. Six hundred million people, a fifth of Earth's population, watched on television as Armstrong descended the ladder and spoke the most famous words in exploration history: \"That's one small step for man, one giant leap for mankind.\" The journey had taken eight years and cost twenty-five billion dollars. President Kennedy had set the goal in 1961, challenging America to land a man on the Moon and return him safely to Earth before the decade was out. At the time, NASA had logged fifteen minutes of human spaceflight. No one knew if humans could survive in space for the week required for a lunar mission. The risks were enormous. The Saturn V rocket that launched Apollo 11 was the most powerful machine ever built, containing three million parts, any one of which could cause catastrophic failure. During the landing, computer alarms nearly aborted the descent. Armstrong had to fly manually past a boulder field, landing with only 25 seconds of fuel remaining. The astronauts spent two and a half hours on the lunar surface, collecting samples, planting a flag, and leaving behind scientific instruments. They also left a plaque reading \"We came in peace for all mankind\" and medallions honoring the astronauts who had died in the Apollo 1 fire. The return journey was flawless. The astronauts splashed down in the Pacific and were retrieved by the USS Hornet. They spent three weeks in quarantine before being released to ticker-tape parades and worldwide acclaim. Five more Apollo missions landed on the Moon before the program ended in 1972. No human has been back since. The footprints Armstrong and Aldrin left that day remain undisturbed, preserved in lunar dust for millions of years to come.",
    design_config: {"thumbnailColor":"#263238","titlePage":{"backgroundColor":"#263238","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#263238","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#263238"},{"background":"#E8E8E8","text":"#000000"},{"background":"#1976D2","text":"#FFFFFF"}],"imagePlaceholderColors":["#263238","#E8E8E8","#1976D2"],"imageAspectRatios":[1.4,0.9],"imageColorOffset":0,"imagePositionSeed":3}
  },
  {
    slug: "smallpox-eradication",
    title: "The Eradication of Smallpox",
    description: "Humanity's greatest medical triumph",
    category: "Science",
    thumbnail_color: "#C62828",
    body_text: "For thousands of years, smallpox killed approximately thirty percent of those it infected, leaving survivors scarred for life. The virus killed pharaohs and peasants, emperors and infants. In the twentieth century alone, it killed an estimated 300 million people. On May 8, 1980, the World Health Organization declared smallpox eradicated from the face of the Earth, the first and only human disease ever eliminated. The campaign began in 1967 when smallpox was still killing two million people annually. The WHO launched a global vaccination effort, but the initial strategy of vaccinating entire populations proved too slow and expensive. A new approach emerged: ring vaccination. Instead of vaccinating everyone, health workers would identify new cases, isolate the sick, and vaccinate everyone who had contact with them. The disease was contained before it could spread. Success required heroic effort. Vaccination teams traveled by canoe, on foot, and on camelback to reach remote villages. They navigated civil wars and crossed hostile borders. In Somalia, the last country with endemic smallpox, health workers searched house to house offering rewards for reporting cases. The final known case was Ali Maow Maalin, a hospital cook in Marka, Somalia, who recovered in October 1977. Two years of surveillance followed to confirm the disease was truly gone. When the WHO made its historic announcement, it represented the triumph of international cooperation and scientific medicine. Smallpox vaccines are no longer routinely given. The virus now exists only in two laboratories, one in the United States and one in Russia. Whether these samples should be destroyed remains controversial. Some scientists want to preserve them for research. Others argue the risk of escape is too great. The disease that shaped human history now survives only in freezers, a prisoner of the species it once devastated.",
    design_config: {"thumbnailColor":"#C62828","titlePage":{"backgroundColor":"#C62828","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#C62828","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#C62828"},{"background":"#2E7D32","text":"#FFFFFF"},{"background":"#14213D","text":"#FFFFFF"}],"imagePlaceholderColors":["#C62828","#2E7D32","#14213D"],"imageAspectRatios":[1.3,0.85],"imageColorOffset":1,"imagePositionSeed":2}
  },
  {
    slug: "chernobyl-disaster",
    title: "The Chernobyl Disaster",
    description: "The night the reactor exploded",
    category: "Science",
    thumbnail_color: "#FFD600",
    body_text: "At 1:23 AM on April 26, 1986, reactor number four at the Chernobyl Nuclear Power Plant exploded. The blast lifted the 1,000-ton lid off the reactor core and sent a plume of radioactive material into the atmosphere. It was the worst nuclear accident in history. The explosion resulted from a safety test gone catastrophically wrong. Engineers had disabled multiple safety systems to test whether the reactor could power itself during an emergency. When they lost control of the chain reaction, the reactor core overheated and ruptured. The resulting fire burned for ten days, releasing radioactive contamination that spread across Europe. Soviet authorities initially tried to hide the disaster. The nearby city of Pripyat, home to 50,000 people, was not evacuated until thirty-six hours after the explosion. Many residents had already received dangerous doses of radiation. In the following weeks, 600,000 \"liquidators\" were sent to clean up the site, shoveling radioactive graphite off rooftops, building a concrete sarcophagus around the ruined reactor, and burying contaminated vehicles. Many received radiation doses that shortened their lives. The final death toll remains disputed. Direct casualties numbered fewer than fifty, but thousands more are believed to have died from radiation-related cancers in the decades following. A zone extending eighteen miles from the plant remains largely uninhabited. Wildlife has returned in the absence of humans, creating an eerie wilderness patrolled by wolves and wild horses. Chernobyl changed how the world thought about nuclear power. Countries canceled reactor orders. Safety regulations tightened. The Soviet Union's attempt to conceal the disaster accelerated its loss of credibility at home and abroad. The ruins of reactor four still stand, now covered by a new protective structure designed to last a hundred years. The radiation will last longer.",
    design_config: {"thumbnailColor":"#FFD600","titlePage":{"backgroundColor":"#FFD600","textColor":"#000000"},"colorPalette":[{"background":"#000000","text":"#FFD600"},{"background":"#FFD600","text":"#000000"},{"background":"#FFFFFF","text":"#000000"},{"background":"#37474F","text":"#FFFFFF"},{"background":"#E63946","text":"#FFFFFF"}],"imagePlaceholderColors":["#FFD600","#37474F","#E63946"],"imageAspectRatios":[1.5,0.9],"imageColorOffset":0,"imagePositionSeed":4}
  },
  {
    slug: "dinosaur-extinction",
    title: "The Day the Dinosaurs Died",
    description: "66 million years ago, an asteroid hit Earth",
    category: "Science",
    thumbnail_color: "#FF6F00",
    body_text: "Sixty-six million years ago, an asteroid six miles wide struck what is now the Yucatan Peninsula of Mexico at 45,000 miles per hour. The impact released energy equivalent to ten billion Hiroshima bombs. Within hours, seventy-five percent of all species on Earth were doomed. The asteroid hit shallow ocean, vaporizing water and bedrock into a superheated cloud that spread across the planet. Within minutes, everything within a thousand miles was incinerated. The shockwave generated earthquakes of magnitude eleven or higher. Tsunamis over a hundred feet tall swept across the Caribbean and flooded coastlines thousands of miles away. The real killing came later. The impact ejected billions of tons of rock into the atmosphere. Some of this debris reentered as a rain of molten glass, heating the air like an oven and igniting wildfires worldwide. Soot and sulfur blocked the sun for months or years. Temperatures plummeted. Plants stopped growing. The food chain collapsed from the bottom up. The dinosaurs, who had dominated Earth for 165 million years, vanished almost entirely. Only the lineage that would become birds survived. Mammals, small and adaptable, endured in burrows and emerged into a transformed world. Without the extinction of the dinosaurs, they would never have inherited the Earth. The crater, called Chicxulub after a nearby town, was not discovered until 1991. Geologists had suspected an asteroid impact since 1980, when they found a layer of iridium, a rare metal common in asteroids, in rocks from exactly 66 million years ago. But the crater itself lay hidden beneath a half-mile of limestone, its shape visible only in gravity maps and drill cores. The asteroid that ended the age of dinosaurs created the world we live in. Our existence is the consequence of cosmic violence beyond imagination.",
    design_config: {"thumbnailColor":"#FF6F00","titlePage":{"backgroundColor":"#FF6F00","textColor":"#000000"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#FF6F00","text":"#000000"},{"background":"#FFFFFF","text":"#FF6F00"},{"background":"#5D4037","text":"#FFFFFF"},{"background":"#14213D","text":"#FFFFFF"}],"imagePlaceholderColors":["#FF6F00","#5D4037","#14213D"],"imageAspectRatios":[1.6,0.85],"imageColorOffset":1,"imagePositionSeed":3}
  },
  {
    slug: "dna-structure-discovery",
    title: "The Double Helix",
    description: "How Watson and Crick cracked the code of life",
    category: "Science",
    thumbnail_color: "#7B1FA2",
    body_text: "On February 28, 1953, James Watson and Francis Crick walked into the Eagle pub in Cambridge and announced they had discovered the secret of life. They had just built a three-dimensional model of DNA that explained how hereditary information is stored and copied. The double helix would become the most famous molecular structure in history. The discovery emerged from a race. At least three research groups were competing to solve DNA's structure: Linus Pauling at Caltech, the King's College London team led by Maurice Wilkins and including Rosalind Franklin, and the Cambridge pair. Pauling had recently discovered the alpha helix structure of proteins and seemed likely to win. Watson and Crick had an advantage: they didn't do experiments. Instead, they built physical models, trying different arrangements of atoms until they found one that fit all the known constraints. They knew DNA contained four bases, adenine, guanine, cytosine, and thymine, but not how they connected. The crucial insight came from an American crystallographer named Jerry Donohue, who pointed out that chemistry textbooks showed the bases in the wrong form. When Watson tried the correct forms, he found that adenine paired perfectly with thymine, and guanine with cytosine. The structure suddenly made sense. Two spiral strands wound around each other, connected by paired bases like rungs on a twisted ladder. When the cell divided, the strands could separate and each could serve as a template for a new partner. Heredity was chemistry. Watson and Crick published their discovery in a one-page paper in Nature. They shared the Nobel Prize in 1962 with Wilkins. Franklin, whose X-ray photographs had provided crucial evidence, had died of cancer four years earlier, likely caused by radiation exposure in her laboratory. She received no credit in the Nobel citation.",
    design_config: {"thumbnailColor":"#7B1FA2","titlePage":{"backgroundColor":"#7B1FA2","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#7B1FA2","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#7B1FA2"},{"background":"#00BCD4","text":"#000000"},{"background":"#14213D","text":"#FFFFFF"}],"imagePlaceholderColors":["#7B1FA2","#00BCD4","#14213D"],"imageAspectRatios":[1.4,0.9],"imageColorOffset":0,"imagePositionSeed":2}
  },
  {
    slug: "lysenkoism-soviet-science",
    title: "Lysenkoism",
    description: "When Soviet ideology corrupted genetics",
    category: "Science",
    thumbnail_color: "#B71C1C",
    body_text: "From 1927 to 1964, Soviet biology was dominated by a peasant agronomist who rejected evolution and genetics. Trofim Lysenko claimed that acquired characteristics could be inherited, that wheat could be transformed into rye, and that Mendelian genetics was bourgeois pseudoscience. Scientists who disagreed were imprisoned or executed. Lysenko rose to power during Stalin's collectivization of agriculture, which had caused famines that killed millions. He promised miraculous crop yields through techniques that required no expensive equipment or scientific training. Cold-treating seeds, he claimed, could turn winter wheat into spring wheat. Planting seeds closer together would make them cooperate rather than compete. None of it worked. But Lysenko had Stalin's ear. Classical genetics, with its emphasis on competition and random variation, contradicted Marxist ideology. Lysenko's theory, which held that organisms could be improved through proper conditioning, aligned with Soviet beliefs about human perfectibility. The regime suppressed genetics as capitalist propaganda. Hundreds of scientists lost their positions. Some were sent to labor camps. The prominent geneticist Nikolai Vavilov, who had assembled the world's largest collection of plant seeds, was arrested and died in prison of starvation. Soviet biology fell decades behind the West. The agricultural techniques Lysenko championed contributed to crop failures and food shortages. After Stalin's death, criticism of Lysenko grew, but he retained support under Khrushchev. Only in 1965, after both men had lost power, was Lysenko finally removed from his position. Soviet genetics never fully recovered. Lysenkoism remains a warning about what happens when political ideology dictates scientific truth. The results can be measured in ruined careers, wasted years, and millions of preventable deaths.",
    design_config: {"thumbnailColor":"#B71C1C","titlePage":{"backgroundColor":"#B71C1C","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#B71C1C","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#B71C1C"},{"background":"#FFD60A","text":"#000000"},{"background":"#4A4A4A","text":"#FFFFFF"}],"imagePlaceholderColors":["#B71C1C","#FFD60A","#4A4A4A"],"imageAspectRatios":[1.3,1.0],"imageColorOffset":1,"imagePositionSeed":3}
  },
  {
    slug: "leakey-fossil-hunters",
    title: "The Leakey Fossil Hunters",
    description: "The family that found humanity's ancestors",
    category: "Science",
    thumbnail_color: "#8D6E63",
    body_text: "Louis and Mary Leakey spent decades searching the African rift valleys for evidence of human origins. Their discoveries proved that humanity evolved in Africa, overturning the scientific consensus that had pointed to Asia. Their son Richard continued their work, making the family name synonymous with paleoanthropology. Louis Leakey was born in Kenya to British missionaries and grew up speaking Kikuyu as his first language. He became convinced that Africa was the birthplace of humanity at a time when most scientists looked elsewhere. The Piltdown Man forgery seemed to prove that human evolution had occurred in Europe. Asian fossils suggested that continent as the most likely origin. The Leakeys found otherwise. In 1959, after almost thirty years of searching, Mary discovered a 1.75-million-year-old skull at Olduvai Gorge in Tanzania. Nicknamed \"Nutcracker Man\" for its massive jaw, the fossil was far older than any human ancestor known at the time. It established East Africa as the crucible of human evolution. More discoveries followed: Homo habilis, the first toolmaker; early Homo erectus; footprints preserved in volcanic ash for 3.6 million years, proving our ancestors walked upright before their brains grew large. Each find pushed human origins further back in time and confirmed Africa's central role in our story. The Leakeys were not easy personalities. Louis had affairs that strained his marriage. Richard lost both legs in a plane crash and entered Kenyan politics. Family disputes became public feuds. But their scientific legacy is unquestioned. Before the Leakeys, human evolution was poorly understood and mired in fraud and speculation. After the Leakeys, the broad outlines were clear. We came from Africa, and the Leakeys helped us understand how.",
    design_config: {"thumbnailColor":"#8D6E63","titlePage":{"backgroundColor":"#8D6E63","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#8D6E63","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#8D6E63"},{"background":"#C4B39A","text":"#000000"},{"background":"#2E7D32","text":"#FFFFFF"}],"imagePlaceholderColors":["#8D6E63","#C4B39A","#2E7D32"],"imageAspectRatios":[1.5,0.85],"imageColorOffset":0,"imagePositionSeed":4}
  },
  {
    slug: "halley-comet",
    title: "Halley's Comet",
    description: "The wanderer that returns every 76 years",
    category: "Science",
    thumbnail_color: "#311B92",
    body_text: "In 1705, Edmund Halley realized that the comets of 1531, 1607, and 1682 were the same object, returning on a predictable orbit. He predicted it would return in 1758. Halley died in 1742, but the comet appeared on schedule, confirming Newton's laws and becoming the first comet named after a person. The comet has been observed for over two thousand years. The Bayeux Tapestry depicts it appearing in 1066, just before the Norman Conquest. Chinese astronomers recorded it in 240 BCE. Some scholars have suggested, controversially, that it was the Star of Bethlehem. Mark Twain was born in 1835 during one appearance and predicted he would die during its next return in 1910. He did, the day after it reached perihelion. The 1910 return caused widespread panic. Astronomers announced that Earth would pass through the comet's tail, which contained cyanogen, a poisonous gas. Hucksters sold \"anti-comet pills\" and \"comet-proof shelters.\" Some people sealed their windows with rags. Others held comet parties, reasoning that if they were going to die, they might as well celebrate first. Of course, comet tails are so diffuse that they have no effect on Earth. The next return, in 1986, disappointed those who remembered the spectacular show of 1910. Light pollution and an unfavorable geometry meant most observers saw only a fuzzy blob. But spacecraft visited the comet for the first time, revealing a potato-shaped nucleus covered in dark organic material, blacker than coal. Halley's Comet will return in 2061. Many people alive today will see it. Some children born now may live to see it twice, watching in their youth and then again in extreme old age, the same wanderer their ancestors saw for a hundred generations.",
    design_config: {"thumbnailColor":"#311B92","titlePage":{"backgroundColor":"#311B92","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#311B92","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#311B92"},{"background":"#00D9FF","text":"#000000"},{"background":"#14213D","text":"#FFFFFF"}],"imagePlaceholderColors":["#311B92","#00D9FF","#14213D"],"imageAspectRatios":[1.4,0.9],"imageColorOffset":1,"imagePositionSeed":2}
  },
  {
    slug: "hubble-universe-expanding",
    title: "Hubble's Expanding Universe",
    description: "The astronomer who proved the cosmos grows",
    category: "Science",
    thumbnail_color: "#0D47A1",
    body_text: "In 1924, Edwin Hubble pointed the world's largest telescope at a fuzzy patch of light called the Andromeda Nebula and proved it was a galaxy, a vast island of stars like our own Milky Way but immensely far away. The universe, it turned out, was unimaginably larger than anyone had thought. Then Hubble discovered something even more astonishing: it was getting bigger. Working at Mount Wilson Observatory in California, Hubble measured the distances to dozens of galaxies and compared them to their spectra. He found that the farther away a galaxy was, the faster it appeared to be receding from Earth. The entire universe was expanding, with every galaxy flying away from every other galaxy like dots on an inflating balloon. The implications were revolutionary. If the universe was expanding now, it must have been smaller in the past. Run the clock backward far enough, and everything must have started from a single point. The Big Bang theory was born. Einstein, who had added a fudge factor to his equations to keep the universe static, called it his greatest blunder. Hubble himself never received the Nobel Prize, because astronomy was not then considered a category of physics. He campaigned to change the rules but died in 1953 before achieving his goal. His legacy lives on in the Hubble Space Telescope, launched in 1990 and still operating, which has provided the most detailed views ever obtained of the distant universe. Hubble showed us that we live in one galaxy among billions, in a universe that emerged from nothing and continues to grow. Every patch of darkness contains galaxies we haven't discovered yet. The cosmos that Hubble revealed is vaster and stranger than any astronomer before him had imagined.",
    design_config: {"thumbnailColor":"#0D47A1","titlePage":{"backgroundColor":"#0D47A1","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#0D47A1","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#0D47A1"},{"background":"#311B92","text":"#FFFFFF"},{"background":"#00D9FF","text":"#000000"}],"imagePlaceholderColors":["#0D47A1","#311B92","#00D9FF"],"imageAspectRatios":[1.6,0.85],"imageColorOffset":0,"imagePositionSeed":3}
  },
  {
    slug: "helicobacter-ulcer",
    title: "The Ulcer Rebel",
    description: "The doctor who drank bacteria to prove his point",
    category: "Science",
    thumbnail_color: "#00897B",
    body_text: "For decades, doctors knew that stomach ulcers were caused by stress, spicy food, and excess acid. They treated patients with antacids, bland diets, and advice to relax. Then an Australian physician named Barry Marshall drank a flask of bacteria and proved everyone wrong. Marshall and his colleague Robin Warren had identified spiral-shaped bacteria in the stomachs of ulcer patients. They believed Helicobacter pylori, as the organism came to be called, was the true cause of ulcers. The medical establishment was skeptical. The stomach was too acidic for bacteria to survive, they said. Ulcers were a lifestyle disease, not an infection. No one would fund clinical trials. Unable to infect laboratory animals, Marshall took drastic action. In 1984, he drank a broth containing billions of H. pylori cultured from a patient's stomach. Within days, he developed gastritis, the inflammation that precedes ulcers. A biopsy confirmed the bacteria had colonized his stomach lining. He cured himself with antibiotics. The experiment was dangerous, unethical by modern standards, and utterly convincing. Marshall's self-experiment made headlines, but it took another decade for the medical community to fully accept the new understanding. Drug companies that made billions from anti-ulcer medications had little incentive to promote a cure that required only a short course of antibiotics. Doctors who had built careers on stress-based theories resisted change. By the time Marshall and Warren received the Nobel Prize in 2005, antibiotics had become the standard treatment for ulcers, curing a condition that had once been considered chronic and incurable. Millions of patients were spared a lifetime of medication and dietary restrictions. One scientist's willingness to risk his own health had overthrown decades of medical orthodoxy.",
    design_config: {"thumbnailColor":"#00897B","titlePage":{"backgroundColor":"#00897B","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#00897B","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#00897B"},{"background":"#E8E8E8","text":"#000000"},{"background":"#14213D","text":"#FFFFFF"}],"imagePlaceholderColors":["#00897B","#E8E8E8","#14213D"],"imageAspectRatios":[1.3,1.0],"imageColorOffset":1,"imagePositionSeed":4}
  },
  {
    slug: "thalidomide-tragedy",
    title: "The Thalidomide Tragedy",
    description: "The drug that changed pharmaceutical testing",
    category: "Science",
    thumbnail_color: "#455A64",
    body_text: "In 1957, a German pharmaceutical company released a sleeping pill marketed as completely safe. Thalidomide was advertised as so gentle it could be given to pregnant women for morning sickness. Within five years, it had caused one of the worst pharmaceutical disasters in history, leaving over ten thousand children with severe birth defects. Thalidomide crossed the placenta and interfered with fetal development during a critical window of pregnancy. Children whose mothers had taken even a single dose were born with shortened or missing limbs, defects of the eyes and ears, and internal organ damage. The connection took years to establish because the drug was sold under different names in different countries, and doctors initially suspected a viral cause. An Australian obstetrician named William McBride and a German pediatrician named Widukind Lenz independently traced the epidemic to thalidomide in 1961. The drug was withdrawn from most markets, but thousands of children had already been affected. Many died in infancy. The survivors faced lifetimes of disability and discrimination. In the United States, FDA medical officer Frances Kelsey had blocked thalidomide's approval, requesting more safety data despite pressure from the manufacturer. Her caution prevented an American tragedy and earned her a presidential medal. The disaster transformed pharmaceutical regulation worldwide. New rules required drugs to be tested for effects on reproduction before marketing. Clinical trials became longer and more rigorous. The principle that drugs should be proven safe, not merely assumed to be harmless, became fundamental to medicine. Thalidomide itself eventually found new uses, treating leprosy and certain cancers. It remains on the market today, surrounded by strict controls to prevent exposure during pregnancy. The tragedy that gave it its reputation also ensures those controls will never be relaxed.",
    design_config: {"thumbnailColor":"#455A64","titlePage":{"backgroundColor":"#455A64","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#455A64","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#455A64"},{"background":"#E63946","text":"#FFFFFF"},{"background":"#4A4A4A","text":"#FFFFFF"}],"imagePlaceholderColors":["#455A64","#E63946","#4A4A4A"],"imageAspectRatios":[1.4,0.85],"imageColorOffset":0,"imagePositionSeed":2}
  },
  {
    slug: "deep-blue-chess",
    title: "Deep Blue Defeats Kasparov",
    description: "When a machine beat the world chess champion",
    category: "Science",
    thumbnail_color: "#1976D2",
    body_text: "On May 11, 1997, a computer beat the world chess champion in a six-game match. Deep Blue, an IBM supercomputer capable of evaluating 200 million positions per second, defeated Garry Kasparov 3.5 to 2.5. It was the first time a machine had beaten a reigning world champion under standard tournament conditions. Chess had long been considered a benchmark for artificial intelligence. The game combines simple rules with enormous complexity: there are more possible chess games than atoms in the observable universe. For decades, computers improved steadily but remained no match for the best human players. Kasparov, perhaps the greatest chess player who ever lived, dismissed them as mere calculators, unable to match human intuition and creativity. The 1997 match proved otherwise. In game two, Deep Blue made a move that stunned the chess world, a subtle knight maneuver that seemed to demonstrate strategic understanding rather than brute-force calculation. Kasparov, rattled, began to suspect the machine was receiving human assistance. His play deteriorated. He resigned the final game after only nineteen moves. Kasparov demanded a rematch. IBM refused and dismantled Deep Blue, leaving the result to stand as a landmark moment in the history of both chess and computing. Kasparov's suspicions were never confirmed, and most experts believe Deep Blue won fairly. The defeat marked a turning point in humanity's relationship with artificial intelligence. If machines could beat us at chess, what else might they eventually surpass us in? The question has only grown more urgent as AI systems have conquered go, poker, and video games, and begun to challenge humans in creative fields from art to writing. Deep Blue was just the beginning.",
    design_config: {"thumbnailColor":"#1976D2","titlePage":{"backgroundColor":"#1976D2","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#1976D2","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#1976D2"},{"background":"#FFD60A","text":"#000000"},{"background":"#14213D","text":"#FFFFFF"}],"imagePlaceholderColors":["#1976D2","#FFD60A","#14213D"],"imageAspectRatios":[1.5,0.9],"imageColorOffset":1,"imagePositionSeed":3}
  }
];

async function uploadStory(story) {
  const response = await fetch(`${SUPABASE_URL}/rest/v1/stories`, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      "apikey": SUPABASE_KEY,
      "Authorization": `Bearer ${SUPABASE_KEY}`,
      "Prefer": "resolution=merge-duplicates,return=minimal"
    },
    body: JSON.stringify({
      slug: story.slug,
      title: story.title,
      description: story.description,
      category: story.category,
      thumbnail_color: story.thumbnail_color,
      published: true,
      published_at: new Date().toISOString(),
      body_text: story.body_text,
      design_config: story.design_config,
      updated_at: new Date().toISOString()
    })
  });

  if (!response.ok) {
    const text = await response.text();
    throw new Error(`${response.status}: ${text}`);
  }
}

async function main() {
  console.log(`Uploading ${stories.length} Science stories to Supabase...\n`);

  let success = 0;
  let failed = 0;

  for (const story of stories) {
    try {
      process.stdout.write(`Uploading: ${story.title}... `);
      await uploadStory(story);
      console.log("Done!");
      success++;
    } catch (error) {
      console.log(`Error: ${error.message}`);
      failed++;
    }
  }

  console.log(`\nComplete! ${success} succeeded, ${failed} failed.`);
}

main();
