/**
 * War Category - 25 New Stories
 * Usage: node scripts/new-content/war-new.mjs
 */

const SUPABASE_URL = "https://egfwisgqdyhzpmeoracb.supabase.co";
const SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVnZndpc2dxZHloenBtZW9yYWNiIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2ODQyNzM0OSwiZXhwIjoyMDg0MDAzMzQ5fQ.S8h1fIepxWb44gPSPpWQ8fE0Q-SCYfL0QcBRUV7fXgs";

const stories = [
  {
    slug: "battle-of-gettysburg",
    title: "The Battle of Gettysburg",
    description: "Three days that turned the Civil War",
    category: "War",
    thumbnail_color: "#3E5C76",
    body_text: `In the first three days of July 1863, approximately 165,000 men clashed in the fields and hills around a small Pennsylvania town. When it was over, more than 50,000 soldiers lay dead, wounded, or missing. The Battle of Gettysburg became the bloodiest engagement of the American Civil War and the moment when Confederate hopes for victory began to die. General Robert E. Lee had invaded the North, hoping to win a decisive battle on Union soil that would break Northern morale and force a negotiated peace. His Army of Northern Virginia had seemed invincible, having won a string of victories against larger Union forces. Lee believed one more triumph would end the war. He was wrong. The battle began almost by accident on July 1, when Confederate troops searching for shoes encountered Union cavalry. Fighting escalated as both armies rushed reinforcements to the scene. By evening, the Confederates had pushed Union forces back through the town onto the high ground of Cemetery Ridge. But they had not destroyed the enemy army. The next two days brought increasingly desperate attacks. On July 2, Confederate assaults on the Union flanks at places called Little Round Top, the Peach Orchard, and the Wheatfield produced horrific casualties but no breakthrough. On July 3, Lee ordered a massive frontal assault against the center of the Union line. Twelve thousand men marched across a mile of open ground under artillery fire. Pickett's Charge, as it became known, was a disaster. Barely half the attackers made it back to Confederate lines. Lee retreated to Virginia, never to threaten the North again. The Confederacy would fight for nearly two more years, but after Gettysburg, they were fighting to delay defeat, not achieve victory. Four months later, Abraham Lincoln came to dedicate a cemetery on the battlefield and delivered a speech of 272 words that redefined the meaning of the war and the nation.`,
    design_config: {"thumbnailColor":"#3E5C76","titlePage":{"backgroundColor":"#3E5C76","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#3E5C76","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#3E5C76"},{"background":"#8D6E63","text":"#FFFFFF"},{"background":"#C4B39A","text":"#000000"}],"imagePlaceholderColors":["#3E5C76","#8D6E63","#C4B39A"],"imageAspectRatios":[1.4,0.9],"imageColorOffset":0,"imagePositionSeed":2}
  },
  {
    slug: "pearl-harbor-attack",
    title: "The Attack on Pearl Harbor",
    description: "The day that woke a sleeping giant",
    category: "War",
    thumbnail_color: "#1565C0",
    body_text: `At 7:48 AM on December 7, 1941, the first wave of Japanese aircraft appeared over the Hawaiian island of Oahu. Within two hours, they had killed 2,403 Americans, sunk or damaged 21 ships, and destroyed 188 aircraft. The attack on Pearl Harbor thrust the United States into World War II and changed the course of the twentieth century. Japan had been planning the assault for nearly a year. Admiral Isoroku Yamamoto, who had studied at Harvard and served as a naval attache in Washington, understood American industrial capacity. He knew Japan could not win a prolonged war. The only hope was to destroy the Pacific Fleet in a single blow and force a quick negotiated peace. The attack achieved tactical surprise. American commanders had received warnings of possible Japanese aggression but expected attacks on the Philippines or Southeast Asia, not Hawaii. Radar operators spotted the incoming planes but their report was dismissed as a scheduled flight of American bombers. Sailors were eating breakfast when the bombs started falling. The destruction was catastrophic. Battleship Row took the worst of it. The USS Arizona exploded when a bomb penetrated its forward magazine, killing 1,177 men. The USS Oklahoma capsized, trapping hundreds of sailors below decks. Oil from ruptured tanks turned the harbor into a burning hellscape. Yet the attack was also a strategic failure. The American aircraft carriers, the most important ships in the Pacific, were not in port that day. The Japanese did not destroy the fuel storage tanks or repair facilities, which would have crippled American operations for months. And by attacking before declaring war, Japan united American public opinion in a way nothing else could have. President Roosevelt called it a date which will live in infamy. The sleeping giant had awakened, and it would not rest until Japan surrendered unconditionally four years later.`,
    design_config: {"thumbnailColor":"#1565C0","titlePage":{"backgroundColor":"#1565C0","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#1565C0","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#1565C0"},{"background":"#BF360C","text":"#FFFFFF"},{"background":"#4A4A4A","text":"#FFFFFF"}],"imagePlaceholderColors":["#1565C0","#BF360C","#4A4A4A"],"imageAspectRatios":[1.5,0.85],"imageColorOffset":1,"imagePositionSeed":3}
  },
  {
    slug: "bombing-of-dresden",
    title: "The Bombing of Dresden",
    description: "The firestorm that consumed a city",
    category: "War",
    thumbnail_color: "#BF360C",
    body_text: `On the night of February 13, 1945, 796 British bombers dropped nearly 2,700 tons of explosives and incendiary devices on Dresden, a German city swollen with refugees fleeing the advancing Soviet army. The following day, American bombers returned. By the time the attacks ended, large portions of the city center had been reduced to ash. The death toll remains disputed to this day. Dresden had been one of the most beautiful cities in Europe, known for its baroque architecture, its art collections, and its porcelain. It had little heavy industry and minimal military significance. Critics of the bombing argued it was an act of terror against civilians, not a legitimate military operation. Defenders pointed out that Dresden was a transportation hub for troops moving to the Eastern Front. The attack came as the war in Europe entered its final months. Germany's defeat was certain, but fighting continued on two fronts. The strategic bombing campaign had been grinding on for years, destroying German cities one by one in an attempt to break civilian morale and cripple war production. Dresden became the most controversial of these raids. The firestorm created by the incendiary bombs generated winds of hurricane force that sucked oxygen out of basements where civilians sheltered. Temperatures reached 1,500 degrees Fahrenheit. People who ventured onto the streets caught fire. Those who hid in cellars suffocated. Bodies were found fused to melted asphalt. German propaganda claimed 200,000 or more had died. Modern historians estimate the toll at 25,000 to 35,000, still a staggering number. The bombing became a symbol of the moral ambiguity of strategic warfare. Kurt Vonnegut, an American prisoner of war who survived the attack, later wrote Slaughterhouse-Five, transmuting his experience into one of the most influential antiwar novels ever published. Dresden's destruction still haunts debates about what is permissible in war.`,
    design_config: {"thumbnailColor":"#BF360C","titlePage":{"backgroundColor":"#BF360C","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#BF360C","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#BF360C"},{"background":"#FFD60A","text":"#000000"},{"background":"#4A4A4A","text":"#FFFFFF"}],"imagePlaceholderColors":["#BF360C","#FFD60A","#4A4A4A"],"imageAspectRatios":[1.3,0.9],"imageColorOffset":0,"imagePositionSeed":4}
  },
  {
    slug: "battle-of-the-bulge",
    title: "The Battle of the Bulge",
    description: "Hitler's desperate gamble in the Ardennes",
    category: "War",
    thumbnail_color: "#455A64",
    body_text: `On December 16, 1944, more than 200,000 German soldiers launched a surprise attack through the Ardennes forest in Belgium. The assault caught Allied forces completely off guard. Within days, German units had created a massive bulge in the Allied lines, threatening to split the British and American armies and capture the vital port of Antwerp. It was Hitler's last major offensive of the war. The plan was audacious but desperate. Germany was losing on every front. The Soviets were advancing from the east, and Allied forces were pushing toward the Rhine from the west. Hitler believed a decisive blow against the western Allies would force them to negotiate a separate peace, allowing Germany to focus on the Soviets. His generals thought it was madness. The attack achieved initial surprise because Allied intelligence had dismissed the Ardennes as impassable for large armored forces. The same assumption had allowed Germany to invade France successfully in 1940. American units holding the line were mostly green troops or exhausted veterans resting in a quiet sector. They were overwhelmed. The weather favored the Germans at first, with fog and clouds grounding Allied aircraft. But the advance soon slowed. American defenders at key crossroads like Bastogne refused to surrender. When a German commander demanded capitulation, Brigadier General Anthony McAuliffe famously replied with a single word: Nuts. The weather cleared on December 23, allowing Allied aircraft to devastate German supply columns. Fuel shortages, fierce resistance, and the arrival of reinforcements ground the offensive to a halt. By mid-January, the bulge had been eliminated and the Germans were in full retreat. The battle cost America nearly 90,000 casualties, making it the bloodiest single engagement for American forces in World War II. For Germany, it had squandered irreplaceable men and equipment. The war would end four months later.`,
    design_config: {"thumbnailColor":"#455A64","titlePage":{"backgroundColor":"#455A64","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#455A64","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#455A64"},{"background":"#5D4037","text":"#FFFFFF"},{"background":"#C4B39A","text":"#000000"}],"imagePlaceholderColors":["#455A64","#5D4037","#C4B39A"],"imageAspectRatios":[1.4,0.85],"imageColorOffset":1,"imagePositionSeed":2}
  },
  {
    slug: "dunkirk-evacuation",
    title: "The Miracle of Dunkirk",
    description: "When Britain rescued an army from the beach",
    category: "War",
    thumbnail_color: "#37474F",
    body_text: `In late May 1940, the British Expeditionary Force was trapped. German armies had swept through Belgium and northern France, cutting off nearly 400,000 Allied soldiers against the English Channel. They were surrounded, outnumbered, and running out of ammunition. The war was barely three weeks old, and Britain was about to lose its entire professional army. Then something remarkable happened. Between May 26 and June 4, a hastily assembled fleet of destroyers, ferries, fishing boats, and private yachts crossed the Channel and brought the soldiers home. Over 338,000 men were evacuated from the beaches and harbor of Dunkirk in what became known as Operation Dynamo. The evacuation succeeded partly because of Hitler's puzzling decision to halt his tanks short of the beaches for two critical days. German commanders feared their armor was overextended and vulnerable to counterattack. The Luftwaffe was given the task of destroying the trapped army from the air. It failed. RAF fighters, flying from bases in England, contested control of the skies. Meanwhile, the British Admiralty commandeered every vessel that could float. The fleet that arrived at Dunkirk included pleasure cruisers, lifeboats, river barges, and yachts. Their civilian owners often came with them, sailing into combat zones to rescue soldiers they had never met. The evacuation was a defeat dressed as a victory. Britain had lost all of its heavy equipment and many of its trained soldiers. The French army, left to fight on alone, would surrender within weeks. Yet Dunkirk saved the core of the British army and preserved the nation's ability to continue the war. Winston Churchill warned against calling it a victory, but the rescue became a symbol of British resilience. The little ships that crossed the Channel entered national mythology. Sometimes survival is enough.`,
    design_config: {"thumbnailColor":"#37474F","titlePage":{"backgroundColor":"#37474F","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#37474F","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#37474F"},{"background":"#1565C0","text":"#FFFFFF"},{"background":"#E8E8E8","text":"#000000"}],"imagePlaceholderColors":["#37474F","#1565C0","#E8E8E8"],"imageAspectRatios":[1.5,0.9],"imageColorOffset":0,"imagePositionSeed":3}
  },
  {
    slug: "hiroshima-atomic-bomb",
    title: "Hiroshima",
    description: "The day the atomic age began",
    category: "War",
    thumbnail_color: "#D84315",
    body_text: `At 8:15 AM on August 6, 1945, a single bomb exploded 1,900 feet above Hiroshima, Japan. The blast was equivalent to 15,000 tons of TNT. In an instant, approximately 80,000 people died. By the end of the year, radiation sickness and burns would push the death toll to over 140,000. The atomic age had begun in the most terrifying way imaginable. The bomb, nicknamed Little Boy, had been developed in complete secrecy by the Manhattan Project. Scientists from across the Allied nations had worked for three years to unlock the power of nuclear fission. Many of them hoped the weapon would never be used. But the war with Japan ground on, and estimates for a conventional invasion predicted hundreds of thousands of American casualties. President Truman authorized the attack. The Enola Gay, a B-29 bomber, took off from Tinian Island in the early morning hours. Crew members had been told they were carrying a new weapon that might end the war. They did not fully understand what that meant until they saw the mushroom cloud rising 40,000 feet into the sky. On the ground, everything within a mile of the hypocenter was vaporized. People caught in the open were instantly incinerated, leaving only shadows burned into stone. Those farther away suffered horrific burns and radiation injuries. The city's wooden buildings ignited, and firestorms consumed what the blast had not. Three days later, a second atomic bomb destroyed Nagasaki. On August 15, Japan announced its surrender. The bombs had achieved their military purpose. They had also created a new existential threat to humanity. The Cold War nuclear arms race followed, eventually producing arsenals capable of destroying civilization many times over. Hiroshima became a memorial to the victims and a warning about the weapons we had created. The peace park now standing at the hypocenter draws visitors from around the world, a reminder of where the atomic age began.`,
    design_config: {"thumbnailColor":"#D84315","titlePage":{"backgroundColor":"#D84315","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#D84315","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#D84315"},{"background":"#FFD60A","text":"#000000"},{"background":"#4A4A4A","text":"#FFFFFF"}],"imagePlaceholderColors":["#D84315","#FFD60A","#4A4A4A"],"imageAspectRatios":[1.3,0.85],"imageColorOffset":1,"imagePositionSeed":4}
  },
  {
    slug: "battle-of-verdun",
    title: "The Battle of Verdun",
    description: "The meat grinder of the Western Front",
    category: "War",
    thumbnail_color: "#5D4037",
    body_text: `For ten months in 1916, French and German soldiers slaughtered each other in the hills around Verdun, a fortress city in northeastern France. When it finally ended, an estimated 700,000 men had been killed or wounded. The landscape itself had been obliterated, transformed into a moonscape of craters, debris, and human remains. Verdun became the symbol of World War I's senseless carnage. German Chief of Staff Erich von Falkenhayn designed the attack with a chilling rationale. He did not expect to capture Verdun. He wanted to bleed France white by forcing the French army to defend a position of enormous symbolic importance at any cost. The battle would be an industrialized slaughter, with German artillery doing most of the killing while French troops marched into the meat grinder. The assault began on February 21 with the largest artillery bombardment in history. Over a million shells fell in the first day alone. German troops advanced through the devastation, expecting to find only corpses. Instead, they encountered French soldiers who had survived in deep bunkers and were ready to fight. The battle became a nightmare of attrition. Positions changed hands repeatedly. Fort Douaumont, captured by the Germans early on, became a tomb for hundreds of soldiers from both sides. The constant shelling churned the ground so thoroughly that bodies were buried and exhumed repeatedly. Some soldiers went mad from the endless noise and horror. The French held. General Philippe Petain organized a rotation system that brought fresh troops to the front while exhausted survivors were pulled back. The phrase They shall not pass became the French rallying cry. By December, a series of French counterattacks had recaptured most of the lost ground. Verdun had not fallen, but the price was beyond calculation. The battlefield remains scarred today, with forests growing over the bones of the unrecovered dead.`,
    design_config: {"thumbnailColor":"#5D4037","titlePage":{"backgroundColor":"#5D4037","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#5D4037","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#5D4037"},{"background":"#8D6E63","text":"#FFFFFF"},{"background":"#C4B39A","text":"#000000"}],"imagePlaceholderColors":["#5D4037","#8D6E63","#C4B39A"],"imageAspectRatios":[1.4,0.9],"imageColorOffset":0,"imagePositionSeed":2}
  },
  {
    slug: "battle-of-the-somme",
    title: "The Battle of the Somme",
    description: "The bloodiest day in British military history",
    category: "War",
    thumbnail_color: "#6D4C41",
    body_text: `On July 1, 1916, the British Army suffered 57,470 casualties in a single day. Nearly 20,000 of those men were killed outright. It was the bloodiest day in British military history, the opening of the Battle of the Somme, and a catastrophe that would define a generation. The plan had seemed straightforward. After a week-long artillery bombardment that was supposed to destroy German defenses, British and French troops would advance across no man's land and break through the enemy lines. Allied commanders expected the Germans to be dead or dazed, their barbed wire cut, their trenches flattened. They were disastrously wrong. The German defenses were deeper and stronger than anyone realized. Troops had sheltered in bunkers carved into the chalk, emerging unscathed when the shelling stopped. The wire had not been cut. British soldiers, many of them volunteers who had enlisted in the first wave of wartime enthusiasm, walked into machine gun fire and were mowed down in rows. Some battalions lost ninety percent of their men in the first hour. The battle continued for four more months. Commanders refused to abandon the offensive, convinced that one more push would achieve the breakthrough. It never came. Tanks made their debut at the Somme but were too few and too unreliable to change the outcome. By November, when winter mud finally halted the fighting, the Allies had advanced barely six miles at a cost of over 600,000 casualties. German losses were comparable. The Somme shattered the romantic illusions about war that had sent millions of young men marching off to enlist in 1914. It produced a generation of poets and writers who would never forget what they had seen. The Somme was where the modern world's understanding of war's horror was forged.`,
    design_config: {"thumbnailColor":"#6D4C41","titlePage":{"backgroundColor":"#6D4C41","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#6D4C41","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#6D4C41"},{"background":"#8D6E63","text":"#FFFFFF"},{"background":"#C4B39A","text":"#000000"}],"imagePlaceholderColors":["#6D4C41","#8D6E63","#C4B39A"],"imageAspectRatios":[1.5,0.85],"imageColorOffset":1,"imagePositionSeed":3}
  },
  {
    slug: "gulf-war-desert-storm",
    title: "Operation Desert Storm",
    description: "The 100-hour war that reset expectations",
    category: "War",
    thumbnail_color: "#F9A825",
    body_text: `On February 24, 1991, the largest American military operation since Vietnam began. Coalition ground forces invaded Kuwait and southern Iraq, beginning what would become known as the 100-hour war. In four days, they destroyed the Iraqi army and liberated Kuwait at a cost of fewer than 200 American dead. It was an astonishing display of technological superiority that reshaped military thinking for a generation. The Gulf War had begun the previous August when Saddam Hussein's forces invaded and occupied Kuwait, a small oil-rich nation on Iraq's southern border. The international response was swift and unified. The United Nations authorized force to remove Iraqi troops, and a coalition of 35 nations assembled in Saudi Arabia. For five months, diplomacy failed to produce an Iraqi withdrawal. The air campaign started on January 17, 1991, and it was unlike anything seen before. Precision-guided weapons allowed bombers to strike individual targets with accuracy that would have been impossible a decade earlier. Television audiences watched videos of bombs flying through windows and down ventilation shafts. Iraqi air defenses were systematically destroyed. When the ground assault finally came, Iraqi forces had been pounded for five weeks. Coalition troops swept through Iraqi positions that had been advertised as formidable. Thousands of Iraqi soldiers surrendered at the first opportunity, often to journalists or even remote-controlled drones. The Republican Guard, Saddam's elite forces, were crushed in tank battles that lasted hours. The speed of victory created unrealistic expectations. Military planners began to believe technology had fundamentally changed warfare, that future conflicts would be quick and relatively bloodless. The invasion of Iraq twelve years later would prove otherwise. Saddam Hussein remained in power after the Gulf War, his regime surviving until 2003. The easy victory had consequences that would take decades to unfold.`,
    design_config: {"thumbnailColor":"#F9A825","titlePage":{"backgroundColor":"#F9A825","textColor":"#000000"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#F9A825","text":"#000000"},{"background":"#FFFFFF","text":"#F9A825"},{"background":"#5D4037","text":"#FFFFFF"},{"background":"#E8E8E8","text":"#000000"}],"imagePlaceholderColors":["#F9A825","#5D4037","#E8E8E8"],"imageAspectRatios":[1.4,0.9],"imageColorOffset":0,"imagePositionSeed":4}
  },
  {
    slug: "falklands-war",
    title: "The Falklands War",
    description: "Britain's last imperial adventure",
    category: "War",
    thumbnail_color: "#0D47A1",
    body_text: `On April 2, 1982, Argentine forces invaded the Falkland Islands, a windswept British territory in the South Atlantic, eight thousand miles from London. Most people had never heard of the islands. Within ten weeks, Britain had launched a naval task force, recaptured the territory, and lost 255 servicemen in the last old-fashioned naval war of the twentieth century. Argentina had claimed the islands, which they called the Malvinas, since the nineteenth century. The military junta ruling the country believed Britain would not fight for a distant colonial remnant with a population of fewer than two thousand people. They believed wrong. Prime Minister Margaret Thatcher, her government unpopular and seemingly adrift, saw the invasion as a challenge that demanded a military response. The task force that sailed from Portsmouth included aircraft carriers, destroyers, and troop transports, many of them hastily modified for combat. The journey took three weeks. The fighting was intense and costly. The destroyer HMS Sheffield was sunk by an Exocet missile, shocking a British public unused to naval casualties. The transport Atlantic Conveyor was hit, destroying helicopters critical for the land campaign. Argentine aircraft pressed home attacks despite heavy losses, sinking or damaging multiple ships. On land, British forces fought through freezing conditions against a larger Argentine garrison. The battles at Goose Green and Mount Longdon produced some of the fiercest infantry combat since Korea. By June 14, Argentine forces in Port Stanley surrendered. The war's consequences reshaped both nations. In Argentina, the defeat discredited the military government and accelerated the return to democracy. In Britain, victory transformed Thatcher's political fortunes and contributed to her landslide reelection the following year. The Falklands remain British today, their status guaranteed by the blood shed to keep them.`,
    design_config: {"thumbnailColor":"#0D47A1","titlePage":{"backgroundColor":"#0D47A1","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#0D47A1","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#0D47A1"},{"background":"#14213D","text":"#FFFFFF"},{"background":"#E8E8E8","text":"#000000"}],"imagePlaceholderColors":["#0D47A1","#14213D","#E8E8E8"],"imageAspectRatios":[1.3,0.9],"imageColorOffset":1,"imagePositionSeed":2}
  },
  {
    slug: "battle-of-waterloo",
    title: "The Battle of Waterloo",
    description: "Napoleon's final defeat",
    category: "War",
    thumbnail_color: "#3E2723",
    body_text: `On June 18, 1815, near a small Belgian village called Waterloo, Napoleon Bonaparte met his final defeat. The battle lasted only nine hours, but it ended twenty-three years of nearly continuous warfare and redrew the map of Europe for a century. It was the last time Napoleon would command an army. The emperor had returned from exile just three months earlier, escaping from Elba and reclaiming France in a bloodless coup that sent the restored Bourbon monarchy fleeing. The allied powers of Europe immediately declared war. Napoleon knew he had to strike quickly, before the Austrian, Russian, and Prussian armies could converge on France. He invaded Belgium with 124,000 men, hoping to defeat the British and Prussian forces separately before they could unite. The British commander, the Duke of Wellington, chose to make his stand on a ridge south of Waterloo. His army of 68,000 men, a mixed force of British, Dutch, Belgian, and German troops, would hold this position while waiting for Prussian reinforcements. Napoleon attacked with characteristic aggression. The battle began with a diversionary assault on the fortified farmhouse of Hougoumont, which absorbed French troops all day without falling. Wave after wave of infantry and cavalry crashed against Wellington's lines, which bent but did not break. By late afternoon, Napoleon could see Prussian columns approaching from the east. He committed his Imperial Guard, the elite veterans who had never been defeated. When they too were thrown back, the French army collapsed. The retreat became a rout. Napoleon fled to Paris, abdicated, and surrendered to the British. He spent his remaining years in exile on Saint Helena, a remote island in the South Atlantic. Wellington became a national hero and eventually prime minister. The peace that followed Waterloo lasted, with few interruptions, until 1914.`,
    design_config: {"thumbnailColor":"#3E2723","titlePage":{"backgroundColor":"#3E2723","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#3E2723","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#3E2723"},{"background":"#8D6E63","text":"#FFFFFF"},{"background":"#FFD60A","text":"#000000"}],"imagePlaceholderColors":["#3E2723","#8D6E63","#FFD60A"],"imageAspectRatios":[1.5,0.85],"imageColorOffset":0,"imagePositionSeed":3}
  },
  {
    slug: "siege-of-troy",
    title: "The Siege of Troy",
    description: "The war that inspired Western literature",
    category: "War",
    thumbnail_color: "#8D6E63",
    body_text: `According to Homer, the Greeks besieged the city of Troy for ten years because a Trojan prince named Paris had stolen Helen, the most beautiful woman in the world, from her Greek husband. When the city finally fell, it was through deception: a giant wooden horse filled with hidden soldiers. The story has captivated Western imagination for nearly three thousand years. But was any of it real? For centuries, scholars assumed Troy was purely mythological. Then, in the 1870s, a German businessman named Heinrich Schliemann excavated a mound in northwestern Turkey and discovered the ruins of multiple ancient cities built one atop another. One of these, destroyed by fire around 1180 BCE, matched the traditional date of the Trojan War. Troy was real. The war may have been too. Archaeological evidence suggests the city was wealthy and strategically located, controlling trade routes between the Mediterranean and the Black Sea. Conflict with Mycenaean Greeks, the civilization that preceded classical Greece, is entirely plausible. The details Homer preserved—the armor, the ships, the social customs—match what we know of the Bronze Age. But Homer wrote four centuries after the events he described. His Iliad focuses on just a few weeks of the war, telling the story of the Greek hero Achilles and his quarrel with Agamemnon, the expedition's leader. It is not history but epic poetry, shaped by centuries of oral tradition. The wooden horse itself may be a poetic metaphor for an earthquake or a siege engine. We will never know for certain what happened at Troy. What we know is that the story of the siege became the foundation of Western literature, the model for countless tales of heroes and wars and the fall of cities. Every war story since has lived in Troy's shadow.`,
    design_config: {"thumbnailColor":"#8D6E63","titlePage":{"backgroundColor":"#8D6E63","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#8D6E63","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#8D6E63"},{"background":"#5D4037","text":"#FFFFFF"},{"background":"#C4B39A","text":"#000000"}],"imagePlaceholderColors":["#8D6E63","#5D4037","#C4B39A"],"imageAspectRatios":[1.4,0.9],"imageColorOffset":1,"imagePositionSeed":4}
  },
  {
    slug: "battle-of-cannae",
    title: "The Battle of Cannae",
    description: "Hannibal's masterpiece of destruction",
    category: "War",
    thumbnail_color: "#B71C1C",
    body_text: `On August 2, 216 BCE, near the Italian town of Cannae, the Carthaginian general Hannibal Barca achieved one of the most complete military victories in recorded history. Facing a Roman army nearly twice the size of his own, he orchestrated a double envelopment that killed or captured approximately 70,000 enemy soldiers in a single afternoon. Roman power seemed on the verge of annihilation. Hannibal had already accomplished the impossible. Two years earlier, he had led an army including war elephants across the Alps in winter, losing thousands of men but arriving in Italy to threaten Rome directly. He had crushed Roman armies at the Trebia River and Lake Trasimene. Now Rome had assembled its largest force ever, determined to destroy the Carthaginian menace once and for all. The Roman commanders were confident. They outnumbered Hannibal roughly 86,000 to 50,000. They deployed their infantry in an unusually deep formation, planning to punch straight through the Carthaginian center with overwhelming weight. It was exactly what Hannibal wanted. He placed his weakest troops in the center and his best on the flanks. As the Roman infantry pushed forward, the Carthaginian center slowly gave ground, bending but not breaking. Meanwhile, Hannibal's cavalry swept around the flanks and attacked the Roman rear. The trap was sprung. Surrounded on all sides, the Romans could not maneuver or retreat. They were compressed into an ever-tightening mass and systematically butchered. Hannibal's soldiers killed until their arms grew tired. Among the dead was one of the Roman consuls and eighty senators. Yet Rome did not surrender. Despite losing an army that represented one in five adult male citizens, the Senate refused to negotiate. They raised new legions, adopted a strategy of avoiding pitched battle, and eventually carried the war to Africa, where Hannibal was finally defeated at Zama in 202 BCE. Cannae became the military textbook example of tactical perfection, studied by generals for two thousand years.`,
    design_config: {"thumbnailColor":"#B71C1C","titlePage":{"backgroundColor":"#B71C1C","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#B71C1C","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#B71C1C"},{"background":"#8D6E63","text":"#FFFFFF"},{"background":"#FFD60A","text":"#000000"}],"imagePlaceholderColors":["#B71C1C","#8D6E63","#FFD60A"],"imageAspectRatios":[1.3,0.85],"imageColorOffset":0,"imagePositionSeed":2}
  },
  {
    slug: "battle-of-agincourt",
    title: "The Battle of Agincourt",
    description: "When English longbows defeated French chivalry",
    category: "War",
    thumbnail_color: "#1B5E20",
    body_text: `On October 25, 1415, a sick and starving English army faced annihilation in northern France. King Henry V had fewer than six thousand men, most of them archers suffering from dysentery after weeks of marching. The French army blocking their path numbered perhaps twenty thousand, including the flower of French nobility in their finest armor. By nightfall, the French army had been destroyed and over ten thousand Frenchmen lay dead in the mud of Agincourt. Henry had invaded France to press his claim to the French throne. After capturing the port of Harfleur, his army was too weakened to continue. He decided to march to the English-held port of Calais, but French forces moved to intercept. Battle became inevitable. The French were overconfident. Their constable, Charles d'Albret, chose a battlefield where the forest on either side would funnel his cavalry charge directly at the English lines. He planned to overwhelm the archers and sweep away Henry's army in one glorious charge. Instead, the terrain became a death trap. The field had been freshly plowed and soaked by autumn rains. When the French cavalry charged, their horses bogged down in the mud. English longbowmen, protected by sharpened stakes, unleashed a storm of arrows that felled horses and riders. Men in heavy armor who fell could not rise from the muck. French infantry following the cavalry climbed over the bodies of the fallen, only to meet English men-at-arms in close combat. The slaughter continued for hours. At one point, fearing a renewed attack, Henry ordered prisoners killed, a controversial decision that haunts his reputation. The victory made Henry master of northern France and led to the Treaty of Troyes, which recognized him as heir to the French throne. He died two years later, and everything he had won was eventually lost. But Agincourt entered English legend, immortalized by Shakespeare as the triumph of the happy few against impossible odds.`,
    design_config: {"thumbnailColor":"#1B5E20","titlePage":{"backgroundColor":"#1B5E20","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#1B5E20","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#1B5E20"},{"background":"#8D6E63","text":"#FFFFFF"},{"background":"#FFD60A","text":"#000000"}],"imagePlaceholderColors":["#1B5E20","#8D6E63","#FFD60A"],"imageAspectRatios":[1.5,0.9],"imageColorOffset":1,"imagePositionSeed":3}
  },
  {
    slug: "battle-of-kursk",
    title: "The Battle of Kursk",
    description: "The largest tank battle in history",
    category: "War",
    thumbnail_color: "#4E342E",
    body_text: `In July 1943, nearly two million soldiers and six thousand tanks clashed on the plains of central Russia in the largest armored battle in history. The Battle of Kursk lasted fifty days and ended with the German army in irreversible retreat. After Kursk, the Red Army would never stop advancing until it reached Berlin. Germany had lost the strategic initiative at Stalingrad the previous winter, but Hitler was determined to regain it. A massive bulge in the front line around the city of Kursk seemed to offer an opportunity. By attacking from north and south simultaneously, the Germans planned to cut off and destroy the Soviet forces in the salient, inflicting a defeat that might stabilize the Eastern Front. The Soviets knew the attack was coming. They had broken German codes and had detailed intelligence from a spy ring in the German High Command. Marshal Georgy Zhukov prepared the deepest defensive system ever constructed, with multiple lines of trenches, millions of mines, and massive reserves held back for a counteroffensive. The Germans attacked on July 5 with their newest tanks, including the formidable Tiger and Panther models. For a week, they ground through Soviet defenses, taking terrible losses but making slow progress. The climax came at Prokhorovka, where approximately 1,200 tanks fought at point-blank range in what became the single largest tank engagement in history. Neither side won a clear victory, but the Germans could not afford the losses. On July 12, the Soviets launched their counteroffensive. Within a month, they had retaken Kharkov and were pushing west. The German army that had once seemed invincible was now clearly losing. Kursk proved that the Red Army had learned from its earlier defeats. Soviet tactics, equipment, and leadership had improved dramatically. Germany had bet everything on one last offensive gamble and lost.`,
    design_config: {"thumbnailColor":"#4E342E","titlePage":{"backgroundColor":"#4E342E","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#4E342E","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#4E342E"},{"background":"#B71C1C","text":"#FFFFFF"},{"background":"#8D6E63","text":"#FFFFFF"}],"imagePlaceholderColors":["#4E342E","#B71C1C","#8D6E63"],"imageAspectRatios":[1.4,0.85],"imageColorOffset":0,"imagePositionSeed":4}
  },
  {
    slug: "battle-of-britain",
    title: "The Battle of Britain",
    description: "When the RAF saved the free world",
    category: "War",
    thumbnail_color: "#1976D2",
    body_text: `In the summer of 1940, Britain stood alone against Nazi Germany. France had fallen. The Soviet Union was still honoring its pact with Hitler. The United States remained neutral. Only the English Channel and the Royal Air Force prevented German invasion. For three months, young pilots fought a desperate battle in the skies over southern England that would determine the fate of the world. The Luftwaffe was tasked with destroying the RAF and establishing air superiority over the Channel, without which an amphibious invasion was impossible. Germany had more aircraft and more experienced pilots. Britain had radar, which allowed controllers to direct fighters to intercept incoming raids, and the advantage of fighting over home territory, where downed pilots could return to duty. The battle began in July with attacks on Channel convoys and coastal targets. In August, the Luftwaffe shifted to striking airfields and aircraft factories, trying to destroy the RAF on the ground. Fighter Command was being worn down. Losses of trained pilots exceeded the rate at which replacements could be trained. By early September, some squadrons were operating at half strength. Then Hitler made a fateful decision. Enraged by a British bombing raid on Berlin, he ordered the Luftwaffe to attack London instead of continuing to target airfields. The Blitz, as it became known, killed over 40,000 British civilians. But it also gave Fighter Command time to recover. On September 15, the RAF inflicted such heavy losses on German bomber formations that Hitler postponed the invasion indefinitely. It would never be rescheduled. Churchill famously said that never in the field of human conflict was so much owed by so many to so few. The few were approximately 2,900 pilots, over 500 of whom died during the battle. Many were barely out of their teens. They saved Britain and kept alive the possibility of eventual Allied victory.`,
    design_config: {"thumbnailColor":"#1976D2","titlePage":{"backgroundColor":"#1976D2","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#1976D2","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#1976D2"},{"background":"#14213D","text":"#FFFFFF"},{"background":"#E8E8E8","text":"#000000"}],"imagePlaceholderColors":["#1976D2","#14213D","#E8E8E8"],"imageAspectRatios":[1.3,0.9],"imageColorOffset":1,"imagePositionSeed":2}
  },
  {
    slug: "battle-of-iwo-jima",
    title: "The Battle of Iwo Jima",
    description: "The island fortress that cost 26,000 American casualties",
    category: "War",
    thumbnail_color: "#37474F",
    body_text: `The island was tiny, barely eight square miles of volcanic rock and black sand. But Iwo Jima lay directly on the flight path between American bases in the Marianas and Japan. Taking it would provide an emergency landing field for damaged B-29 bombers and eliminate Japanese fighters that intercepted the raids. In February 1945, the Marines landed to discover the most formidable defensive system they had ever faced. Japanese General Tadamichi Kuribayashi had transformed Iwo Jima into an underground fortress. Miles of tunnels connected fortified positions across the island. Artillery and machine guns were positioned to cover every beach and every approach. The Japanese had learned from previous island battles and abandoned the futile banzai charges that had wasted their strength. They would make the Americans pay for every yard. The initial bombardment, three days of naval gunfire and aerial bombing, barely scratched the defenses. When Marines hit the beaches on February 19, they found themselves struggling through volcanic ash that provided no traction and no cover. Japanese fire from the dominating height of Mount Suribachi and from hidden positions across the island turned the landing beaches into killing grounds. The battle lasted thirty-six days. Marines fought through a maze of pillboxes, bunkers, and interconnected caves, often advancing only yards at a time. Flamethrowers and demolition charges were the primary weapons for clearing defensive positions. The famous photograph of Marines raising the American flag on Mount Suribachi was taken on the fifth day, but the hardest fighting still lay ahead. Nearly 7,000 Marines and sailors died taking Iwo Jima. Almost all of the 21,000 Japanese defenders were killed. The island that was supposed to be conquered in five days had required more than a month. But the B-29s now had their emergency airfield, and by war's end, over 2,400 bombers had made emergency landings there, saving an estimated 24,000 American airmen.`,
    design_config: {"thumbnailColor":"#37474F","titlePage":{"backgroundColor":"#37474F","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#37474F","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#37474F"},{"background":"#5D4037","text":"#FFFFFF"},{"background":"#C4B39A","text":"#000000"}],"imagePlaceholderColors":["#37474F","#5D4037","#C4B39A"],"imageAspectRatios":[1.5,0.85],"imageColorOffset":0,"imagePositionSeed":3}
  },
  {
    slug: "battle-of-okinawa",
    title: "The Battle of Okinawa",
    description: "The typhoon of steel",
    category: "War",
    thumbnail_color: "#0D47A1",
    body_text: `From April to June 1945, American forces fought the bloodiest battle of the Pacific War on the Japanese island of Okinawa. The campaign cost over 12,000 American dead, perhaps 100,000 Japanese military casualties, and as many as 150,000 Okinawan civilians. The Japanese called it the Typhoon of Steel. For the Americans, it was a preview of what an invasion of the Japanese mainland might require. Okinawa was different from previous Pacific battles. It was Japanese home territory, not a distant colonial outpost. The civilian population was large and had been indoctrinated to resist. Japanese commanders had assembled the largest concentration of artillery in the Pacific and planned to bleed the invaders through attrition rather than futile counterattacks. The American landing on April 1 met light resistance, but the advance south soon bogged down against the Shuri Line, a network of fortifications that the Japanese defended with suicidal tenacity. Rain turned the battlefield to mud. Progress was measured in yards. Kamikazes attacked the supporting fleet in waves, sinking or damaging dozens of ships and killing thousands of sailors. The fighting produced scenes of horror. Civilians died in the crossfire or were killed by Japanese soldiers who feared they would surrender. Some committed mass suicide, convinced by propaganda that the Americans would torture them. The battle became a grinding attrition that consumed men at rates not seen since the Western Front. When organized resistance finally ended on June 22, Japan's ability to defend the home islands had been demonstrated. American planners estimated that an invasion of Japan would cost hundreds of thousands of casualties. The atomic bombs dropped on Hiroshima and Nagasaki in August made that invasion unnecessary. But the experience of Okinawa had already convinced many that any price was worth avoiding such a campaign.`,
    design_config: {"thumbnailColor":"#0D47A1","titlePage":{"backgroundColor":"#0D47A1","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#0D47A1","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#0D47A1"},{"background":"#37474F","text":"#FFFFFF"},{"background":"#E8E8E8","text":"#000000"}],"imagePlaceholderColors":["#0D47A1","#37474F","#E8E8E8"],"imageAspectRatios":[1.4,0.9],"imageColorOffset":1,"imagePositionSeed":4}
  },
  {
    slug: "battle-of-inchon",
    title: "The Landing at Inchon",
    description: "MacArthur's masterstroke in Korea",
    category: "War",
    thumbnail_color: "#004D40",
    body_text: `On September 15, 1950, American forces launched an amphibious assault at Inchon, a port on the west coast of Korea. The landing was a desperate gamble that violated nearly every principle of amphibious warfare. It succeeded beyond all expectations, trapping the North Korean army and reversing the course of the Korean War in a single stroke. Three months earlier, North Korea had invaded the South, driving American and South Korean forces into a shrinking perimeter around the port of Pusan. The situation seemed hopeless. General Douglas MacArthur proposed an audacious solution: land behind enemy lines at Inchon, cut their supply routes, and destroy them between two forces. His own planners were skeptical. Inchon had some of the most extreme tides in the world, with channels navigable only a few hours each day. The harbor was protected by fortified islands. The sea walls were high enough to require scaling ladders. Navy planners calculated the odds of success at one in five thousand. MacArthur overruled them all. The landing achieved complete surprise. North Korean defenders were quickly overwhelmed. Within two weeks, American forces had recaptured Seoul and severed the enemy's logistics. The North Korean army, cut off from supplies and reinforcements, disintegrated. Survivors fled north in disarray. MacArthur's gamble had paid off spectacularly. The victory seemed to confirm his genius. It also encouraged overconfidence that would lead to disaster. In the weeks that followed, MacArthur pushed north toward the Chinese border despite warnings that China might intervene. In November, over 300,000 Chinese troops crossed the Yalu River and drove the United Nations forces back in the longest retreat in American military history. The Korean War would drag on for three more years. But Inchon remained MacArthur's masterpiece, a reminder that sometimes the impossible is merely improbable.`,
    design_config: {"thumbnailColor":"#004D40","titlePage":{"backgroundColor":"#004D40","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#004D40","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#004D40"},{"background":"#1976D2","text":"#FFFFFF"},{"background":"#E8E8E8","text":"#000000"}],"imagePlaceholderColors":["#004D40","#1976D2","#E8E8E8"],"imageAspectRatios":[1.3,0.85],"imageColorOffset":0,"imagePositionSeed":2}
  },
  {
    slug: "battle-of-dien-bien-phu",
    title: "The Fall of Dien Bien Phu",
    description: "The battle that ended French Indochina",
    category: "War",
    thumbnail_color: "#2E7D32",
    body_text: `In the spring of 1954, the French army suffered one of the most decisive defeats in colonial military history. At a remote valley in northwestern Vietnam called Dien Bien Phu, Viet Minh forces surrounded and destroyed an elite French garrison, ending nearly a century of French rule in Indochina and setting the stage for America's Vietnam War. French commanders had deliberately established a base in the valley, hoping to lure the Viet Minh into a conventional battle where French firepower would prove decisive. They underestimated their enemy. General Vo Nguyen Giap, the Viet Minh commander, assembled an army of over 50,000 men and, through an extraordinary effort, dragged heavy artillery through mountains that the French had deemed impassable. The siege began on March 13, 1954. Vietnamese artillery, positioned in the hills overlooking the French base, systematically destroyed the airstrip and the outlying strongpoints. French counterattacks failed to dislodge the guns. The garrison's commander of artillery, realizing his fatal miscalculation, committed suicide. For fifty-five days, the French held on, resupplied only by parachute drops that became increasingly dangerous as the perimeter shrank. Reinforcements volunteered to jump into the trap, knowing they were likely marching to death or captivity. The final assault came on May 7. By evening, the garrison had surrendered. Nearly 12,000 French soldiers went into captivity, from which many would never return. The defeat ended French political will to continue the war. Peace negotiations in Geneva divided Vietnam at the seventeenth parallel, with Ho Chi Minh's communist government controlling the North and a Western-backed regime in the South. The division was supposed to be temporary. It would instead become the fault line for the next war.`,
    design_config: {"thumbnailColor":"#2E7D32","titlePage":{"backgroundColor":"#2E7D32","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#2E7D32","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#2E7D32"},{"background":"#5D4037","text":"#FFFFFF"},{"background":"#FFD60A","text":"#000000"}],"imagePlaceholderColors":["#2E7D32","#5D4037","#FFD60A"],"imageAspectRatios":[1.5,0.9],"imageColorOffset":1,"imagePositionSeed":3}
  },
  {
    slug: "battle-of-antietam",
    title: "The Battle of Antietam",
    description: "The bloodiest day in American history",
    category: "War",
    thumbnail_color: "#5D4037",
    body_text: `On September 17, 1862, approximately 23,000 men were killed, wounded, or went missing in twelve hours of fighting along Antietam Creek in Maryland. It remains the bloodiest single day in American military history, worse than D-Day, worse than any day at Gettysburg. The battle ended Robert E. Lee's first invasion of the North and gave Abraham Lincoln the victory he needed to issue the Emancipation Proclamation. Lee had crossed the Potomac in early September, hoping a victory on Northern soil would encourage European recognition of the Confederacy and undermine support for the war in the Union. But a copy of his orders was found wrapped around three cigars at an abandoned Confederate camp and brought to Union commander George McClellan. For once, McClellan knew exactly where the enemy was and what they planned to do. He still moved too slowly. Lee concentrated his scattered forces near the town of Sharpsburg, taking up defensive positions behind Antietam Creek. By the time McClellan attacked on September 17, the Confederate army was ready. The battle unfolded in three phases across the day. In the morning, Union attacks against the Confederate left produced horrific casualties at locations that became known as the Cornfield and the West Woods. At midday, fighting centered on a sunken road that became so filled with Confederate dead it earned the name Bloody Lane. In the afternoon, Union forces crossed the creek and nearly broke through the Confederate right before reinforcements arrived just in time. Night ended the fighting. Lee's army was battered but not destroyed. McClellan, typically cautious, did not renew the attack the next day, allowing Lee to retreat across the Potomac. The Union had won a tactical victory but missed an opportunity to end the war. Lincoln, disappointed but pragmatic, used the battle as the occasion to announce that all enslaved people in Confederate territory would be freed on January 1, 1863. The war had become a war against slavery.`,
    design_config: {"thumbnailColor":"#5D4037","titlePage":{"backgroundColor":"#5D4037","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#5D4037","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#5D4037"},{"background":"#8D6E63","text":"#FFFFFF"},{"background":"#C4B39A","text":"#000000"}],"imagePlaceholderColors":["#5D4037","#8D6E63","#C4B39A"],"imageAspectRatios":[1.4,0.85],"imageColorOffset":0,"imagePositionSeed":4}
  },
  {
    slug: "battle-of-hastings",
    title: "The Battle of Hastings",
    description: "The conquest that created England",
    category: "War",
    thumbnail_color: "#6A1B9A",
    body_text: `On October 14, 1066, an arrow struck King Harold II of England in the eye, ending the battle that would transform English history forever. By nightfall, the last Anglo-Saxon king lay dead on the field, and William, Duke of Normandy, had won the crown of England. The Norman Conquest had begun. The crisis started with the death of King Edward the Confessor in January 1066. Edward had no children, and multiple claimants emerged. Harold Godwinson, the powerful Earl of Wessex, was crowned king by the English nobility. But William of Normandy insisted Edward had promised him the throne and that Harold himself had sworn to support his claim. Across the Channel, William assembled an invasion fleet. Harold spent the summer waiting for the Norman attack, but the first threat came from the north. Harald Hardrada, King of Norway, invaded with a Viking army. Harold marched his forces three hundred miles in five days and destroyed the invaders at the Battle of Stamford Bridge. Three days later, William landed at Pevensey on the southern coast. Harold marched south again, covering nearly two hundred miles in less than two weeks. His exhausted army took up position on Senlac Hill near Hastings. For most of the day, the English shield wall held. Norman cavalry charges broke against the disciplined infantry. But Harold could not go on the offensive without abandoning his strong position. Late in the day, feigned Norman retreats drew portions of the English line out of formation, where they were cut down. The famous arrow may be legend, but Harold died and his army broke. William marched on London and was crowned king on Christmas Day. Over the following years, he crushed all resistance and replaced the English aristocracy with Norman lords. The language, laws, and culture of England were transformed. The Battle of Hastings was not just a change of kings but the end of one civilization and the beginning of another.`,
    design_config: {"thumbnailColor":"#6A1B9A","titlePage":{"backgroundColor":"#6A1B9A","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#6A1B9A","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#6A1B9A"},{"background":"#8D6E63","text":"#FFFFFF"},{"background":"#FFD60A","text":"#000000"}],"imagePlaceholderColors":["#6A1B9A","#8D6E63","#FFD60A"],"imageAspectRatios":[1.3,0.9],"imageColorOffset":1,"imagePositionSeed":2}
  },
  {
    slug: "battle-of-marathon",
    title: "The Battle of Marathon",
    description: "The run that saved Greek civilization",
    category: "War",
    thumbnail_color: "#00695C",
    body_text: `In 490 BCE, a Persian army landed on the plain of Marathon, twenty-six miles from Athens. The Persians had come to punish the Athenians for supporting a revolt in their empire and to add Greece to their vast dominions. What happened next would shape the course of Western civilization. The Athenian army was vastly outnumbered, perhaps 10,000 hoplites against 25,000 or more Persians. The Spartans had promised reinforcements but would not march until after a religious festival. Athens could not wait. General Miltiades convinced his fellow commanders to attack before Persian cavalry could deploy. The Greek charge covered the mile of open ground at a run, closing with the enemy before their archers could inflict heavy casualties. On the wings, the Greeks broke through and routed the Persian flanks. Then they turned inward, catching the Persian center in a double envelopment. The Persians fled to their ships, leaving over 6,000 dead on the plain. Athenian losses were 192. The victory was stunning, but the danger was not over. The Persian fleet was sailing for Athens, hoping to take the city before the army returned. According to legend, a runner named Pheidippides raced from Marathon to Athens to deliver news of the victory. He arrived, gasped out his message, and died. The modern marathon race commemorates his feat, though historians debate whether it actually happened. The Athenian army marched back in time to prevent the Persian landing. The invasion was over. Greece would remain free to develop the democracy, philosophy, and culture that became foundations of Western civilization. Ten years later, the Persians returned with a far larger force. They were defeated again, at Thermopylae, Salamis, and Plataea. Marathon was where the Greeks first learned they could win.`,
    design_config: {"thumbnailColor":"#00695C","titlePage":{"backgroundColor":"#00695C","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#00695C","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#00695C"},{"background":"#5D4037","text":"#FFFFFF"},{"background":"#FFD60A","text":"#000000"}],"imagePlaceholderColors":["#00695C","#5D4037","#FFD60A"],"imageAspectRatios":[1.5,0.85],"imageColorOffset":0,"imagePositionSeed":3}
  },
  {
    slug: "battle-of-salamis",
    title: "The Battle of Salamis",
    description: "The naval battle that saved Greece",
    category: "War",
    thumbnail_color: "#01579B",
    body_text: `In September 480 BCE, the fate of Greece hung on a naval battle in the narrow straits between the island of Salamis and the Athenian mainland. The Persian fleet outnumbered the Greeks by perhaps three to one. King Xerxes himself watched from a golden throne on a hillside, confident he would witness the final conquest of Greece. Instead, he watched his navy destroyed. The Persians had already won every battle that mattered. Their army had forced the pass at Thermopylae after the Spartans' famous last stand. Athens had been captured and burned. The Greek fleet, largely Athenian, was the last hope. But the Greek commanders were divided, and some wanted to retreat to the Peloponnese to protect their own cities. Themistocles, the Athenian commander, sent a secret message to Xerxes, claiming to be a traitor and promising to switch sides if the Persians attacked. It was a ruse to force battle before the Greek alliance collapsed. Xerxes took the bait, ordering his fleet into the straits where their superior numbers would be neutralized. The narrow waters meant only a portion of the Persian fleet could engage at any time. Greek triremes, smaller and more maneuverable, had the advantage in close combat. They rammed enemy ships and sheared off their oars, leaving them helpless. The battle lasted a full day. By evening, the Persians had lost over 200 ships to perhaps 40 Greek losses. Xerxes, his supply lines threatened by the loss of naval supremacy, retreated to Asia with most of his army. The remaining Persian forces in Greece were destroyed the following year at Plataea. Salamis saved Greek independence at the moment it seemed doomed. The civilization that produced democracy, philosophy, theater, and so much else survived because of what happened in those narrow waters. Themistocles became a hero, though he would later be exiled and end his days in the service of the Persian king he had defeated.`,
    design_config: {"thumbnailColor":"#01579B","titlePage":{"backgroundColor":"#01579B","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#01579B","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#01579B"},{"background":"#00695C","text":"#FFFFFF"},{"background":"#E8E8E8","text":"#000000"}],"imagePlaceholderColors":["#01579B","#00695C","#E8E8E8"],"imageAspectRatios":[1.4,0.9],"imageColorOffset":1,"imagePositionSeed":4}
  },
  {
    slug: "battle-of-tours",
    title: "The Battle of Tours",
    description: "The hammer that stopped the Muslim advance",
    category: "War",
    thumbnail_color: "#795548",
    body_text: `On October 10, 732, somewhere between the cities of Tours and Poitiers in central France, a Frankish army under Charles Martel defeated an invading Muslim force from Spain. The battle has been called one of the most important in European history, the moment when Islamic expansion into Western Europe was permanently checked. The reality may be more complicated, but the legend has shaped how the West remembers itself. Muslim armies had conquered Spain in just seven years beginning in 711. They crossed the Pyrenees and raided deep into Frankish territory, seeking plunder and possibly permanent conquest. In 732, Abd al-Rahman al-Ghafiqi led a large expedition north, sacking Bordeaux and advancing toward the wealthy monastery of St. Martin at Tours. Charles Martel, whose name means the Hammer, was the effective ruler of the Frankish kingdoms, though he never took the title of king. He gathered an army from across his domains and marched to intercept the invaders. The two forces faced each other for seven days before the Muslims attacked. The battle was fierce but decisive. Contemporary sources are sparse and often contradictory, but they agree that the Frankish infantry held against cavalry charges and that Abd al-Rahman was killed in the fighting. When night fell, the Muslim army retreated. They had lost their commander and their baggage train. The expedition was over. Charles Martel's victory made him the dominant power in Western Europe. His grandson Charlemagne would be crowned Emperor, founding a dynasty that shaped medieval civilization. The Muslim forces never again seriously threatened territory north of the Pyrenees. Whether Tours actually saved Christian Europe or was simply one battle among many remains debated. What matters is that for over a thousand years, Europeans have believed it was the crucial moment when the tide turned.`,
    design_config: {"thumbnailColor":"#795548","titlePage":{"backgroundColor":"#795548","textColor":"#FFFFFF"},"colorPalette":[{"background":"#000000","text":"#FFFFFF"},{"background":"#795548","text":"#FFFFFF"},{"background":"#FFFFFF","text":"#795548"},{"background":"#8D6E63","text":"#FFFFFF"},{"background":"#FFD60A","text":"#000000"}],"imagePlaceholderColors":["#795548","#8D6E63","#FFD60A"],"imageAspectRatios":[1.3,0.85],"imageColorOffset":0,"imagePositionSeed":2}
  }
];

async function uploadStory(story) {
  const response = await fetch(`${SUPABASE_URL}/rest/v1/stories`, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      "apikey": SUPABASE_KEY,
      "Authorization": `Bearer ${SUPABASE_KEY}`,
      "Prefer": "resolution=merge-duplicates,return=minimal"
    },
    body: JSON.stringify({
      slug: story.slug,
      title: story.title,
      description: story.description,
      category: story.category,
      thumbnail_color: story.thumbnail_color,
      published: true,
      published_at: new Date().toISOString(),
      body_text: story.body_text,
      design_config: story.design_config,
      updated_at: new Date().toISOString()
    })
  });

  if (!response.ok) {
    const text = await response.text();
    throw new Error(`${response.status}: ${text}`);
  }
}

async function main() {
  console.log(`Uploading ${stories.length} War stories to Supabase...\n`);

  let success = 0;
  let failed = 0;

  for (const story of stories) {
    try {
      process.stdout.write(`Uploading: ${story.title}... `);
      await uploadStory(story);
      console.log("Done!");
      success++;
    } catch (error) {
      console.log(`Error: ${error.message}`);
      failed++;
    }
  }

  console.log(`\nComplete! ${success} succeeded, ${failed} failed.`);
}

main();
